### ISSUE TITLE
Locked / Unlocked items

### ISSUE THREAD

**Issue by lanejcf** [dasilva333/TowerGhostForDestiny#101]
With the introduction in Destiny of the ability to lock/unlock equipment so that it can only be broken down when unlocked, would it be possible to add this to the tool 
1) Showing/filtering locked /unlocked items
2) Ability to lock all items/guns/armour to save going thought all items individually within Destiny.
3) lock/unlock items individually within tower ghost

Just a few thoughts

**Comment by matthubb** [comment]
As far as I'm aware, there's no API available for modifying the locked status.

So, thought No.1 is achievable, but thoughts No.2 and No.3 are probably not.

**Comment by dasilva333** [comment]
The API currently does support the item.locked flag, the only problem is they are all equal to false even if you lock it in game, also there is no API to lock things remotely, the lock functionality is already built into TGD as of 2.0.3 or something if Bungie does decide to enable the lock flag it should just start working for everyone. Closing this issue as it has already been addressed
