### ISSUE TITLE
Export item list

### ISSUE THREAD

**Issue by Joshbuss** [dasilva333/TowerGhostForDestiny#102]
I would love to have the ability to export against of all of my items into either an excel spreadsheet or a CSV file

Inclusion of all info available per item would be awesome

**Comment by pattont** [comment]
Out of curiosity what would you do with the .csv seeing as you could just pull up Tower Ghost to search/preview anytime you wanted to see your items?

**Comment by dasilva333** [comment]
Hey man I'm not sure how useful most people would find it, but for my own curiosity and maybe a future release I coded it up. If you'd like to try it on Chrome do the following:
1. Press F12 and go to the Console tab
2. paste the following code and run it
3. it will prompt a file download and thats the csv for ya

https://gist.github.com/dasilva333/80cd9135118b23ac7ed7

Thanks
