### ISSUE TITLE
iOS: Unable to 'Equip' in Loadouts

### ISSUE THREAD

**Issue by Leki27** [dasilva333/TowerGhostForDestiny#106]
If i use the app to create a new loadout or edit a loadout, i had the option to hold a weapon to directly equip the weapon...
This work with the past version - but on 2.1.7 i can hold as long as a i want , the weapon will not show up on the loadout. I can add weapons to my loadout by tapping it - but i can't find a way to "blueframe" the weapon...

is that a bug or what am i doing wrong?

**Comment by dasilva333** [comment]
Sorry about that @Leki27 I introduced a new bug expect the fix in 2.1.8 thanks!

**Comment by Leki27** [comment]
I can see that this has been fixed now with the new update - Thanks much
