### ISSUE TITLE
Equipping loadout

### ISSUE THREAD

**Issue by ml97** [dasilva333/TowerGhostForDestiny#107]
If a weapon is in a loadout and equipped on another toon, it will timeout the loadout process when trying to transfer.

**Comment by dasilva333** [comment]
@ml97 
are you able to reproduce the issue every time? 
Are you running this In Chrome? 
Are you able to provide any debug logs of the when it times out? (Press F12 and visit the Console tab and save any messages you get)
what version did you try?

I just tried it for one of my loadouts and it worked fine. thanks

**Comment by jantjis** [comment]
Same for on today on the iOS App. It transferd the 3 Items (from Vault & Warlock), but before the 4th one (Black Hammer equipped on my Hunter) it timed out.

**Comment by ml97** [comment]
I was running the iOS app. It happened every time I tried to transfer until I Unequipped items in the loadout. I will try again today. It doesn't give a error, it just stays on the transfer screen.  How can I get messages on the app if it does happen?

**Comment by ml97** [comment]
I was running the iOS app. It happened every time I tried to transfer until I Unequipped items in the loadout. I will try again today. It doesn't give a error, it just stays on the transfer screen.  How can I get messages on the app if it does happen?

**Comment by ml97** [comment]
I equipped three weapons and made the transfer with no issues this time. Great app!

**Comment by dasilva333** [comment]
thanks @ml97 maybe what you experienced was some strange network connectivity issue. please feel free to make a new issue if you have trouble with using loadouts in the future and I'll keep a close eye on feedback to make sure there isn't a bug hidden somewhere in there
