### ISSUE TITLE
Enhancement - Re-order Loadouts

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#108]
At some point it would be really really nice to be able to re-order the loadouts. I have tried my best to name them something meaningful, but being able to re-order them and have that order be saved would be the best. 

Doesn't have to be this exactly, but this is what I was thinking:
http://rubaxa.github.io/Sortable/

**Comment by dasilva333** [comment]
Sorry man I don't agree with this change, the bottom items are ordered by category and the menu items are ordered chronologically. Thanks for your feedback!

**Comment by pattont** [comment]
Yea, I meant just the menu items not the actual items. Sorry I should have been more clear. I basically, just want to re-order my loadouts in the dropdown.

For instance, I want Arc, Void, and Solar first. Then, I want PVE - Sunsinger, PVE - Voidwalker then I want some other weapon loadouts. I have too many loadouts to just quickly look at them and being able to just drag and drop the load outs in the menu to the order I want would be excellent.
