### ISSUE TITLE
Exotic Weapons filter not working

### ISSUE THREAD

**Issue by PillowMetal** [dasilva333/TowerGhostForDestiny#11]
In both the Android app and my Chrome browser, the menu item filter for "Set/Exotic Weapons" is not working anymore.  It simply leaves the filter in its previous state, showing what it did before you try to use the new filter. In fact, the previous highlighted menu selection remains selected as well.

**Comment by dasilva333** [comment]
Thanks man I wasn't aware of the issue, turns out it was the 4th horseman aching to come back and kick my ass. Well I beat him down good so expect the fix in 1.7.3 thanks

**Comment by hkp** [comment]
Does this mean that the 4th horseman exotic not displaying will be fixed in 1.7.3? Can't see it on Chrome at least.

**Comment by dasilva333** [comment]
Nope and 1.7.3 is already out

**Comment by PillowMetal** [comment]
This issue is now resolved and a commit containing the message "fixes #11" would automatically close it when merged with the master branch, but is there a manual way to close this issue?

**Comment by dasilva333** [comment]
yes you click on the button that says "close and comment" instead of the one that says "comment" thanks for your help
