### ISSUE TITLE
Dedicated "clear filter" button

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#110]
It would be mega-helpful to have some sort of "clear filter" button that doesn't require 3 taps to get to:
hamburger icon -> gear icon -> clear filters

Maybe this button ONLY shows up when you have filters applied, which in turn solves an ancillary problem: knowing you have a filter applied when viewing your items.

Currently there is not indication of whether or not a filter is applied other than by drilling down on every filter menu.

**Comment by Joshbuss** [comment]
I agree,  many times I have set a filter and want to clear it,  but have to click through each filter in order to find and clear the right one

**Comment by dasilva333** [comment]
This is a good one, I'll make it live next to the refresh button especially after saving all that space by removing the version # on mobile. The hardest part is probably going to be picking an icon that presents clear filters, feel free to suggest a few from this list:

http://www.fatcow.com/images/fatcow-icons/fatcow-3926.png

Thanks guys

**Comment by Joshbuss** [comment]
Out of that list,  I like the "cross"  icon.  Big red apparent X.  Simple,  yet effective

**Comment by M3Rocket** [comment]
I don't like icons that can be ambiguous. 

I think it should be simple--a "text button" that says, "Clear Filters" should appear to the right/bottom of all the filter dropdowns as soon as any filter is set. That way, it could act as an indicator that a filter was set as well as provide a quick way to reset them.

**Comment by Titus-s** [comment]
I think that "text button" will take to much space. 
I suggest to use icon "filter_clear". 
![image](https://cloud.githubusercontent.com/assets/11790750/7408368/74f77162-ef1c-11e4-96aa-b0f5da04cd14.png)
I think it's most popular icon for filter.

**Comment by lanejcf** [comment]
In the chrome version, it would be nice to have the 'clear filter' next to the filter text box on the top left of the screen.

**Comment by weborican** [comment]
I think any icon with the funnel and either the X (or the red circle with minus sign in the middle) on top of it will do the trick.

Like:
http://icons.iconarchive.com/icons/fatcow/farm-fresh/32/filter-delete-icon.png
http://icons.iconarchive.com/icons/icons8/windows-8/128/Data-Clear-Filters-icon.png

**Comment by dasilva333** [comment]
@Titus-s I like the filter_clear icon the best I think I'll go with that, 

I'm going to place the icon next to the refresh icon on the top left. It wouldn't make sense to have a text button because indeed it would take too much space. I'll also try to make the refresh/clear buttons available in the mobile interface next to the quick scroll (I'll have to see if it fits).

Thanks for the feedback guys

**Comment by dasilva333** [comment]
@weborican @Titus-s @lanejcf  expect the button in 2.4.1 thanks man

**Comment by M3Rocket** [comment]
The icon looks nice, but can the tooltip on the icon read "Clear All Filters!" 

I'm not a fan of icons only, because honestly, most average users are befuddled by them.

**Comment by dasilva333** [comment]
Good idea, tooltips are always a plus on icons. Expect it in 2.5.5 thanks

**Comment by M3Rocket** [comment]
FYI--Toot-tip doesn't appear for me on either Firefox or Chrome 2.5.5
