### ISSUE TITLE
Dismissing the About and Help window

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#111]
Now that the version number doesn't show up anymore on mobile platforms -  bring it back please :-)  - we are forced to open the About page in order to find out which version we are running. I have discovered that it can be rather difficult to close this window in different mobile platforms (especially difficult on iPhone). Can we add a top-right closing X, or button, in order to simplify the mechanics of closing these windows?

**Comment by weborican** [comment]
OMG, I'm just now realizing there IS a closing X on the top-right corner! Doh!

OK, make this a request to make that X much more visible, it super-stealthy as it is on version 2.1.9  :-)

**Comment by dasilva333** [comment]
Closing this issue in favor of issue #98 please try to read the existing issues before opening a new one and leave your feedback there. thank you
