### ISSUE TITLE
Unable to move gear in vault if using loadouts

### ISSUE THREAD

**Issue by BigOch** [dasilva333/TowerGhostForDestiny#112]
When creating loadouts, the app is able to move items from one character to another but unable to move them from the vault. I originally thought this could be an Android issue but have replicated it using the chrome extension on my computer as well. It seems to only be a problem with the loadouts though. I can transfer items individually from the vault without issue.

**Comment by dasilva333** [comment]
I think this issue is related to issue #91 where transfer fails at time. please leave any feedback there. thanks
