### ISSUE TITLE
iPhone 6 network error 502

### ISSUE THREAD

**Issue by Stry73** [dasilva333/TowerGhostForDestiny#114]
App launches but does not connect. Network error 502.

**Comment by dasilva333** [comment]
@Stry73 thanks for reporting the issue I'm glad someone came through I had the same problem and managed to fix it as of 2.2.2, have you updated to the latest version and is it fixed yet?

If it's not fixed yet try to do a full uninstall and reinstall and also let me know if that fixed it.

Thanks!

**Comment by dasilva333** [comment]
Assuming its fixed thanks anyways man
