### ISSUE TITLE
IOS: Enhancement Suggestion - Support 1Password for login

### ISSUE THREAD

**Issue by zxaos** [dasilva333/TowerGhostForDestiny#116]
In IOS, logging into things could be simplified by allowing the browser to pull login information from the 1password app. This would make logging in significantly less painful.
(see https://blog.agilebits.com/2014/07/30/introducing-the-1password-app-extension-for-ios-8-apps/ for video and documentation )

**Comment by dasilva333** [comment]
This is a Phonegap Build application that doesn't allow me to do any native things such as interacting with other applications, also logging in on iOS is a limitation of the NSHTTPCookieAcceptPolicyAlways policy I can't change in WebView. Closing this ticket as it is something I can't fix
