### ISSUE TITLE
Set to all not clearing other filters

### ISSUE THREAD

**Issue by RuneUlf** [dasilva333/TowerGhostForDestiny#117]
Under the set button, when you select all previous selected filters are not cleared.

**Comment by dasilva333** [comment]
@RuneUlf can you provide an exact example of the situation encountered?
What filters did you use in the menu?
What filters did not clear?
You are talking about "Clear Filters" under the Settings right?
(example: I set the Damage Filter, Progress Filter and when I click Clear Filters the Progress filter was still active)

**Comment by RuneUlf** [comment]
When you got to the set and select all it is not clearing previous selections.  I selected missing xp and it only showed those, but when I went to select all afterwards it was still only showing missing xp ones.

**Comment by dasilva333** [comment]
@RuneUlf I cannot reproduce can you describe exactly the steps you take?
Here's the steps I take:
Set > VOG Armor > Clear Filters (Works)
Set > Crota Weapons > Show Missing Items > Clear Filter (Works)
Progress > Missing XP > Clear Filter (Works)
Set > VOG armor > All (Works)

Please try to describe the issue more clearly so I can try to reproduce the problem. Thanks

**Comment by RuneUlf** [comment]
Under set I was looking at the missing items and then I selected all, but all I could see was the missing items.  I think there should be a clear in there to remove those filters I can see why you would want all in the missing filters.  Having to reselect a filter to clear it when you might have multiples selected could be made quicker.  Sorry confused the missing xp with the show missing items.

**Comment by dasilva333** [comment]
There's an option to clear all filters under Settings (cog icon) > Clear Filters so I'm glad you got this figured out. If you want a faster way to clear it use that as it wouldn't make sense to put clear filters under every menu item (set, weapon, progress, etc) bc it would clutter up the menu even more.

Thanks for your feedback
