### ISSUE TITLE
Missing items not labeled

### ISSUE THREAD

**Issue by RuneUlf** [dasilva333/TowerGhostForDestiny#118]
When showing missing items for Crota, VOG...etc, you see a picture of the item but there is not any indication of what the item is. I am missing 2 guns for VOG, but I only see the picture of the item.  Clicking on the item tells me nothing.  Here should be a way to name the item also so you know what you are missing.

**Comment by dasilva333** [comment]
When DestinyDB tooltips are enabled you can hover over the items to see what they are, clicking on the item isn't supported unless you enable DestinyDB mode at which point you can click for more info.
See attached screenshot: http://i.imgur.com/X3AVmvR.png
Thanks for your feedback but I won't be labeling missing items
