### ISSUE TITLE
Transfer Material Quantity dialog box broken/disappears in Android Tower Ghost v2.2.6

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#120]
When ever I click to transfer materials and the quantity box pops up, I can't seem to select the quantity and type in a new number. When I touch the quantity number, the keyboard flashes on-screen, and then both the window with the quantity and the keyboard disappears.

I have tried this on both a Nexus 7 (2013) and Nexus 4.

Uninstalled 2.2.6, went back to base install, refused upgrade and it works again.

**Comment by M3Rocket** [comment]
I'm beginning to think the auto-Hydrate isn't a good idea. I think I would prefer to be able to stick with any particular release version that is stable but more recent than the last Hydrated version (v2.1.4 I think?) posted on the Play store.

Is there any archive where I can download the 2.2.2 APK and sideload it instead?

**Comment by dasilva333** [comment]
I had a feeling that making dialog boxes clickable to dismiss would cause issues somewhere I just wasn't sure where, this bug report clears it for me. I'll have to improve the popup to make the click to dismiss not be part of that specific one. Thanks for your feedback as for going back. There is no going back! Here's the list of all the available apks: https://github.com/dasilva333/TowerGhostForDestiny/commits/div-movile-dist/TowerGhostforDestiny-release.apk

**Comment by M3Rocket** [comment]
Frankly, as quick as you have been in fixing things, I'm not terribly concerned. ;-) Was just thinking out loud. Besides, I always revert to the Chrome/Firefox versions if I had to where I have total control over versions.

**Comment by dasilva333** [comment]
2.2.7 fixed it try it out now

**Comment by weborican** [comment]
Fixed at my end. Thank you!

**Comment by dasilva333** [comment]
Alright no problem thanks for reporting this stuff
