### ISSUE TITLE
Auto Pad Height not working for stacks taller than 3

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#121]
Screen shot is pretty self-explanatory--seems like Auto Pad Height only works for stacks of up to 3 rows? Seems not to work in the Consumables & Materials sections when its 4 rows or more:

![5-1-2015 11-31-03 am](https://cloud.githubusercontent.com/assets/3769123/7435205/6d2ca684-eff6-11e4-844f-ffbbed298c82.png)

**Comment by dasilva333** [comment]
closing this issue in favor of issue #88 there's already an enhancement planned that will take care of this. thanks for your feedback

**Comment by M3Rocket** [comment]
Kewl. Didn't see the other one. I'm going blind in my old age...
