### ISSUE TITLE
Sub Class icons broken in Android 2.3.1

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#127]
Icons for the sub class is showing a broken link

![screenshot_2015-05-03-11-29-38](https://cloud.githubusercontent.com/assets/3769123/7446459/281cc1e8-f18e-11e4-86f5-5dc40204ed47.png)

**Comment by dasilva333** [comment]
Yeah I noticed that too on IOS they should be fixed now (still 2.3.1), let me know thanks!

**Comment by M3Rocket** [comment]
Fixed on Android.
