### ISSUE TITLE
Move Item dialog overlap on Android

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#128]
Hard to explain this one, but if you touch select an item that is at the bottom of the screen (last two rows) where the move dialog popup usually is, the item is moved immediately and the popup disappears as if one had "double-clicked" that area. I'm not sure how to title this bug.

![screenshot_2015-05-03-11-33-35](https://cloud.githubusercontent.com/assets/3769123/7446492/3103ca6c-f18f-11e4-9c91-f1c9cea00c77.png)

![screenshot_2015-05-03-11-31-53](https://cloud.githubusercontent.com/assets/3769123/7446491/2a2b62e0-f18f-11e4-8141-57d0f1fa6fd8.png)

**Comment by dasilva333** [comment]
@M3Rocket thanks for the bug report, it looks fine on my devices but that's probably because they all have a similar resolution. Can you provide me your device's name or resolution? THanks

**Comment by M3Rocket** [comment]
Happens on both my Nexus 7 (2013) and Nexus 4.

**Comment by dasilva333** [comment]
@M3Rocket problem fixed in 2.3.6 try it out and confirm its fixed, feel free to close the ticket once you do.thanks

**Comment by Mulchman** [comment]
I haven't tried 2.3.6, but I also encounter this on a Samsung 10.1" tablet.  It's like the click that makes the move popup show up in the first place is immediately sent through to the move popup dialog before the user even sees it.

**Comment by M3Rocket** [comment]
Just checked with 2.3.7 and the same problem. Don't think the fix worked. @Mulchman describes the problem well.

**Comment by dasilva333** [comment]
@Mulchman  @M3Rocket This problem has been fixed including the height of the overlay and making sure the item click doesn't transfer to the move popup click. Let me know so we can close this out thanks

**Comment by M3Rocket** [comment]
Yes--seems fixed for me. Closing the issue. THANK YOU!
