### ISSUE TITLE
Unable to finish to load my inventory after I logged in PSN account

### ISSUE THREAD

**Issue by AngelFireOmega** [dasilva333/TowerGhostForDestiny#129]
The screen stays at  the loading screen forever,
![screen](https://cloud.githubusercontent.com/assets/12227071/7448102/4bddf3a8-f243-11e4-9e1a-363855a83db9.png)

**Comment by dasilva333** [comment]
Chrome or Firefox? Did it work for you before? Can you try providing any crashes in the console?
Press F12 and visit the console tab if you're on Chrome and copy and paste any messages here or into www.pastebin.com thanks

**Comment by AngelFireOmega** [comment]
It is chrome on Mac book 2014 and both the browser and system are under Traditional Chinese.
Thanks.
![error](https://cloud.githubusercontent.com/assets/12227071/7449927/8b557d7a-f271-11e4-854d-834e488ac56a.png)

**Comment by dasilva333** [comment]
@AngelFireOmega Can you try providing me the same screenshot as the one you gave me except with the Source tabs open. If you can try to find data/itemDefs.js and make sure that's loading for you too. Thanks!

**Comment by AngelFireOmega** [comment]
sure.
![screen](https://cloud.githubusercontent.com/assets/12227071/7466189/0813a608-f311-11e4-807f-b9ba559da811.png)

**Comment by AngelFireOmega** [comment]
I tried to change my MAC OS X language to English and then it works.
After I change it back to Traditional Chinese (zh-TW) this issue happens again.
I think this is a language related one.

**Comment by dasilva333** [comment]
Can you try 2.2.8 on your OS X with Traditional Chinese enabled?
The link for the file is here: https://github.com/dasilva333/TowerGhostForDestiny/blob/34311e3411b73d6c8c795d8d1cbe5b148d25c1e7/tower_ghost.zip
Install instructions can be found here at the bottom: http://dasilva333.github.io/TowerGhostForDestiny/

**Comment by AngelFireOmega** [comment]
This issue is still happening on v2.2.8.
Last night, my friends also report the same issue on Tradition Chinese Windows environment.

For more information, we are using PS4 account.

Thanks.

![2 2 8](https://cloud.githubusercontent.com/assets/12227071/7486316/fb98b394-f3d5-11e4-9f04-60768b2f596b.png)

**Comment by dasilva333** [comment]
@AngelFireOmega I think I messed up my version numbers, if you could please do me the favor of trying 2,2.6 found here:
https://github.com/dasilva333/TowerGhostForDestiny/blob/b466aa27da491307fb5b54088dcc52be056be352/tower_ghost.zip

Also I have another question, do you know what is the last version that worked for you?

**Comment by Doubleken** [comment]
I got the same problem too, still cannot fix it. :(

**Comment by AngelFireOmega** [comment]
@dasilva333 v2.2.6 is still not working for me. Same problem.

**Comment by dasilva333** [comment]
@AngelFireOmega for the third and last time, do you remember what version if any version worked for you? I know if you switch to English font it works but in the past has any version worked for you with the Chinese font enabled? Your answer might provide me a clue as to when I broke it so please let me know it's important.

@Doubleken  You have the same problem on your Kindle Fire? DIM is only for Google Chrome

**Comment by Doubleken** [comment]
I don't have Kindle Fire, cannot test it.

**Comment by AngelFireOmega** [comment]
No. This add-on has never worked for me in Chinese.

Richard Pinedo <notifications@github.com> 於 2015年5月6日 星期三寫道：

**Comment by dasilva333** [comment]
@AngelFireOmega can you help me out I can't figure out how to change the font in Chrome so I can reproduce it, is this something that you change in your Mac settings and I would have to change in my Windows? Let me know I'd like to make this more international friendly thanks.

**Comment by AngelFireOmega** [comment]
@dasilva333 what I did was just change the Mac OS system language. It can be changed in the Mac OS preference. as for windows, I think it should be the sam.

**Comment by Doubleken** [comment]
Before I use Chinese system in Mac, after change it to English, still NOT work for me.

**Comment by AngelFireOmega** [comment]
Just download the latest version v2.4.8 and still not working.
![tgd](https://cloud.githubusercontent.com/assets/12227071/7557817/900eef1e-f7ca-11e4-93e6-bf342aaa6631.png)

**Comment by Doubleken** [comment]
Yes, still cannot work for me too.
But DIM v3 work really good!

**Comment by AngelFireOmega** [comment]
It's working foe me now. Thanks for the good work.

**Comment by Doubleken** [comment]
Same, it work prefect now!
Love this App!

**Comment by dasilva333** [comment]
Great thanks for the feedback guys good stuff
