### ISSUE TITLE
Option to auto equip items in loadout

### ISSUE THREAD

**Issue by Titus-s** [dasilva333/TowerGhostForDestiny#13]
First - thank you for your hard work. 
It's a great tool, and I recommend it to all my friends but we all miss a feature to auto equip selected items in loadout. 
I've got three warlocks and every time when I change the character I transfer items and have to equip it manually. I would be really great to do it in two clicks.

**Comment by dasilva333** [comment]
Cool man this is actually an incoming feature,it has been previously requested thanks for posting it here now I can close the old one thanks

**Comment by dasilva333** [comment]
This feature has been added as of 1.7.3 please try it and close the ticket if it's been resolved thanks

**Comment by Titus-s** [comment]
It's not possible to move equipped items. 
No matter if you try to do it using loadout or just select equipped item and move to another character. 
Logs from console:
Loadout:
Uncaught TypeError: undefined is not a function          app.js:205 
unequip                                                  app.js:343 
store.done                                               app.js:384 
store                                                    app.js:260 
equipload                                                outs.js:101 
swapItems.transferNextItem                               loadouts.js:119
swapItems                                                loadouts.js:202 
transfer.dialog.buttons.action                           bootstrap-dialog.js:795 
(anonymous function)                                     jquery.js:3 
m.event.dispatch                                         jquery.js:3 r.handle

Move equipped item:
Uncaught TypeError: undefined is not a functionapp     app.js:205
unequipapp                                             app.js:343
store.done                                             app.js:384
store                                                  VM648:1
click                                                  knockout.js:83
(anonymous function)                                   jquery.js:3
m.event.dispatch                                       jquery.js:3
m.event.add.r.handle

**Comment by dasilva333** [comment]
Please try the latest version and confirm it's still and issue thank you

**Comment by Titus-s** [comment]
I forget to mention - tested on version 1.7.6. 
It works if you try to move unequipped item.

**Comment by dasilva333** [comment]
thanks for your feedback titus I found a bug I was sure I fixed, it's really fixed now as of 1.7.7 let me know if it's fixed

**Comment by Titus-s** [comment]
Tested on version 1.7.7
It works fine, but there is small issue: 
When (for example) on destination character is exotic chest equipped and you try to equip exotic helmet (first in a row) then it is not equipped but stored. 
As I mentioned it's a small issue. It would be great if you could fix it, if it's not too complicated. Otherwise leave it as it is now and close this issue. 

Thanks for your great job.

**Comment by dasilva333** [comment]
Cool I didn't notice that, the way I tested it was making a loadout with 1 primary exotic while having an exotic special equipped and notice that didn't work either. latest commit should fix it. expect it in 1.7.9

**Comment by Titus-s** [comment]
Tested on version 1.7.9:
It works when transferring weapons, but doesn't when transferring armor. Behave as I described in my last post - store but not equip.

I got question about swapping. Why it swap items when on destination character is 9 (not 10) specified items (e.g. primary weapons)? I've noticed that it first move item from loadout to destination character and then equip. I thought that swap will appear when you have 10 specified items.

**Comment by dasilva333** [comment]
You're right the text that says "this item will be equipped" doesn't show up when I confirm the transfer for armor. Thanks for the bug report as for your other question...

The way transfers work is it adopts one of two strategies, the first one is simple if the item you want fits in the place you want it in then no problem I just transfer The second scenario is when the item you want putting it in the place you want would cause you to have 10 items, in that instance I use the 'swap' tech to prevent you from ever reaching 10 as the ideal situation in all cases would be for all characters to always have 9 slots open on all bucket types.

Hope that made sense thanks again for the update and I'll get it fixed

**Comment by Titus-s** [comment]
I'm not sure if I described issue clear enough.
Tested on version 1.8.0 on Chrome.

Scenario 1 - Armor
Let say:
- on target character is equipped Exotic Gauntlets 
- in loadout is only Exotic Helmet with equip checkbox selected.
When I click on target character in loadout the Exotc Helmet is stored instead of equip. This happen (probably) because I have equipped Exotic Gauntlets. 

Scenario 2 - Weapons
Let say: 
- on target character is equipped Exotic Machine Gun
- in loadoud is only Exotic Primary weapon with quipe checkbox selected.
When I click on target character in loadout the Exotc Primary weapon is stored instead of equip. This happen (probably) because I have equipped Exotic Machine Gun. 

Please notice that Scenario 1 doesn't work on versions 1.7.9 and 1.8.0 (Exotic Helmet was just moved to target character - not equipped).
Scenario 2 works on version 1.7.9 (primary was equipped) but doesn't work on 1.8.0 (primary was just moved to target character - not equipped).

Hope this is clear enough now.

**Comment by dasilva333** [comment]
Agreed, the above two scenarios work fine when the target and destination character are the same but not when they target and destination are different. I'll be fixing that bug today thanks for the feedback you're being super helpful. 

Just to clarify (I have a Titan, Warlock, Hunter): 
Titan has exotic heavy/special equipped, in loadout only exotic primary weapon with equip checkbox selected, when I click on the titan character to apply the loadout of a single primary exotic it works fine and unequips the special or heavy and equips the exotic primary. When testing the same loadout on the hunter or warlock the weapon is indeed xfered but not equipped.

**Comment by dasilva333** [comment]
I commit the fix I'll be asking you to retest it later on today on version 1.8.1

**Comment by dasilva333** [comment]
@Titus-s  try it now as of 1.8.1 it's ready

**Comment by Titus-s** [comment]
First of all I want to thank you for improving this tool and your hard work. 
Auto equipping works great (at least for armor and weapon).
I found another problem with loadout, but I request it in new issue. Forgive me - I'm a QA :)
This is closed.
