### ISSUE TITLE
Unable to move an equipped weapon when a single exotic weapon is in the same bucket

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#131]
Not sure if it matters whether the equipped weapon is a legendary or not. Attached is a gif showing what happens. The same thing happens for both the Special and Heavy weapon bucket on version 2.3.2 on Chrome and Android, and version 2.3.3 on iOS:
![equip_bug](https://cloud.githubusercontent.com/assets/12019978/7460383/2c6db132-f268-11e4-96ea-f82d27b53bb6.gif)

**Comment by dasilva333** [comment]
One more thing were you logged in the game when you tried it? Have you tried the same steps without being logged in the game? I just can't reproduced it and Im trying to think of what would cause it to do that.
Thanks!

**Comment by weborican** [comment]
Not logged in at all. PS4 is on sleep mode at home :-)

**Comment by dasilva333** [comment]
@weborican I was able to reproduce it now I was derping on my side I'll get it fixed as part of 2.3.4 thanks man

**Comment by dasilva333** [comment]
@weborican try 2.3.4 only available in the ios branch and let me know if it's fixed I'll be updating all branches to the latest version later on

**Comment by weborican** [comment]
Will test as soon as I get home from work. How exactly do I test the iOS branch without a new ipa for iOS?

**Comment by dasilva333** [comment]
Simply update your iOS copy to the latest version, should read 2.3.4

**Comment by dasilva333** [comment]
Via hydra hydration auto updater

**Comment by weborican** [comment]
That's what I've been trying to do, but it doesn't seem to detect the new version. Three finger tap doesn't tell me there is a new version either, it simply refreshes.

**Comment by M3Rocket** [comment]
Same for me with Android. Didn't show 2.3.3, and now not 2.3.4. Still on 2.3.2

**Comment by dasilva333** [comment]
Yeah its only part of the IOS branch at the moment, still making adjustments to it. To use it you have to be part of the FlightTest or be jailbroken and have the AppStore.ipa installed

**Comment by weborican** [comment]
I have the non-jailbroken version I installed manually after sending you my iPhone's udid. Is that why I'm not seeing it? I can always delete it and install the FlightTest version.

**Comment by weborican** [comment]
OK, back home now and I have installed the TestFlight version, which gave me 2.3.4.

Tested with my two cases and this version seems to take care of that particular problem. I will test some more later tonight, but looks like we are good for now.

**Comment by dasilva333** [comment]
Great let me know if you find anything else and we can re open the ticket otherwise I think this case is solved. thanks a lot man you're a huge help!
