### ISSUE TITLE
iOS (7+) status bar not shown or incorrect color

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#134]
In iOS 7+ the status bar at the top is supposed to adjust color to match the colors used in the app. Not sure if this is done automatically or decided by the developer, but I think it's automatic. 

Currently it's now shown in TGD, here's what it looks like: 

![img_1145](https://cloud.githubusercontent.com/assets/4229542/7473448/17207cd2-f2f0-11e4-99c8-d09ce75e6a84.jpg)

Here's what it should look like, e.g. in another app

![kindle-4 5-for-ios-iphone-screenshot-002](https://cloud.githubusercontent.com/assets/4229542/7473455/258b38ac-f2f0-11e4-91a1-98a521d3acd9.png)

I have another screenshot from a previous version where it is shown but with the wrong color (the glitch at the bottom of the screen is fixed now): 

![img_1143](https://cloud.githubusercontent.com/assets/4229542/7473484/584a8784-f2f0-11e4-9436-3dd69df663d3.jpg)

**Comment by ssoriche** [comment]
The hydration process takes over the status bar when it looks for a new version and overrides whatever settings have been made for the status bar.

Leaving this open as an enhancement to be revisited on the day when hydration is no longer used.

**Comment by dasilva333** [comment]
@wickles can you confirm it's better in 2.4.0? Thanks man

**Comment by wickles** [comment]
Better but kind of hard to read, doesn't look right. 

![img_1147](https://cloud.githubusercontent.com/assets/4229542/7551066/e39c26d4-f62f-11e4-9b69-a9779b7cefe9.jpg)

**Comment by dasilva333** [comment]
I like the way it looks, it's the same matching color as the app's background instead of the pitch black it used to be. What do you think @ssoriche is there room for improvement?

**Comment by ssoriche** [comment]
I've played around with the different settings to make the text white. In the iOS simulator it changes no problem, but in the Hydrated application, it refuses to change.

I'll play around with it some more, maybe it's just a timing thing.

**Comment by dasilva333** [comment]
Closing this issue, 2.9.1+ iOS apps will not include Hydra so this shouldn't be a problem anymore. Let me know if there's still any issue with the latest update. Thanks @wickles
