### ISSUE TITLE
Problem selecting heavy to be equipped.

### ISSUE THREAD

**Issue by tonymccallie** [dasilva333/TowerGhostForDestiny#135]
When I put more than one heavy in a loadout and click the checkbox to mark one as equipped, nothing happens. If I close the loadout and reopen, I can see the checkmark. 
If I click on both checkmarks, nothing happens, but if I reload the loadout, BOTH are checked. I'm on 2.3.5 on Chrome.

**Comment by dasilva333** [comment]
If you can confirm it's also fixed in Chrome 2.3.6 that would be great, feel free to close the ticket when you do thanks!
