### ISSUE TITLE
Intellect/Discipline/Strength out of order - UI Consistancy

### ISSUE THREAD

**Issue by moeyjar** [dasilva333/TowerGhostForDestiny#136]
In Destiny, you view in Intellect/Discipline/Strength, the plugin has this incorrect.  See screenshot.

![ordering](https://cloud.githubusercontent.com/assets/12259797/7480439/e6166594-f33e-11e4-8ce8-f037b5f66a45.JPG)

**Comment by M3Rocket** [comment]
Unfortunately, I think the popups are all from destinydb.com. They need to change the order there.

**Comment by dasilva333** [comment]
@moeyjar That's right the layout, and order of stats and perks is determined by DestinyDB so it's not something I control or I can fix. Thanks for your feedback
