### ISSUE TITLE
Enhancement:  Keep the top bar visible when scrolling with multiple characters

### ISSUE THREAD

**Issue by moeyjar** [dasilva333/TowerGhostForDestiny#137]
It would be nice if the TGD chrome app would keep the top bar when scrolling down.

![topbar](https://cloud.githubusercontent.com/assets/12259797/7480483/2e986be6-f33f-11e4-8486-c726e5b79b0b.JPG)

**Comment by pattont** [comment]
Agreed - I find myself scrolling back to the top as well to remember when I am transferring some items. Not sure having it hover on the way down is the best option, maybe just have a form of the icon in some sort of background horizontally, but have it really transparent in the background.

**Comment by dasilva333** [comment]
Sorry guys I don't agree with this change, thanks anyways and thanks for your feedback
