### ISSUE TITLE
Enhancement: Loadout Menu Re-Ordering

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#138]
I have already requested this once before, but I decided to have another go at explaining the issue with pictures. As you can see from below I have a number of loadouts. When I edit any of them, the order changes to last edited at the bottom. If I want them in any kind of order other than this I have to re-open and save every other one to get my order back which is a huge pain. Please O'Please implement some sort of sorting either with putting in a number in the edit loadout menu, allowing alphabetizing below the "create" and "cancel" buttons in the dropdown, or drag/dropping them in the loadouts dropdown. 

If you do implement you could have it save the current order at the "default" then as people edit make changes and save to the cloud which wouldn't re-order anyone's list without their knowledge. 

![loadouts](https://cloud.githubusercontent.com/assets/2903357/7480350/0c1453fe-f336-11e4-8a12-72593fac2717.JPG)

Proposed JS Library:
http://rubaxa.github.io/Sortable/

Having the handlebar icons for draggable would be excellent for the UI.
![sortable](https://cloud.githubusercontent.com/assets/2903357/7480461/b10f2442-f336-11e4-9683-51b259acb420.JPG)

**Comment by pattont** [comment]
Any progress on this? Would be super cool.

**Comment by dasilva333** [comment]
Loadout sorting implemented in 3.9.0.7 expect it by the end of the day, let me know if there's any issues with it. thanks!

**Comment by pattont** [comment]
Has this version been pushed yet? I still don't have it.


Travis

**Comment by rkingsla** [comment]
@pattont Have the update yet?  If not, go to Options, Settings, turn off updates. Close settings. Go back and enable auto updates. If that doesn't work, close TGD. Re-open.

**Comment by pattont** [comment]
Got it last night thanks.


Travis
