### ISSUE TITLE
Enhancement:  Show the total of Intellect/Discipline/Strength on equipped gear.

### ISSUE THREAD

**Issue by moeyjar** [dasilva333/TowerGhostForDestiny#139]
On the top bar, perhaps list the total intellect/discipline/strength of your equipped armor.  When you equip another item, or add to a loadout, it should also list this (some people may want a specific loadout when raiding/IB, etc)

**Comment by pattont** [comment]
Yea, that would be pretty awesome!

**Comment by dasilva333** [comment]
You can now see those stats when clicking on the light level in the emblem for each character. Thanks for the suggestion good stuff. Closing this ticket bc its been completed already.
