### ISSUE TITLE
Inventory never loads

### ISSUE THREAD

**Issue by Vondrook** [dasilva333/TowerGhostForDestiny#141]
Trying to use the app on my iPhone 6+ and the app never loads my inventory. I am able to login to my Microsoft account and it shows my budgie.net account page but after that it goes to a grey screen with a spinning blue bar and nothing ever loads. I have tried waiting up to ten minutes with nothing ever happening. I have tried uninstalling and reinstalling.  I have tried going to the menu and refreshing but nothing ever happens.

**Comment by dasilva333** [comment]
Are you jailbroken or flight test? What version is it reporting? Let me know thanks

**Comment by Vondrook** [comment]
Flight test. Version 2.3.7

**Comment by pattont** [comment]
Try force closing and re-opening. If it has you log-in again to your bungie account so be it, but that should fix it. Mine has hung up like this before.

**Comment by dasilva333** [comment]
@Vondrook what is the last version you remember working for you? If you provide me your UDID 
http://whatsmyudid.com/ I can create a version for you to debug the problem. Thanks

**Comment by Vondrook** [comment]
It has never worked for me. At work now will get you the udid later this
evening when I get off work.

**Comment by dasilva333** [comment]
@Vondrook I'm assuming it's fixed or you stopped caring, it's been over a week. I'm closing this ticket to get clean out any old tickets. Thanks anyways

**Comment by Vondrook** [comment]
Sorry, the day I was supposed to get the phone info back to you we had some
bad weather come through our area and I forgot about it. After the last few
updates you have made it has been working just fine. Once again, sorry for
not responding.
