### ISSUE TITLE
Iron Banner Weapon Filter missing Timur's Lash

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#142]
Setting filter to IB Weapons show Efredeet's Spear and Jolder's Hammer correctly. But Timur's Lash is missing. When I select Show Missing Items, there are two pre-TDB Timur's Lash showing. My Timur's Lash is TDB, so that could be the reason why the filter isn't working.

**Comment by dasilva333** [comment]
issue #97
