### ISSUE TITLE
Running app from source: "Account has no data"

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#145]
Checked two versions of the app - dasilva333's master branch (up to date - 2.3.8) and my fork's master branch (up to date w/ dasilva333's latest changes merged in - 2.3.8) - and both are giving "Account has no data" errors when loading. Chrome store version 2.3.7 still working as expected.

Random bug on my end? Anyone who runs the app via source experiencing this?

**Comment by Mulchman** [comment]
fetched upstream, merged to my fork's master, and now the error is "Error loading inventory {"error":true}" so it looks like work is actively being done. I'll close this and keep watching for source changes.

**Comment by rkingsla** [comment]
I'm seeing this as well.  I believe it has to do with the work that is being done with the 'background' Bungie page load. If I close the page that opens, it seems that I can refresh and get data.

This is very early data and shouldn't be taken as a cause, but just an observation.
