### ISSUE TITLE
Suggestion: for easy scrolling, freeze rows containing Vault/Character title

### ISSUE THREAD

**Issue by Cravit8** [dasilva333/TowerGhostForDestiny#146]
On my iPad in landscape, it'd be easier to know what character I'm looking at items for when I'm below the vault/character graphic emblems.
My suggestion is the include the character emblem in the frozen pane of the top command row.

I generally stay in the view showing 'All' items, so I often have to scroll back up to confirm I'm switching items to the correct character.

Dasliva333 you are awesome.

**Comment by dasilva333** [comment]
Originally someone requested this for the desktop, and I dismissed it, now someone is requesting it for mobile, now for mobile it usually wouldn't make sense because you already have the quick scroll but if the layout can fit all 4 columns then quick scroll wouldn't show or apply. I believe this is a valid suggestion at this point. Thanks for the feedback

**Comment by Cravit8** [comment]
dasilva333
Per my use with an iPad 3:
With the newer version, not only is the character icon title not frozen, it is missing altogether in landscape mode, which means I cannot even use the app in landscape mode now, which was my favorite method because of less scrolling.

I sincerely hope this can be remedied. I notice on Chrome it is fine, but the landscape oreientation for iPad is borked. I'll attach a picture. Thank you for all you do, you're amazing.
![img_0969](https://cloud.githubusercontent.com/assets/12302601/7705940/6c0ab05c-fe15-11e4-9909-86dc4955b2ae.PNG)

**Comment by Cravit8** [comment]
Just want to say fabulous work on the app man! I donated via paypal under "
setapart4m@hotmail.com"

**Comment by dasilva333** [comment]
This is coming to version 2.8.9 thanks @Cravit8
