### ISSUE TITLE
More feedback when swiping 

### ISSUE THREAD

**Issue by Adiel-dev** [dasilva333/TowerGhostForDestiny#147]
When I swipe on iPhone (either to the left of right) I can filter through ARMOR/WEAPONS/GENERAL.

It would be nice if the application briefly showed me in which view/state I was. I remember being very confused when I swiped for the first time and I thought it was a bug. 

Also you can't go to the ALL state/view when swiping. There needs to be way simple way get back to the default state. Like a dedicated clear all button or way to swipe back to ALL.

**Comment by dasilva333** [comment]
Already part of issue #46 thanks for your feedback
