### ISSUE TITLE
Improve Sign In Prompt

### ISSUE THREAD

**Issue by Adiel-dev** [dasilva333/TowerGhostForDestiny#148]
I posted this on Reddit but thought it would be more appropriate here:

You could clarify the text more. Make it more of a welcome screen instead displaying it as an error. 

Something like:  "The app has been updated. In order to continue,  please sign-in with your PSN/MS credentials" 

So text that explains why stuff is happening, appearing or why some actions are needed to be done is a good way to avoid confusion. Make sure to clarify that the sign-in thing is "by design". The word "error" does really suggest it's some kind of bug/not meant to happen. 

"Please wait, your inventory is loading" is a great message you added in 2.3.8! It really does give you more feedback on what is happening.

**Comment by dasilva333** [comment]
Heh thanks for your feedback, I actually just commit those changes like 20 minutes ago. Coming in 2.4.0 so I'll leave this ticket open for future comments make sure it's all good for everyone.

**Comment by dasilva333** [comment]
Here it is:

http://i.imgur.com/b8ovpI8.png

I'll leave it up to @joshhunt if he wants to make any further improvements to this. Thanks guys

**Comment by joshhunt** [comment]
I'm happy to tackle this over the weekend if I have some time in-between raids. Is there a branch for this with it starting to be improved?

**Comment by Adiel-dev** [comment]
Before you roll it out. I would most definitely use a sans serif font!

**Comment by joshhunt** [comment]
Oh don't worry, I'll be sure to spice it up as appropriate.

**Comment by dasilva333** [comment]
@joshhunt thanks man whenever you can, it's already part of ios and master branch you can check out either of them. It's a temporary measure to hopefully appease Apple's reviewers.

**Comment by dasilva333** [comment]
@bluetidepro is helping me with the styling this is what he's got so far:
http://bluetide.pro/1ggE4/3ADyoeSc
