### ISSUE TITLE
Make contributing easier/smoother

### ISSUE THREAD

**Issue by bluetidepro** [dasilva333/TowerGhostForDestiny#149]
I absolutely love using this extension. I'm a UI/UX designer, and want to contribute to the repo and help amp up the design/ux a bit. You guys should look at adding a few files to the repo to help people to contribute. A few things would be a `CONTRIBUTING.md`, `.editorconfig`, etc.

Here are some good examples used by Bootstrap:

- https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md
- https://github.com/twbs/bootstrap#contributing
- https://github.com/twbs/bootstrap/blob/master/.editorconfig (this helps keep the code editors all uniform for things like spaces vs tabs, etc.)

Let me know, I would love to fork this ASAP and help out! :)

-Zach
https://twitter.com/bluetidepro

**Comment by Mulchman** [comment]
I'd love some help: https://github.com/dasilva333/TowerGhostForDestiny/issues/122

Where should the functionality go, what should it look like, toggles for including/excluding the vault, toggles for including/excluding certain consumables/materials (warlocks don't need sapphire wire), etc.

**Comment by bluetidepro** [comment]
Okay, I'll take a look. It would also be a good idea to add to the `readme.md` sine wats to run the app locally and how to build it and such locally so we can work on it! :)

**Comment by Mulchman** [comment]
I only know how to run locally on Windows through Chrome-
* get the git repository setup on your machine however you like and keep it up to date however you like
* turn on developer extensions in Chrome and then 'load unpacked extensions...' and point it to where you have the git repository on your machine

(I disable the chrome store version of TGfD while developing, too, so I don't get confused by multiple icons.)

![chrome options](http://i.imgur.com/foWX6XQ.png)

**Comment by bluetidepro** [comment]
Speaking of all this, do you guys have a better way to talk about the project off of Github? Maybe a free slack group or chat or something? Might be easier to talk things out that way! :)

**Comment by dasilva333** [comment]
I'm pretty happy with how my Contributing page is turning out. Closing this issue thanks guys
https://github.com/dasilva333/TowerGhostForDestiny/blob/master/CONTRIBUTING.md
