### ISSUE TITLE
Loadouts with Sparrow on iOS 8.3 not working.

### ISSUE THREAD

**Issue by themantisreturns** [dasilva333/TowerGhostForDestiny#15]
If a loadout contains any tier of a sparrow the assign buttons do not respond.  Also, the sparrow icon only shows a dot on the loadout menu. Once a sparrow is added to the loadout nothing else can be added. (This is on an iPhone 5 running iOS 8.3 non-jailbroken.)

![img_4833](https://cloud.githubusercontent.com/assets/11854958/7089982/dac90140-df6d-11e4-8892-888df6601d77.png)

(You're doing a fantastic job with this!)

**Comment by dasilva333** [comment]
It works for me, please try 1.7.3 once it is released it has improvements to the loadouts I'll give you an update when it's available. Also thank you for the kind words :)

**Comment by dasilva333** [comment]
Problem has been resolve as of 1.7.3 please try it and close the ticket if it's fixed thanks

**Comment by dasilva333** [comment]
Closing ticket as issue has been resolved and no new reports have come in
