### ISSUE TITLE
Loadouts not transferring to Firefox

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#152]
My loadouts are showing and loading correctly on Chrome and Android. But it is not showing up at all on my Firefox extension.

I just noticed this with 2.4.1, but may have been there since 2.4.0?

**Comment by M3Rocket** [comment]
Pastebin: http://pastebin.com/BNfFM2iH

**Comment by dasilva333** [comment]
Cloud based loadouts are not supported, closing this ticket for issue #99 thanks for your feedback
