### ISSUE TITLE
set menu filters not working after clear filter icon clicked

### ISSUE THREAD

**Issue by PillowMetal** [dasilva333/TowerGhostForDestiny#153]
Clicking "Set/Crota's End Weapons" does not filter the displayed weapons properly. It actually performs the same function as "Set/All Weapons". This occurs in the chrome extension v2.4.1.

**Comment by PillowMetal** [comment]
Performed a refresh of my browser and now the menu item is working fine, not sure what was causing the initial problem. I will close this issue and open a new one if this problem reappears and I can identify the conditions that are causing it.

**Comment by PillowMetal** [comment]
I can now reliably reproduce this problem, and it has to do with the new clear filter icon. To reproduce, filter the weapons set by Crota's End weapons. Then click the clear filter icon which makes the display reset. Now the Crota's End menu item is still selected, but even selecting another item and then coming back to it still does not make it work.

By the way this occurs with any menu item in the Set list... I performed the same functions with the Iron Banner weapons and it does the same thing. It appears when the clear filter icon is clicked, it sets makes the currently selected weapon filter the same as "All Weapons"

Not sure if this also happens with Armor.

**Comment by dasilva333** [comment]
Good catch, expect the fix in 2.4.2 thanks

**Comment by PillowMetal** [comment]
This is now fixed, closing issue.
