### ISSUE TITLE
Destiny DB Tooltips for raid armor is incorrect

### ISSUE THREAD

**Issue by kohum** [dasilva333/TowerGhostForDestiny#154]
The Destiny DB tooltips for raid armor alone is incorrect.  This issue seems to have been introduced in the latest version.  Non raid armor stats are showing up correctly.

**Comment by dasilva333** [comment]
Good catch sniper kitty expect the fix in 2.4.2

**Comment by kohum** [comment]
Lol... didn't realise that was my profile pic until I read your comment. It has been changed ! :)

**Comment by dasilva333** [comment]
@kohum Can you confirm it's been fixed? Thanks

**Comment by kohum** [comment]
Yes... This has been fixed !
