### ISSUE TITLE
Timur's Lash missing from Iron Banner Weapons Filter

### ISSUE THREAD

**Issue by PillowMetal** [dasilva333/TowerGhostForDestiny#155]
When filtering from the Set menu for Iron Banner Weapons, Timur's Lash is not shown.  All other IB weapons appear, but not this one.

**Comment by TopTenTiger** [comment]
I can confirm this. Mine doesn't show up either.

**Comment by dasilva333** [comment]
It all fits under issue #97 follow the issue to read the latest comment thanks
