### ISSUE TITLE
Can't transfer equipped armor in v2.4.3

### ISSUE THREAD

**Issue by kohum** [dasilva333/TowerGhostForDestiny#159]
Unable to transfer an armor piece that is equipped on another character.  Unequipped armor works fine.  Equipped weapons work just fine.  This issue only seems to be affecting armor.

**Comment by Titus-s** [comment]
This is the same issue as I've described in #91.

**Comment by dasilva333** [comment]
well said @Titus-s closing this as it will be addressed in issue #91
