### ISSUE TITLE
Suggestion: standardised formatting for maintainability 

### ISSUE THREAD

**Issue by matthubb** [dasilva333/TowerGhostForDestiny#163]
**Caveat**

This is just a suggestion to aid / ease contribution submissions and review, I'm no expert in collaborative github-based web-development and usually I write in a white-space sensitive language where this is less of an issue.

**Cause**

There have been some pull requests which have had huge change sets because someone's editor has  made changes to whitespace all over the place. I've made efforts to avoid doing this as it hinders code review.

**Suggestion**

Accepting that there will always be variation in editors, perhaps something like [js-beautify](https://www.npmjs.com/package/js-beautify) could be used to make code format consistent?

**Example**
- make a script in the build directory that reformats all of the .js (and perhaps the html as well?)
- have this part of the release process so that releases are always have standardised formatting
- contributers could use it too so that if their editor has rearranged vast swathes of whitespace it can be reflowed to a common format before they submit a pull request

**Comment by ssoriche** [comment]
I like this suggestion, would definitely help with maintainability, and doesn't look terribly complicated to implement.

**Comment by matthubb** [comment]
Here's a possible starting point for such a script: [gistfile](https://gist.github.com/matthubb/650381e727f9539efa13)

Looks in `www`, `www/js` and `www/css` for `html`, `js` and `css` files to reformat them using js-beautify with it's default parameters. It's probably not very graceful, not much in the way of safeguards. Wouldn't suggest it was run outside of a version controlled environment for rollback.

Feedback welcomed.

**Comment by dasilva333** [comment]
Perfect well done @matthubb I'm focusing completely on bugs at the moment but when I get a breather I'll integrate that script into my build folder. If you'd like to submit a pull request for adding that file to the build folder along with the reformatted files I wouldn't mind either. Thanks for your help

**Comment by matthubb** [comment]
As written, it's using relative paths from the current working directory and this being `TowerGhostForDestiny`. Is this okay? Or should the paths be modified so that it's run from `TowerGhostForDestiny/build`?

**Comment by dasilva333** [comment]
the paths should be modified so that it's run from the build folder indeed, keep it relative so no need to hardcode TowerGhostForDestiny in the script instead do something like ../www/js/

Thanks man

**Comment by matthubb** [comment]
PR #167 has paths relative from `build`

**Comment by dasilva333** [comment]
this has long been fixed as the code_format.js tool that is part of the build process. thanks to @matthubb
