### ISSUE TITLE
Loadouts stopped working in 2.5.1

### ISSUE THREAD

**Issue by seg7** [dasilva333/TowerGhostForDestiny#164]
...was ok in yesterdays version! Javascript console:

Uncaught TypeError: Cannot read property 'tierType' of null(anonymous function) 
@ loadouts.js:449t 
ga.js:38 crash reported

I guess it self reported in the last line :)
On a unrelated side note, there's a call to /www/cordova.js Failed to load resource: net::ERR_FILE_NOT_FOUND in index.html not packed inside the extension.

**Comment by dasilva333** [comment]
Can you confirm its fixed in 2.5.2 thanks?

**Comment by seg7** [comment]
Nope, same error with 2.5.2

**Comment by dasilva333** [comment]
Can you tell me or show me what's on the broken loadouts? Thx

**Comment by drammarb** [comment]
Faced the same issue with my crota's end weapons loadout. When I remove abyss defiant from the list, it works fine. May be this helps in solving the issue.

**Comment by ZeroGwafa** [comment]
My previously saved loadouts, both show, and load.  But when trying to make a new loadout with 2.5.2, I get the same JS "Uncaught TypeError: Cannot read property 'tierType' of null".  Looks like line 450 in loadouts.js?

**Comment by seg7** [comment]
Ok i guess what the problem is, all loadouts works fine since 2.5.2 but one, after adding/removing one by one the culprit is the Song of Ir Yût which i think it's the only weapon from all loadouts that currently sits at the vault, all other are equipped in the characters, maybe this can pinpoint the error.

**Comment by dasilva333** [comment]
yeah that's the problem expect the fix in 2.5.3

**Comment by dasilva333** [comment]
@seg7 can you confirm its fixed in 2.5.4? thx

**Comment by seg7** [comment]
@dasilva333 yes working flawless now, i though you closed the issue before :)

**Comment by dasilva333** [comment]
I'm glad, i don't see it being closed previously but thanks for the speedy response
