### ISSUE TITLE
(2.5.2) iOS (iPhone 6) Move menu icons in landscape very big

### ISSUE THREAD

**Issue by aap007** [dasilva333/TowerGhostForDestiny#166]
First of all.. I love this app! Thank you, Richard and everyone who contributed!

Just downloaded v2.5.2 and I am very happy with all the improvements I have seen so far.

I noticed that the icons in the move menu have become very big in v2.5.2, unnecessary consuming a lot of the precious space, see below.
![img_3591](https://cloud.githubusercontent.com/assets/10104857/7588707/069b7586-f8bf-11e4-84a6-f247df5610ff.PNG)
This only applies to the landscape layout.

The size of the icons for the loadout menu is perfect, so i would recommend this size for the move menu as well.
![img_3590](https://cloud.githubusercontent.com/assets/10104857/7588922/2d490774-f8c0-11e4-952d-6b9fae38b02f.PNG)

One small detail: in the loadout menu the icon's for 'vault' and characters could be aligned lower. (This also only applies to the landscape layout.)

In portrait mode it looks fabulous.

**Comment by dasilva333** [comment]
This has been fixed as of 2.9.3 try it out and let me know if it's gotten better thanks @aap007

**Comment by aap007** [comment]
I will check it out as soon as it becomes available for iOS.

Thanks in advance!

**Comment by aap007** [comment]
Issue solved! Thank you!
