### ISSUE TITLE
Inventory never loads

### ISSUE THREAD

**Issue by havvkeye** [dasilva333/TowerGhostForDestiny#168]
iPhone 6 using app through TestFlight

Stopped working around 2.5.1 and I sent an email, did not see a reply.

It is currently getting hung up on the blue loading bar screen after several updates, now running 2.5.3 still not being able to load the inventory.

**Comment by dasilva333** [comment]
Are you getting an error message? What blue loading bar is it stuck on?

There's currently two:
1. "loading user data" (problem with your account if its stuck here)
2. "please wait, loading your inventory" (problem with your connection if its stuck here)

Let me know so we can figure it out. Thanks

**Comment by havvkeye** [comment]
It is the second one.  It no longer has the screen asking me to log in, it just loads directly to this screen each time I open it.  I have soft reset my phone and still the same thing.  It happens on wifi and LTE when the destiny app seems to transfer and work fine.  (I am assuming you meant my connection to the bungie servers but more info is usually better than not enough)

**Comment by havvkeye** [comment]
I am an idiot - sorry for wasting your time.  I found the answer in your known issues log and it is working now.  I did in fact need to log in through settings.
