### ISSUE TITLE
Burn filter not working for Kinetic weapons

### ISSUE THREAD

**Issue by maverick171** [dasilva333/TowerGhostForDestiny#17]
As of 1.6.3, When I select kinetic weapons from the filter, no weapons show up in any characters or the vault. Even when selecting it with another burn type, kinetic weapons don't show.

![image](https://cloud.githubusercontent.com/assets/11897268/7100657/1e7fc186-e026-11e4-9693-03de8f2d9ca1.jpg)
![image](https://cloud.githubusercontent.com/assets/11897268/7100658/1ea2f7a0-e026-11e4-9f2e-d75781d87f1e.jpg)

**Comment by dasilva333** [comment]
Bug has been already fixed, please try the latest Chrome version 
https://github.com/dasilva333/TowerGhostForDestiny/tree/div-movile-dist
https://github.com/dasilva333/TowerGhostForDestiny/
to make sure it's been resolve and then close the ticket thank you.

**Comment by maverick171** [comment]
Sorry, forgot to mention I'm using iOS version 1.6.3, where the issue is happening.

**Comment by dasilva333** [comment]
Problem has already been fixed in the latest version please do not report any bugs found in the FlightTest unless you can also reproduce it in the latest version of Chrome thanks
