### ISSUE TITLE
Android Landscape versus Portrait icon size/display

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#172]
In versions 2.4.x, when in portrait mode, it shows two columns. In landscape, it shows four columns. This was perfect on my Nexus 7 (2013). But on my Nexus 4, it always only show two columns--resulting in overly large icons in landscape mode. On the smaller Nexus 4 screen, perhaps three columns in landscape is the best compromise since 4 columns will make the icons too small and hard to operate?

**Comment by dasilva333** [comment]
Just tell me what you think looks best and I'll change it. I can control the # of columns for each individual device so give me your desired outcome:

Nexus 7: 1 portrait, 3 landscape
Nexus 4: 2 portrait, 3 landscape 

I improved it the best I could but without the physical device in my hand I can't tell if it looks too small or not. Thanks for your feedback

**Comment by M3Rocket** [comment]
Nexus 7 (both 2013 and original): 2 portrait, 4 landscape
Nexus 4: 2 portrait, 3 landscape
Nexus 5: 2 portrait, 3 landscape

**Comment by dasilva333** [comment]
Got it, it won't be fixed any time soon because I'm focusing on bugs but your feedback does help get it right once and for all, thanks

**Comment by revdarwin** [comment]
iPhone 6.  2 columns in portrait and 3 in landscape.

**Comment by dasilva333** [comment]
@revdarwin I disagree I think 2 column portrait in iPhone 6 looks too small, I'm only supporting 2 column mode in iPhone 6+. I will make sure that iPhone 6 has 3 columns in landscape. Thanks for your feedback

**Comment by Doubleken** [comment]
My phone is 6'' Huawei mate 7 1920x1080, wish can display 4 columns in landscape. (Now in 3 columns)
Or make a option, that we can choose how many columns?

**Comment by NoCodeLeftBehind** [comment]
Samsung Galaxy S4 Active
Portrait: 1 column (currently shows 2 but is too small)
Landscape: 3 columns (currently shows 2 but room for another)

**Comment by lllgurulll** [comment]
Please keep it at single column for phones,  two column on an LG G2 makes the boxes too small

**Comment by dasilva333** [comment]
I'm going to be working on this issue today so expect the fix on 2.6.3 thanks guys

**Comment by dasilva333** [comment]
Hey guys I added the ability to set the number of columns on the app as well as improved the default size for a lot of screen sizes so im closing this issue, feel free to open a new one in the future if there's something more wrong
