### ISSUE TITLE
View Options: # of columns and show Vault as the last column (rightmost) rather than first (leftmost)

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#174]
Currently, the Vault is always in the first column shown in TG. I suggest moving it to the last column for a couple of reasons:

1. Usually, when I need to move a couple of items, it is usually because it is equipped on another character rather than in the vault. For example, when I'm running Crota's End, after one kill with my Titan, the group usually goes again with their next character, or Warlock in my case. I usually then have to quickly move a couple of weapons between the characters. This is more difficult than it needs to be on mobile (two columns) since the first column is the Vault. 

2. The only column that isn't the same height with "Auto Pad Height" (when working properly) is again the Vault. Visually, I think it's visually jarring to basically have the only non-matching height column to the farthest left rather than being on the farthest right. 

3. The priority should always be the characters' inventories because the vault is mainly used for storing or moving weapons/items. Items that are used a lot are usually equipped or stored on characters. It stands to reason then that the characters' inventory should be shown before the vault's.

**Comment by dasilva333** [comment]
I don't know man I don't like the right side simply because that's DIM's side and I don't want to feel like I'm imitating them I suppose there's a lot of valid reasons for putting it on one side or the other, perhaps make it an option and please everyone involved. I'll leave it open for discussion for now. Feel free to message @bluetidepro for an invite to slack, read issue #170 for more info

**Comment by chrisdudek** [comment]
It's definitely a personal preference issue. I like it first because I store everything I can in the vault and use that as my Starting Point. After I'm done with any of my characters, I always move my valuables back to the vault.

For your specific issue, I would suggest creating Loadouts. For example, you could have a Crota Loadout and then simply "equip" that Loadout on your Warlock after you're done with your Titan (using your example).

I'm not trying to diminish your preference for it on the right, but I think it's something that should be an option rather than just changed.

**Comment by M3Rocket** [comment]
Loadouts work fine until you have duplicate weapons and near full inventories. Then items start getting moved willy-nilly to make room. Without the ability to lock weapons to certain characters, it quickly becomes a problem just trying to figure out where certain weapons are moved. 

The Bungie site has the vault flyout on the right. It just makes more sense to me since the storage vault isn't the character I play with that it'd be least accessed. If you're moving stuff back into the vault after you're done with the character, it just seems superfluous now that we have an app to move items between characters. That seems like a habit from when we had to fly back to the tower to store items into the vault so that we can pick it up with the next character. 

I don't see the point of moving frequently used weapons back into the vault. With the ability to transfer any weapon between characters easily without going to the tower, it would seem like all you'd do when you're done with one character is to switch to the next and move the weapons using the app. Why bother moving it back to the vault at all? In my case, I couldn't do that anyway since my inventories are almost always nearly full anyway, often with one slot open at each for transferring.

Moving weapons are the main convenience of the app--most other consumables and materials are "non-critical" because they are plentiful of each, splitting 1000 weapon parts between characters is just fine since there's always plenty of space on most character inventories for consumables. Also, they can stack. Besides, a lot of the other items like strange coins, motes of light, commendations, etc. I never need unless I'm in the tower. Weapons are plentiful in a different way, and is swapped more often than any other type of inventory for obvious reasons. 

@dasilva333: I think an option for either would be fantastic. As is, it's just more difficult than it should be to move a couple of weapons from one character to another on a mobile phone with two columns since by default, you only see two columns in portrait mode. Since the active character is always the leftmost column (second only to the Vault currently), you have to scroll a ways down to get to the inventory of the other two characters.

**Comment by M3Rocket** [comment]
BTW--none of this is an issue on a larger computer screen with a mouse and keyboard of course since one can easily have all four columns on the screen at once.

**Comment by M3Rocket** [comment]
I've been thinking more about this in a general way. Perhaps instead of just an option to position the Vault column, maybe provide a way to order the columns. That way, people would be free to choose how they want their columns to be displayed. And while we're at it, provide a way for people to specify number of columns shown on their device:

![tgd-view-options](https://cloud.githubusercontent.com/assets/3769123/7644251/2e0c01c8-fa57-11e4-9cbb-98c844ab934d.png)

**Comment by M3Rocket** [comment]
Perhaps merge https://github.com/dasilva333/TowerGhostForDestiny/issues/172 with this one.

**Comment by Mulchman** [comment]
@M3Rocket I like the idea of being able to rearrange the Guardian ordering and having them always be constant in whatever order the user set.

**Comment by dasilva333** [comment]
@M3Rocket I think that dialog is brilliant it addresses a lot of the concerns various people have address over time, I'll keep #172 open because I'd still like to fix the default for those devices. 

I'd also have to consult @bluetidepro and see if there's an easy way to dynamically switch the breakpoints for the number of columns. Let me know thanks

**Comment by dasilva333** [comment]
@M3Rocket  can you confirm you see the new view options?

**Comment by M3Rocket** [comment]
@dasilva333 I can see the option under the "View" menu, but when I try to select it, it simply collapses the menu and I don't see the dialog box for the view settings. This is with 2.6.5 on both my Nexus 7 (2013) and Nexus 4. 

I'd also suggest that since this isn't technically a "filter" to move that menu option to Settings instead.

**Comment by dasilva333** [comment]
It's not a dialog box popup so it doesn't pop up it shows at the top of the page, the menu bar isn't automatically closing when you pick the option that's going to be fixed, I didn't want to continue to clutter settings with more options so I'm leaving it under View

**Comment by M3Rocket** [comment]
I see. It's confusing the heck out of me to select that option and not see it pop-up on the screen since the menu is now blocking it.

What does the XS, SM, MD, and LG correspond to? Meaning how is the cutoff point determined? Number of pixels? I think it can get confusing.

Also, when Vault Position is set to Last/Right, and columns are set to 3, the Vault shows up right-justified on the next row. I think it should be left-justified on the next row when # of columns is set to 3.

**Comment by dasilva333** [comment]
Closing this issue in favor of issue #292
