### ISSUE TITLE
Suggestion: Transfer Item Dialog Box

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#177]
I store all the weapon telemetries in my Vault. Often times, I find myself needing just one of each telemetry when turning in bounties. Using Tower Guardian on mobile/tablet requires using the pop-up keyboard to override the default value which is the max amount. The keyboard does NOT pop-up automatically on Android, and I need to click on the amount number to bring it up, then backspace over the amount, and type in "1." 

Is there a way to include two buttons for "Min" and "Max" right next to the amount dialog box so we can just click/tap a button instead to get one or max (the most common choices I'm guessing)?

![tgd transfer](https://cloud.githubusercontent.com/assets/3769123/7622998/6ae82202-f98a-11e4-8493-acce3134adb5.png)

**Comment by M3Rocket** [comment]
Maybe even add "spinner" controls:

![tgd transfer](https://cloud.githubusercontent.com/assets/3769123/7623128/aaf91b66-f98b-11e4-83b3-7f894b5bc9fb.png)

**Comment by Mulchman** [comment]
I like these ideas.

**Comment by dasilva333** [comment]
This is a good one thanks man

**Comment by M3Rocket** [comment]
@Mulchman Since this dialog appears when you click on a specific item from a specific location (vault/character), "All" does mean from one specific location to another. Although the buttons can simply say "Min" and "Max."

As for the scenario where you want to consolidate all the same items from multiple locations to one character, I think perhaps a good place for this "Consolidate" button would be on the "Extras" dialog box where "Normalize" is right now in Issue https://github.com/dasilva333/TowerGhostForDestiny/issues/122

**Comment by rkingsla** [comment]
There seems to be ‘some’ confusion over the term ‘Normalize’.  I get it, but others seem to find it…  Odd. If I’m missing the wrap up over that discussion, apologies and disregard.

 

Might I suggest “Distribute’?

**Comment by rkingsla** [comment]
Disregard, guys...  I've been out of town since Sunday and just noticed the Normalize - distribute across characters dialog....  Nice add.  Great work!

**Comment by Mulchman** [comment]
Noob question: what's the CSS class to use to make the buttons look like the BootstrapDialog.alert() 'close' button? I've tried various things: btn-default, btn-primary (and others) and they don't match.

**Comment by Mulchman** [comment]
#207 was accepted, so closing this issue for now.

**Comment by M3Rocket** [comment]
@Mulchman Any way of showing the item name or icon in the transfer dialog easily? The dialog appears at the top center of the window and positioning-wise, makes it quite ambiguous as to what I'm transferring especially when distracted.

**Comment by Mulchman** [comment]
@M3Rocket certainly. "Transfer Materials - Heavy Ammo Synthesis" - something like that?

**Comment by M3Rocket** [comment]
@Mulchman Yes please! That would be nice.

**Comment by dasilva333** [comment]
This has been much been completed and done, Im closing out this ticket. Feel free to open a new one for @Mulchman if there's anything else that needs done
