### ISSUE TITLE
Loadouts should not allow multiple Exotics to be "equipped"

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#178]
Currently, one can select multiple Exotic Armor/Weapons to be equipped and saved as a loadout. This will obviously result in an error when you try to apply that loadout to any character.

![tgd-bug](https://cloud.githubusercontent.com/assets/3769123/7624754/a169b06c-f9a2-11e4-83cb-9434008e338f.png)

TG should only allow one exotic armor and one exotic weapon to be equipped in any loadout.

**Comment by dasilva333** [comment]
Changing to bug because it actually results in an error mid transfer. Thanks for the report

**Comment by M3Rocket** [comment]
Copying this from Reddit because it's relevant to this discussion:

Hey, sorry I probably made myself unclear. As you suspected I am talking about loadouts. But it seems to me, loadouts are applied from top (Helmet) to bottom (Legs). But if you have an exotic equipped on your chest and then try to apply a loadout with an exotic helmet, the helmet is not equipped.

I hope I made myself clear this time. If not, in a Titan example: Make a loadout with St 14 equipped and one with Armamentarium equipped. Try switching back and forth between those loadouts and I think you will see what I mean!

And great work by the way, love using the app!

**Comment by M3Rocket** [comment]
I think this could be solved by implementing a refresh and check before equipping (not transfer and store) in this particular logic:

1. Is there an exotic to be equipped in the loadout?

2. If the exotic being equipped is armor, is it being applied to the appropriate Guardian type (Titan, Warlock or Hunter)?

3. Is there already another exotic armor/weapon equipped on destination Guardian? If yes, does the loadout contain non-exotic armor/weapon to swap with the currently equipped exotic (to free up the exotic slot for inbound equipment from the loadout)? Unequip/swap the existing exotic first. Then equip the rest of the non-exotics. Last step is to transfer and equip the inbound exotic from the loadout.

Hope that was clear. Of course, all the other rules regarding non-exotics need to be incorporated amidst the rules outlined above.

**Comment by dasilva333** [comment]
Fixed in 3.0.1 thanks
