### ISSUE TITLE
Auto-equip when items are already in buckets

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/TowerGhostForDestiny#18]
If I equip a load out where the items are already in the characters inventory, I get a screen that tells me there is nothing to transfer, but the items do not get equipped.

**Comment by dasilva333** [comment]
expect it fixed in 1.7.5 thanks man

**Comment by dasilva333** [comment]
it works completely as of 1.7.7 please try it and confirm thanks

**Comment by dasilva333** [comment]
closing this ticket in favor of issue #13 it includes all the possible problems you encountered with loadouts thanks man
