### ISSUE TITLE
SET filter - select All with Show Missing Items

### ISSUE THREAD

**Issue by Solhawk17** [dasilva333/TowerGhostForDestiny#180]
A trapped error occurs when in the "Set" filter with "Show Missing Items" selected. In this filter select Exotic Weapons, then select "All". Error happens when "All" is selected.

Application requested I post this on GitHub.

Cheers!

**Comment by dasilva333** [comment]
Expect it fixed in 2.5.6 thx

**Comment by dasilva333** [comment]
@Solhawk17 can you confirm this is fixed in 2.5.8? thanks

**Comment by Solhawk17** [comment]
It works!

**Comment by dasilva333** [comment]
Cool man thank you for your feedback closing this ticket now

**Comment by Solhawk17** [comment]
Richard,

I have an enhancement request, but I'm not sure if it's possible.

When you hover over a weapon, you can see the weapon stats/numbers like
this:

[image: Inline image 2]

Is there a way to see these weapon stats/*numbers *AFTER the perks have
been applied? For instance, Six Dreg Pride, the RANGE stat nearly doubles
after the perk HAND LOADED is applied. I would like to know the *actual
value* of range after the perk is applied.

OR if you know how I can get this information, I'd really appreciate it.

Thanks,

-Hank

**Comment by dasilva333** [comment]
Sorry no can do, that information isn't available in the API so even if I wanted to I couldn't render that type of information on top of the existing tooltip. Cool idea though thanks anyways

**Comment by Solhawk17** [comment]
Cool thanks for the quick reply!
