### ISSUE TITLE
Visual Indicator for a full Vault

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/TowerGhostForDestiny#184]
Ran into this the other day, didn't realize that I'd filled my vault of weapons and I wasn't able to transferring anything until I freed up some space. It would be nice to have a visual indicator (like turning the Weapons header red if there's no space).

Screenshot attached of the section I'm talking about:

![](https://i.imgur.com/Eg0FmAX.png)

If that reaches 36/36 then turn that section red, or some other indicator.

**Comment by bluetidepro** [comment]
No problem @ssoriche, I can easily do this! I'll show you a few solutions here in the next few days and you can let me know what you prefer! :+1:

**Comment by rkingsla** [comment]
Great idea, really.  I've run into this a few times.  Might I suggest flashing bight green neon?  ;o)

**Comment by dasilva333** [comment]
this will be fixed as of 2.9.3
