### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#185]
Enable us to drag and drop items between characters/slots, like in new version of DIM (v3.0+). I figured there would be a ticket for this already and it's just on the back burner or something, but I didn't see any.

**Comment by dasilva333** [comment]
I want something that works both on mobile and desktop so I've been holding off on that until I find a solution that works right. Also lots of bug fixing going on

**Comment by M3Rocket** [comment]
Drag and drop works well with a mouse and large screen. I don't think it works as well on small to tiny touch screens on mobile devices. Using a finger just isn't very precise. I suggest consider implementing this only on the Chrome/FF plug-ins. 

I can already forsee all kinds of problems of where did I drop the item when people try to use drag and drop on their phones, and they hit the edge of the screen and it starts scrolling. Or if their fingers lift off the screen at the wrong time for whatever reason.

**Comment by dasilva333** [comment]
Agreed it's a very sensitive topic where a lot can go wrong easily so I won't approach it lightly. Thanks for the feedback @M3Rocket

**Comment by dasilva333** [comment]
Drag and drop has been implemented in TGD since 3.x.x
