### ISSUE TITLE
iOS Horizontal View

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#186]
Love the new look from 2.5.7, but it introduced some viewing issues on the iPad in horizontal view. 

1: Top bar now covers 1/4th of the screen

![image](https://cloud.githubusercontent.com/assets/2903357/7645573/eb3fa54c-fa84-11e4-81f3-4f5b6c0df0bc.jpg)

2: Loadouts only work in horizontal view, clicking them in vertical mode does nothing
![image](https://cloud.githubusercontent.com/assets/2903357/7645591/194d453e-fa85-11e4-9c83-155eaa0ded86.jpg)

**Comment by bluetidepro** [comment]
@pattont I'll take a look at these issues and get them fixed :)

**Comment by pattont** [comment]
Awesome thank you!! This app is so great..



On May 14, 2015 at 10:09:37 PM, Zach Reed (notifications@github.com) wrote:

@pattont I'll take a look at these issues and get them fixed :)

**Comment by matt-cahill** [comment]
Came here to report the same bug. Would also like to commend the awesome-ness of the new look!

On a side note I can use the load out menu in vertical mode, I just have to tap it and then scroll the menu up to show the revealed options.

**Comment by dasilva333** [comment]
Problem was fixed as of 2.6.3 please confirm

**Comment by matt-cahill** [comment]
Confirmed. Thanks!
