### ISSUE TITLE
Little grey boxes on items with no associated stats

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#188]
Just a small visual bug. On weapons, combat armor, and stackable items, there is a box displaying a number indicating the attack, defense, or number of items. On other items there is a little box in the corner instead where the number would usually go. I'm guessing that shouldn't be there. This has been an issue for a while, just filing a ticket now. 

![screen shot 2015-05-14 at 7 04 42 pm](https://cloud.githubusercontent.com/assets/4229542/7645902/c0f36f26-fa70-11e4-9725-b5591337eba1.png)

**Comment by M3Rocket** [comment]
FYI--this was also present prior to 2.5.7. You can also see it in the old design that was reverted in 2.5.8. Except because it isn't a rounded corner, it's easy for the eye to miss it.

**Comment by wickles** [comment]
Umm, I'm still seeing this bug? Haven't been playing as much so I'm not sure if it was fixed with that merge, but I still see the boxes in 2.9.9.

**Comment by dasilva333** [comment]
Taken care of thanks @wickles expect it fixed in 3.0.1

**Comment by wickles** [comment]
Fixed now, thanks.
