### ISSUE TITLE
Changing which account Tower Ghost loaded up

### ISSUE THREAD

**Issue by Volcannon** [dasilva333/TowerGhostForDestiny#190]
It would be nice if my PSN wasn't the first thing Tower Ghost loaded up, considering I mostly use my Xbox One.

**Comment by Volcannon** [comment]
Perhaps if there was an option to remember which account you used last so that next time when it loaded up, it would go directly to it.

**Comment by dasilva333** [comment]
Thanks man I'm glad someone finally made a ticket so I can care of it.

**Comment by Volcannon** [comment]
No problem.

**Comment by jimeh** [comment]
:+1: I'd like to see this too :)

**Comment by dasilva333** [comment]
Hey @Volcannon @jimeh can you confirm it's been fixed as of 2.6.9? Thanks

**Comment by jimeh** [comment]
Yep, it's fixed. Properly remembers which account I last had loaded :)

**Comment by Volcannon** [comment]
Yes, it works like a charm. Thank you very much.
