### ISSUE TITLE
Loadouts are not appearing in menu after being uploaded to the cloud.

### ISSUE THREAD

**Issue by Los556** [dasilva333/TowerGhostForDestiny#191]
I created a loadout and hit save, app says it was saved to cloud, then when I go to loadouts there's nothing there except for create and cancel. I'm using a Kyocera Hydro Android phone.

**Comment by M3Rocket** [comment]
Try scrolling the menu upwards on Android. It's "hidden" below the menu cutoff after tapping the loadouts menu option.

**Comment by Los556** [comment]
After tapping loadouts it only says create and cancel. No loadouts show up, I've created two Crota and Vog, neither show up.

**Comment by M3Rocket** [comment]
It works for me. I created one called Android Test on my Nexus 4, and it saved and shows everywhere else. Try clearing the app cache and restarting TGD--it will force it to redownload the 2.5.7 update.

**Comment by Los556** [comment]
That worked, actually had to clear data. Thank you.
