### ISSUE TITLE
Loadouts wont move secondarys or heavys

### ISSUE THREAD

**Issue by brownbearDaniel** [dasilva333/TowerGhostForDestiny#193]
![screenshot_2015-05-16-09-41-36](https://cloud.githubusercontent.com/assets/12470855/7665480/ccf32d66-fbb0-11e4-9920-bd62c25cad63.png)

**Comment by rkingsla** [comment]
Hey, brownbearDaniel....  thanks for the report.

Which version? When this occurs, can we get a screen shot of the vault and for the Primary bucket that it says it won't be moved to? Looking at the code, it APPEARS that the bucket on the Wolf emblem character is full (10 items).

Can you confirm and provide some added details, including screenshots?  MUCH appreciated!

**Comment by dasilva333** [comment]
@brownbearDaniel @rkingsla this has been fixed as of 2.9.2+ try it out and let me know if you still have any issues thanks
