### ISSUE TITLE
New post-patch engrams not showing up

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#194]
Looks like the new engrams obtained after the 1.2 patch are not showing up. I believe most (if not all) of these engrams were obtained doing the queen's bounties, but I'm not sure that matters.

I'm seeing them on my console and via bungie.net, but not on TGD. I do see older engrams thought, so it is definitely something to do with new ones.

**Comment by M3Rocket** [comment]
Any engram containing HoW items will not show on TGD, and will not be decrypted by Rahool until 10am PDT on Tuesday 5/19. My guess is that these have new "SKU's" in the API that Richard has not added yet to TGD.

**Comment by schubydoo** [comment]
Note: DIM has this functionality.

**Comment by dasilva333** [comment]
@M3Rocket @weborican can you guys confirm if it's fixed in 2.5.8?

**Comment by rkingsla** [comment]
It is....  All of my recently obtained HoW engrams now show up as expected and the count for weapons, etc. is now accurate where it was off by whatever number of HoW item engrams were in storage.

I think you can close it as far as 2.5.8 is concerned.

**Comment by weborican** [comment]
It is all looking good at my end. Damn (I'm looking at you Pack of Wolves), I've got me an insane number engrams!!!

I agree with @rkingsla , I think you can close the ticket now.
