### ISSUE TITLE
Postmaster public event packages not showing

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#195]
I'm not sure if they are supposed to show, or if they ever have, but I'm not seeing any of my daily public event packages that are at the postmaster on TGD. I currently don't have anything else waiting for me there, so I can't tell if this is only an issue with these packages or with all postmaster items. I will update this ticket if I manage to get something else in there that shows up on TGD.

**Comment by M3Rocket** [comment]
Public Event packages were never shown on TGD as far as I remember. When you go to the Postmaster in-game, there are two sections. TGD only shows what is on the bottom section--which can contain up to 20 items.

Not sure if this was a limitation with the Bungie API.

**Comment by dasilva333** [comment]
I'm not sure if it's an API limitation or if I missed adding it to the Post Master section. I'll check it out and close this ticket if it can' be done.

**Comment by M3Rocket** [comment]
@dasilva333 I see Bungie's revamped site is now showing all 40 items for the postmaster. Not sure whether they just made it available via API. I remember that Bungie's site also always only showed the bottom group of 20  and not the top group of 20.

**Comment by dasilva333** [comment]
problem will be fixed in 2.7.3 thanks
