### ISSUE TITLE
Landscape mode on iPad shows search bar / refresh all the time

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#196]
On the iPad, viewing TGD on landscape mode shows the search bar and the refresh timer fields all the time.
![img_0195](https://cloud.githubusercontent.com/assets/12019978/7667445/5eb65806-fbcd-11e4-8b87-654db60d3a99.jpg)

**Comment by M3Rocket** [comment]
@bluetidepro Maybe consider "-" and "+" buttons to the left and right of the "Refresh Timer Input." On mobile, those tiny up/down arrows are impossible to hit correctly.

**Comment by NoCodeLeftBehind** [comment]
Same problem and note that, as pictured, this obscures the Vault and character headings. Also, is the refresh timer box even necessary? I doubt most even use it, and it unnecessarily clutters up the UI. Perhaps move it to an advanced settings page or something (which I think you will need eventually for other customization settings).

**Comment by rkingsla** [comment]
Just adding that this also repo's on iPad mini.  Likely not a surprise, but for full clarity and awareness.

**Comment by M3Rocket** [comment]
Thinking about this more, perhaps it's better to move this to the settings dialog. The number by itself on the menu bar is confusing since there is no label. Frankly, probably only a very few choose to change it from 300 seconds IF they have Auto Refresh set on anyway.

**Comment by rkingsla** [comment]
Not diminishing M3Rocket's comment above, the layout issues on iPad mini seem to be resolved. Everything works as expected.  Nice job, team!

**Comment by dasilva333** [comment]
Thanks for the feedback guys, as the patch notes state I reverted the new style until issues like this one are resolved on all platforms, it seems it's been taken care of we're just battling some other details with the new style. Regarding that field I do agree it's better fit for somewhere else but it's not going to change until the new flyout menu is added.

**Comment by dasilva333** [comment]
Problem has been fixed as of 2.6.3 please confirm thanks

**Comment by weborican** [comment]
Confirmed working perfectly on iPad, iPhone 6 and Nexus tablet. Thanks!
