### ISSUE TITLE
Add informations about raids and missions

### ISSUE THREAD

**Issue by magictony31** [dasilva333/TowerGhostForDestiny#197]
Hello,
thanks for this application ! It's great !

But i think it could be perfect with more informations, and specially the informations about raids and weekly missions. We could see at a glance wich character we should take to make Crota's end in level 33...

Thank you

**Comment by rkingsla** [comment]
I’m going to leave the bigger design decisions to Richard – he’s done a great job so far.  I like your idea, but I’d say that we need an awesome tool to manage content across characters.  That’s this tool. And, this tool needs to stay laser-focused on this.

 

IMHO, adding features that don’t enhance this goal are meant for other apps.  Perhaps Richard would want to start a similar project that would interact with this app? Adding more things to an existing app of this magnitude might threaten to become the Microsoft Word (huge, bloated, 90% of features not used except for maybe 5% of the user population – and yes, I fall into that 5% (Professional Tech Writer)) of Destiny apps.

 

Leave TGD to do Tower Duties. Destiny Informer or Destiny Tracker (I have no idea if these are available names or even worthy) might be that new app that would track most other things NOT inventory. Right now, this app does A LOT of stuff that the competitors/co-op-petitors (recall where TGD started…) do not do. And it does these things really well. I prefer to stay on that path. Another app that can use TGD, and TGD use the new app – I’m all for it.

 

And, FWIW, most things LIKE progress in raids etc. are only partially available from Bungie. You can determine (Crota for example) if you have defeated Crota or the Deathsinger on Lvl 33 or Lvl 30. You can’t know if you have looted the Abyss chest or the Thrall hallway chest – regardless of Level. It’s just the limits of what Bungie currently exposes.

 

Just my .02(insert your currency symbol here)

**Comment by dasilva333** [comment]
Agreed,don't want a bloated app and it doesn't make sense to put this in an inventory app.
