### ISSUE TITLE
Show glimmer and marks

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#199]
This is mostly just a "quality of life" type request. Websites like destinystatus.com show your glimmer and vanguard/crucible marks for all characters. I think would be nice to show these somewhere in TGD.

**Comment by dasilva333** [comment]
Perhaps in the future with a different UI it could be done, not with the current navbar

**Comment by pattont** [comment]
Could it be on a popout which shows just some random information about your character. I'm not sure if number of hours are accessible along with glimmer, marks, currrent bounties selected? Just spit balling :-)

**Comment by dasilva333** [comment]
Closing this out, you can access DestinyStatus from the menu as a pop up within the app. thanks for the feedback guys

**Comment by rkingsla** [comment]
And, it’s awesome!  Exactly what I think the use case is all about.
