### ISSUE TITLE
Auto-Hide Main Menu After Selecting Loadout for Mobile 

### ISSUE THREAD

**Issue by chrisdudek** [dasilva333/TowerGhostForDestiny#2]
Suggestion: after selecting an option under Loadout (Create, or the name of a saved Loadout), show the Loadout section at bottom and hide the main menu.

Right now, after you hit create or select the loadout you want, you have to hide the main menu (hamburger button) before you can really perform another action.

Much more efficient to auto-hide this menu so the end user can go right into their next step.

Thanks!

**Comment by brazenisgod** [comment]
I think even better would be to add a toggle on the far left of that bar.  might be hard to get it back if its autohidden methinks.

**Comment by dasilva333** [comment]
Problem fixed expect it in 1.7.3

**Comment by dasilva333** [comment]
Menu bar auto closes when creating or selecting a loadout, please verify it's been resolved and close the ticket once you do 
thanks

**Comment by chrisdudek** [comment]
Works like a charm.
