### ISSUE TITLE
Menu Behaviour on iOS TestFlight 1.7.1

### ISSUE THREAD

**Issue by matthubb** [dasilva333/TowerGhostForDestiny#20]
Observed:

If you select an option from the menu like Refresh or View / Weapons, the menu stays open after selection. 

Expected:

Usually selecting an option from a drop down menu closes the menu automatically.

**Comment by dasilva333** [comment]
Expect it fixed in 1.7.5 release

**Comment by dasilva333** [comment]
problem fixed in 1.7.6 please retest and close ticket thanks

**Comment by dasilva333** [comment]
Problem has been fixed with no reply closing this ticket
