### ISSUE TITLE
App stuck on the inventory loading screen on iPad

### ISSUE THREAD

**Issue by westonsouza** [dasilva333/TowerGhostForDestiny#201]
Since I launched the app this morning on my iPad I have been unable to get past the inventory loading screen. I chose not to install the update on my iPhone due to the issue, so don't know if this affects other devices.

**Comment by jbkly** [comment]
I'm having the same issue on Android, starting this morning. On loading the app it stays on "Please wait, your inventory is loading..." indefinitely. Restarting the app and restarting the device don't fix it.

**Comment by Mulchman** [comment]
I had this as well. Ended up deleting app cache to essentially make it
rehydrate to latest. Worked after that.

**Comment by westonsouza** [comment]
I still have this problem after updating

**Comment by unclben** [comment]
I have the same problem (stuck at "your inventory is loading" on my HTC One M7. 
Clearing cache didn't make a difference.
Next I tried clearing all app data. After signing back in to XBL, now it gets stuck on "loading user data" instead.
I then tried uninstalling/reinstalling the app completely, and again I get stuck at "loading user data".

**Comment by Mulchman** [comment]
What can we do to help figure out this problem? It's happening more frequently on my Android tablet and Android phone, and a buddy had it happening on HoW launch day. My steps to "fix" have been to force stop the application, clear data, then start the app and do the hydration + sign in.

**Comment by dasilva333** [comment]
I totally missed this one @westonsouza have you managed to get it to work?

**Comment by westonsouza** [comment]
It is working now. It must have been related to something else you fixed.

**Comment by unclben** [comment]
@dasilva333 Mine is working again, too, as of maybe 3 days ago. No idea what changed. I'm pretty sure it happened after I did a reinstall but did NOT update upon opening the app, but I can't swear to that.

**Comment by pattont** [comment]
Yea, lately I am finding that the iPad app is near impossible to use on my iPad Mini or iPhone 6 because the load times are so bad. When the first beta for iOS was available it was AWESOME and has slowly (sorry for the pun) become unusable due to load times. If I uninstall the app and re-install it works ok that time, but force closing and re-opening it leads to the horrible inventory load once again.

:-( :-( :-(

**Comment by pattont** [comment]
Just an update - this one appears resolved because the newest versions have been loading quickly on my iPad. Excellent work!!!
