### ISSUE TITLE
Suggestion: Prefer the old layout/design to the new one

### ISSUE THREAD

**Issue by kohum** [dasilva333/TowerGhostForDestiny#202]
Ok. This isn't really an enhancement. But I really like the old design/layout compared to the new one which felt like it was taking up too much space and  hence required more scrolling. I found that it was faster to find stuff with the old design.  I know that we have reverted back to the old design for  now and would really like it to stay that way. :) Thanks !!!

**Comment by xdtrammell** [comment]
I like the new gui so much more then the old one. If you are going to take it away as the default please let us use it as an option. I play with my pc right next to me and I have plenty of screen real estate and I loved the new GUI.

**Comment by kohum** [comment]
So do I.  I have my pc next to me.  I just find that without the extra thick borders etc, the old layout still worked better and also collapsed better when you are filtering things out.  The new layout for some reason did not collapse properly and I still had to scroll up and down looking for stuff.

**Comment by dasilva333** [comment]
Thank for your opinions everyone, closing this out since there's nothing to do here however I do agree there were drawbacks to the new design on how the space was managed. Expect the new style back sometime in the future when it's ready for all platforms.
