### ISSUE TITLE
Visual differentiator to identify HoW engrams

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#206]
Taken directly from DIM, but it is super nice/helpful to see which engrams are HoW and which aren't (especially now, before HoW drops).

![how engrams](https://cloud.githubusercontent.com/assets/12019978/7683066/1a3ec4da-fd42-11e4-9d18-7aa74b02ae1f.png)

**Comment by rkingsla** [comment]
Nice idea, I like this....

The downside is - obviously - the time (potentially) to implement, test and deploy might exceed the cost benefit for about 14-15 or so hours before it becomes completely irrelevant (as HoW is going to make all engrams equal play partners, which I'm sure you know...).

Good thing I don't make these decisions, right?  ;o)

**Comment by weborican** [comment]
Oh, I totally agree/understand... but maybe worth the code to handle this for when this happens again (Comet?) :-)

**Comment by rkingsla** [comment]
Yes, absolutely!  Good point....

**Comment by dasilva333** [comment]
@rkingsla is right putting this one on the back burner leaving it open as an enhancement thanks for the feedback guys

**Comment by dasilva333** [comment]
The images being produced by Bungie automatically have the little I and II on the top right corner closing this issue as fixed
