### ISSUE TITLE
Enhancement: Add ability to lock/unlock weapons and items

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#209]
Bungie's new site adds the ability to lock/unlock weapons and items. The new icons also show the status of the lock as well. I think these would be a good additions to TGD.

![tgd_lock](https://cloud.githubusercontent.com/assets/3769123/7688728/d4fb2db8-fd5b-11e4-9e9c-12098536fa42.png)

Maybe a quick double-click on the item icon would toggle lock/unlock and the visual indicator?

**Comment by dasilva333** [comment]
I actually had coded the ability to see the locked state already but then I removed it because their API wasn't ready. I think being able to at least see the state is pretty important for the app. Thanks @M3Rocket

**Comment by Mulchman** [comment]
I thought this would be something easy for me to add - displaying whether stuff is locked or not - but I can't get the alignment right after ~45 minutes of tweaking. Help me w/ the CSS please (http://imgur.com/wKU37D7). :(

![KnowNoCSSMagic](http://i.imgur.com/wKU37D7.png)

**Comment by Mulchman** [comment]
Might need the elusive @bluetidepro to make an appearance? I just don't understand what impacts what with respect to the <div> arrangement(s) and the CSS stuff.

**Comment by Mulchman** [comment]
Coming soon...
