### ISSUE TITLE
iOS TestFlight 1.7.1 - XHR timeout / retry

### ISSUE THREAD

**Issue by matthubb** [dasilva333/TowerGhostForDestiny#21]
I'm temporarily on an internet connection that appears to have upstream session contention. Latency isn't a problem, or speed, but some TCP connections seem to fail to start. You could call this packet loss on connection attempts. 

In the app I'm seeing this as my third character doesn't load and the barber pole stays on indefinitely. 

I can't easily investigate here, but are the requests to the Bungie API wrapped in timeout / retry logic? If a timeout is occurring, it doesn't seem like it is being handled.

**Comment by dasilva333** [comment]
Good point sir, the code in bungie.js has an onerror handler that just resorts to throwing a dumb error I'll look into getting that improved in the future so it can retry instead

**Comment by dasilva333** [comment]
The onerror handlers for all requests with the bungie API now have 3 max retry attempts before giving up, I'd ask you to try and reproduce it but it's a hard one. Feel free to leave any additional feedback. Closing this ticket

**Comment by matthubb** [comment]
Nice one. 

When I get back to my workstation I'll simulate some network issues to test it.
