### ISSUE TITLE
Lost Loadouts

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#210]
Just loaded the app and my loadouts aren't there. This has happened before and a refresh has fixed it. I was in the process of saving a loadout and it wouldn't save, refreshed and none were there. Are you having issues at the moment?

**Comment by anwnn** [comment]
Seeing this as well on two iOS devices. Inventories load, but loadouts are gone. Refreshing and signing in again don't seem to resolve it.

**Comment by dasilva333** [comment]
Can you confirm it's fixed by now? Thanks guys

**Comment by pattont** [comment]
Looks like my loadouts are back.. Thanks!

**Comment by anwnn** [comment]
Yup, working for me as well.
