### ISSUE TITLE
DestinyDB Hover

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#211]
I don't think this is an issue on your end, but I wanted to report it to make sure. With a number of weapons I can no longer see their stats and all I can see is that they are upgradable with etheric light. With the case of the Speer below I have more than one arc one (pvp vs. pve) and I can no longer tell which is which. (Yes they are unleveled because I had to re-roll them yesterday :-))

![speer](https://cloud.githubusercontent.com/assets/2903357/7725559/e1c252b4-fec9-11e4-92c8-ed23082e74f2.png)

**Comment by dasilva333** [comment]
Thanks for opening this ticket I'll investigate and see if there's something I can do to bring back what perks it actually has, even though it's upgradeable I dont see why the API would suddenly revert to this display. I'll try to get it fixed but I cant make any promises thanks @pattont

**Comment by pattont** [comment]
This one appears resolved. I'm guessing it was on the DestinyDB side because 2.6.2 hover now shows the perks on my efrideets. :-)

**Comment by dasilva333** [comment]
Oh right I did fix it in 2.6.2 it's actually all custom code that i add on top of DestinyDB, those guys have no way of knowing what particular perks you have so I just add it in there after it loads. Thanks for confirming this for me

**Comment by pattont** [comment]
Excellent news! Thanks Richard!
