### ISSUE TITLE
HoW Items not showing

### ISSUE THREAD

**Issue by equesaspe** [dasilva333/TowerGhostForDestiny#212]
I have noticed that HoW items do not display in the app. The items are counted in the totals but are unable to be seen or selected.

**Comment by dasilva333** [comment]
Can you provide an example as to what Item is not showing? Also please provide what version number you are using by clicking on the word TGD on the top right, thanks

**Comment by equesaspe** [comment]
WP 2.4.0 and nothing from the HoW expansion is showing. Prime example the new side arm vestian dynasty

**Comment by equesaspe** [comment]
Treasure keys also.

**Comment by dasilva333** [comment]
yeah WP is stuck on 2.4.0 until further notice expect 2.6.x by Monday the latest thanks for your feedback
