### ISSUE TITLE
Incorporate new 'Sets'

### ISSUE THREAD

**Issue by schubydoo** [dasilva333/TowerGhostForDestiny#213]
With HoW released I think it would be beneficial to incorporate the new end-game sets like Queens Guard, Trials, and Prison of Elders: http://db.planetdestiny.com/houseofwolves

**Comment by dasilva333** [comment]
paging @rvvisse if he wants to help out on this one that would be great, I made a previous post on issue #97 on how anyone can help out get this thing going

I'll repost the new instructions here if anyone wants to take a stab at it:

Download my source code for master branch and open this file:
https://github.com/dasilva333/TowerGhostForDestiny/blob/master/www/js/destinyexotics.js#L140

Add to that array the new "Sets" for example Prison of Elders would be:

>    "ironArmor": [
>        2452629279,
>        2413349891,
>        2810850918,
>        1063666591,
>        1312172922,
>        2314015087
>    ],
>  "prisonOfEldersArmor": [
     -find the ids and populate them here-
>]
>};

There's a great page on PlanetDestiny.com that has all the items neatly grouped into categories:
http://db.planetdestiny.com/houseofwolves

Also the ID is in the link so you dont even have to click into the item to get what it is. Example:
http://db.planetdestiny.com/items/view/909225554

**Comment by schubydoo** [comment]
Seems simple enough.  I'll see what I can whip up too.  Though please don't let that discourage anyone else from trying!

**Comment by dasilva333** [comment]
Just to be clear here is the laundry list of things that need done for HoW:

http://db.planetdestiny.com/houseofwolves

update exoticArmor, exoticWeapons with the new items from that link
create poeArmor, poeWeapons with the ids from that link
create tooArmor, tooWeapons with the ids from that link
create queensWeapons with the ids from the Queens Guard list

I don't think we should have a set for Tower Vendor stuff but if someone wants to create a set called: towerArmor, towerWeapons and include those ids that would be alright with me but not required.

Thanks again guys

**Comment by schubydoo** [comment]
https://github.com/dasilva333/TowerGhostForDestiny/pull/215

First time doing this, please check my work!

**Comment by dasilva333** [comment]
@schubydoo great job if you could update that one little trailing comma I'll go ahead and merge it in otherwise I can just fix it myself after I merge it, let me know thanks

**Comment by schubydoo** [comment]
Looks like you merged it, thanks for the quick updates!

**Comment by dasilva333** [comment]
Alright this is completed I'm closing this out thanks again man
