### ISSUE TITLE
Sorting of things

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#217]
I'd like to open a discussion on sorting weapons/armor/gear.

I mess around with my consumables and materials A LOT and it's always hard comparing a character to another character to see if I need to move things around when the items aren't in the same visual position between players.

Unsorted (http://imgur.com/K1PyxRp):
![unsorted](http://i.imgur.com/K1PyxRp.png)

Sorted (http://imgur.com/VPhe6YZ):
![sorted](http://i.imgur.com/VPhe6YZ.png)

For the sorted picture I just changed Profile.js's get function to:

```javascript
get: function(type) {
	return _.sortBy(this.items().filter(this.filterItemByType(type, false)), function(item){ return item.description; });
},
```

* What are thoughts on sorting - yes/no?
* Does it need both ascending and descending?
* Include rarity + name in the sort of weapons/armor? Exotics -> legendary -> rare -> uncommon -> white
* Top level menu option? Section header icon?

(I don't mind making the patch for the feature if there's enough interest and direction on all the use cases.)

**Comment by dasilva333** [comment]
Yes submit the pull request I think this is a good change:

Sorting - yes
Both Asc/Desc - No just pick one
Yes, sort by rarity then name so it looks even better
No option no icon just a static sort

**Comment by M3Rocket** [comment]
I like @dasilva333 KISS on this. Great idea @Mulchman!

Just an observation: In the Materials section, I think there should be group sorted as well. IOW, Planetary Materials should go together; Energies and Shards; Weapon Parts/Class materials; Coins/Motes of Light/Tokens; et al.

**Comment by Mulchman** [comment]
Playing with something extremely simple (weird formatting just to try and make it readable)-

```javascript
get: function(type) {
	return _.sortBy(
		_.sortBy(this.items().filter(this.filterItemByType(type, false)),
					function(item){ return item.description; }),
		function(item){ return item.tierType * -1; });
},
```

Gives results like this (imgur gallery for full size: http://imgur.com/5BnUOM2,6lN8oav,ncIhSQ1).

![example](http://i.imgur.com/5BnUOM2m.jpg)
![example](http://i.imgur.com/6lN8oavm.jpg)
![example](http://i.imgur.com/ncIhSQ1m.jpg)

I'm not a fan of "Treasure Key" showing up before "Axiomatic Beads" simply due to the fact that Treasure Keys are Legendary. Thoughts? Maybe consumables/materials needs a bit more special handling like @M3Rocket suggests?

**Comment by dasilva333** [comment]
Nah I think it's fine, it's already complex enough as it is, the problem with adding this sort of code into the mix is that it adds a big performance hit in a big way so let's commit something simple and straight forward, test it and benchmark it before we expand further upon the refinements. Feel free to submit the PR whenever you're ready that last one looks great

**Comment by M3Rocket** [comment]
@Mulchman Sorting on that third screenshot looks good enough to me.
