### ISSUE TITLE
300 Fatebringer shows up as missing XP

### ISSUE THREAD

**Issue by kohum** [dasilva333/TowerGhostForDestiny#219]
This is a strange one.  When the "Progress > Missing XP" filter is selected, fatebringer shows up even though it's 300 and not missing any XP.  Vision of Confluence, Atheon's Epilogue or any other old maxed out 331 weapon don't show up.  I even have a vanilla devil you know and shadow price which is maxed at 300 that don't show up.  Fatebringer is the only one.

PS: Is this a subtle hint from the devs that we should be maxing our fatebringer ASAP? =P

**Comment by kohum** [comment]
Seems to affect my Efrideet's spear as well. It's at 331 max.  Initially I thought this might affect other iron banner weapons but my 331 max gheleon's demise and jolder's hammer correctly don't show up as missing xp.

**Comment by dasilva333** [comment]
API is broken it's returning bad data I can't fix the progress stuff until Bungie fixes their end closing this ticket as it's not something I can fix

**Comment by kohum** [comment]
yeah... thought it may be api related. Wasn't sure. Thanks.
