### ISSUE TITLE
Not able to select anything after update to 1.7.1

### ISSUE THREAD

**Issue by maverick171** [dasilva333/TowerGhostForDestiny#22]
Using iPhone 6
The login is fine, but nothing is selectable, the DestinyDB info comes up when double tapping items, but cannot single tap an item to transfer or equip the item.

**Comment by dasilva333** [comment]
Sorry man it was a known bug back in 1.7.1 it's fixed now closing ticket and expect 1.7.6 to arrive to the Flight Test beta testers by tmrw. 

Thanks
