### ISSUE TITLE
Ability to view latest changes popup when we click on the version number

### ISSUE THREAD

**Issue by kohum** [dasilva333/TowerGhostForDestiny#222]
This is a minor but sometimes I miss the changes listed in the latest version since I'm in a hurry to transfer some item over.  It would be great if we could view the latest changes floating box when we click on the version number on the left.

**Comment by dasilva333** [comment]
good idea thanks

**Comment by dasilva333** [comment]
this was added a while ago, closing out this ticket thanks for the feedback

**Comment by kohum** [comment]
Oh yeah..  thanks for this.  It's really helpful.  Should have closed it myself.
