### ISSUE TITLE
Hydration deployment issue on Windows phone

### ISSUE THREAD

**Issue by Adimal** [dasilva333/TowerGhostForDestiny#223]
After several unanswered emails, I thought this might be the next best approach. Windows Phone version is still 2.4.0, which does not show the new HoW items.

I'm not sure if this is an issue with Hydration deployment on Windows phones, or simply a case of the latest Windows version lagging behind the now current v2.6.3

**Comment by dasilva333** [comment]
Simply a case of the latest version lagging behind , this has also been answered in several reddit threads. I submit the package to Microsoft today so perhaps by tomorrow you guys should have 2.6.3

Thanks for your feedback
