### ISSUE TITLE
Viewing loadout requires landscape

### ISSUE THREAD

**Issue by SmixNZL** [dasilva333/TowerGhostForDestiny#226]
Just installed the app and seems like I may have found a bug.

If you tap the Menu icon and select Loadouts, nothing displays.  If you then change to landscape, the available Loadouts then populate.  Toggling back to portrait will then show the available Loadouts.  If you re-open the app, the above must be repeated.

TGD 2.6.5
Galaxy S5 
Kernel: 3.4.0-4469118
Build: LRX21T.G900FXXU1BOC8

**Comment by dasilva333** [comment]
@SmixNZL  I can't reproduce it, make sure you wait until the profiles are completely loaded before looking at the loadouts as they do come from a server.

**Comment by SmixNZL** [comment]
@dasilva333 thanks for the quick response.  I've made a quick video with me reproducing the issue.  For some reason the weapon/gear icons don't show initially in the video, but I can confirm that they were there before pressing the menu button https://www.youtube.com/watch?v=RCfX-LdBzTs

**Comment by M3Rocket** [comment]
Uhhh--after you "click" Loadouts on the menu, just scroll down. You will see them listed. ;-)

**Comment by SmixNZL** [comment]
@M3Rocket /backs away slowly in shame.

Apologies for wasting your time, and again, thanks for the quick responses.

**Comment by dasilva333** [comment]
No problems I think this confusion has happened to more people than just you, Ill rearrange it so it's harder to get it wrong. Thanks for your feedback
