### ISSUE TITLE
Firefox TGD 2.6.6 Menu overflows to Second Line

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#228]
![tgd-bug](https://cloud.githubusercontent.com/assets/3769123/7853067/8e68ed86-04bd-11e5-9327-707545153cf6.png)

Obscures the headers. This is in Windows 7, FF 38.0.1, TGD 2.6.6

When I expand the window, it reverts to one line.

**Comment by dasilva333** [comment]
Thanks man I'll make sure this is fixed

**Comment by M3Rocket** [comment]
This looks fixed in 2.7.0
