### ISSUE TITLE
Auto Pad Height broken when Vault is on the rightmost position in 2.6.6

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#229]
When the Vault is in the default leftmost position, Auto Pad Height seems to work correctly with any rows that are 3 or less (known bug with stacks of 4 or more). When the vault is set to the rightmost position, Auto Pad Height doesn't work at all.

![tgd-bug](https://cloud.githubusercontent.com/assets/3769123/7868264/9d0171c0-052f-11e5-83e4-d62022e59e3c.png)

Strange thing is that you can set the vault back to the left, hit F5 to refresh so that it's working. Then switch the vault back to the right, and Auto Pad seems to stick, but only till the next screen refresh.

**Comment by dasilva333** [comment]
this has been fixed as of 2.7.0+, more improvements coming in 2.7.3 regarding the height. closing this issue as it is now been resolved thanks man
