### ISSUE TITLE
refresh icon not working

### ISSUE THREAD

**Issue by PillowMetal** [dasilva333/TowerGhostForDestiny#23]
In both the chrome extension and Android app, when clicking the refresh icon, the blue loading bar appears, but the refresh never completes and the blue loading bar remains.

**Comment by dasilva333** [comment]
problem fixed in 1.7.6 please retest and close ticket thanks

**Comment by PillowMetal** [comment]
This is now working in 1.7.6. Closing the issue. Thanks!
