### ISSUE TITLE
2.6.6 - header ordering issue

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#230]
Sometimes the vault/character 1/2/3 headers get out of whack. This is in 2.6.6 and I've seen it in Chrome and on an Android tablet.

![example](http://i.imgur.com/XnPVWgJ.png)

**Comment by dasilva333** [comment]
can u reproduce this consistently? do u know how to make it happen every time? thanks let me know

**Comment by Mulchman** [comment]
I just got refresh in the top right corner. I've had the vault bounce
around to many locations, including the far right.

**Comment by Mulchman** [comment]
"Got" was supposed to be "hit"- "I just hit the refresh... "

**Comment by dasilva333** [comment]
i fixed it, didnt set a detfault for vaultPos, should be fixed by 2.6.7 thanks

**Comment by dasilva333** [comment]
closing this issue its been long fixed, feel free to let me know if u still experience the issue in this ticket thanks
