### ISSUE TITLE
Error loading inventory {"error":true}

### ISSUE THREAD

**Issue by adamusprime** [dasilva333/TowerGhostForDestiny#233]
I am on an iPhone 4S.  Earlier this evening the app updated and then got stuck on an orange loading bar that said "please wait signing into Bungie".  This happened forever and it never was able to successfully sign into Bungie.  I close the app and reopened it and had the same issue. I deleted the app and re-downloaded it and am now receiving the error message above when I try to open the app and look in my inventory.

I can't find any information about it on the site, so any help would be greatly appreciated as I've come to love and depend on this app for my destiny playing experience.

**Comment by adamusprime** [comment]
I deleted and re-downloaded this app again and told her to ignore the update when prompted. It was able to load my inventory as usual. I then close the app and reopened the app and allowed it to download the update and then again received the above error.

**Comment by adamusprime** [comment]
I'm running the not updated one I downloaded from the App Store and it doesn't recognize all of my weapons (showing nothing in my titan's special slot, not showing Queen weapons in my Warlock's primary slot, etc.)

**Comment by matthubb** [comment]
I'm having the same issue with iOS: stuck on an orange bar signing in. 

However, selecting "Log in PSN" from the settings menu will do its thing and then load my inventory

**Comment by Los556** [comment]
Having the same issue on Ipad, opened it, ran most recent update, then get: Error loading inventory {"error":true}. Deleted it and reinstalled, ignored update, but new items are not showing. Ran update again and got the same error.

**Comment by dasilva333** [comment]
Seems I broke it on the last update 2.6.7 for ios only, @adamusprime @Los556 @matthubb can you guys tell me what type of account you have?
-is it dual linked to xbox and ps? yes/no
-is it linked only to one account? if so which one
-if its linked to two accounts, is one of them invalid?

Let me know Ill try to solve this today but I'm going to be pretty busy today so I'm not sure if I'll get to ttill tonight thanks guys

**Comment by dasilva333** [comment]
Problem fixed, please update to 2.6.8 and confirm if it's still an issue for you thanks

**Comment by matthubb** [comment]
Spends a while on orange bar but does now load without intervention. 

Fixed for me. (PSN only)

**Comment by drinkc0ke** [comment]
Confirmed also working for XBL on iPhone 6 running iOS 8.3, as of the 2.6.8 update.

**Comment by adamusprime** [comment]
Fixed!  iPhone4S for XBL.  Thank you!
