### ISSUE TITLE
Missing weapons from PoE Weapon Sets

### ISSUE THREAD

**Issue by schubydoo** [dasilva333/TowerGhostForDestiny#234]
This is more of a reminder for myself (or anyone who has time).  There seems to be some more weapons recently found exclusively dropped from Skolas.

See: "Weapons (II from Skolas)" from http://db.planetdestiny.com/houseofwolves

**Comment by dasilva333** [comment]
thanks for your help on this stuff man, i added some of the mercury weapons that were missing from there as well and moved the file to setDefs.js and no more having to use the _fix structure. FYI
