### ISSUE TITLE
Loadout Items .."will be moved." shows [weapon/armor name]undefined

### ISSUE THREAD

**Issue by rkingsla** [dasilva333/TowerGhostForDestiny#235]
I've just noticed this, and may have been in a previous build. Current build in use: 2.6.9

(I've also searched and if this is already reported, I didn't find it.  apologies if this is reported and known)

Items that are swapped are correct.
Items that will be equipped are correct.
Items moved and equipped are correct.

It APPEARS that only items moved and just moved have the text "will be moved" as "undefined".
![item move undefined](https://cloud.githubusercontent.com/assets/2037051/7913607/f019f1f2-0836-11e5-9bdc-f5b73c55ca28.png)

**Comment by dasilva333** [comment]
thanks man i'll get this fixed asap

**Comment by dasilva333** [comment]
this was fixed as of 2.7.0 closing it out
