### ISSUE TITLE
Missing XP category displays incorrect items

### ISSUE THREAD

**Issue by True-Ninja** [dasilva333/TowerGhostForDestiny#237]
![towerghost](https://cloud.githubusercontent.com/assets/12725831/7953360/c5716b90-0991-11e5-8031-a26aedc6c1e5.png)

This was one of my favorite and most used features up until it seemed to stop working a few versions ago. There are items that come up when I select Missing XP that do not need any experience, and in fact sometimes are completely maxed out, and even ascended.

**Comment by rkingsla** [comment]
Yep - it's ben reported and closed a few times. The net is: Richard can't do anything about the fact that some weapons that are fully ascended still show up as missing XP. The data for items missing XP is consumed directly from Bungie - not a decision that is made locally to the App. Until Bungie updates their item max XP flags on their end, the Gally, TLW, and others will continue to be erroneously reported as missing XP  when, in fact - they aren't.

Hope that helps.

**Comment by dasilva333** [comment]
Well said sir I'm glad you understand @rkingsla I feel bad when I close tickets like this but that's pretty much the gist of it. Hopefully they'll fix up their API so this can stop being a problem. Thanks for the summary

**Comment by True-Ninja** [comment]
I see. Sorry I didn't realize it had already been reported. Thanks anyway.

**Comment by rkingsla** [comment]
No need to apologize!  Frankly, like most here, I think that issues should be reported - even if they are duplicates of known issues - and later closed.  The alternative is that issues that are not known don't get reported and fixed. Obviously this is bad....

Thank you for taking the time to report the issue.
