### ISSUE TITLE
Please be patient, logging into Bungie.

### ISSUE THREAD

**Issue by d1464c** [dasilva333/TowerGhostForDestiny#238]
For some reason this last week I can't get past the please be patient, logging into Bungie. It's an orange loading bar that doesn't continue. This was on my iPhone 6+ and iPad.

**Comment by ssoriche** [comment]
I've had a similar issue, and when I clicked on the cog and select PSN Login, the Bungie login pane opened showing that there were errors logging into Bungie. It automatically refreshed, signed in and I was able to continue.

**Comment by d1464c** [comment]
I don't see that option. Are you talking about the settings cog? I just see Clear Filers, About, ? Help and Donate.

**Comment by ssoriche** [comment]
On my iPad, under Donate is DestinyExotics Share URL, a number of toggles, and then PSN Login and Live Login. On my iPhone 6 I have to click on the Menu hamburger, then scroll to settings, click settings and scroll down to PSN Login.

**Comment by d1464c** [comment]
I*'m on the iPhone 6+ and under settings there's no XBL Login like I mentioned above.

**Comment by ssoriche** [comment]
Does your menu not look like this? Are you running the version of Tower Ghost from the App Store?
![image](https://cloud.githubusercontent.com/assets/19838/7967015/7ffa847a-09f5-11e5-899d-e87409726ff0.jpg)

**Comment by d1464c** [comment]
No, my menu isn't as detailed. Yes, it's from the app store. Version 2.6.9

**Comment by d1464c** [comment]
![image](https://cloud.githubusercontent.com/assets/12735033/7967246/d60385fa-09f6-11e5-9879-afe08379d5bb.jpg)

**Comment by ssoriche** [comment]
Yes, mine looks just like that too, until I scroll the menu down by sliding my finger up on the menu items.

**Comment by d1464c** [comment]
That did it! Thanks. It took 4 pulls and it finally popped up. Is that like finding the hidden chest in VoG?
