### ISSUE TITLE
List Light level on Armor

### ISSUE THREAD

**Issue by mpastreich** [dasilva333/TowerGhostForDestiny#239]
Ability to either display Current Light level (in leu of Defense level), or to display split "Current/Max" light level.

Would suggest this be a toggle and have it replace currently displayed armor value.

**Comment by dasilva333** [comment]
Cool simple idea thanks for the feedback

**Comment by mpastreich** [comment]
No problem, happy to help this great project in whatever small way I can. :)

**Comment by dasilva333** [comment]
this has been added as of 2.7.1 closing this issue
