### ISSUE TITLE
Loadouts seem to be trying to unnecessarily swap weapons?

### ISSUE THREAD

**Issue by r3mus** [dasilva333/TowerGhostForDestiny#240]
I've been noticing that weapons are being swapped quite a bit when using loadouts, though all characters have quite a few slots available in each weapon class and I'd think it should only move instead of swap? Does it always try and swap, or only when it determined you'd exceed the available slots? The result of this is because I'm low on vault space, this happens a lot: 
![image](https://cloud.githubusercontent.com/assets/1480253/8010833/b3bd7726-0b68-11e5-93c9-e8fbd4dad190.jpg)

**Comment by dasilva333** [comment]
the app should know ahead of time there are no slots and ideally all measure should be taken to avoid showing that error message during the transfer. I'll look into it further and try to improve the algorithm to prevent that from happening. thanks

**Comment by r3mus** [comment]
Cool thanks! It seems it happens more frequently when using a large loadout (10 or so). Dropping it down to 4 or 5 it works correctly. But I did the math on the available slots and it shouldn't have had a problem.

**Comment by r3b3lspy** [comment]
Yes this is happening almost all the time, usually after I receive the error I close this app and open Loadouts app and it works all the time, I like your app better but 95% of the time I cannot transfer sets as it is always telling me there is no space when there is plenty of slots available on all characters and I'll use the Loadouts app without issues.

**Comment by M3Rocket** [comment]
I think this is part of the larger discussion of the logic used for swapping/equipping. Maybe we can consolidate this with issue https://github.com/dasilva333/TowerGhostForDestiny/issues/236

**Comment by r3mus** [comment]
Agreed @M3Rocket

**Comment by dasilva333** [comment]
@r3mus @M3Rocket @r3b3lspy TGD 2.9.2 includes a full suite of enhancements to the transfer logic, I'm closing this out as I expect all this issues to have been fixed. Please leave any feedback if you're still having problems. Thank you
