### ISSUE TITLE
New Safari extensions gallery

### ISSUE THREAD

**Issue by r3mus** [dasilva333/TowerGhostForDestiny#244]
Just stumbled across this today! https://beta-extensions.apple.com very exciting stuff, and would seal the deal for ditching Chrome entirely if TG worked in Safari!!

**Comment by dasilva333** [comment]
The link doesn't work when I try to submit an extension at the bottom, Ill keep it pinned so I can try it later on. Thanks for the info

**Comment by r3b3lspy** [comment]
I've tried the link and it is working, do you have a developer account?  Can you submit an extension for the current safari browser instead of the beta one?

**Comment by dasilva333** [comment]
I can't submit an extension for the current browser instead. Link still doesn't work, its not the the link posted doesn't work. It's the blue "submit" button at the bottom leads to me to a 404 after I sign in to this page:

https://developer.apple.com/register/completeRegistration.action?cancelURL=https%3A%2F%2Fdeveloper.apple.com%2Fprograms&successURL=https%3A%2F%2Fdeveloper.apple.com%2Fsafari%2Fextensions%2Fsubmission%2F

I suppose it's still in beta Ill try it again as it's closer to release.

**Comment by r3mus** [comment]
Yeah - looks like it'll be available some time around the release of "El Capitan" (WTF name?).

**Comment by r3b3lspy** [comment]
The blue button it is worked no without issues here, when I try it will take me to a screen to submit the actual extension with the form to add all your data. 

https://developer.apple.com/safari/extensions/submission/

**Comment by dasilva333** [comment]
I get "Page Not Found" when I visit the link you provide there, I don't see a form. Some weirdness going on there not sure what to make of it.

**Comment by r3b3lspy** [comment]
I'm a developer with a valid developer (paid) account,  that may be the issue? I've attached the screenshot from the summit page.
![screenshot_2015-06-11_11_45_05](https://cloud.githubusercontent.com/assets/12128020/8111409/acdae5b2-102f-11e5-9668-930d4adc8e76.jpg)

**Comment by dasilva333** [comment]
Interesting, I wasn't getting that then I navigated through all the developer pages at one point I was forced to accept to a new Terms of Service agreement, now I revisit that link and I see the form just like you guys. At this point it's just a matter of developing and submitting the extension however it seems you need a Mac to develop Safari extensions still. Despite the fact that their developer guide states:

> "Safari extensions are supported in Safari 5.0 and later on the desktop (Mac and Windows). Safari extensions are not currently supported on iOS."

When searching for the latest Safari for Windows download:
https://developer.apple.com/downloads/?q=safari
"Safari 7.1.7 and 6.2.7 beta for OSX" is the only option available.

**Comment by r3mus** [comment]
I'm hoping that someone will devise a means of porting Chrome extensions - phonegap maybe?

**Comment by r3b3lspy** [comment]
I would love to see that too

**Comment by dasilva333** [comment]
No plans to support TGD on Safari
