### ISSUE TITLE
"Consolidate" consumable/material option

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#245]
I've wanted to have a "Consolidate" feature for a while now (previously mentioned in this issue https://github.com/dasilva333/TowerGhostForDestiny/issues/122) and a reddit user brought it up here (http://www.reddit.com/r/TowerGhostForDestiny/comments/38jd6m/normalize_improvements/) and here (http://www.reddit.com/r/TowerGhostForDestiny/comments/38mfk2/suggestion_consolidate_items/) so maybe it's time to do something about it.

### Premise/Use Case

*I want all Relic Iron from all my characters transferred to this single character*

### Where does it live?

* Should it be a collapsible section on the **Extras** dialog (http://imgur.com/rMwAtK6)?
![extras](http://i.imgur.com/rMwAtK6.png)

* Should it be an extra option on the **Transfer Materials** dialog (http://imgur.com/fMf2pbk)?
![transfer](http://i.imgur.com/fMf2pbk.png)

* Something else?

### Discussion

Chime in. (I'm partial to stuffing this in the **Extras** section but once again it'll be a hidden feature that some (most?) people don't know about.)

**Comment by dasilva333** [comment]
I like the second option better because the "Transfer Materials" popup is already within the context of transferring to a specific character at that point you're offering an additional option (the consolidate checkbox) which will make it obvious to use and visible to all to find. I say go for the second option unless you really like the first option then you can add both options that would be fine too.

Thanks man

**Comment by Mulchman** [comment]
@dasilva333 I get where you're coming from and thought that as well.

What about completely different workflows/entry points/visibility for these add-on type features (consolidate/normalize/bulk-transfer)? Clickable icons on section headers or something? I really have nothing, but where these features should go always seems to be a reluctant solution.

**Comment by dasilva333** [comment]
Perhaps that would work in the future when we have the new Dash menu for now adding a consolidate button anywhere in the menu would make it even more cluttered. For phase 1 I say we just go with the first option of providing the consolidate inline with the transfer menu as I see myself using that option the most. Good luck and keep up the good work :)

**Comment by M3Rocket** [comment]
I like this in the Transfer Materials dialog better until there is a way to specify where to consolidate from. Let's say I want to consolidate from all Guardians to one, but not from the vault. 

It seems to me the Transfer Mats dialog box option would simply mean consolidate from ALL sources to the present Guardian/Vault. I think logically, it can reside in the Extras as well, with the one in Extras providing more detailed consolidation options.
