### ISSUE TITLE
2.7.0

### ISSUE THREAD

**Issue by seg7** [dasilva333/TowerGhostForDestiny#246]
Loadouts vanished :(

**Comment by rkingsla** [comment]
Probably going to need more details.  Phone (which?), tablet (which?), browser (which?) etc.  Can you create a new loadout and it still disappears?

FWIW, I'm on 2.7.0 (Chrome) and do not see this problem....

**Comment by seg7** [comment]
Chrome Version 43.0.2357.124 (64-bit)
Can create new ones just fine, just can't see my old ones.

Javascript console if it helps:
Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/cordova.js Failed to load resource: net::ERR_FILE_NOT_FOUND
https://www.towerghostfordestiny.com/ga.cfm Failed to load resource: net::ERR_CONNECTION_RESET
https://www.towerghostfordestiny.com/api.cfm Failed to load resource: net::ERR_CONNECTION_RESET

**Comment by seg7** [comment]
Update: Can't access the url http://www.towerghostfordestiny.com/ on the browser, dns? Probably the reason the loadouts are not loaded?

**Comment by rkingsla** [comment]
I hate eating my own words....   :o/  Just pulled latest updates and reloaded.  Repro of your issue is confirmed.  Loadouts gone.

**Comment by dasilva333** [comment]
Thanks for the heads up guys, it seems my sever is not responding I'll look into why. rest assured your loadouts are still safe in the db

**Comment by dasilva333** [comment]
Domain is back up, loadsout should be working thanks for reporting this issue guys

**Comment by rkingsla** [comment]
Working perfectly......  Thank you!
