### ISSUE TITLE
While executing a load out with a shader it will try to swap the "No Shader" shared and fail

### ISSUE THREAD

**Issue by ddcruver** [dasilva333/TowerGhostForDestiny#248]
I discovered this while trying to make a load out for Iron Banner. I would add the shader and class items to the load out and then load it for whatever character I want to play as. It works great by not transferring class items to class that can't equip them but when it goes to the shader that is were it can messes up.

I don't know how it chooses what it swaps out but if your inventory is full it will need to swap something and it sometimes chooses the "No Shader" shader.

**Comment by dasilva333** [comment]
Ill have to test it out see if I can reproduce the problem, bottom line is if you're swapping shaders around the same rule apply as everything else, you always need one slot open in your shader slots otherwise things will fail and work unpredictably. Good luck

**Comment by dasilva333** [comment]
I fixed the problem, loadouts should no longer try to swap the 'no shader' item with an actual shader in the future. So to recap if you have 9 shaders on ur titan and u have 9 shaders on ur hunter, you select goldspiral in your loadout and xfer it to the titan. you should see it present an option to swap goldspiral with another random shader that's not the 'no shader' option.If you have 10 shaders in your titan its not going to work bc its full.
