### ISSUE TITLE
Quick Loadout App or Panel

### ISSUE THREAD

**Issue by ddcruver** [dasilva333/TowerGhostForDestiny#249]
The loadout feature is nice and fast as it is but it would be interesting to have an phone app that uses the smarts you have developed and map single buttons to do load out switches.  So the button has a loadout, character, etc. assigned to it and you just press it.  The app seems to not work as well on my Android Phone or Tablet so some feature to make quick assignments would be great.

**Comment by dasilva333** [comment]
Perhaps when the new menu is implemented this will make more sense for now I'm not going to clutter the interface further by adding more buttons than it needs. Thanks for your feedback
