### ISSUE TITLE
Move menu for items on rightmost guardian goes off screen

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#25]
As the title says. Fortunately it's possible to scroll over and see the menu, but better behavior would probably be to check if the menu goes off the screen, and if so align the right side of the menu to the item rather than the left side.

**Comment by dasilva333** [comment]
Sorry man I don't really understand the problem, if you could visualize it or provide a screenshot that would be great. Also note for all my element positioning I'm using jQuery UI which handles it for me so I might not be able to find or fix the bug you see. 

Thanks

**Comment by wickles** [comment]
Yep, sorry, I was worried that might not make sense. Here's an illustration. 

This is what happens if you click on an item away from the right edge of the browser window:

![screen shot 2015-04-13 at 5 35 11 pm](https://cloud.githubusercontent.com/assets/4229542/7128230/26e88ac6-e204-11e4-81cf-c2419c7bd2b6.png)

Here's what happens if you click on an item near the right edge of the browser window. Notice how it goes off the screen. You can still scroll over to it, but it's a bit annoying. 

![screen shot 2015-04-13 at 5 35 23 pm](https://cloud.githubusercontent.com/assets/4229542/7128250/5926f3a6-e204-11e4-8e13-3682a735b835.png)

Here is a cartoon showing what I would like it to do instead (pretend that it is the same item's move box): 

![screen shot 2015-04-13 at 5 35 23 pm copy](https://cloud.githubusercontent.com/assets/4229542/7128241/40193388-e204-11e4-9472-a216a204e10d.png)

Hope that makes sense.

**Comment by dasilva333** [comment]
Good catch I hadn't noticed that I think it's a simple fix expect it in version 1.8.1 I'll ask you when to try it again thanks

**Comment by dasilva333** [comment]
Problem fixed in 1.8.1 please retest it and let me know thanks

**Comment by wickles** [comment]
Works great now save for some minor details. It doesn't seem to work if it's the first move menu opened, i.e. reload the extension and try clicking on an item on the far right and it will exhibit the old behavior. Close the menu and try again and it will work correctly from now on until reloading the extension. 

One other thing I noticed is that when it opens to the right (old behavior), the menu is aligned on the left side of the item you clicked on. When it opens to the left (new behavior), the menu is still aligned on the left side of the item. It might make more sense to align to the right side of the icon when the menu opens to the left. Hope that makes sense.

**Comment by dasilva333** [comment]
Good catch @wickles I was able to reproduce the problem it is indeed not working right the first time and then it starts working right. As for the alignment I'm happy with how it's always aligned to the left side of the item but since I'm fixing this "first-time" bug I'll revisit it and see if I can subtract the width of the image so it'll line up to the right side instead.

Thanks for your feedback

**Comment by wickles** [comment]
No problem, I'll go ahead and close this now.
