### ISSUE TITLE
PoE/IB weapons not recognized correctly

### ISSUE THREAD

**Issue by KBanause** [dasilva333/TowerGhostForDestiny#250]
For Prison of Elders every weapon exists in two types:
With and Without elemental damage.
Example:
Wolfslayers' Claw (normal version) and Wolfslayers' Claw II (weapon with elemental damage that drops after defeating Skolas in the level 35 PoE).

I have both but when I set a filter to show only the PoE weapons, only the Wolfslayers' Claw is visible.

Also the new Iron Banner weapons are not recognized as Iron Banner weapons (the new ones are with a II symbol in the icon).

**Comment by KBanause** [comment]
I forgot: I'm using the Chrome extension of TGD, version 2.7.0

**Comment by dasilva333** [comment]
thx for the info

**Comment by dasilva333** [comment]
problem will be fixed as of 2.7.2 thanks

**Comment by KBanause** [comment]
Unfortunately this issue is not fixed. See screenshots

![iron_banner_autorifle](https://cloud.githubusercontent.com/assets/999719/8192257/2d85fcd8-146d-11e5-8604-a97974ce8c00.png)
![iron_banner_weapons](https://cloud.githubusercontent.com/assets/999719/8192259/2d870da8-146d-11e5-9ec6-c567a5632afb.png)
![missing_ib_weapons](https://cloud.githubusercontent.com/assets/999719/8192255/2d85cb5a-146d-11e5-9663-b26f5fb8c415.png)
![missing_poe_weapons1](https://cloud.githubusercontent.com/assets/999719/8192260/2d889eb6-146d-11e5-89ab-cbdf7e3f843d.png)
![missing_poe_weapons2](https://cloud.githubusercontent.com/assets/999719/8192256/2d86075a-146d-11e5-8727-37ebe2d30998.png)
![poe_six_dregs_pride_ii](https://cloud.githubusercontent.com/assets/999719/8192258/2d86faac-146d-11e5-88ed-3732172e467e.png)
![poe_weapons](https://cloud.githubusercontent.com/assets/999719/8192261/2d9ccb66-146d-11e5-9c21-19056af7cb0c.png)

**Comment by dasilva333** [comment]
Sorry I misspoke I meant 2.7.3 the next release, the current release is 2.7.2

**Comment by KBanause** [comment]
As of version 2.7.9, the new iron banner weapons are still not in the Iron Banner Set view

**Comment by dasilva333** [comment]
@KBanause Thanks for the update, I thought I got em all but I suppose I missed a few perhaps @schubydoo could help out or if you want to lend a hand that's great too.

To resolve the issue here's what I need you to do:

- Go to the menu, click on DestinyDB mode
- Click on the weapons missing on the IB set
- provide me the links to those weapons in this post

Thanks

**Comment by KBanause** [comment]
@dasilva333 

https://destinydb.com/items/2115569661   (Silimar's Wrath)
https://destinydb.com/items/892062222     (Gheleon's Demise)
https://destinydb.com/items/3968437225   (Skorri's Revenge)
https://destinydb.com/items/3582249030   (Timur's Lash)
https://destinydb.com/items/2180040613   (Efrideet's Spear)
https://destinydb.com/items/1730663491   (Fellwinter's Lie)
https://destinydb.com/items/1923132366   (Perun's Fire)
https://destinydb.com/items/136148814     (Jolder's Hammer)
https://destinydb.com/items/3947396344   (Radegast's Fury)

**Comment by dasilva333** [comment]
thanks man expect it in 2.8.0
