### ISSUE TITLE
item not showing in android and chrome app

### ISSUE THREAD

**Issue by Bazzu85** [dasilva333/TowerGhostForDestiny#251]
Hi,
i'm using android and chrome app..

First time app is used all working..
second time nothing is showing..

here's is a screen..

https://www.dropbox.com/s/fv58nxgx71760uz/Screenshot%202015-06-14%2013.10.01.png?dl=0

same situation in android app..

I've tried to click on psn login, use psn account but nothing happen...

I have to uninstall and reinstall app..

**Comment by dasilva333** [comment]
Thank you for the bug report, this is a new bug that was recently introduced I'm surprised it affected mobile. Will get this fixed. @Bazzu85 After you uninstall and reinstall did it start working again or is it completley non-functional now?

**Comment by Bazzu85** [comment]
hi, thx for feedback..

after a data delete (android) the app start working fine..
i'm trying chron extension!

**Comment by Bazzu85** [comment]
seems to work on both platform! thx dude!

**Comment by dasilva333** [comment]
Im glad that fixed it for you, I will be investigating solutions to avoid this happening to other people in the future. Thanks for your feedback I'm going to close this ticket now
