### ISSUE TITLE
App won't load on Samsung Galaxy Tab 10.1 Android 4.04

### ISSUE THREAD

**Issue by ovazquez242** [dasilva333/TowerGhostForDestiny#252]
I get a message indicating Cookies must be enabled on Chrome before loading TGD? But there is no way that I can do this Chrome is setup to allow cookies on the Tablet. 
![screenshot_2015-06-14-20-17-22](https://cloud.githubusercontent.com/assets/12887758/8151381/0509ed3a-12da-11e5-92f5-efa58d2580a5.jpg)

**Comment by dasilva333** [comment]
Thanks for the bug report I'll get this fixed asap

**Comment by ovazquez242** [comment]
I tried installing it prior to the update and it would not finish loading my inventory before at least it would login to the bungie.net site it just seemed to get stuck finishing the loading process.  Now it returns the error message.

**Comment by ovazquez242** [comment]
I know it's an older device but it's still very much usable so I would love to get it to work for TGD love the all by the way and getting the word our on it to the community.

**Comment by dasilva333** [comment]
Try version 2.7.2 and above it has a fix to prevent that message from showing, let me know if it works. Thanks

**Comment by ovazquez242** [comment]
How can I dl 2.72 app store only shows 2.1.1



—

**Comment by dasilva333** [comment]
it just auto updates itself so install the store version and let it update to 2.7.2 and it should work

**Comment by ovazquez242** [comment]
Actually this is 2.7.2 that's happening on



—

**Comment by dasilva333** [comment]
Sorry I misspoke it's hard to keep a timeline of everything that goes into every version, expect the fix in 2.7.3 for android coming out soon. Thanks

**Comment by weborican** [comment]
FYI, this is still happening on 2.7.5

**Comment by dasilva333** [comment]
@weborican you're getting the same error message on 2.7.5 in Android now? can you let me know exactly what device you're using as I cant reproduce this problem. thanks

**Comment by weborican** [comment]
OMG, I just relaunched TGD on my Android device and it (again!) presented me with the "new version available" screen. Updated and now it works. WTF?

Oh wait, it is now 2.7.7. Did you make any changes for this on .6 or .7 version. If you did, it now works :-)

I haven't used TGD on my Android device for a few weeks now, so I don't know when it stopped working.

**Comment by dasilva333** [comment]
@weborican thanks for the quick reply 2.7.7 just changed some minor things how i report other errors and 2.7.6 redefines the definition of isChrome so I think that's what fixed it for you, see the commit here:

https://github.com/dasilva333/TowerGhostForDestiny/commit/3e6284886fe4d51bf6f25fd36c34d06b11e069f5

I'm going to wait for @ovazquez242 to confirm its working as of 2.7.7 now and consider this fixed. thanks again

**Comment by weborican** [comment]
Yes, I believe it was your isChrome definition change that fixed it. Thanks @dasilva333 !

**Comment by dasilva333** [comment]
I believe this has been fixed a while ago, please leave any feedback if you are still having issues as of 2.9.1. Thank you
