### ISSUE TITLE
Auto Pad Height adds an extra row in new version 2.7.2

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#254]
![screen shot 2015-06-15 at 4 18 29 pm](https://cloud.githubusercontent.com/assets/4229542/8172870/4887d13a-137a-11e5-9db9-96d73f0eca16.png)

**Comment by Mulchman** [comment]
The extra padding is also there on an Android tablet.

**Comment by dasilva333** [comment]
thanks guys I too noticed the problem recently expect it fixed as of 2.7.3

**Comment by dasilva333** [comment]
this has already been fixed as of 2.7.3+ thanks guys
