### ISSUE TITLE
Trials Passage shows up in Postmaster section

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#255]
Trials Passages are showing up in the Postmaster section. (Running from source which says 2.7.2.)

Example (http://imgur.com/aXyswfM)
![example](http://i.imgur.com/aXyswfM.png)

**Comment by dasilva333** [comment]
Thanks, I suppose it doesn't belong there but there isn't anywhere else it does belong. Not sure where it should go instead. I do appreciate being able to see it though. Perhaps I'll leave it there for now

**Comment by Mulchman** [comment]
A new "missions" section? I don't know. Clicking/touching- it would be cool if it showed win/loss in some manner.

**Comment by Mulchman** [comment]
In case you haven't seen it locally yet, it's showing 11/10 due to having max bounties + the Trials Passage (http://imgur.com/QVmeDn8)-

![example](http://i.imgur.com/QVmeDn8.png)

**Comment by Mulchman** [comment]
Iron Banner medallions also showing in Postmaster section. (Just relaying, don't kill me.)
