### ISSUE TITLE
Off by one error with bounties

### ISSUE THREAD

**Issue by rkingsla** [dasilva333/TowerGhostForDestiny#256]
Should be easy to see.  Two bounties are reported - one is actually in place.
![beta 2 7 3 off by one error](https://cloud.githubusercontent.com/assets/2037051/8193176/dbe78ef2-1438-11e5-9eb0-4f0319f56b56.png)

**Comment by dasilva333** [comment]
lol damn @rkingsla it's not even out yet and you're already finding bugs. thanks man that's actually already been resolved i just havent pushed the latest changes yet

**Comment by rkingsla** [comment]
;o)  Working for Microsoft for a bunch of years makes a good software tester.  Well, by Microsoft standards....

**Comment by dasilva333** [comment]
Closing this out as it's already been resolved. thanks again
