### ISSUE TITLE
Share URL displays blank page on FF 38.0.5 and IE 11

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#257]
The Share URL in 2.7.8 returns a blank page for me in both Firefox and Internet Explorer. Seems to only work in Chrome?

**Comment by dasilva333** [comment]
thanks for the update, i saw your inventory and you have some pretty cool shaders man it's fixed now closing out the ticket

**Comment by M3Rocket** [comment]
Very cool--thanx @dasilva333 ! Wish I had more space for shaders really. I don't like that it shares the same vault space as armor since armor is obviously more important.
