### ISSUE TITLE
item missing exp not showing when using filter

### ISSUE THREAD

**Issue by Bazzu85** [dasilva333/TowerGhostForDestiny#258]
Hi,

I have a truth tht is not full experienced and when filtering with "missing xp" is not showing..

other items like murmur or 77 wizard instead are showed like missing xp but are maxed (without etheric light)

here's a screens:

truth not showing
https://www.dropbox.com/s/87sdw44rm387k8m/Screenshot%202015-06-18%2022.42.22.png?dl=0

truth without filters:
https://www.dropbox.com/s/jymeofalufpf100/Screenshot%202015-06-18%2022.43.32.png?dl=0

**Comment by dasilva333** [comment]
There's a problem with Bungie's API where I'm getting inconsistent and unreliable data to accurately show the items in those filters. I'm closing out this issue until Bungie gets their act together and fixes their API

**Comment by Bazzu85** [comment]
ok!
