### ISSUE TITLE
maxed items showing when set to missing xp

### ISSUE THREAD

**Issue by gamey1000** [dasilva333/TowerGhostForDestiny#259]
![desktop capture-06-20-2015 12-43-06](https://cloud.githubusercontent.com/assets/11579647/8268186/1e69d596-174a-11e5-9682-20ff0086013c.jpg)
My Ice breaker and Hunger of Crota are showing up when I have missing xp selected even though I have the gold border around both. They also don't show up when maxed progress is selected
![desktop capture-06-20-2015 12-47-36](https://cloud.githubusercontent.com/assets/11579647/8268205/8b76cdec-174a-11e5-84cb-9d91362e218e.jpg)

**Comment by M3Rocket** [comment]
This is a bug in the Bungie API and has existed since the HoW release. Can't be fixed by Tower Ghost until Bungie decides to fix it on their end.

**Comment by dasilva333** [comment]
@M3Rocket well said, you can also tell it's bugged on their end if you visit the companion app or the bungie website you'll see items with gold borders that don't belong to it.
