### ISSUE TITLE
No longer see the app in my FlightTest app

### ISSUE THREAD

**Issue by lambs0n** [dasilva333/TowerGhostForDestiny#26]
Was it removed?

**Comment by dasilva333** [comment]
Yeah it's going to happen. I'll write up a nice message for you guys next time I release the next one so everyone is aware of the 'cycle' I myself was also unaware of it. So the way it works is I submit for review a new version, get it approved, and send invites,

Problem is for me to release a /new/ version I have to stop the current version and submit the new one for approval, usually that takes only a few hours and you'll have the new one right away. The upside is if you currently have it installed you get to keep it, if you didn't install it before it got 'cut off' then you have to wait until a new beta is released.

Thanks
