### ISSUE TITLE
Equipped weapons issue

### ISSUE THREAD

**Issue by lllgurulll** [dasilva333/TowerGhostForDestiny#261]
The manager used to allow me to move weapons around that were still equiped on my other characters.  Now I have to manually go unequip them before I can move them with the app.  Can you change this back to the old way that allowed us to move them without having to unequip them first.

**Comment by lllgurulll** [comment]
To expand a bit.  I CAN move an single equipped weapon with the app but when I use loadouts is where the problem exists.  If even one weapon is equipped it breaks loadouts now.  This wasn't an issue last week.

**Comment by dasilva333** [comment]
Yeah I agree there's problems with the logic I'll mark this as a bug so it can get fixed even though this is probably related to an existing open bug. Thanks for the feedback

**Comment by dasilva333** [comment]
I've revamped the transfer logic as of 2.9.2 I'm closing this out, please leave any feedback if you have problems with that version or any above. Thanks
