### ISSUE TITLE
Hydration Update screen on Windows Phone hangs

### ISSUE THREAD

**Issue by larryhl** [dasilva333/TowerGhostForDestiny#262]
Whenever I load the app on WP, it always asks to update. However if I do choose to update, the progress bar fills up and then just stays there indefinitely or at least until the screen turns itself off.

Since WP supports auto updating through the Store, I was wondering if it was possible to just have an option to disable the Hydration check if it's not an easy fix, since choosing to ignore every single time is annoying at best.

**Comment by dasilva333** [comment]
Yeah I agree I think the next release of WP is going to be Hydra-free thanks for the feedback I'm closing this out
