### ISSUE TITLE
Long initial load on Android tablet leads to broken images

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#263]
This happens on my *Samsung Tab 10.1* tablet almost every time I start the app out for the first time after powering on the tablet. The last character loaded usually has a lot of broken thumbnail images and I have to tap refresh to get things to show up. My guess is something is timing out somewhere?

Here's what I mean (http://imgur.com/dTHvEqY):
![example](http://i.imgur.com/dTHvEqY.png)

**Comment by Mulchman** [comment]
@dasilva333 any pointers as to where to start investigating?

**Comment by dasilva333** [comment]
@Mulchman the loading has been greatly improved since 6/23 please confirm if the problem still exists in 3.4.x so I can reopen the issue if it's still there. Thanks
