### ISSUE TITLE
Issue with selecting item on mobile

### ISSUE THREAD

**Issue by Titus-s** [dasilva333/TowerGhostForDestiny#268]
Hello, recently I've bought Xperia Z3 tablet and install TGD. 
There is very frustrating issue with selecting items. Often I have to tap twice or more to appear "Move to" dialog. Sometimes it appear after one tap but always with 0,5 - 1 second delay. 

I have to add, that this is not just my problem. I still recommend this app to my friends and this is the first issue they reporting to me. I don't know if you read comments on google play - for example last comment few days ago: "Not working after last update. Many bugs. Inventory is laggy as hell."

I've try to solve this issue with reboot device, reinstall app, even check screen but without success. 
Other app works fine, so the most probably problem is with TGD.

**Comment by M3Rocket** [comment]
I definitely notice this delay on various Android devices. Turning on "Destinydb Tool Tips" seems to "help" sometimes in that when you select something, the loading bar appears for the tooltip immediately followed by the Move dialog. So at least you know your click registered.

**Comment by MostDefiantly** [comment]
I have the same issue on my Kindle Fire. I tap (sometimes many many times) to get the move box to pop up. I can long press on any item and it will work 100% of the time, so it's only related to multi-clicks. 

It appears to be loosely correlated to scrolling or scroll position. If I am scrolled the top of the screen for instance, I can click pretty consistently and add or remove loadouts. If I am scrolled to the bottom of the screen I can't even click the box to assign a name to a loadout or close the box or add items or anything. I can't even select an item from the title bar (View/Set/Tier/etc).

**Comment by Reaper2015** [comment]
I can confirm that this issue is present on my new Samsung Galaxy S6. I just upgraded from an S4 and this app worked flawlessly on it.  I'm leaning towards this issue being related to the new, higher resolution QHD display/touch combo. Please fix.

**Comment by davidhosier** [comment]
I'm still having this problem.  Samsung Galaxy S5 with Android 4.4.2 and Tower Ghost 3.3.6.  Sometimes single-tap selects an item, sometimes not.  Sometimes double-tap works.

**Comment by Reaper2015** [comment]
Love this app.  Still straight up does not work (touch input) on my Galaxy S6. Having to use my old S4 on WiFi solely for this purpose.

**Comment by davidhosier** [comment]
This app is awesome, and I'd love to see it succeed.  But from a technical standpoint, I just don't understand how it's not registering taps.  Maybe there's a delay somewhere in there, or a chunk of code is running on each screen-press that gets stuck in a loop or something.

**Comment by Reaper2015** [comment]
I honestly think it's related to the new, higher resolution panels that
Samsung switched to in their more recent models, as I've not heard much
from people using phones from different manufacturers. Works great on my
S4, Galaxy Tab 8.4 Pro and on my iPhone 6 (work cell). Sister's S5, and
newer Samsung Tab (don't know the name) have the same issue as my S6.

**Comment by MostDefiantly** [comment]
I would agree about screen resolution, but my 1st Gen Kindle Fire is only like 1024x600. I am running CM11 (Kit Kat 4.4.4) on it.

**Comment by Reaper2015** [comment]
Definitely a strange issue. I don't believe it's linked to anything
software related, on the Android side, as I've seen the same issue on ICS,
JB, KK and Lollipop so far. My gut tells me it has to be a software (tower
ghost)/phone hardware disagreement or incompatibility.

**Comment by dasilva333** [comment]
I still plan to fix the issue, the problem is reproducing it. I need the hardware to reproduce it so I'll have to wait until one becomes available to me. Sorry if I can't do more guys.

**Comment by davidhosier** [comment]
Thanks for replying, @dasilva333.  I'd mail you my phone if it would help, but I kind of need it!  Is there any other way I could help?  Maybe send some debug information or something?  It's not hard to reproduce the problem on my phone -- it happens every time I use the app.

**Comment by Reaper2015** [comment]
Richard,

I'm sure I can speak for all when I say that we appreciate your hard work.
I can support in any way possible (debug data, information, etc.). I'd send
you my old S4 if it had the same issue. I can reproduce this problem on
demand with my S6 running Lollipop. I should be seeing the marshmallow
update before too long so I'll be interested to see if it behaves any
differently afterwards.

Thanks again.

**Comment by dasilva333** [comment]
It seems the problem is related to the HammerJS library I use. looking up people with similar issues turns up all these tickets:

https://github.com/hammerjs/hammer.js/issues/804
https://github.com/hammerjs/hammer.js/issues/683
https://github.com/driftyco/ionic/issues/1729

For those of you having issues if you could visit this site:

http://hammerjs.github.io/

Please confirm if you do or don't have issues registering tap and press events on their official demo site.I also came up with an android APK you can side load (3.4.3) with the latest compiled HammerJS library not the default provided 2.0.4. During my testing I found the problem was reduced but not eliminated, I'd like someone's else help testing it and letting me know if the problem gets better, the same, or worse. Thanks guys

Android APK:
https://build.phonegap.com/apps/1398768/download/android

**Comment by Reaper2015** [comment]
WEBSITE:

Galaxy S6 (Lollipop 5.1.1) - Drag = 100% / Tap = <20%

iPhone 6 -  Drag = 100% / Tap = 100%

I'll side-load the app in a few and provide feedback.

Hope this helps!

Thank you!

**Comment by Reaper2015** [comment]
First impressions of side-load:

Within 30 seconds of opening = 4/6 touches registered. Been seeing about
1/6.

After 30 seconds, back to 1/6 registering.

It almost seems like the app is not redrawing after touch. Like it's
registering all touch, but there's no overlay (gun/armor outline beneath
visible overlay) to detect the input. Hope this makes sense. Seems like the
input layer just becomes inactive. What's strange is that long-press, drag
and scrolling is completely unaffected.

Brian

**Comment by dasilva333** [comment]
I got rid of HammerJs and replaced it with another library called QUO, I built the following APK with that new library. @Reaper2015 @davidhosier @MostDefiantly Please try it again and leave any feedback as to whether it is better or worse. Thanks


https://build.phonegap.com/apps/1398768/download/android

**Comment by davidhosier** [comment]
I tried the HammerJs site on my phone, and it registered click-and-drag events, but only every few single click events, similar to how the current Tower Ghost app functions.  And I tried your most recent build in the comment above, and that seems to work perfectly.  I think you're on the right track.

**Comment by davidhosier** [comment]
I just installed the new version, and everything seems to be working beautifully.  Thanks, and keep up the good work!

**Comment by dasilva333** [comment]
Rewrote the touch input controls as of 3.9.1.1 with added support for triple tap and more consistent behavior with registering clicks, let me know if anyone is still having an issue so I can re-open this back up. Thanks guys
