### ISSUE TITLE
Auto-Equip is not Loadout Specific

### ISSUE THREAD

**Issue by chrisdudek** [dasilva333/TowerGhostForDestiny#27]
As always, the app keeps getting better and better. 

I noticed that when I create a NEW loadout and then select weapons to auto-equip, those weapons are then selected in other loadouts. 

For example, I have Loadout 1 auto-equip Primary 1. Loadout 2 auto-equips Primary 2. If Loadout 1 also has Primary 2 in it, then Loadout 1's auto-equip switches to Primary 2. I hope that makes sense. 

It would be great if the auto-equips were specific per Loadout. 

Thanks!

**Comment by chrisdudek** [comment]
Forgot to mention I am on v. 1.8.0 hydrated iOS beta for iPhone 5s.

**Comment by dasilva333** [comment]
Closing this ticket in favor of issue #13 it explains all the caveats and how the system is currently working try version 1.8.1 and thanks for your feedback

**Comment by chrisdudek** [comment]
@dasilva333 - I noticed this issue is still present in 1.8.1. To be honest, #13 covers a few topics and I wasn't fully understanding if this issue is explained in there or not.

If you could comment as to whether or not the weapons can be loadout specific, it would be appreciated. Not a huge deal if they can't be...but I thought I would let you know that this issue is still present, to see if you expect it to be or not.

Thanks again.
