### ISSUE TITLE
Loadouts options don't appear in portrait view

### ISSUE THREAD

**Issue by acedanger** [dasilva333/TowerGhostForDestiny#271]
Regarding the mobile version of TowerGhost, when I select the "Loadout" menu item, there aren't any menu items displayed when in portrait mode. When I rotate my devices to landscape mode, the menu items are displayed.

I've tried both on my phone (ATT Samsung S4) and tablet (Samsung Tab S 8.4").

**Comment by M3Rocket** [comment]
What version of TGD are you using? I can't reproduce this with 2.7.9. Seems to work fine for me on various Android devices.

**Comment by acedanger** [comment]
tl;dr it's not an issue.
In the process of taking screen shots of the issue on my phone, I discovered that the menu behind the hamburger icon is scrollable. The loadout menu items are visible when I scroll.

Thanks for making me revisit it.
