### ISSUE TITLE
Armor Loadouts

### ISSUE THREAD

**Issue by bigdave215** [dasilva333/TowerGhostForDestiny#272]
I am unable to transfer armor loadouts on a Samsung note 4.  When I try to transfer a loadout of armor it gives me a item will not be moved message.  It also has a picture of the vault instead of the character portrait.  When transferring the items back to the vault from a character it gives me the same message.

**Comment by rkingsla** [comment]
Yes, I can reproduce the behavior. It's as if the only destination possible is the vault.  I can manually move items back and forth but using a defined loadout wants to move only to the vault. Oddly, it SAYS it will EQUIP the vault if I check the item to equip.  Obviously, this would be interesting to see.  :o)

**Comment by rkingsla** [comment]
Apologies - Chrome version 2.82

**Comment by dasilva333** [comment]
There's a whole bunch of tickets already open to get this issue addressed, closing this out in favor of the earlier ones. Thanks for your feedback. This will be fixed
