### ISSUE TITLE
Focused Light consumable not showing at Postmaster

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#273]
New item from Red Bull Destiny code not showing in TGD but is showing at Bungie.net
![image](https://cloud.githubusercontent.com/assets/3769123/8468097/36fa9750-201c-11e5-8972-dc336d4cce7b.png)

**Comment by Mulchman** [comment]
Probably requires @dasilva333 running the update_definitions script?

**Comment by dasilva333** [comment]
I bought 2 cans of Red Bull yesterday I just didn't open them yet, will be opening them today and fixing this bug while I'm pumped up on Red Bull lol. Thanks for the feedback guys

**Comment by dasilva333** [comment]
I just got around to using the codes and it seems to be showing up for me just fine under Consumables, can you confirm? Thx

**Comment by M3Rocket** [comment]
It may show under consumables AFTER you pick it up? I'm still not showing it at the Postmaster. I didn't pick mine up yet because I'm saving it for The Taken King to upgrade the new sub-class.

**Comment by dasilva333** [comment]
@M3Rocket @Mulchman has this issue been properly addressed? Can we settle for a solution without an extra web request to make this work?

**Comment by Mulchman** [comment]
No. I only see the item in the invisible bucket when hitting the 'account'
endpoint.

**Comment by Mulchman** [comment]
If anyone wants this feature, it's in my runner branch.
