### ISSUE TITLE
XP Function Not Working

### ISSUE THREAD

**Issue by Elmlea** [dasilva333/TowerGhostForDestiny#274]
Using the Chrome build, V2.8.3.  When I select "missing XP," "full XP" or "maxed" from the "Progress" menu, nothing is displayed correctly.

For example, on selecting "missing XP," TGD displays some XP-filled but non-ascended 331 weapons.  It also displays some exotics ascended to 365, which are complete.

Selecting "full XP" brings up some weapons which I haven't put any XP into at all.

Selecting "maxed" works, but doesn't differentiate between non-ascended 331 weapons and ascended 365 ones.

Could an extra category be added to do this, and is this a known issue with other items not displaying correctly?

**Comment by dasilva333** [comment]
This is a known issue with the Bungie API. I will try to list this under Known issues in the app somewhere to avoid further tickets created for this. Thanks for your feedback. Closing it out until it's resolved on Bungie's end
