### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by pbjelly31** [dasilva333/TowerGhostForDestiny#275]
This might be a feature that I haven't figured out yet, but I find it a little tedious having to select an individual item and then select where to put that item before moving on to the next one. Being able to select multiple items and then select the destination would be much easier and quicker.

**Comment by dasilva333** [comment]
Try using the loadouts, that's what they're for. So you can create a group of items to quickly and easily move to a destination. I'll keep this suggestion open so I can think about a toggle mode for moving groups outside of loadouts. Thanks for your feedback

**Comment by Mulchman** [comment]
Other behaviors (mass normalizing (normalizing more than 1 item at a time))
could benefit from a multi select mode as well.

**Comment by Mulchman** [comment]
Reading this again, and seeing a post on the DIM subreddit that's very similar to the idea @pbjelly31 suggested  (https://www.reddit.com/r/DestinyItemManager/comments/3co6ob/possible_solution_to_1_pulls_lag_time/), I can see where this would come in handy for me.

Yes, as @dasilva333 mentioned, loadouts can solve this problem but loadouts are very static and unchanging.

On mobile, especially my tablet, it can take quite a bit of time to move items around. A "dynamic loadout" type of feature - multi-selecting many items then clicking transfer once - could be very beneficial. And if it did all the cool things the loadout code already does - moving/equipping to make the transfers work if things are blocked - that'd be extremely powerful.

**Comment by dasilva333** [comment]
This has already been implemented as of 2.9.1 @pbjelly31 thanks guys
