### ISSUE TITLE
All I see is "Hi"  in the top left corner of my screen

### ISSUE THREAD

**Issue by RavingGerbil** [dasilva333/TowerGhostForDestiny#276]
Nexus 6, most current android version.

**Comment by Mulchman** [comment]
When the "hi" stays for more than 30 seconds I do this:

* hit home to get out of Tower Ghost for Destiny
* open Advanced Task Killer and kill Tower Ghost for Destiny
* hit the button that shows all currently open programs (on phone I hold down the home button for a second and on tablet there's a dedicated button to it) and slide the Tower Ghost for Destiny app off the list
* try opening Tower Ghost for Destiny again repeating the cycle until it opens

**Comment by dasilva333** [comment]
Thanks for answering this for me @Mulchman good set of directions there, closing out this issue as it's something I can't fix until I release a new store binary with Hydra thanks guys
