### ISSUE TITLE
Grey screen with Hi message

### ISSUE THREAD

**Issue by LiqwdE** [dasilva333/TowerGhostForDestiny#277]
Running a rooted but stock rom galaxy note 3. All I get is a grey screen with a message saying hi... am i missing something?

**Comment by rkingsla** [comment]
Probably going to need a bit more information.  Does it literally and completely say nothing but "hi"?

**Comment by Mulchman** [comment]
That's what happens when the hydration gets stuck/doesn't work. Kill the app and try again.

**Comment by Mulchman** [comment]
https://github.com/dasilva333/TowerGhostForDestiny/issues/276

**Comment by LiqwdE** [comment]
Yes, grey screen with only the one word in top left hand corner. But it
started working so I don't know. Glitch, to much stuff open, who knows

**Comment by dasilva333** [comment]
This will be fixed when Hydra is removed from the store release, closing this ticket out thanks guys
