### ISSUE TITLE
[Bug?] Tower Ghost claims I didn't have item slots available but it appears that I did.

### ISSUE THREAD

**Issue by reneruiz** [dasilva333/TowerGhostForDestiny#279]
I've been getting this error a lot lately and I finally decided I wanted to bring this to the developer's attention for some clarification.

So I have a handful of loadouts I use, the one in particular I was trying to send to my Titan was one for all my PvE Weapons I like to use.

I've been constantly getting an error that claims I don't have item slots available. [Screenshot.](http://clicky.reneruiz.me/by2y)

So I looked back at the free slots available in the vault and my Titan, and it seems as if I should have enough, right? [Screenshot](http://clicky.reneruiz.me/by9B)

I'm open to the idea, that I'm missing a detail and just need clarification on how Tower Ghost wants to work, but on the surface, it appears—to me at least—that it *should* be working.

Would appreciate any help on the matter. Thanks all!

**Comment by dasilva333** [comment]
There's a ton of tickets open with that issue #261 #236 #240 please check for existing tickets before opening new ones. Thank you

**Comment by Mulchman** [comment]
@reneruiz do you mind recording your browser window while trying to do the loadout equip? (Jing.com has a way you can record. This'll show us the full picture of everything you're trying to do and all the steps along the way.)
