### ISSUE TITLE
Static share site issues

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#282]
Tracking some issues so we don't forget. One of these is for an unreleased feature.

* sub class images don't show
* Post Master breakout (the Messages / Lost Items sections that are unreleased) and Post Master items don't show

**Comment by Mulchman** [comment]
Actually, someone else's Post Master is showing up (http://towerghostfordestiny.com/share/?psn/Masha2932) but mine isn't (https://towerghostfordestiny.com/share/?psn/Mulchman11).

**Comment by M3Rocket** [comment]
Sub Class images are broken for me too. But Postmaster items shows fine for me.

**Comment by M3Rocket** [comment]
As is Postmaster now that I "shared" using the new version with the separate Messages/Lost Items section.

**Comment by dasilva333** [comment]
static share synced as of 2.9.1 with no issues reported
