### ISSUE TITLE
Improve Character Stats Information Window

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#285]
Currently:
![image](https://cloud.githubusercontent.com/assets/3769123/8784520/6a09beae-2ed7-11e5-8ff3-8c2bf1a7b4d6.png)

As compared to Bungie.net:
![image](https://cloud.githubusercontent.com/assets/3769123/8784566/985488d4-2ed7-11e5-8371-dfa156938dfa.png)

Need a better representation of the numbers in TGD. Not sure how Light 168 in TGD translates to Light 34 at Bungie.net?

**Comment by M3Rocket** [comment]
Also, the current Character Stats window pops up centered and at the top of the page. This becomes confusing since it's not indicated which character stats I'm looking at.

**Comment by M3Rocket** [comment]
Maybe something like this when pointer is hovered over the character emblem:
![image](https://cloud.githubusercontent.com/assets/3769123/8835156/87c223ae-306d-11e5-9293-94ec714bd230.png)

1. I left out Optics since I don't know what that stat translates to.

2. The emblem is improved over existing one. I took it off Destinystatus.com, but the Bungie.net one is very similar except it shows Clan tag rather than Character type. I prefer Character Type.

3. The emblem for the "baby" Titan on the right should probably not use the "Light" icon since it is only Level 15. Should also not use yellow color on the number--just white.

**Comment by dasilva333** [comment]
Good ideas @M3Rocket always love the layouts, just wish you could submit it as a PR so I can just accept it and move on, good stuff nonetheless thanks

**Comment by M3Rocket** [comment]
Heh--yeah! I can do Photoshop, but it's been at least 15 years since I've done any coding. I can make CSS changes and such, provide graphics, icons, etc. But you really don't want me doing any PR's. ;-)

**Comment by dasilva333** [comment]
The layout for the stats has been changed to more closely match the proposed design change, expect to see it in 2.9.4 please leave any feedback if problems found.
