### ISSUE TITLE
Sniper missing in Filter Dropdown

### ISSUE THREAD

**Issue by Solhawk17** [dasilva333/TowerGhostForDestiny#289]
I think "Sniper" is missing from the filter dropdown list. Also, can you sort that list alphabetically?

Thanks,

-Hank
![tg_weaponfilter](https://cloud.githubusercontent.com/assets/12447677/8805475/0fe28562-2f97-11e5-95cc-492723659cb0.JPG)

**Comment by M3Rocket** [comment]
This looks fixed in 2.8.9
