### ISSUE TITLE
Armor category item maximum is incorrect.

### ISSUE THREAD

**Issue by NoCodeLeftBehind** [dasilva333/TowerGhostForDestiny#29]
Currently, TGD groups helmets, gauntlets, chests, and boots under the armor category for a character. It lists the maximum for the armor category as X/30 when it should be X/40 (character can carry up to 10 of each of those 4 armor types).

**Comment by dasilva333** [comment]
Thanks man this ticket is similar to your next one issue #30 so I'm going to close this one out in favor of the other one and get that stuff done
