### ISSUE TITLE
View Options Minor Graphical Anomalies 

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#292]
From unreleased v2.8.8:
![image](https://cloud.githubusercontent.com/assets/3769123/8815753/5c8419cc-2fd2-11e5-8a30-823a4f6d44a2.png)

Suggestion:
![image](https://cloud.githubusercontent.com/assets/3769123/8815916/9d776126-2fd4-11e5-8478-61c736910d91.png)

**Comment by dasilva333** [comment]
Closed the other issue to keep it clutter free but I'm including this image as reference for what I can do to sort the characters in the future:
https://cloud.githubusercontent.com/assets/3769123/7644251/2e0c01c8-fa57-11e4-9cbb-98c844ab934d.png

**Comment by Adiel-dev** [comment]
2.8.8 has done something with the positioning of the characters and vault. Have this issue even after reinstalling on iPad and iPhone.   In the game Warlock is selected. 
![image](https://cloud.githubusercontent.com/assets/12046885/8829889/84dae3d4-3099-11e5-9fde-ba955794806a.jpg)
![image](https://cloud.githubusercontent.com/assets/12046885/8829891/84eaaee0-3099-11e5-8f34-c577eec61782.jpg)
![image](https://cloud.githubusercontent.com/assets/12046885/8829890/84e9c4d0-3099-11e5-923c-30abaab23889.jpg)
![image](https://cloud.githubusercontent.com/assets/12046885/8829892/850293f2-3099-11e5-8e0e-29dcd32efb02.jpg)

**Comment by M3Rocket** [comment]
Yeah--2.8.8 is bugged with the display modes. All should return to normal soon with 2.8.9

**Comment by dasilva333** [comment]
Problem fixed in 2.8.9 thanks guys
