### ISSUE TITLE
Hovering over consumables and materials: Hadronic Essence

### ISSUE THREAD

**Issue by Solhawk17** [dasilva333/TowerGhostForDestiny#293]
When Hovering over consumables or materials, the hover box only shows information for Hadronic Essence.

![treasurekey](https://cloud.githubusercontent.com/assets/12447677/8825722/d960ca66-3046-11e5-81b2-5ee61e3b4965.JPG)
![blackwaxidol](https://cloud.githubusercontent.com/assets/12447677/8825723/d962ab60-3046-11e5-98b0-ff5cf8963698.JPG)
![moteoflight](https://cloud.githubusercontent.com/assets/12447677/8825724/d9669a36-3046-11e5-91fc-cf70bfea84b9.JPG)

**Comment by dasilva333** [comment]
Problem fixed in 2.8.8 thx

**Comment by Solhawk17** [comment]
Cool. I was looking to see if it was mentioned in Github to avoid duplicate
issue posts, but couldn't find it.

Tower Ghost is awesome and I know we all appreciate it (The 100 Hero Squad
<https://www.bungie.net/en/Clan/Forum/805076/0/1/0>)!
