### ISSUE TITLE
POE armors stats now showing properly

### ISSUE THREAD

**Issue by waver123** [dasilva333/TowerGhostForDestiny#295]
I'm running chrome version 2.8.7 on windows.
The popup diaglog box use to properly show the stats *int/dis/str" of my POE armor, now it's showing some generic values, e.g. my POE chest piece for example are all showing as "77/174", I can't tell one from the other.

![ghost_pr](https://cloud.githubusercontent.com/assets/1783531/8835698/e8db3876-3070-11e5-82e1-c55910e64294.jpg)

**Comment by waver123** [comment]
was this fixed?  issue was not correct?
There's no reason given on closing.

**Comment by M3Rocket** [comment]
Yes--this has been fixed. New version coming in a few hours. Here's how it looks now:
![image](https://cloud.githubusercontent.com/assets/3769123/8837706/8ee99450-307c-11e5-8c30-99db3e190f68.png)

**Comment by waver123** [comment]
thank you!
