### ISSUE TITLE
The popup title for all Materials displays "Spinmetal" 

### ISSUE THREAD

**Issue by WarbirdXBL** [dasilva333/TowerGhostForDestiny#298]
The popup title for all Materials displays "Spinmetal" .
It does not inhibit transfer, but is troubling.

**Comment by M3Rocket** [comment]
Yes--fixed in upcoming version. Should be an hour or two at most.

**Comment by dasilva333** [comment]
Problem fixed in 2.8.9

**Comment by WarbirdXBL** [comment]
Thank you thank you thank you!  And another thank you for reading my mind about idea of locking the emblems to the top when scrolling :)
