### ISSUE TITLE
Vault area in TGD should be reorganized to more closely match actual Vault

### ISSUE THREAD

**Issue by NoCodeLeftBehind** [dasilva333/TowerGhostForDestiny#30]
The Vault area in TGD is divided into Weapons, Armor, Misc, and Styling storage areas.  However, the actual Vault has only Armor, Weapons, and General storage areas. This difference results in an inaccurate/unclear representation of available Armor and General space. For example, TGD lists Class items under Styling, but the in the actual destiny Vault they are cosidered armor and take up space in the Armor storage area. (Destiny itself calls these Class Armor.) My suggestion would be to move Class Armor up under the Armor category (include count in maximum /24 in Vault and /50 on character). Replace Misc with General and include everything else under Misc and Styling to sub categories under General.

**Comment by dasilva333** [comment]
I agree the counts and organization will be redone based on your feedback. I think moving things around and changing the counts like this will really help clear things up. Expect it in the next version thanks.

**Comment by dasilva333** [comment]
@NoCodeLeftBehind Try version 1.8.4 and report back to close this ticket thanks

**Comment by WarbirdXBL** [comment]
Regarding max counts reflecting  the new 1.1.2 values, it looks fine in FF 1.8.4.

**Comment by dasilva333** [comment]
Great I'm glad it was thanks to @NoCodeLeftBehind  feedback that pushed me for revamping the layout into three sections General/Armor/Weapons. Closing the ticket as the issue has been resolved

**Comment by NoCodeLeftBehind** [comment]
Reorganization looks good, but there are a couple minor issues:
1) While class items are now grouped/displayed  under Armor, their item count is still included in the count for General and not for Armor as it should be to accurately reflect status. This is true for Vault and actual characters.
2) Vault now lists an empty Post Master section. I think only actual characters need and should have a Post Master section.

**Comment by dasilva333** [comment]
Reopening ticket so I can take care of those minor issues, thanks man

**Comment by NoCodeLeftBehind** [comment]
Oh I made a new issue as I wasn't sure you would see this. Close one or the other if you want. Keep up the awesome work!

**Comment by dasilva333** [comment]
Since you're around I'll make 1.8.7 for Chrome/Firefox please retest it to make sure it's solved completely and close both issues. Thanks
https://github.com/dasilva333/TowerGhostForDestiny/tree/div-movile-dist

**Comment by NoCodeLeftBehind** [comment]
Sorry, I was heading out as I wrote that and just got home to test. Looks good now except the General area has incorrect item count (too high) on the characters (but Vault is correct). From the math, it appears to me the class item count is still being included in the characters' General area count (instead of just in the Armor area--i.e.they are getting counted in both).

**Comment by dasilva333** [comment]
The armor counts seem fine for all my stuff but after adding up the values for my general section it seems 1 of them has an invalid count. I tested it by counting the values of each bucket and verifying it matches the total. I'll have to test all 3 columns now to make sure it comes out right. Thanks for your help, it will be fixed.

**Comment by NoCodeLeftBehind** [comment]
Yeah, Armor section count is definitely good now. It is just the General section count that is too high on each character, and the difference in what TGD shows and actual＝the number of class items on that character, so that's why I think they may be getting counted in both places.

**Comment by dasilva333** [comment]
Turns out it was counting the post master in the general items so that's why it was off. Expect a fix in the next version

**Comment by dasilva333** [comment]
hey @NoCodeLeftBehind try out the latest version and confirm the counts are good thanks

**Comment by NoCodeLeftBehind** [comment]
All item counts are good. Nice work.
