### ISSUE TITLE
Missing Subclass perks in 2.8.9

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#303]
It used to show in 2.8.7:
![image](https://cloud.githubusercontent.com/assets/3769123/8862399/32491c38-3145-11e5-9d88-1bb82a5c4d14.png)

In the current 2.8.9 build:
![image](https://cloud.githubusercontent.com/assets/3769123/8862438/5f792f2c-3145-11e5-8c32-33ceb80eab39.png)

**Comment by dasilva333** [comment]
problem fixed
