### ISSUE TITLE
DestinyDB Tooltips visual anomalies

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#304]
When showing properly:
![image](https://cloud.githubusercontent.com/assets/3769123/8863104/9116e722-314a-11e5-8a61-8a7245e2ccc2.png)
![image](https://cloud.githubusercontent.com/assets/3769123/8863130/bbc547c0-314a-11e5-9ce4-0b4116f72507.png)
![image](https://cloud.githubusercontent.com/assets/3769123/8862880/f38e5e50-3148-11e5-9a2a-78dd46ef8ae6.png)

Incorrect in 2.8.9:
![image](https://cloud.githubusercontent.com/assets/3769123/8862767/f2e61098-3147-11e5-8c76-134bc0ab926e.png)
![image](https://cloud.githubusercontent.com/assets/3769123/8863067/4cae22da-314a-11e5-96a0-30f11f0b65de.png)
![image](https://cloud.githubusercontent.com/assets/3769123/8862774/fd206b44-3147-11e5-8157-74440ac35c77.png)
![image](https://cloud.githubusercontent.com/assets/3769123/8862778/09ebc10c-3148-11e5-8dcf-ce533b6acd46.png)
![image](https://cloud.githubusercontent.com/assets/3769123/8863188/50b9b58c-314b-11e5-966f-a364015e6db6.png)

**Comment by M3Rocket** [comment]
@Mulchman Seems to me that the Bounties Tooltips are slightly narrower than the others. Also, the icon is also smaller.

Is there any way to leave the description of the bounty in there after it's completed instead of the awfully redundant "Turn in at the Bounyy Tracker to collect your reward."

**Comment by dasilva333** [comment]
problem fixed
