### ISSUE TITLE
Sticky Character Emblem visual improvement 

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#306]
The sticky Character Emblems recently introduced in 2.8.8+ works really well in most cases. However, on mobile devices where not all four columns are shown at the same time, there can be situations when scrolling where it can be confusing as in this screenshot:
![image](https://cloud.githubusercontent.com/assets/3769123/8865537/12f2f014-3165-11e5-8238-5f0e3a1ddb6f.png)

1. This is the weapons only view (swipe right on mobile). 
2. Scroll down till the first two characters end and where the third character and vault (my vault is set to display last) is displayed without a header emblem.

I think row 2 and up need character emblems as separators as well. Row 1 doesn't need it simply because as soon as one scrolls above the 2nd row, the 1st row emblems would appear and the 2nd row separator emblem would scroll down.

**Comment by dasilva333** [comment]
Sorry man I disagree with these changes I think the current system is fine and not confusing, regarding the vault emblem it's normal for it to not show if you scroll past the point you can see it. Thank you anyways for your feedback

**Comment by Mulchman** [comment]
Look carefully at the picture. There are 4 characters being shown but only
2 emblems. It's pretty confusing, actually.

**Comment by matthubb** [comment]
I agree with Mulchman. Playing with this last night. It was pretty confusing where the next character starts and that the indicators don't update until the scrolling stops. 

There was a native l HTML5 thing for floating section headers that are pushed out when the next one comes along.... But it was removed. 

Was trying to think of better ways. Like leaving the character banners in for those that aren't the top ones. Bit messy.

**Comment by M3Rocket** [comment]
@dasilva333 Not sure you understand what I meant. I didn't mean to change the floating headers. What I meant is exactly @Mulchman and @matthubb describes.

**Comment by dasilva333** [comment]
Alright yes I agree I'm reopening this issue so I can take care of the problem I see. Sorry I misunderstood the problem earlier. Bottom line is there are 4 characters showing and only 2 emblems show up. In the screenshot provided in the first post the active characters should have position: fixed emblems and the Hunter/Vault should have position: relative emblems that fit in the blank space shown. I'll make some tweaks to it to account for that scenario thanks for the feedback

**Comment by dasilva333** [comment]
This has been fixed as of 2.9.0 closing it out
