### ISSUE TITLE
weapon filtering

### ISSUE THREAD

**Issue by PillowMetal** [dasilva333/TowerGhostForDestiny#308]
There is a weapon filter for the exotic bounty which makes since it is a weapon bounty, but then there is a filter for vanguard bounty as well. I can understand wanting to include that bounty for filtering, and it doesn't really fit anywhere else, but to be consistent and complete, shouldn't you also have the crucible bounty, the iron banner bounty, and queen's bounty included in weapon filtering as well?

An alternative would be to create a new menu item filter just for bounties, but that may be overkill since exotic bounty does actually belong in the weapon filter and the others could just come along for the ride.

**Comment by dasilva333** [comment]
This is a bug in an old version, weapons should only show in the weapons filter. Please state your version # next time creating a bug thank you.

**Comment by PillowMetal** [comment]
I always have the latest version pushed to me in the Chrome browser, but I am not getting 2.9.0 pushed to me for some reason.  Even if I refresh or update my extensions, I am not getting the new version, I am still stuck on 2.8.7. Why would that be? I even uninstalled the extension and re-installed it and the Chrome store is still using 2.8.7
