### ISSUE TITLE
hover popups

### ISSUE THREAD

**Issue by PillowMetal** [dasilva333/TowerGhostForDestiny#309]
When hovering over consumables and materials, all titles read "Hardonic Essence". This may be a DestinyDB issue, but I wanted to point it out for you to take a look.

**Comment by rkingsla** [comment]
Hey, PillowMetal....  Which device/browser and version of TGD?  This problem (as I recall) was fixed a version or two ago...  Current version is 2.9.0 on Chrome, and iOS devices... (those are the two I use....)

**Comment by dasilva333** [comment]
Like @rkingsla said, this has been fixed as of 2.9.0 thanks for your feedback

**Comment by PillowMetal** [comment]
I always have the latest version pushed to me in the Chrome browser, but I am not getting 2.9.0 pushed to me for some reason. Even if I refresh or update my extensions, I am not getting the new version, I am still stuck on 2.8.7. Why would that be? I even uninstalled the extension and re-installed it and the Chrome store is still using 2.8.7
