### ISSUE TITLE
Chrome extension is "stuck" on 2.8.7

### ISSUE THREAD

**Issue by payote** [dasilva333/TowerGhostForDestiny#310]
The Chrome extension has not updated since 2.8.7 was released on July 20th. The current version in the Chrome web store is 2.8.7

https://chrome.google.com/webstore/detail/tower-ghost-for-destiny/gdjndlpockopgjbonnfdmkcmkcikjhge?hl=en

**Comment by PillowMetal** [comment]
This is the exact problem I had that led me to report 3 bugs that apparently have been resolved in later versions. I too am stuck on Chrome 2.8.7 even after uninstalling and re-installing.

**Comment by payote** [comment]
Yes, the update came through for me as well. Closing.
