### ISSUE TITLE
Tool Tip visual inconsistency

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#311]
There seems to be some extra spacing with some of the perks listings on weapons.
![image](https://cloud.githubusercontent.com/assets/3769123/8891881/cf2a814a-32ee-11e5-83ce-c75383a1c603.png)

**Comment by rkingsla** [comment]
I might be wrong, but I think that these are pulled directly from destindb.  Much like the bungie.api, I'm thinking that the team can't do much with what destinydb serves up.  

Of course, I could be wrong.

Good catch, though!

**Comment by dasilva333** [comment]
Problem fixed, expect to see it in 2.9.1 thanks
