### ISSUE TITLE
iOS Remote Control Script?

### ISSUE THREAD

**Issue by DTGBR** [dasilva333/TowerGhostForDestiny#312]
I have the iOS version of Tower Ghost.
When I start it I get this alert box:

>##### index.html
>You will see this warning once per session.

>You are using a remote control script on this site - if you accidentally push it to production, anyone will have control of your visitor's browser.  Remember to remove this script.

Even after deleting and reinstalling I still get this message.

Am I risking getting my account hacked if I run this?

**Comment by dasilva333** [comment]
Sorry about that I left the debug tag on today for a few hours it should be cleared up as of 7 hours ago, so please try to run a hydra update before reporting new bugs to ensure it's gone. Thanks for your feedback
