### ISSUE TITLE
2.9.0 apk w/o Hydration?

### ISSUE THREAD

**Issue by DMWill** [dasilva333/TowerGhostForDestiny#313]
I'm not sure where to post this since this isn't a technical issue.  Android, through the PlayStore is stuck on version 2.8.6.  TGD only works on my tablet without Hydration.  Is there somewhere I can download the apk for 2.9.0 without Hydration?

**Comment by dasilva333** [comment]
It's coming to the app store soon, no other way to try it out otherwise. Thanks for your feedback
