### ISSUE TITLE
Show missing items bar obscured by vault and character headers

### ISSUE THREAD

**Issue by mike565sd** [dasilva333/TowerGhostForDestiny#315]
In Chrome for OSX, when viewing an item set and "Show Missing Items" is selected, the missing items  bar shows up behind the headers for the vault and characters until the browser is resized. After resizing the browser, the headers pop down beneath the missing items bar.

Missing Items behind headers:
<img width="1345" alt="screen shot 2015-07-27 at 11 52 46 pm" src="https://cloud.githubusercontent.com/assets/8825840/8925211/c1706a10-34ba-11e5-9334-2ad73a7cdb0d.png">

Missing Items above headers (after resizing browser):
<img width="1354" alt="screen shot 2015-07-27 at 11 53 13 pm" src="https://cloud.githubusercontent.com/assets/8825840/8925208/bceae8bc-34ba-11e5-8495-b7ce7c371c72.png">

**Comment by dasilva333** [comment]
This is fixed as of 2.9.2 and will be furthered improved in 2.9.3 thanks @mike565sd
