### ISSUE TITLE
Suggestion: Generate Armor Data-file/Webpage (stats, perks)

### ISSUE THREAD

**Issue by wein3967** [dasilva333/TowerGhostForDestiny#316]
For those of us that like to play around with armor builds (chronic optimizers), it would be helpful if we could "dump" a data file (or simple csv webpage) containing a list of all the armor and their associated stats and perks. A sample list might be Class, Type, Tier, Name, Light, Intellect, Discipline, Strength, Perk, Perk, etc..

**Comment by dasilva333** [comment]
Thanks for the feedback, I don't agree with this functionality. If you want the ability to dump all your data from TGD into a CSV here's the gist for it:

https://gist.github.com/dasilva333/80cd9135118b23ac7ed7

**Comment by wein3967** [comment]
Thanks. JS isn't really my language, but I'm happy to take a look at your example and try to take it from  there.

**Comment by dasilva333** [comment]
Simple you open the extension in Chrome, press F12 to open the Developer window, click on the Console tab on the right top side. Paste my code into the console and press Enter. The page should automatically queue up a file for you to download which is the csv of all your items

**Comment by wein3967** [comment]
Ahh, I see. Appreciate the walk-through. Excellent. Thanks.
