### ISSUE TITLE
Prison of Elders class items not listed when filtering by "PoE Armor"

### ISSUE THREAD

**Issue by Tsothoga** [dasilva333/TowerGhostForDestiny#318]
As the title says, the three items listed below don't appear to be included in the "PoE Armor" filter:

Mark of a Kellslayer
Kellhunter's Hood
"Dread's Enmity"

**Comment by schubydoo** [comment]
Working on a fix shortly.

**Comment by dasilva333** [comment]
This has been fixed as of version 2.9.2 thanks @schubydoo
