### ISSUE TITLE
Unable to close release notes on iPad Air 2 / iOS 9.0 beta

### ISSUE THREAD

**Issue by floatingatoll** [dasilva333/TowerGhostForDestiny#319]
Hi, since pushing iOS 9 to my iPad Air 2, I've been unable to move beyond the release notes dialog on my iPad Air 2. The 'x' is untappable and there's no other apparent way to bypass the release notes.

**Comment by dasilva333** [comment]
It's a known issue, there is an update that will be pushed to the store for 2.9.1 that will fix that. Thanks

**Comment by mackan11** [comment]
Hello i can conform IOS9 beta still has the same issue on 2.9.1, "he 'x' is untappable and there's no other apparent way to bypass the release notes"

in the IOS app Store it shows ver 2.1.3 (updated 20/may/2015) but then i lunch the app it then updated it self to ver 2.9. might this be the issue as it was not the main update from the app store.

**Comment by dasilva333** [comment]
Latest App Store version is 2.1.3, we are waiting on Apple to finish reviewing actual 2.9.1 which once updated will fix the problem with IOS 9. Thanks guys

**Comment by dasilva333** [comment]
Apple officially approved 2.9.1 for the App Store try it now @mackan11 @floatingatoll This problem should be fixed now thanks guys
