### ISSUE TITLE
Armor Shader showing as menu selection in Weapon menu

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/TowerGhostForDestiny#32]
As the title states there's a selection for Armor Shader within the menu selection. I'd previously seen a Helmet entry too.

Screenshot says it all:

![img_0115](https://cloud.githubusercontent.com/assets/19838/7160438/fe15076a-e356-11e4-9340-83798df0ab3a.PNG)

**Comment by Titus-s** [comment]
I have still Helmet in 1.8.4:
![image](https://cloud.githubusercontent.com/assets/11790750/7179776/793d1bbe-e43b-11e4-8e4a-ed0a733115bd.png)

**Comment by dasilva333** [comment]
Yeah the issue hasn't been addressed yet thanks for looking out tho

**Comment by dasilva333** [comment]
Problem fixed as of 1.8.7 please retest and close the ticket thanks

**Comment by ssoriche** [comment]
Confirmed fixed.
