### ISSUE TITLE
Receiving error when trying to use Tower Ghost in Firefox.

### ISSUE THREAD

**Issue by indiemonk** [dasilva333/TowerGhostForDestiny#320]
When I try to access my inventory in Firefox, the app gives me " Error: Please add valid X-API-Key header to request. Visit https://www.bungie.net/developer for details." I have no idea if this is on my end or what but I can't access my inventory at all.

**Comment by klefto3** [comment]
I'm getting the same error code.

**Comment by dasilva333** [comment]
Thanks for the heads up, not sure why this is happening I will get this fixed, in the meantime Chrome and mobile platforms still work as well as standalone Windows/OSX/Linux

**Comment by patchm00** [comment]
what windows standalone?

**Comment by patchm00** [comment]
same error btw, was working this afternoon about 3 hours ago and just now getting that error

**Comment by apbrimah** [comment]
I too am receiving this error (all day yesterday). I had to resort to other tedious methods (LOL). Hopefully there will be a solution found today. Thanks for such a great tool.

**Comment by dasilva333** [comment]
Download the zip of the master project and run the launch.bat file to use the app as a standalone windows app.

**Comment by apbrimah** [comment]
I don't see a zip file. Have a direct link? Thx

**Comment by dasilva333** [comment]
https://github.com/dasilva333/TowerGhostForDestiny/archive/master.zip There you go

**Comment by apbrimah** [comment]
Thanks!

**Comment by indiemonk** [comment]
Problem seems to be solved now. I've been having no problems accessing my inventory at all today.

**Comment by apbrimah** [comment]
Same here. Thanks!!!

**Comment by dasilva333** [comment]
I think it ended up being a problem with the Bungie back end, glad it's resolved now
