### ISSUE TITLE
Optimise iOS app for iPhone 6/6+

### ISSUE THREAD

**Issue by liammackie** [dasilva333/TowerGhostForDestiny#322]
It would be really nice to have a larger version of this great tool on this damn mammoth screen!

**Comment by rkingsla** [comment]
I may be completely misunderstanding the request, but have you looked into the options to layout and resize the columns and items?  For example, from my iPad Mini... Select View -> View Options  Play around a bit with the Grid for XS to LG, 1-4. You should be able to find a combination that should suit your 'phablet'.

**Comment by dasilva333** [comment]
Indeed @rkingsla good answer, that's how you can optimise it and personalize it to your needs, under View | View Options
