### ISSUE TITLE
Floating headers causing poor performance

### ISSUE THREAD

**Issue by DrPippin** [dasilva333/TowerGhostForDestiny#323]
Since the floating headers were introduced the app's smoothness has been rather significantly negatively impacted. If this has not been noticed by other people I will take a video of it to demonstrate what I am referring to. Personally, I am ok without floating headers as the character emblems are highlighted to denote which character you are on. Is this something that can be removed to improve smoothness, or have an option added to the settings to allow us to individually decide if we want it? If it is here to stay, I have a possible implementation that could improve the app's snappiness when scrolling through characters that I can try and describe if warranted.

**Comment by dasilva333** [comment]
Cool man thanks for the feedback I haven't received any complaints about that so thank you for letting me know. Let's do both I say I make it an option in the settings to enable/disable and you provide a pull request with the better implementation so that when enabled it'll perform better for those users.

Thanks

**Comment by dasilva333** [comment]
This will be fixed in the next version @DrPippin

**Comment by DrPippin** [comment]
I looked at making a pull request, unfortunately I'm a bit lost with github as a non-programmer (anything beyond cout << "hello world"; loses me).  I didn't understand the requirement to select a base/compare branch, and didn't want to mess something up.  So, instead, I'll just make a quick description of what I have been seeing happening in iOS 8.4, and then try and outline what I envisioned.  If it is something that can be used I'll let you copy/paste this to wherever it needs to end up:

Currently the floating header bar switch off when moving between characters isn't happening until you stop scrolling.  If you don't stop scrolling, you'll be looking at the inventory of your second or third character despite still having the floating header (and outline around the emblem) denoting the vault.  If you start at your second character with the floating header and emblem outline denoting the second character, you can scroll straight to the bottom of the app and never have it switch the floating header/emblem outline to the third character until you finally stop scrolling at the bottom of the app.

Also, the first time you tap on one of the quick-jump emblems to jump straight to a specific character the screen scrolls to the appropriate character but then jumps back up 1/3 of a screen and no floating header is displayed.  When this happens sometimes two emblems are outlined (the original in full brightness and the one you tried to jump to in half brightness).  If you tap an emblem to jump to it a second time it correctly jumps to the start of that character and highlights the emblem/displays the header appropriately.  The third time you try to jump to a character through an emblem touch it incorrectly does the jump & header/emblem display just like the first time.  The fourth time jumping by emblem works properly.

If I'm remembering correctly, prior to implementation of the floating header the emblem outline would properly update to the correct character as you scrolled and without need to stop scrolling.  If this was the case and it is possible to reinstitute that behavior, what I envisioned was making the fixed header bar slightly taller, moving all the information in the header bar up to the top, and adding text in the fixed header bar beneath the emblems that is linked with the emblem outline to say what character is currently being looked at in plain white letters (VAULT, TITAN 34, etc).  This would completely do away with the current floating header bar and hopefully remove the issues that have been occurring with it not handing off correctly when scrolling between characters. Currently the four emblems (vault and three guardians) are sitting at the very bottom of the fixed header bar, so even if this suggestion isn't implemented, I would love to see the emblems centered vertically in the fixed header bar like "TGF" and the settings icon are.

**Comment by dasilva333** [comment]
Thanks anyways, try out 2.9.3+ it has improved support I would say it's 90% ready because it has a small chance of glitching sometimes. Try it out and let me know thanks.

As for contributing you can check out this document here for more info:
https://github.com/dasilva333/TowerGhostForDestiny/blob/master/CONTRIBUTING.md

You can also use paint/photoshop to make crude mock ups of what you mean as I don't really understand very well (can't visualize) what you're trying to say. Thanks for your feedback though. Cheers

**Comment by rkingsla** [comment]
Or, you can use Jing to actually record what is happening...  It's a free tool by TechSmith that records the screen and...  Just a thought.  I've found it pretty helpful since I found about it here a few months ago.

Get it here:  https://www.techsmith.com/jing.html
