### ISSUE TITLE
Selecting 'General Items' in multi-select results not correct

### ISSUE THREAD

**Issue by rkingsla** [dasilva333/TowerGhostForDestiny#325]
The below occurs in both Chrome and Windows 10 desktop - iOS not yet tested.

Checking all other scenarios, the multi-select feature works correctly. When selecting materials or consumables under a character for multiple item transfer to another character results in "Currently unable to create loadouts with this item type."

When under the Vault, all items under General result in (at least my case) a Vanguard package item being placed in the 'To Transfer' stack. Trying to select more than one General item results in "Currently unable to create loadouts with this item type."
![multi-select-1](https://cloud.githubusercontent.com/assets/2037051/9277039/4cb5c542-426d-11e5-98d4-db1291183520.jpg)
![multi-select-2](https://cloud.githubusercontent.com/assets/2037051/9277041/4cb7353a-426d-11e5-8b30-0df81d6848d6.jpg)
![multi-select-3](https://cloud.githubusercontent.com/assets/2037051/9277040/4cb5c664-426d-11e5-9675-a95c798e1761.jpg)

**Comment by dasilva333** [comment]
Multi-select and loadouts will not support materials and consumables, I will do a better job at making sure that it is clear when you attempt to do so and clean up some of these problems. Thanks

**Comment by rkingsla** [comment]
Cool....  thanks, Richard!

**Comment by rkingsla** [comment]
BTW, I *LOVE* this feature add.  Another differentiator in the TGD column....
