### ISSUE TITLE
How do you actually update the iOS up now since the Hydra updater was removed?

### ISSUE THREAD

**Issue by Adiel-dev** [dasilva333/TowerGhostForDestiny#326]
There seems to be no indication how to update the App or will it go through the App Store now for every .x.x release?

**Comment by dasilva333** [comment]
You pretty much just wait until the next update from the app store like every other app.

**Comment by Adiel-dev** [comment]
Okay I like it. The tradeoff of not having the latest version right away is well worth the consistency. What about the standalone desktop apps? Do you have to re-download them manually from the site when new versions hit or do they update automatically?

**Comment by dasilva333** [comment]
Those have to be manually downloaded as well, currently the only platform that supports auto updating to the latest version is the Google Chrome Store.

**Comment by Adiel-dev** [comment]
Good to know. Maybe put that on the site next to the download links? So people don't hang on to the old versions for too long.
