### ISSUE TITLE
Windows Phone multi select bugs

### ISSUE THREAD

**Issue by equesaspe** [dasilva333/TowerGhostForDestiny#328]
Hi. The double click function on windows phone takes more than two presses. Sometimes the dialog of the multi select is covered by the normal move dialog. Also when selecting the UI can duplicate the same item twice in the multi select even if you have one. I am using a Nokia Lumia 1520. Suggested fix: Double click on touch screen mobile is wonky at best. Add a multiselect bottom to the top bar next to the character slots so that it scrolls down. When you want to multi select press it to pop up the UI and then select items.

**Comment by dasilva333** [comment]
Agreed while it works a lot better in iOS there is definitely room for improvement on the WP side. Thanks for the suggestion I'll look into making it better.

**Comment by equesaspe** [comment]
I wouldn't bang your head against the wall or anything. It works if someone wants to use it but I think a button would work better without a headache (for you).

**Comment by dasilva333** [comment]
I think the header icon for each section next to the refresh icon is a brilliant idea as it would solve the issues in Android/WP for getting the multi-select working.

**Comment by dasilva333** [comment]
Multi select icon added to 3.0.1 plus expect to see it in the next release thanks @equesaspe
