### ISSUE TITLE
Move refresh timer (300 seconds) closer or part of Refresh (secs) section

### ISSUE THREAD

**Issue by moeyjar** [dasilva333/TowerGhostForDestiny#329]
So I feel pretty dumb, but the 300 beside the search wasn't quite apparent that this was the refresh time for the page.  I thought it had something to do with filtering for the gun levels! 

To make this clearer, maybe the Refresh number should be closer, or part of the Refresh dialog (maybe where it has (secs), would certainly make this more apparent.

**Comment by dasilva333** [comment]
Thanks for the feedback, it's no big deal to move the 300 to be closer to the refresh so that its more visually appealing. I'll try it out thanks again

**Comment by dasilva333** [comment]
Part of 2.9.5 thanks
