### ISSUE TITLE
[Rename] Update Loadouts to Respect Actual Vault Space Availability

### ISSUE THREAD

**Issue by chrisdudek** [dasilva333/TowerGhostForDestiny#33]
Wanted to start out saying that the loadout feature is working better and better man, great work.

It would be a huge time saver for me and probably others to be able to move multiple weapons (and/or items, armor, etc.) to the vault or other characters at the same time. I realize that the loadouts has a similar function, but let me try to explain...

If I start up Crota Raid, I can equip my "Raid - Crota" loadout on Character 1. I blast through that raid and want to go straight into VoG. Depending on my weapon selection per raid, there can be a completely different set of weapons I want to run with. So I try to equip my "Raid - VoG" loadout on Character 1, but his slots are full. I need to move items to the vault, and in mass, so I can equip my VoG loadout. Right now, I am having to click the weapons one by one and then move each to the vault. It's not terrible by any means, way better than it was before we could even do it before apps. But if I have to move 10+ weapons over, it takes some time.

My suggestions (when I write items I'm referring to Weapons/Armor/Materials/etc.):

1. Ability to select multiple items and then move them in mass
2. Ability to select a loadout and move all items to vault (without the app trying to swap those for items for others of the same type, unless it is out of space)

Option 2 might be the easiest to do and it would work effectively. If I'm done running Crota, I can hit the Crota loadout and select "Vault", then go to my VoG loadout and equip to Character 1.

Thanks!

**Comment by dasilva333** [comment]
"So I try to equip my "Raid - VoG" loadout on Character 1, but his slots are full. I need to move items to the vault, and in mass, so I can equip my VoG loadout."
-Not a true statement, if you try to use your VOG loadout and the slots are full you will be prompted with the option to swap an existing gun in that bucket with your target item. There is no need to manually move stuff out of that character and into the vault as the loadout process already takes care of the swaps for you.

Regarding your suggestions:
1. I won't be implementing that as it is already part of loadouts
2. That ability already exists using: Create a loadout, click on the Vault icon
(if your vault is out of space it'll try to swap if it all those items fit in there without a swap it'll just simply move them)

Closing this ticket as there is no issue to be had here.

Thanks for your feedback!

**Comment by chrisdudek** [comment]
For number 2, the Vault is not full. See screenshot below. I created a loadout of 1 weapon (currently on Titan). I then select the loadout, hit Vault, and it tells me it HAS to do a swap:

![vault](https://cloud.githubusercontent.com/assets/11835064/7168383/a2b87f7e-e382-11e4-95a4-ed4dd7bebcb7.jpg)

It shouldn't have to swap anything out. It should just move the Vex to the vault. Please let me know if I'm missing something obvious.

**Comment by b0bbybacc** [comment]
This could be, just guessing, an issue with the fact that the vault space for weapons just grew to 36. I haven't looked to see if anyone has changed the logic when checking how many weapons are currently in the vault when it comes to the swap logic.

**Comment by dasilva333** [comment]
Good job sir, sorry about closing the ticket early your second example made it obviously clear there is a problem. I was able to reproduce the issue and indeed it only happens when applying the loadout to the vault. It's under the impression the vault only has 10 slots so it treats everything as a swap. I'll be adding a fix to prevent that from happening.

Thanks

**Comment by dasilva333** [comment]
Problem will be fixed in 1.9.6 please try it out and let me know thanks @b0bbybacc and @chrisdudek

**Comment by chrisdudek** [comment]
Thanks man. I'll give it a shot once 1.9.6 is out for UDID iPhone version.

**Comment by dasilva333** [comment]
@chrisdudek @b0bbybacc the fix for try to move a loadout of say 1 item into the vault and it wanting to swap despite there being space has been addressed as of 1.9.7. please try it out and let me know thanks

**Comment by chrisdudek** [comment]
Works like a charm man. Great job and thanks for the quick fix!
