### ISSUE TITLE
2.9.4: Third character is broken.

### ISSUE THREAD

**Issue by schubydoo** [dasilva333/TowerGhostForDestiny#330]
After upgrading to 2.9.4 my third character is stuck.  I can't close the stats window, and the weapons/armor won't show.  Not sure what changed, but I did try closing, restarting, re-installing.

![capture](https://cloud.githubusercontent.com/assets/12485317/9320643/3bba467c-4511-11e5-8842-5a818977e958.PNG)

**Comment by dasilva333** [comment]
It's fixed as of 2.9.5 thanks for the feedback let me know how it goes
