### ISSUE TITLE
Load Outs - Duplicate Items

### ISSUE THREAD

**Issue by Solhawk17** [dasilva333/TowerGhostForDestiny#332]
I have 2 Ice Breakers and 2 Gjallarhorns. I created a load out with Ice Breaker and Gjallarhorn, both fully ascended. After transferring the load out to a character, the NOT ascended ones were transferred instead of the fully ascended ones.

Thanks!

**Comment by dasilva333** [comment]
@Solhawk17 Try 2.9.6 coming soon and let me know if you can still reproduce the issue. thanks

**Comment by Solhawk17** [comment]
This looks good now. Thanks!!!
