### ISSUE TITLE
Updating iOS Version past 2.9.1

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#333]
Out of curiosity how can I force an update from 2.9.1 to the current 2.9.5 on iOS? Neither the app store version nor the one in Test Flight let me get past 2.9.1. While this version is fine, you have made big improvements in load out transfers that I would like to take advantage of :-).

**Comment by dasilva333** [comment]
You can't, just gotta wait until I submit another update to the App Store and Apple approves it. I'm planning on submitting 2.9.6 to the AppStore this week so expect to see it next week. Thanks

**Comment by pattont** [comment]
Excellent, I was just used to the updates coming in as I started the app.
