### ISSUE TITLE
Lock/Unock (Your Users Will Want This)

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#334]
Differences aside, TGfD is still the best and users will want this. (This is from my private branch if anyone's wondering why everything is nicely aligned + full character reload on clicking the emblem header).

Commits:
* Bulk of it: https://github.com/Mulchman/TowerGhostForDestiny/commit/f4bb46d9f271332d7beac7f8158a298df0e7145f
* Excluding it on consumables and materials: https://github.com/Mulchman/TowerGhostForDestiny/commit/2144749cc6c21dc90f4b4ebb224abcd71d7ba0b3)

Video showing item lock/unlock: http://screencast.com/t/zFwSZhbM6Xi8

No pull request.

**Comment by dasilva333** [comment]
Cool stuff, excellent idea good job on that. So how should we go about integrating it in TGD?

**Comment by rkingsla** [comment]
BTW, I love this....  The Jing video TOTALLY nails why this is super-cool....

**Comment by dasilva333** [comment]
Thanks @Mulchman differences aside your work is awesome keep it up :-) Btw I modified the autoPadHeight function so check it out when you can

**Comment by Mulchman** [comment]
Think you broke it.

![example](http://i.imgur.com/eRoJP2l.jpg)

**Comment by dasilva333** [comment]
Try it now it should be good to go, thanks for that good looking out
