### ISSUE TITLE
Unable to transfer loadouts if attempting to move 10 weapons to one bucket in game

### ISSUE THREAD

**Issue by dasilva333** [dasilva333/TowerGhostForDestiny#336]
Title says it all, basically while you're in game the API disables the ability to unequip your currently in-use weapon so I'll have to add logic to account for that error/scenario and allow the loadouts to continue despite this problem.

**Comment by rkingsla** [comment]
Ahhh!  So THAT'S what the issue is....  OK, makes sense now.

**Comment by dasilva333** [comment]
Problem fixed as of 2.9.9 let me know if you still have problems @rkingsla thanks
