### ISSUE TITLE
Nepal Shader and Emblem are not showing

### ISSUE THREAD

**Issue by rkingsla** [dasilva333/TowerGhostForDestiny#337]
Title says it all.... The correct Character banner does show up. Anything I can provide?

**Comment by dasilva333** [comment]
Expect it fixed in the next version. it was probably added to the database recently so I'll have to release a new version with the updated definitions. Thanks

**Comment by rkingsla** [comment]
And it's fixed....  Thank you, good sir!  My 'Lock (currently using the shader and emblem) appreciates it!
