### ISSUE TITLE
Nepal Shader/Emblem is not available in Tower Ghost

### ISSUE THREAD

**Issue by kohum** [dasilva333/TowerGhostForDestiny#338]
The nepal shader/emblem does not show up in the slot.  So I can't equip or transfer them.

**Comment by rkingsla** [comment]
Refer to issue #337.  I initially reported the issue, Richard has since resolved it and it will show up in the next released version of TGD.

**Comment by dasilva333** [comment]
This will be fixed in the next release of TGD 2.9.8 thanks guys
