### ISSUE TITLE
Firefox and TGD 3.0.5 can't move items?

### ISSUE THREAD

**Issue by patchm00** [dasilva333/TowerGhostForDestiny#343]
i can drag and drop but if i turn off drag/drop i can't move (it only shows me weapon info, not the vault/move).  i also can't create loadouts since i am unable to click an item.  Using Windows 10 and it worked last version

**Comment by dasilva333** [comment]
It's a known issue I'll be working to develop a solution in the next version. To summarize the state of Firefox in TGD:

-Drag and drop enable causes the move pop up not to show
-Disable drag and drop to return to the normal behavior
-Loadouts can only be creatd if drag and drop is disabled

Expect a fix in the follow versions

**Comment by patchm00** [comment]
Ah yes, if I reload the page after turning off drag/drop it works.  Thanks for your work on this, it's great!

**Comment by dasilva333** [comment]
Problems fixed as of 3.9.1.2 Let me know if it's still an issue, thanks!
