### ISSUE TITLE
Suggestion: Swap technology for materials/consumables

### ISSUE THREAD

**Issue by kohum** [dasilva333/TowerGhostForDestiny#345]
I love the new swapping that happens when trying to move weapons or amour to a character where the armour or weapon slot is full.  It would be great if this worked for materials/consumables as well.  Currently, when trying to move spinmetal from one character to another where the material slot is full results in an error instead of an option to swap with an existing item.

**Comment by dasilva333** [comment]
good suggestion sir, it should be working as of 3.2.x try it out let me know if ou have any problems. thanks
