### ISSUE TITLE
Floating Transfer Window Update

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#346]
When you change an emblem from one char to another the top emblem changes, but the transfer window doesn't get updated. Small issue, but I thought I would post.
![transfer window](https://cloud.githubusercontent.com/assets/2903357/9607549/c4eb7952-5097-11e5-9fa2-2cc296ac8ba3.PNG)

**Comment by kohum** [comment]
Also, it would be really good if there was slight gap between the vault and the character emblems in the transfer window.

**Comment by dasilva333** [comment]
This has been resolved as of 3.3.x, let me know if it's still a problem. thanks guys
