### ISSUE TITLE
updated 3.0.1 causes infinite load time on iOS 9 latest PB

### ISSUE THREAD

**Issue by DekuBleep** [dasilva333/TowerGhostForDestiny#347]
Hello,

Ever since I downloaded the 3.0.1 update to Tower Ghost I experience infinite time load screens to load my arsenal from Bungie.  It never loads after very long waits.  This happens on both my iPad Air 1 and my iPhone 6 Plus.  I am running the latest PB (pretty sure its PB3) of iOS 9 as of Today, Sept. 3.   Tower Ghost worked perfectly before I downloaded update  3.0.1.  I have deleted and reinstalled Tower Ghost.  And I have logged in and logged back out and logged in again to with Tower Ghost and it didn't change the behavior at all.  

With my same setup I have no problems loading my arsenal with the Bungie Destiny App, or other Apps.  

Thanks!

**Comment by dasilva333** [comment]
iOS 9 is still in beta it is not going to be compatible with Tower Ghost until at least a week after iOS 9 is officially released. The reason for removing iOS 9 support it to make sure that the app doesn't break for everyone else when 2.0/TTK drops. Thanks for your feedback,

**Comment by phreak373** [comment]
I also have the same issue, but on iOS 8.4.1.  I am able to log into xbox live/bungie and then it keeps loading the arsenal (eternal green bar).  Have deleted/reinstalled several times and nothing fixes the issue.
