### ISSUE TITLE
[Feature Request] - Have a setting to move full item stack

### ISSUE THREAD

**Issue by diegobim** [dasilva333/TowerGhostForDestiny#35]
I'd like to request this feature: to have a setting that can be toggled, so when I move my stackable items (shards, energies, strange coins and such), all of them will be transfered without the confirmation dialog. Some clicks less after a raid is done and I'm putting my unluck drops into the vault ;)

By the way, thanks for the awesome work!!!

**Comment by dasilva333** [comment]
Seems easy enough to implement, I will add this after I take care of all the major bugs currently on the app. Thanks for your feedback

**Comment by diegobim** [comment]
Looking forward to it. Thanks again for your time!

**Comment by dasilva333** [comment]
Leaving ticket open so I can actually address it in the future. Thanks again

**Comment by seansli** [comment]
Actually, I have a suggestion — when the transfer materials amount popup comes up, there should automatically A) have the text box be focused (so that you can just backspace and type whatever number you want without clicking) and B) have enter submit it (so you don't have to click Transmit, the way you do now). This way, if you want to transfer the whole stack, it's just click on the material, the character, and then press enter.

**Comment by dasilva333** [comment]
I agree to all that stuff keep it up guardian

**Comment by dasilva333** [comment]
@seansli I need you to confirm it's fixed in the latest version thanks

**Comment by wickles** [comment]
I am very happy with the change but I think it would be slightly improved if, when it focused on the input box, it highlights the default number so that you can just immediately type in another number. Or at least put the cursor at the end of the box rather than the beginning.

**Comment by seansli** [comment]
@dasilva333 Looks good to me. Wickles has a good point about auto-highlighting, but I'm happy with the focus/enter shortcuts.

**Comment by dasilva333** [comment]
Easy enough to change the word 'focus' to the word 'select'. Thanks jQuery! Expect the fix in 1.9.6

**Comment by dasilva333** [comment]
@seansli @wickles if you guys could report back it's been fixed as of 1.9.7 that'd be great thanks

**Comment by wickles** [comment]
Works perfectly now, thanks @dasilva333

**Comment by dasilva333** [comment]
Sweet thanks guys

**Comment by diegobim** [comment]
Thanks a ton! Sent some paypal love towards you guys. Keep up the awesome work :clap: :clap: :clap:
