### ISSUE TITLE
setlockstate API seems to have changed

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#350]
Noticed in my branch that lock/unlock has stopped working, so the problem most likely exists here as well. Just a heads up-

> setlockstate error:
> { "Response":0, "ErrorCode":1619, "ThrottleSeconds":0, "ErrorStatus":"DestinyInvalidAction", "Message":"You are not allowed to perform that action.", "MessageData":{} }

**Comment by Mulchman** [comment]
https://www.bungie.net/en/Clan/Post/39966/151360187/0/0/1

> Not that anyone should be using it :wink: :wink: :nudge: :nudge: and you didn't hear it from me :wink: :nudge: buuuuuuuuut SetLockedState will unfortunately be broken until 9/8. It's a long and painful story of grief and woe, and occasional version conflicts. It's a long story. Anyways, this feature will be back on the 8th, my apologies for the unofficial and unsupported inconvenience that may or may not be happening to theoretical people theoretically using this service.

> (*whoosh* off I go don't tell anyone you saw me here)

**Comment by rkingsla** [comment]
For what it's worth, to add some context to what the "person who was never here" is relating: It's not working on Bungie's site either.  Hence, they intentionally 'broke' something in the API (e.g. added something that relies on something that isn't available) in advance of the 2.0 update coming out.  Soooo, long story short - Not TGD, not the "person who was never here", but Good ole' Bungie breaking their own 'stuff'.  They just knew it and put up a nice "Yeah, you can't do that" message.

**Comment by Mulchman** [comment]
The whole 'locked' flag is changing on items to be 'state' with a couple
different values ('locked', 'tracked') so in my mind 'SetLockState' not
working has to do with those upcoming changes.

**Comment by Mulchman** [comment]
@dasilva333 : SetLockState works once again. I'm not sure why you removed it?

**Comment by dasilva333** [comment]
Fixed in 3.1.3 thanks guys
