### ISSUE TITLE
Motes of Light show up incorrectly in Post Master section

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#351]
Motes of Light are showing up in 'Messages' instead of 'Lost Items', should you get one after your materials are full.

**Comment by Mulchman** [comment]
![example](http://i.imgur.com/EC6gjI1.png)

**Comment by Mulchman** [comment]
Fixed in my runner branch if you cared.

**Comment by dasilva333** [comment]
you'll submit a PR for the itemBG but not this?
