### ISSUE TITLE
Android seems to be very crashy

### ISSUE THREAD

**Issue by aicm** [dasilva333/TowerGhostForDestiny#355]
Hi there, 

Awesome piece of software! I don't know how we managed to transfer Destiny items with such crude tools such as the official destiny app in the past. Like peeling potatoes with a spoon.

I used "seems to be" because I have not tested your app on a vanilla Android install. I have the N8013, Samsung Galaxy Note 10.1 (the old version, not 2014), running Omnirom version 5.1.1 from 06/28/2015 (http://forum.xda-developers.com/galaxy-note-10-1/orig-development/rom-omnirom-n8000-n801x-t2950440) and the last 2 versions of TGFD have crashed when scrolling. Initially I thought it was at any time, but now I can see that it's when more than one view category is selected (weapons, armor, general), or View all is selected. 

I don't know how to pull crash logs out of android, but it's rooted and I'm a fast learner. Just let me know what you need, I'll find out how to get it.

Thanks!

**Comment by dasilva333** [comment]
You can only ever set one View at a time so you can't enable Weapons and Armor at the same time for example, so to clarify all I have to do is set it to View All and scroll and sometimes itll crash?

**Comment by aicm** [comment]
Hi. 

Yes, that's how I'm able to crash mine. If I scroll very slowly sometimes I can go lower before it freezes.

If I press the task switcher button and return to TGD it will changes it view to wherever I scrolled, but the UI is still frozen. I switch to some other software and return to TGD, and TGD UI is still frozen, but it crashes shortly after. 

It eventually crashes if I press the task switcher button and return to TGD repeatedly, as well.

**Comment by aicm** [comment]
Recording my screen is impossible, it keeps crashing .. anyway... gotta love android.

So I figured out how to pull a logcat out of the device while I re-created the bug: http://pastebin.com/raw.php?i=gUQ0hY65

Hope this helps.

**Comment by aicm** [comment]
Update: Did a git clone on your master and compiled the debug apk. I can't crash it in a Lollipop 5.1.1 emulator on x86, however, the same debug apk on the real device crashes. I'm beginning to think it's some silly thing omniROM changed/removed.

**Comment by aicm** [comment]
Letting the device sleep after the UI froze (swapBuffers encountered EGL_BAD_SURFACE on ... halting render) and waking it after a few seconds unfreezes the UI, however just a tiny bit of scrolling will freeze it again. I read somewhere that this might be related to a driver issue, namely an EGL compability patch in CM, which is what OmniROM is based on.

**Comment by aicm** [comment]
Yup, I installed CM 12.1 (newer release of 5.1.1 and they fixed the OpenGL ES driver problem. Cordova is fine :) 

Thank you.

**Comment by dasilva333** [comment]
Great I'm glad you got it figured out, I just code for the web using javascript so I'm out of touch as to what the logs meant or the problem means but thanks for that. Good job
