### ISSUE TITLE
Can't get 3.1.0 to work in the browser

### ISSUE THREAD

**Issue by aicm** [dasilva333/TowerGhostForDestiny#356]
Hello there, 

I've been trying to compile the latest commit for the browser and I'm not having any luck in Safari, Chrome or Firefox. Any particular steps I forgot?

Safari says `ReferenceError: Can't find variable: _ in loadouts.js:13`, and that's after I manually added `hammer.min.map`. I'm guessing all these dependencies must be satisfied manually somehow, like the rest of the stuff. I did npm install hammer and underscore, I'll keep playing around.

Chrome says `Refused to set unsafe header "Cookie" in jquery.js:4`, and `XMLHttpRequest cannot load https://www.bungie.net/en/User/Profile. The 'Access-Control-Allow-Origin' header has a value 'http://www.bungie.net' that is not equal to the supplied origin. Origin 'http://domain.name' is therefore not allowed access.`

Firefox seems to be the most silent browser. No errors, yet it does not load anything.

The login links don't work (I manually log in to bungie.net and then refresh TGD).

I'm new to grunt and ruby and all this crap, so I don't know what *needs* to be done to compile this project. I hope I'm close. Any help is appreciate it. 

Thank you.

**Comment by dasilva333** [comment]
You can find install instructions here:

http://towerghostfordestiny.com/index.php/support/

If you want to just try it from the store you can find the links here:

http://towerghostfordestiny.com/index.php/downloads/

FYI TGD doesn't exist for Safari only Chrome or Firefox

**Comment by aicm** [comment]
Hi, yes I finally figured it out, it's an extension, I had assumed it would work in-browser like a hosted app. Turn out, extensions can have special XMLHttpRequest permissions which won't work in Chrome for example, even if you run Chrome with `--args --allow-file-access-from-files --allow-file-access --allow-cross-origin-auth-prompt --disable-web-security`

Thank you!
