### ISSUE TITLE
iOS 9 issue

### ISSUE THREAD

**Issue by AlanVerbeke** [dasilva333/TowerGhostForDestiny#357]
Since the Testflight-beta (which worked like a charm) expired I had to download the app-store version again. This version works perfectly for a while, but after a few hours or a day the app is stuck on "Please wait, loading arsenal from Bungie" and I have to de-install and re-install the app to get it to work again...

I hope this gets fixed soon because I'm really addicted to using your app :D 
Great job!

**Comment by dasilva333** [comment]
Tower Ghost will not be compatible with iOS 9 for at least one week after it's release date on the 16th so expect it to be back up on the 23rd. Thanks

**Comment by phreak373** [comment]
issue is happening with iOS 8.4.1 as well
