### ISSUE TITLE
Failure to load items from Bungie

### ISSUE THREAD

**Issue by ssoriche** [dasilva333/TowerGhostForDestiny#360]
In Chrome (Tower Ghost 3.1.2):

Sign in, get the green bar, green bar closes and then nothing happens. Error log shows:

<img width="554" alt="screen shot 2015-09-09 at 7 53 30 am" src="https://cloud.githubusercontent.com/assets/19838/9761019/f5eb8246-56c7-11e5-950d-cc84e6a820b7.png">

**Comment by jdf99** [comment]
I have the same issue. I can't load into chrome nor can I open the downloadable file as it's greyed out. Funny thing is, DIM is working as it should, it seems

**Comment by dasilva333** [comment]
Expect it fixed in 3.1.3 thanks guys
