### ISSUE TITLE
Failure to load items on Android App

### ISSUE THREAD

**Issue by rcraner** [dasilva333/TowerGhostForDestiny#361]
I'm not sure what to provide, I'm sure it's related to the 2.0 patch.  Tower Ghost does not load any items on my Note 5 since the patch.  Let me know what I need to do/provide to help.

**Comment by adamcsills** [comment]
It's not loading items anywhere; app or chrome plugin.

**Comment by rcraner** [comment]
@adamcsills Chrome plug-in works just fine now that it is fixed.  Dasilva just updated it.

**Comment by adamcsills** [comment]
Literally 2 minutes before I wrote my reply it wasn't working :)

Good lookin' out.

**Comment by dasilva333** [comment]
Expect it fixed in 3.1.5 thanks

**Comment by rcraner** [comment]
Thanks for the reply.  Can I ask if you expect 3.1.5 for android to hit the play store today or tomorrow or will it be further down the road?

**Comment by dasilva333** [comment]
https://www.reddit.com/r/DestinyTheGame/comments/3k98oe/announcement_tower_ghost_for_destiny_now/
