### ISSUE TITLE
Suggestion: make Vault wider (similar to DIM's "Condensed Items" view)

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#362]
More and more players who don't throw things away are going to start winding up with the Vault sections taking up massive amounts of vertical real estate, examples:

(Album: http://imgur.com/a/q3HJd)
![1](http://i.imgur.com/SzIUsfH.png)
![2](http://i.imgur.com/dGrGeko.png)

I suggest adding more rows to the Vault when not in a isMobile situation.

**Comment by Mulchman** [comment]
As a comparison, here is DIM using and not using the "Condensed Items" feature.

Not using "Condensed Items" - 4 column Vault:
![1](http://i.imgur.com/EZYEJdd.png)

Using "Condensed Items" - 5 column Vault:
![2](http://i.imgur.com/JJmf2gn.png)

It's still not wide enough (a single extra column), IMO, but it is something.

**Comment by moeyjar** [comment]
I think having the option to go 5 wide would help, but it's not the end of the world.  The issue is that depending on your screen size, you wouldn't want to scroll side to side to make it fit.  You'd have to make it an option for people, perhaps in the view section.

**Comment by ssoriche** [comment]
Why not paging the vault? It's paged in the game, mimic that.

**Comment by aicm** [comment]
How about making it a scrollable div on the side? You could scroll it independently of the rest of the site.
http://jsfiddle.net/ftkbL/1/

**Comment by Mulchman** [comment]
@ssoriche I really dislike the paging. I want to be able to see everything at one glance. The new Vault is almost impossible for me to use because of the pagination.

**Comment by SteffanLong** [comment]
There's plenty of dead space on the left and right. Making it 5 or 6 columns wide would work just fine on `lg` screens. It would probably require a lot of work though considering they are created using `col-lg-3` currently.

**Comment by dasilva333** [comment]
I'll keep it open but I'm against this enhancement because making the vault wider would cause a lot of layout problems for all platforms. I'll see if i can come up with a middle ground compromise. Thanks guys

**Comment by Mulchman** [comment]
DIM now has a 6 wide vault.

![example](http://i.imgur.com/JHztvQP.png)

This is definitely an area where TGfD needs to follow suite, or it's going to be left behind. There's so much dead space when using TGfD on a computer/laptop. For sure mobile has to remain w/ the 4 column Vault, but the others need to adapt and make use of the space.

**Comment by Mulchman** [comment]
Space comparison between the two apps- DIM left, [custom] TGfD right:

![example](http://i.imgur.com/BPIqoDV.jpg)

**Comment by dasilva333** [comment]
I'll opt to get left behind then. Thanks for the feedback nontheless

**Comment by aicm** [comment]
Well, for what it's worth, I do git pull and inject my own css in the index.html before I recompile the app, and then I can do something interesting, like this:
`div:nth-child(11){width: auto!important;}`
which makes the container div take up all the width available on any device/browser, without breaking anything, and having the icons appear larger. 

My gripe was really with the tiny refresh buttons on top of each category, so I made those larger too, so I can finally tap them using my finger rather than a stylus or cursor.

What I do notice is that @dasilva333 is not open to change and is not keen on making it easy for others to contribute or work on the app itself. So I guess it's more of a take it or leave it kind of approach. That's what kept me from supporting/donating. I understand preference, but I don't understand anti-community when taking an open-source type approach.

**Comment by Mulchman** [comment]
Is there a way I can send you a private message, @aicm ?

**Comment by aicm** [comment]
Sure, you can send emails to *my* at *working* period *name*.
I don't have many changes though, I just change what isn't easy for me to work with :)

**Comment by Mulchman** [comment]
So I tried "my at working period name" -> my@working.aicm and of that
failed... what's it again?

**Comment by aicm** [comment]
name is the actual TLD. > working.name

**Comment by Mulchman** [comment]
Had to look up what TLD meant. I'll just end up playing with the change you mentioned: **div:nth-child(11){width: auto!important;}**. It's getting too complicated trying to figure out the email. I'm already annoyed your post was deleted/removed for this issue and I had to dig through email trash to find it.

**Comment by aicm** [comment]
Gotcha. Sorry about that, TLD is top level domain. For example, .com is a TLD. The email is my@working.name

**Comment by Mulchman** [comment]
They made it even better. You can customize the # of columns for players and for Vault.

![example](http://i.imgur.com/kHagV7E.png)

**Comment by Turk10mm** [comment]
The option to add columns for characters and a separate option to add rows to the vault is the only enhancement that I personally would request implemented.  I only use the chrome extension, but I can see why implementing this across platforms would be difficult.  While comparing this feature to DIM is all well and good, the fact is TG has surpassed DIM functionality.  So I'm 99.9% happy with your work and I use it every day.  Thank you for your time and effort.

**Comment by dasilva333** [comment]
@Turk10mm Thank you for being the only person who actually understands why implementing this across platforms would be difficult, if someone is interested enough in they could always submit a pull request just like all these other pull requests already closed, after all this is open source

https://github.com/dasilva333/TowerGhostForDestiny/pulls?q=is%3Apr+is%3Aclosed. (61 Closed)

Thanks for appreciating my work, time and effort it's a full time effort keeping up with Bungie and I'm only one person.

**Comment by Mulchman** [comment]
Wider views are only being requested on desktop, ie. isMobile == false

**Comment by SunburnedGoose** [comment]
+1

**Comment by Mulchman** [comment]
There are new issues with *Auto Pad Height* when changing the vault columns:

![example](http://i.imgur.com/e4SSsyj.jpg)

Notice the players buckets don't match, either (but this is only when vault columns != 4).

**Comment by dasilva333** [comment]
Option added as of 3.4.6 please confirm, thanks for your feedback

**Comment by Mulchman** [comment]
It's definitely a step in the right direction.

![example1](http://i.imgur.com/Weyq79R.jpg)

Next step would be to make the icons the same no matter what scaling options are chosen. People already go insane when things don't line up, and little offsets like below are just going to trigger people further.

![example2](http://i.imgur.com/2P9ZHFB.jpg)

**Comment by dasilva333** [comment]
@Mulchman I disagree on the next step and I won't be making any further changes to ensure icons stay the same, my goal is to give people the ability to choose how big or small they want the vault icons sizes to be not to standardize it to one size fits all. Thanks for your feedback nontheless

**Comment by Mulchman** [comment]
There's a bug in **bucketSizeHandler** in that **itemHeight** is being used for vault item height and profile item height. This screenshot will show you how to reproduce to see the issue.

![example](http://i.imgur.com/00hi4ry.png)

**Comment by Mulchman** [comment]
Also, in the same function, the line **maxProfilesHeight = Math.max(itemHeight * minNumRows, maxProfilesHeight);** does not account for the 2 pixel padding. It should be **maxProfilesHeight = Math.max((itemHeight + 2) * minNumRows, maxProfilesHeight);**

**Comment by dasilva333** [comment]
@Mulchman the last commit 4b8254d has fixed the issue with the background height of those items, I'm not going to add the +2 to the itemHeight for maxProfilesHeight because after extensive testing I can't find a situation where the headers don't line up properly. Do you have a screenshot to prove that adding +2 is necessary because it's not lining up?

**Comment by Mulchman** [comment]
wrt the +2, on buckets where there are 5 rows, like consumables and materials, if your inventory only has 2-3 rows filled in you can visibly see the itemBucketBG isn't as big as it needs to be if the 5 rows were completely filled in.

**Comment by dasilva333** [comment]
The materials and consumables section looks fine for me as shown in this example:

http://i.imgur.com/Vc8Ujqo.jpg

Please provide an actual screenshot example to show me how it's not lining up for your just right.

Thanks

**Comment by Mulchman** [comment]
Your example has all the rows filled out.

![example](http://i.imgur.com/papoNiL.png)

**Comment by dasilva333** [comment]
@Mulchman in the example you provided again it doesn't show any visual issues with how the headers are lining up, are you sure you can even reproduce the problem? If so please simply provide a screenshot of the headers not lining up. Thanks

**Comment by Mulchman** [comment]
Ah, right, you never accepted my **itemBucketBG** fixes. Your **master** is incorrect having **Consumables** and **Materials** @ 4 rows deep instead of 5. Each section can hold 20 items each per player, therefore 5 rows should be the default. (You enforce this default with other buckets (**Primary**, **Heavy**, etc) and partially with **Materials** (but only at 4 rows) but forgot about **Consumables** and making the **minNumRows** 5.)

Your current **master** **Materials** **minNumRows** default:

``` javascript
                } else if (type == "Materials") {
                    minNumRows = 4;
                }
```

What it should technically be:

``` javascript
                } else if ((type == "Materials") || (type == "Consumables")) {
                    minNumRows = 5;
                }
```

Once you make that change, see my most recent screenshot where the **itemBucketBG** is not big enough for 5 rows when only 1-4 rows actually have items in them.

**Comment by dasilva333** [comment]
@Mulchman what does that have to do with the original discussion of the +2 px to the itemHeight? It seems you're changing subjects again rather than sticking to the original discussion as to the purpose of adding the +2 px to the itemHeight for maxProfilesHeight . Still waiting on that screenshot. Good luck!

**Comment by Mulchman** [comment]
If you go back and re-read the posts you'll see that the **itemHeight + 2** thing was brought up because the **itemBucketBG**s didn't line up:

> Also, in the same function, the line
> 
> maxProfilesHeight = Math.max(itemHeight * minNumRows, maxProfilesHeight);
does not account for the 2 pixel padding. It should be
> 
> maxProfilesHeight = Math.max((itemHeight + 2) * minNumRows, maxProfilesHeight);
EDIT: the padding does throw off normal layouts, though, but when things are resized it's needed. So there's clearly a better solution.

In the very next post you said:

> @Mulchman the last commit 4b8254d has fixed the issue with the background height of those items, I'm not going to add the +2 to the itemHeight for maxProfilesHeight because after extensive testing I can't find a situation where the headers don't line up properly. Do you have a screenshot to prove that adding +2 is necessary because it's not lining up?

You're the one who brought up this header-lining-up situation. I'll bold it right here so it stands out - you said: **headers don't line up properly**

I then supplied a picture showing the **itemBucketBG** problem when **minNumRows** is 5 for **Consumables** and **Materials**.

You then dismissed things with the header thing again.

> @Mulchman in the example you provided again it doesn't show any visual issues with how the headers are lining up, are you sure you can even reproduce the problem? If so please simply provide a screenshot of the headers not lining up. Thanks

Again, no one is talking about the headers except you. I'm pointing out **itemBucketBG** sizing issues.

I then corrected you, and you responded with this snarky bullshit once again talking about headers lining up:

> @Mulchman what does that have to do with the original discussion of the +2 px to the itemHeight? It seems you're changing subjects again rather than sticking to the original discussion as to the purpose of adding the +2 px to the itemHeight for maxProfilesHeight . Still waiting on that screenshot. Good luck!

**No one is talking about headers lining up.**  We're talking about **itemBucketBG** being wrong when **minNumRows** is 5 for **Consumables** and **Materials**.

Stop being so rude, childish, and dismissive to those trying to help out all the other customers of this product.

But go ahead, dismiss all of this, close the issue, then come back weeks later and actually do the work because you realize you've been foolish, just as you've done with the wider vault suggestion.

Grow the fuck up, man.

**Comment by dasilva333** [comment]
@Mulchman you are ridiculous and overly sensitive you literally said:

Also, in the same function, the line

    maxProfilesHeight = Math.max(itemHeight * minNumRows, maxProfilesHeight);

does not account for the 2 pixel padding. It should be

    maxProfilesHeight = Math.max((itemHeight + 2) * minNumRows, maxProfilesHeight);

That implies you want me to tweak the maxProfilesHeight by 2px, that has everything to do with the buckets and headers lining up not with how many rows there is. Adjusting the value by 2px doesn't have anything to do with itemBucketBG. I simply wanted proof that changing the code from itemHeight to itemHeight+2 actually fixed anything, something you seem to be avoiding or can't prove. Sorry it takes so long to 'do the work' its not because I realized I've been foolish its because guess what? It takes time, effort and knowledge to make these changes the way I want to so it doesn't break anything and it's a one man team with nobody helping so I'm sorry if you're privileged self can't deal with having to wait for the developer to make the changes and you just demand and expect them to be done at your leisure. Consider yourself blocked and ignored from all future dealings with this project. Stop being so sensitive, man.
