### ISSUE TITLE
Completed Crucible Bounties are now showing as Completed in 3.1.3.  Count needs to be modified to reflect new max.

### ISSUE THREAD

**Issue by moeyjar** [dasilva333/TowerGhostForDestiny#363]
![image](https://cloud.githubusercontent.com/assets/12259797/9766562/ff2b762c-56ef-11e5-828b-dbcb25a2c09d.png)

Show show as completed with a check, similar to Vanguard bounties.  also, the amount should be updated to 16 (you can see it has 16/10

**Comment by moeyjar** [comment]
The more I think about this, I wonder if it's an API error not displaying that it's been completed.

Here's what they look like on bungie.net

![image](https://cloud.githubusercontent.com/assets/12259797/9766711/c7e27854-56f0-11e5-84d5-6aad5820343b.png)

**Comment by moeyjar** [comment]
Maybe we can just get the new max updated for now and revisit

**Comment by dasilva333** [comment]
Problem fixed in 3.1.5 thanks guys
