### ISSUE TITLE
Another Item Bucket BG Consistency Issue

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#364]
There are several buckets where the background area (width/height) is enforced because in the game you can hold a static amount of items in that bucket. This includes things like the "Primary" and "Special" buckets, for example. You can hold 9 + 1 equipped and the item bucket background indicates this correctly.

Example-
![1](http://i.imgur.com/IbDhICi.png)

However, other static in-game buckets like "Class Items" "Emblem" "Shader" "Ship" and "Sparrow" do not have an item bucket background that's enforced to show that it can only hold 9+1 items.

Example-
![2](http://i.imgur.com/UWIw2ZP.png)

**Comment by Mulchman** [comment]
If you want to be especially accurate, the Materials/Consumables now need 'nimNumRows' at 5 as well, since they can hold 20 each. (There's also a current bug in that "Materials" is set to 4 but "Consumables" is not - probably an oversight from the person who submitted that PR in the first place.)

Example fix diff:
![example](http://i.imgur.com/lCjI7sM.png)

**Comment by dasilva333** [comment]
I like it the way it is, thanks for your feedback guys
