### ISSUE TITLE
Toaster Text States "Error" Even Though Successful

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#365]
When successfully completing a normalize operation, the toaster thing pops up saying the success message but the text in the message starts with "Error: [...]"

![example](http://i.imgur.com/YL2Qewk.png)

There are a few other instances where toaster text starts with "Error: [...]" upon a successful operation.

**Comment by dasilva333** [comment]
Problem fixed in .1.5
