### ISSUE TITLE
Suggestion: glimmer amount on exchangeable consumables

### ISSUE THREAD

**Issue by Tsothoga** [dasilva333/TowerGhostForDestiny#367]
Right now, if I look in my vault, I can see I have 30 house banners (I like to keep a pile of glimmer exchange items in stock for Iron Banner weeks). Would it be useful to display the glimmer value (instead of the item count) of those consumables, or would that just cause confusion? Maybe only show it in the transfer dialogue when the "auto-transfer stack" setting is de-selected; if I selected my stack of house banners, chose to move them to my hunter, and then selected 20, a row underneath the # / + / - / One / All would display the # and the glimmer value that it equals.

**Comment by dasilva333** [comment]
I dont agree with showing the value instead of the count but I'll think about a way I can incorporate the value in the transfer pop up. Thanks

**Comment by Tsothoga** [comment]
Looks like this feature has been added. Closing this issue.

**Comment by dasilva333** [comment]
@Tsothoga thanks for closing it, as you probably already noticed its available in the tooltips and in the move pop up
