### ISSUE TITLE
iOS 8.4.1 issue with TG after 3.0.1 update

### ISSUE THREAD

**Issue by phreak373** [dasilva333/TowerGhostForDestiny#369]
Hello,

I downloaded the 3.0.1 update for Tower Ghost after the Bungie/Destiny YR2 patch and I am experiencing an infinite time to load my arsenal from Bungie. It never loads after very long waits. This happens on both my iPad Air and my iPhone 6. I am running the latest version of iOS (8.4.1), prior to the update Tower Ghost worked perfectly. I have deleted and reinstalled Tower Ghost several times, and I have logged in/out and logged back in again to with Tower Ghost with my xbox live account and it didn't change the behavior at all.

With my same setup I have no problems loading my arsenal with the Bungie Destiny App, or other Apps.  I also have no problems loading my arsenal on the google plus version of the app on the google chrome browser but that is inconvenient as my computer is not in the same room as my xbox.  Any help with this would be greatly appreciated

Thanks!

**Comment by dasilva333** [comment]
There's nothing I can do to fix 3.0.1 since it's already released, you're just going to have to wait for 3.0.9 to be released in the App Store today or tomorrow and try it out, let me know if that still gives you issues. Thanks

**Comment by SourXbully** [comment]
I'm am also having the same issue app opens green bar loads but loadouts never appear and I already have the 3.0.9 version. I am on a note 2 using the app downloaded through the play store.  I have also uninstalled and reinstalled it several times since yesterday. I was just assuming it was because of the in game update.

**Comment by SourXbully** [comment]
Version 3.1.5 got it working again thanks so much

**Comment by phreak373** [comment]
I still only see 3.0.1 in the App Store. Still having the same problems. Is there anywhere else to get the updated app. 

Thanks....AL

Sincerely,

Alex Lopez
Leasing Director - Puerto Rico
801 S University Drive, Suite D105
Plantation FL 33324
p. 954-845-7152 \ m. 954-593-4373
NYSE: DDR

**Comment by dasilva333** [comment]
In case you missed it here's an announcement 
https://www.reddit.com/r/DestinyTheGame/comments/3k98oe/announcement_tower_ghost_for_destiny_now/

**Comment by phreak373** [comment]
Thanks so much. Really love the app. So much better than the destiny app. Bungee should hire you to re-build their app. 

Thanks....AL

Sincerely,

Alex Lopez
Leasing Director - Puerto Rico
801 S University Drive, Suite D105
Plantation FL 33324
p. 954-845-7152 \ m. 954-593-4373
NYSE: DDR

**Comment by rkingsla** [comment]
Nah, Bungie should not...  Imagine what TGD would be if Bungie got their hands on it and the SmartPeople(TM) here were no longer free to 'do their thing'.

Be happy that there is a Richard and Co.  Bungie needs to leave their hands off.  And, its' not like they don't know about the app.  Luke Smith even mentioned it by name in the 100 questions segment a few weeks ago with Game Informer.  If Luke remembers, that must be a good thing.
