### ISSUE TITLE
Suggestion for Smoother Searching

### ISSUE THREAD

**Issue by chrisdudek** [dasilva333/TowerGhostForDestiny#37]
Hey man,

This is by no means an "issue" but I remember you saying in reddit to put suggestions on here too. So if you don't agree on this, it's no biggie. Just a cool thought (to me anyways). 

Right now on iOS version, if I'm at the "top" if the app and pull down, the app itself moves down and a black space is at the top. Are you able to replicate the iPhone's Spotlight Search Functionality in your app? Meaning, if I pull down in your app could we get a search bar to find the weapon/armor/material we're looking for? I think that would be pretty cool and an easier location than the hamburger button. 

Also, when I search, can we hide all of the title bars that don't contain any item that matches my search? Rather, just show me the sections that have an item that matches? It would save scrolling when looking for the item. 

Again - no issues here, just ideas I had when playing around in there. 

Great job so far!

**Comment by chrisdudek** [comment]
Just wanted to add a pic that shows the 2nd part of my comment regarding hiding unnecessary categories/sections. Here we can see that I had to scroll down a far way (as indicated by the scroll bar on the right side of the screen) to find the items that match my search.
![image](https://cloud.githubusercontent.com/assets/11835064/7181167/0011c12c-e40e-11e4-9b17-bce92acb8347.jpg)

**Comment by dasilva333** [comment]
Thanks for the suggestions, good stuff I'll mark it as enhancement and try to address some of your concerns when this thing is more stable.

**Comment by dasilva333** [comment]
@chrisdudek So I added some logic for when a search is active the title bars don't show anymore, I think this change cuts down on all the extra stuff shown that's not relevant during a search. As for the spotlight search I thought about it and I don't like the idea. See if you're under View > All, scrolled all the way to the bottom of the page and u want to search for something right now it's as simple as hamburger > search. Implementing the spotlight would require the user to scroll all the way back to the top, search, and scroll all the way back to the bottom to find the relevant results. Thanks for your feedback and expect the next change as part of 2.3.8

**Comment by chrisdudek** [comment]
Yeah - I agree it would be a lot of scrolling to get back to the top in order to search. With all of the improvements you've been making, I'm finding myself having to search less and less. The swipe to filter enhancement was a big win.

**Comment by dasilva333** [comment]
If you can confirm the title bars are gone as part of 2.4.0 when you search, that would be great check it out and let me know thanks

**Comment by chrisdudek** [comment]
Solid man. Gone. Thanks for the enhancement.
