### ISSUE TITLE
Samsung Note 4 - not pulling in gear.

### ISSUE THREAD

**Issue by coasterreal** [dasilva333/TowerGhostForDestiny#370]
First issue I had was when the promotional content for Nepal came out, it never showed up.

Second thing is that I cannot see anything. It loads up and then all I see is the background. No items.

I've uninstalled and reinstalled. I've then uninstalled and restarted, then installed. Nothing works now.

**Comment by masway** [comment]
Same issues here on s6 edge. Nothing shows up

**Comment by coasterreal** [comment]
Masway - if you are already logged into bungie.net, try this.

Uninstalled tower ghost. Then open up bungie.net on phone. Log out!

Now open tower ghost and log in. When I did that, it now works. Maybe a
caching issue?

**Comment by rcraner** [comment]
This was a known bug with the 2.0 Destiny patch.  The app was updated late last night in the app store to resolve this problem.

**Comment by dasilva333** [comment]
3.1.1+ fixes this issue, let me know if this is still a problem thanks guys

**Comment by coasterreal** [comment]
Maybe I downloaded the newest one after several attempts to install - but
mine is working. For me, felt like I had to log out of bungie.net and back
in via TowerGhost. Might have been coincidence.

Either way, I'm working now. So dependant on these great apps!
