### ISSUE TITLE
Issues with Year 2 Changes

### ISSUE THREAD

**Issue by drinkc0ke** [dasilva333/TowerGhostForDestiny#371]
There are a number of issues with TGD since the release of the Year 2 patch yesterday (9/8). Note that I performed all testing on an iPhone 6 running iOS 8.3. Here are the issues I have noted so far:

- Year 2 items (Ghost Shells, Shaders, Emblems, Weapons including Prototypes, Armor Materials, etc) not appearing.

- Loadouts not working properly. They either return an unknown error or end up acting unpredictably, transferring items that are not in the loadout or in either of the buckets affected. Let me know if specific examples are needed.

- Vault space needs to be adjusted to the new size limitations. In cases where there are more items in a certain vault bucket than was previously allowed, TGD thinks that there is no space for another item and will ask if you want to perform an item swap when attempting to transfer an item to the vault.

I will add more issues as I come across them. Please let me know if this is a duplicate bug report and I will remove it (although I checked and couldn't find an existing one). Thanks so much for all the hard work you do! I will continue to provide financial support when I can, and I will try to help in other ways if needed--I'm a web developer by trade, although my day job takes up most of my time (60-70 hours per week).

Best,

drinkc0ke

**Comment by rcraner** [comment]
Per https://www.reddit.com/r/DestinyTheGame/comments/3k98oe/announcement_tower_ghost_for_destiny_now/

Hopefully the iOS app update will be hitting the app store some time today.

**Comment by dasilva333** [comment]
This has all been fixed as of 3.1.5 thanks for posting the link @rcraner

**Comment by drinkc0ke** [comment]
Thanks rcraner and of course dasilva333! I must have missed that post--haven't been able to check Reddit too much lately. I'll keep an eye out for that iOS update.
