### ISSUE TITLE
Cloud Save loadouts not showing in NEW Android App

### ISSUE THREAD

**Issue by rcraner** [dasilva333/TowerGhostForDestiny#372]
I've downloaded the most recent version of TGD for Chrome (3.1.5) and have created several loadouts.  I've also downloaded the most recent version of TGD for Android (3.1.5).  Loadouts created in the Chrome Extension are not appearing in the Android app.

**Comment by rcraner** [comment]
I'm not sure if it's related but the "Share URL" function isn't working either.  It looks like TGD @ towerdestinyforghost.com pulls up version 2.9.1 of TGD.
![capture](https://cloud.githubusercontent.com/assets/11078378/9787655/8e6a31d2-5792-11e5-8c7e-07ba5952e3d2.JPG)

**Comment by dasilva333** [comment]
I'll look into it thanks

**Comment by rcraner** [comment]
With regards to cloud save loadouts, they actually seem to be working now.  Or it could have been my stupidity, not sure yet.

That said, the issue with generating a TGD.com URL to share with friends (my second comment/picture) is still a problem.  Do you want to close this and create a new bug with a more appropriate name?

**Comment by dasilva333** [comment]
Thanks for updating, I'm glad cloud saves are working for you now in Android. Regarding the share site I'm aware of the issues that are currently wrong with it. I'll be updating it after the TTK is released, feel free to make another issue so I can look into it then. Thanks
