### ISSUE TITLE
iOS App Not Working After Destiny Update 2.0

### ISSUE THREAD

**Issue by RedHotTrouble** [dasilva333/TowerGhostForDestiny#373]
Since Destiny's latest pre-Taken King Update 2.0, Tower Ghost stopped working for iOS, at least on my iPhone 6. After the login process, the app just shows a blank default grey background without ever loading my inventory.

**Comment by dasilva333** [comment]
https://www.reddit.com/r/DestinyTheGame/comments/3k98oe/announcement_tower_ghost_for_destiny_now/
