### ISSUE TITLE
More and more items are showing up in the "Messages" section of the "Post Master" that shouldn't be there

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#374]
Following on Motes of Light and the Crux of Crota, certain engrams are now showing up in "Messages"  instead of "Lost Items." Example:

![example1](http://i.imgur.com/MX0aWuX.png)

The checks that segregate out what goes in "Messages" and what goes in "Lost Items" probably need to be reevaluated since 2.0, instead of adding more and more items to the "lostItemsHelper" array.  (DIM seems to handle things correctly.)

EDIT: how things look in DIM (the coin package is in the wrong bucket so ignore that):

![example2](http://i.imgur.com/wYvqtmK.png)

**Comment by dasilva333** [comment]
fixed as of the latest commit expect to see it in 3.1.7 thanks
