### ISSUE TITLE
Light level does not update with in-app refresh

### ISSUE THREAD

**Issue by rkingsla** [dasilva333/TowerGhostForDestiny#375]
Love the light level on the Toon emblem.  Awesome!!  One small issue:  Refresh (in-app) does not update it if changes are made to the characters loadout, the light level does not update until I do a Web page reload.

I know, picky, picky....  ;o)

**Comment by rkingsla** [comment]
Crap...  Forgot my own rule:  Windows, Chrome 3.1.7 from latest Git branch

**Comment by dasilva333** [comment]
fixed as of 3.2.2
