### ISSUE TITLE
Apple iPhone 6 Plus Not loading

### ISSUE THREAD

**Issue by azleb** [dasilva333/TowerGhostForDestiny#376]
App isnt loading items, tried logging in again and reinstalled app.

**Comment by arkie-boy** [comment]
Same here: does not work on iPhone6 or on my (older) iPad Air.  I think it stopped working at 2.0

**Comment by matthewguy** [comment]
Same: I've been trying to use this app on my iPhone6 and since the last update I've not been able to do anything. Just look at a loading screen for hours. Signing in is as far as I can go. But when this worked it was a great app!!!

**Comment by rcraner** [comment]
I'm not an iPhone user but: https://www.reddit.com/r/DestinyTheGame/comments/3k98oe/announcement_tower_ghost_for_destiny_now/

Since I'm not an iPhone user, I can't speak to whether the 3.1.5 update has hit the app store on iPhone or not.

**Comment by dasilva333** [comment]
Just waiting for Apple to approve the update thanks for posting the link

**Comment by arkie-boy** [comment]
Thanks!

Can I just take a second out to say how utterly wonderful TGD is.  Felt completely lost without it for the last few days

Steve
