### ISSUE TITLE
Nothing is loading on Ipad. Desktop and phone working fine.

### ISSUE THREAD

**Issue by Los556** [dasilva333/TowerGhostForDestiny#379]
Login using my Ipad 2, goes through standard login sequence, but after it says Loading Arsenal from Bungie nothing shows on the screen. I've let it sit like that for at least 10 minutes thinking eventually it will load. I have uninstalled and reinstalled Tower Ghost several times and made sure my Ipad was updated. Any help would be appreciated.

**Comment by dasilva333** [comment]
https://www.reddit.com/r/DestinyTheGame/comments/3k98oe/announcement_tower_ghost_for_destiny_now/
