### ISSUE TITLE
The 4th Horseman is not visible

### ISSUE THREAD

**Issue by Titus-s** [dasilva333/TowerGhostForDestiny#38]
The 4th Horseman is still not visible in TGD although it's visible and "movable" already on bungie.net
This is what I get when press Refresh:
GET https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20json%20wher…Fapi.cfm%3Faction%3Dload%26membershipId%3D6857131%22&format=json&callback= jquery.js:4 sendjquery.js:4 m.extend.ajaxapp.js:1057 app.yqlRequestapp.js:1097 app.loadLoadoutsapp.js:944 (anonymous function)bungie.js:169 _request.completebungie.js:98 r.onload
index.html:1 XMLHttpRequest cannot load https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20json%20wher…Fapi.cfm%3Faction%3Dload%26membershipId%3D6857131%22&format=json&callback=. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://dpinoabilojljbnkfdnnbalhigglbhdp' is therefore not allowed access. The response had HTTP status code 403.
app.js:734 found an item without a definition! {"itemHash":2344494718,"bindStatus":0,"isEquipped":false,"itemInstanceId":"6917529046313340492","itemLevel":22,"stackSize":1,"qualityLevel":70,"stats":[{"statHash":4284893193,"value":34,"maximumValue":100},{"statHash":4043523819,"value":39,"maximumValue":100},{"statHash":1240592695,"value":8,"maximumValue":100},{"statHash":155624089,"value":56,"maximumValue":100},{"statHash":4188031367,"value":16,"maximumValue":100},{"statHash":3871231066,"value":5,"maximumValue":100}],"primaryStat":{"statHash":368428387,"value":286,"maximumValue":0},"canEquip":false,"equipRequiredLevel":20,"unlockFlagHashRequiredToEquip":1661276197,"cannotEquipReason":16,"damageType":2,"damageTypeNodeIndex":2,"damageTypeStepIndex":0,"progression":{"dailyProgress":250,"weeklyProgress":250,"currentProgress":90058,"level":5,"step":0,"progressToNextLevel":2558,"nextLevelAt":25000,"progressionHash":953899265},"talentGridHash":4071286579,"nodes":[{"isActivated":false,"stepIndex":0,"nodeHash":4076480290},{"isActivated":true,"stepIndex":0,"nodeHash":402494132},{"isActivated":true,"stepIndex":0,"nodeHash":402641165},{"isActivated":true,"stepIndex":0,"nodeHash":3452924987},{"isActivated":false,"stepIndex":0,"nodeHash":1144665524},{"isActivated":false,"stepIndex":0,"nodeHash":486779184},{"isActivated":false,"stepIndex":0,"nodeHash":1560693961},{"isActivated":false,"stepIndex":0,"nodeHash":1560841054},{"isActivated":false,"stepIndex":0,"nodeHash":99489719},{"isActivated":false,"stepIndex":0,"nodeHash":3872169477},{"isActivated":false,"stepIndex":0,"nodeHash":3359939809},{"isActivated":false,"stepIndex":0,"nodeHash":2947148901},{"isActivated":true,"stepIndex":0,"nodeHash":312682976},{"isActivated":false,"stepIndex":0,"nodeHash":452419628},{"isActivated":false,"stepIndex":0,"nodeHash":1503756812}],"useCustomDyes":true,"artRegions":{},"isEquipment":true,"isGridComplete":false,"perks":[{"iconPath":"/common/destiny_content/icons/f5047d1c49dc3ea21ada3e06573201f3.png","perkHash":3879685265,"isActive":false},{"iconPath":"/common/destiny_content/icons/6b86f1d294a32a3d107aa6a624d7d691.png","perkHash":2568497806,"isActive":true}],"location":2,"transferStatus":0,"locked":false}
app.js:735 2344494718

![image](https://cloud.githubusercontent.com/assets/11790750/7181036/8ce0cc22-e447-11e4-88ab-05371efe1c36.png)

**Comment by dasilva333** [comment]
Yup, it's a known issue with Bungie not providing me the 'definition' of the item. I'm glad someone created a new ticket for this because I have a potential fix to allow you to see it again until they get their act together.

Thanks for your feedback

**Comment by dasilva333** [comment]
@ssoriche and @Titus-s please try 1.8.8 and let me know if the 4th horseman shows up. Problem should be fixed now thanks

**Comment by Titus-s** [comment]
Yes, It shows up, it's visible and transferable. Thank you so much.
