### ISSUE TITLE
Windows Phone Bug

### ISSUE THREAD

**Issue by MThomas72074** [dasilva333/TowerGhostForDestiny#380]
When I installed Tower Ghost For Destiny on my Windows Phone, Nokia Lumia 630,the app made my other apps close as soon as I attempted to open them,data sense,fb,(etc). My on/off button that controls the backlight function stopped working,other than to power on my device. Reset phone to factory standard,reinstalled app,same problems...So I currently can't use this app at all...Can you resolve,PLEASE & THANK YOU.

**Comment by rkingsla** [comment]
What version of Windows are you running on the

**Comment by MThomas72074** [comment]
8.1 update,which is latest version available  according to the phone itself.

-----Original Message-----

**Comment by dasilva333** [comment]
@MThomas72074 try the latest version 3.2.7 in the store and let me know if you still have problems thanks
