### ISSUE TITLE
Incorrect count of armor pieces in vault

### ISSUE THREAD

**Issue by killi2** [dasilva333/TowerGhostForDestiny#381]
TGD shows I have 73/72 pieces of armor/engrams in vault.  Checked with backup transfer app DIM and it shows 70/72.  Manually count each items shows 70/72 pieces.

First noticed Chrome 3.1.8 and still present in 3.2.1

Also present in Android v 3.2.0

**Comment by dasilva333** [comment]
thanks ill get it fixed

**Comment by dasilva333** [comment]
I can't seem to figure out how to fix it, currently the Share URL feature is broken however it works far enough to help me figure out this issue. @killi2 I need your help with testing this situation if you can go into Settings > Share URL > copy and paste the link and provide it in this post. I'll use that information to debug the problem and get it fixed. Thanks

**Comment by killi2** [comment]
im dont have a full vault but all I can say now is that it seems to always
be counting 3 more armor vault items then I have
https://towerghostfordestiny.com/share/?xbl/Irish%20Moss

**Comment by dasilva333** [comment]
thank you, just to confirm you managed to create the share URL when the armor was 3 count more than what it's supposed to right? so the max is 72 you're saying you saved it when it was displaying 75/72 right?

**Comment by killi2** [comment]
No I  mean right now I think it says 64 but I only have 61. I first noticed
it when it was 72/72 but  I had less than 72 in reality....  I'm not at my
computer right this second.  It is consistently  reporting an armor item
overall count 3 higher than I actually have

**Comment by dasilva333** [comment]
So I looked over the data you provided, you currently have 64 armor items in your vault. I manually counted and came away with 64 also, not sure how you're coming up with 61, here's my counts:

3 - ghost
23- class items
3 - boots
5 - chest
13 - gauntlets
17 - helmets

Let me know if my counts are off. thanks

**Comment by killi2** [comment]
Ah, well there is the issue.  ghosts are general items, not armor.

**Comment by dasilva333** [comment]
Good catch, I'll get that resolved as of the next version

**Comment by rkingsla** [comment]
In relation to this, I seem to hoard class items. So, I
ve discovered that you can clearly have more than 24 class items.  And, as such the class items says 25/24.
![class items](https://cloud.githubusercontent.com/assets/2037051/9997351/5bfc49de-6051-11e5-8902-595f8fcd3b64.png)

**Comment by Mulchman** [comment]
![example](http://i.imgur.com/pWAQzAC.png)

**Comment by dasilva333** [comment]
Problem fixed as of 3.2.8+
