### ISSUE TITLE
Can't close changelog on iOS 9.1

### ISSUE THREAD

**Issue by Adiel-dev** [dasilva333/TowerGhostForDestiny#382]
Running Tower Ghost on iOS 9.1 prevents the user from closing the changelog.

**Comment by lanejcf** [comment]
I am also having this running IOS 9.0

**Comment by mainkowitsch** [comment]
I have the same problem in iOS 9.1

**Comment by pattont** [comment]
Same on 9.0

**Comment by dasilva333** [comment]
https://www.reddit.com/r/DestinyTheGame/comments/3k98oe/announcement_tower_ghost_for_destiny_now/
