### ISSUE TITLE
iOS 3.0.9 Stalls at Loading Hydrated Application

### ISSUE THREAD

**Issue by RedHotTrouble** [dasilva333/TowerGhostForDestiny#383]
After the iOS 3.0.9 update, TowerGhost now stalls at the Loading Hydrated Application screen. Deleted and re-downloaded the app but I continue to get stuck on this screen. Screenshot: http://i.imgur.com/vSYcs9Z.jpg

**Comment by Kovensky** [comment]
Happens on iOS 9.0 GM.

**Comment by dasilva333** [comment]
Just be patient the app will eventually move to the next screen it just takes a while

**Comment by RedHotTrouble** [comment]
Thanks! It took a long while but it did work! Yay!!!
