### ISSUE TITLE
Periodic "Code 30" errors on 3.2.1 Firefox extension

### ISSUE THREAD

**Issue by Kovensky** [dasilva333/TowerGhostForDestiny#384]
The error is `Code 30: Error loading inventory`, followed by a huge JSON dump. They seem to happen periodically, or at least when I check the pinned Tower Ghost tab after a few hours the message is usually there waiting for me.

I saved a copy of the JSON dump [here](http://hastebin.com/fobuwuxufo.json), but it might be annoying to read.

**Comment by dasilva333** [comment]
thanks for the heads up i'll look into it

**Comment by dasilva333** [comment]
I was able to reproduce it, expect it fixed in 3.2.2 thanks

**Comment by dasilva333** [comment]
@Kovensky let me know if you still see it on 3.2.6 thanks
