### ISSUE TITLE
Cannot Close “Updates” window after launch

### ISSUE THREAD

**Issue by rowbotik** [dasilva333/TowerGhostForDestiny#385]
After downloading the new version I haven’t been able to get it working on my iPhone or my iPad. The popup that shows the updates on this version of the app can’t be closed. No matter how many times I hit the X it stays. I even tried turning Voice Over on to navigate and hit it but no luck.

![img_0085](https://cloud.githubusercontent.com/assets/4590280/9905962/911c126e-5c4d-11e5-803c-a7d5b5d1584e.jpg)

**Comment by pattont** [comment]
I was about to post the same issue. I'm on iOS 9 GM on both my iPhone and iPad.

**Comment by dasilva333** [comment]
https://www.reddit.com/r/DestinyTheGame/comments/3k98oe/announcement_tower_ghost_for_destiny_now/

**Comment by rowbotik** [comment]
So we’ll have to wait until the 23rd I guess? iOS 9 comes out today. Should people not update if they’d like to continue using this app?

**Comment by dasilva333** [comment]
That is correct
