### ISSUE TITLE
Suggestion: Sort items in section by light level

### ISSUE THREAD

**Issue by kohum** [dasilva333/TowerGhostForDestiny#386]
Now that light level for items is so important, it would be great if within the weapon and armour sections, the items are sorted by light level.  Highest being at the top.  If there was a setting for this kind of sorting, it would be really helpful. Thanks.

**Comment by dasilva333** [comment]
Currently items are ordered by tier, then type. I'll consider adding a third level of sorting by level in the future. Thanks

**Comment by kohum** [comment]
Thanks. Currently, some of the blue items are higher light level than the legendary ones... so ... i guess maybe a setting to only sort by light level and disregard the other ones?

**Comment by dasilva333** [comment]
this is already in 3.2.3 thanks
