### ISSUE TITLE
Cannot Logout

### ISSUE THREAD

**Issue by rowbotik** [dasilva333/TowerGhostForDestiny#388]
On an iPhone 6 running iOS 9 I've found I cannot Logout. My app is stuck at "Loading Arsenal" and will keep trying. If I delete the app and install it, it's fine until it falls off the Multitasking. If I try and choose Settings-Logout it thinks I tapped the Search field.

**Comment by dasilva333** [comment]
Problem fixed as of 3.4.3 please confirm thanks

**Comment by rowbotik** [comment]
Fixed!
