### ISSUE TITLE
Equip gear with highest light level does not work with exotic armour

### ISSUE THREAD

**Issue by kohum** [dasilva333/TowerGhostForDestiny#389]
I have a few exotic 290 helmets and when I use "Equip gear with highest light level", TGD always selects my 287 blue helmet which happens to be my highest non exotic helmet.

**Comment by dasilva333** [comment]
If you're not level 40 yet there's still issues with how it handles changing gear, if you're level 40 what you're probably seeing is the app changing an exotic helmet for a blue and picking an exotic chest or gauntlets instead to make it even higher. Thanks

**Comment by kohum** [comment]
It's not picking any exotics... I don't have any year 2 exotics in my guantlets section. It's picking all the right amour except it doesn't pick the exotic helmet.  I also have a year 2 chest piece that's 290 but TGfD doesn't pick that one either.

**Comment by kohum** [comment]
Just to clarify.. It picks my year 2 hawkmoon correctly.  So exotic weapons seems to work.  Just exotic armour seems to be bugged.

**Comment by dasilva333** [comment]
Try out 3.2.6 and let me know if you're still having troubles, thanks

**Comment by kohum** [comment]
Tested with 3.2.6 and it still doesn't work with exotic armour. Below are the images - 

![hunterexoticarmourtgfdissue1](https://cloud.githubusercontent.com/assets/6478196/10011961/6b554b78-6156-11e5-9118-25e3a54c7fac.png)

![hunterexoticarmourtgfdissue2](https://cloud.githubusercontent.com/assets/6478196/10011965/7aa98148-6156-11e5-93de-877d4e5abbc0.png)
