### ISSUE TITLE
Slow Loading

### ISSUE THREAD

**Issue by gordonthompson** [dasilva333/TowerGhostForDestiny#390]
I've noticed that Tower Ghost is taking increasingly long to load on my Hudl2 + Windows Phone 950 compared to other competitors.  It often takes minutes to get beyond the "Logging into Bungie.. Please be patient". What is it doing exactly? An API call shouldn't take this long. Vault Helper, for example, loads pretty instantly (less than 30s)

Is there a way I can help diagnose the issue?

Thanks

Gordon

**Comment by Adiel-dev** [comment]
I've tested the newest version for iOS on multiple devices and seeing the same problem.  The initial setup and login goed fine until you open up the app again where it doesn't load past the green bar. Clicking the log in for PSN doesn't help either.

**Comment by pattont** [comment]
I've noticed this as well with Chrome with version 3.2.7. I loaded my inventory then closed my browser, re-open and go to Tower Ghost. It takes upwards of 10-12 seconds for my inventory to load nearly every time. Granted I have a lot of items and 11 loadouts, but still this is a long time. Are the images cached locally?

**Comment by dasilva333** [comment]
Loading is a lot faster as of 3.7.8, try it out and let me know if it's still an issue so I can open this ticket back up, thanks guys
