### ISSUE TITLE
Exotic Weapon Touch of Malice doesn't show up

### ISSUE THREAD

**Issue by tEhHoLLoW** [dasilva333/TowerGhostForDestiny#392]
I got a new exotic weapon "Touch of Malice" and it doesn't show up. When I have it equiped it shows that I don't have anything in that slot. I can't touch it or move it.

Bug found on iOS9.

**Comment by dasilva333** [comment]
Please use the Share URL feature and provide your link so I can debug the problem and find a solution, thank you

**Comment by tEhHoLLoW** [comment]
https://towerghostfordestiny.com/share/?xbl/tEhHoLLoW

**Comment by dasilva333** [comment]
@tEhHoLLoW are you familiar with manual installing a Chrome extension? Do you use TGD for Chrome? Unfortunately the Share URL feature wasn't enough info for me to debug the problem. I need access to someone's account that owns that gun. If it's alright with you I can provide you with a debug build that will let me access your inventory remotely (but not your account). Let me know thanks

**Comment by tEhHoLLoW** [comment]
Don't use Chrome but if you give me instructions I can install the debug extension.

**Comment by dasilva333** [comment]
Install instructions: http://towerghostfordestiny.com/index.php/support/
instead of using the zip file in those instructions use the one found here:

https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/tower_ghost_issue392.zip?raw=true

Once open, press F12 in Chrome to open the developer tools and visit the Console tab all the way to the right, refresh the page if you need to, you should see a message like this:

found an item without a definition!

copy and paste the whole log into pastebin,com or your favorite sharing site.

Thanks

**Comment by SteffanLong** [comment]
This is a problem with Bungie's API, not TGfD. It happens on all applications, also Red Death (Year 2). Bungie is aware of the problem.

**Comment by dasilva333** [comment]
@SteffanLong I'm aware that Bungie is aware of the problem however the companion app has better item support for 'Classified' items so I'd like to support it at a basic level to prevent future situations like this.

**Comment by SteffanLong** [comment]
Makes sense.

**Comment by tEhHoLLoW** [comment]
http://pastebin.com/CvMBifgf

**Comment by dasilva333** [comment]
@tEhHoLLoW can u try 3.2.7 for chrome store? it includes a fix that should let u see the weapon now. let me know thanks

**Comment by tEhHoLLoW** [comment]
Yes, I can see the weapon but can't move it.

Error:: The Vendor you requested was not found.

**Comment by dasilva333** [comment]
Thanks for the update, can you provide an updated share url? The info provided might help me debug the problem

**Comment by tEhHoLLoW** [comment]
Updated

**Comment by dasilva333** [comment]
Can you confirm if you're able to transfer it around in the Bungie site or the companion app? Mind posting some screenshots of how it works there? Thx

**Comment by tEhHoLLoW** [comment]
I can't transfer it on the Website because the Primary Weapon Slot is missing when the Weapon is equipped and the companion app has the same error

**Comment by dasilva333** [comment]
@tEhHoLLoW Thanks for the info, so you're saying the weapon is missing altogether in the Bungie Companion App and the Bungie.net inventory manager? There isn't even a missing icon or mention that it's classified? That conflicts with an earlier screen shot I saw where it shows up as Classified with a white icon. At this point I'm pretty much stuck with no solution, I think I can fix it but I'll need access to your actual account to debug the problem fully. If you're comfortable with sharing your Bungie.net username/password you may do so by emailing me directly at support@towerghostfordestiny.com Please make sure to first change your password to something you can share and then change it again after I'm done using it for maximum security protection. Thanks for your help

**Comment by tEhHoLLoW** [comment]
It's showing as classified on the App but on the Website not only the Weapon isn't showing the whole Primary Slot is missing.

**Comment by dasilva333** [comment]
Are you able to move it on the app? Should I expect an email with your account details to debug this issue?

**Comment by pattont** [comment]
This one should be closed, I can move both my black spindle and touch of malice between characters with 3.2.9.

**Comment by dasilva333** [comment]
great thanks for the heads up I forget to close these things once fixed
