### ISSUE TITLE
Arsenal won't load on Android or Chrome

### ISSUE THREAD

**Issue by jon509tech** [dasilva333/TowerGhostForDestiny#393]
Pretty much what the title says. For the past 4 days I have just had blank screens on all my android and chrome devices. I don't have any other devices to test with. Destiny Item Manager still pulls my inventory, or I would assume an API outage. I have tried logging out and back in, as well as uninstalling the Chrome extension and Android app with no joy.

**Comment by boofa2001** [comment]
I'm having the same issue.  I have cleared my android and chrome cache and uninstalled/reinstalled the extension/app, but it comes up and shows that it is using my PSN login but never loads my inventory.  It seems to coincide with the last update.  I haven't used it since it updated until today though.

**Comment by iamrockr** [comment]
Mine worked great until the last update as well and now it just won't load my inventory after authenticating. I'm running Google Chrome version 45.0.2454.99 on Windows 7 Home Premium if that matters.

**Comment by Burdman2006** [comment]
Seeing the same in my android devices as well. Tried reinstalling and still just loads to a blank screen. The issue coincides with the last update.

**Comment by jcat00uk** [comment]
won't work with chrome on my pc, the pc app, or on my android app, it coincides with either the update, or me acquiring red death year 2 version

**Comment by rkingsla** [comment]
I'm pretty sure it has to do with the warning associated with Red Death itself.  You've been terminated, Guardian....  :8ball:

**Comment by jon509tech** [comment]
Note to go along with the above, I obtained a Year 2 Bad Juju and TGFD worked for a day and the next day it stopped. I obtained the Juju on day 1 of year two so if the update was the very next day (or so) then it coincides.

**Comment by drewstinnett** [comment]
TGFD also stopped working for me around the same time I picked up a Year 2 Red Death

**Comment by boofa2001** [comment]
Update has fixed it for me.  Thx a bunch!

**Comment by jon509tech** [comment]
Confirmed working with new update. Thanks so much!

**Comment by drewstinnett** [comment]
Confirmed working as well, nice!
