### ISSUE TITLE
Loadouts Loading Issue

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#394]
Quick issue I have found with the past few version of Tower Ghost including 3.2.6 in Chrome and it involves my loadouts not having all of my items. This loadout below has 7 items in it, yet randomly (until I refresh the page) only has 2-3 items in it. I haven't been able to reliably reproduce it, but it seems as though after I have been transferring things around for a little while and then need to use a loadout it's broken.

![before refresh](https://cloud.githubusercontent.com/assets/2903357/10022763/74d5199c-611c-11e5-8174-f16f0c4eaffc.PNG)

**Comment by dasilva333** [comment]
im aware of the problem in 3.2.6 w loadouts, pls try 3.2.7 and let me know if you can still reproduce it.

thanks
