### ISSUE TITLE
Suggestion: collapse Post Master section when no items waiting

### ISSUE THREAD

**Issue by Tsothoga** [dasilva333/TowerGhostForDestiny#396]
The Postmaster section (with Messages, Special Orders, and Lost Items) could probably be auto-collapsed when none of the characters have anything waiting to be delivered. It's not a huge deal, but it's screen space going to nothing that could be freed up.

**Comment by dasilva333** [comment]
Thanks for the suggestion but I don't agree with this change. 
-I don't like the idea of collapsible sections
-I dont like users being able to uncollapse an empty section to find nothing
-Would break Auto Pad Height if one section is empty but 2 other characters have stuff in the PM

Thanks for your feedback
