### ISSUE TITLE
3.2.7 Transfer Issue

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#397]
With the newest release I can no longer transfer items using a loadout period. Refreshed or not, just hangs on the first item. I can still manually drag them over or tell them where I need them to go.

<img width="623" alt="screen shot 2015-09-22 at 8 07 15 pm" src="https://cloud.githubusercontent.com/assets/2903357/10035206/aaa57686-6165-11e5-8cb2-d972b12287bd.png">

**Comment by tonyNOS** [comment]
Same here.

**Comment by dasilva333** [comment]
Sorry guys 3.2.7 was really messed up with transfers 3.2.9+ should be a lot better now, try it out and let me know if this is still an issue so I can reopen it. Thanks
