### ISSUE TITLE
Enhance scrolling on phones when in landscape mode

### ISSUE THREAD

**Issue by equesaspe** [dasilva333/TowerGhostForDestiny#40]
As of right now using WP when you go to landscape mode it puts the vault and character one over top of character 2/3. This causes excessive scrolling. It would be better if all characters were displayed next to each other and scroll down to see items. See mock up.
![destiny](https://cloud.githubusercontent.com/assets/11979777/7182850/8fb917ca-e419-11e4-9fdd-d70020acbb44.jpg)
So going from this:
Vault.        Character
Item          item
Character Character
Item.         Item
To this:
Vault character character character
Item. Item.         item.        item

**Comment by dasilva333** [comment]
I actually added the swipe left to right to avoid having to scroll to mobile devices recently. I took it out because I thought I noticed a problem on Windows Phone specifically. I'll be turning it on for myself and retesting it again, if the results are good I'll enable it back on. Thanks for your feedback

**Comment by equesaspe** [comment]
I might be a minority on this one, however on my Lumia 1520 monster screen more data less scroll is better. Perhaps even a spot in the menu to select a character to filter to.

**Comment by JonathanRyanFrederick** [comment]
Agree with equesaspe. I posted on this. Less scrolling with more info is better for larger screens like my note4.

**Comment by dasilva333** [comment]
Hey guys I'm closing this issue, after I added the quick scroll buttons at the top scrolling horizontally hasn't seemed as important anymore. It's going to get better though I'm going to be implementing the enhancement on issue #46 instead to further improve the usability. Thanks for your feedback
