### ISSUE TITLE
[Firefox] Error: Please add valid X-API-Key header to request

### ISSUE THREAD

**Issue by generroric** [dasilva333/TowerGhostForDestiny#400]
After selecting PSN and the "Please wait, loading arsenal from Bungie" appears and is replaced by 

 Error: Please add valid X-API-Key header to request. Visit https://www.bungie.net/developer for details.

**Comment by dasilva333** [comment]
This is known to happen from time to time, I'm not sure why but it's on Bungie's end and seems to resolve itself after a while. Still unsure of the cause.

**Comment by DMWill** [comment]
This has been happening to me all day as well.  Chrome and the Windows standalone are both running the same version (3.2.7) and are ok.

**Comment by Zuzzissm0** [comment]
Where did you get windows standalone 3.2.7.? just downloaded mine and it is 3.2.6. Anyways since yesterday i have the API error on firefox and an endless loading screen in iPad and now on the standalone

**Comment by DMWill** [comment]
that's my bad.  i could have sworn it was 3.2.7 on windows.  it's actually 3.2.6, sorry for the confusion.

**Comment by DMWill** [comment]
i thought 3.2.8 might fix this, but it still throws up the same error, requesting to add a "valid X-API-Key header to request."

**Comment by Kovensky** [comment]
Workaround I did locally: in the `window.addEventListener("request-message", ...)` implementation, right next to `xhr.setRequestHeader('x-csrf', window.activeCookie);`, I added `xhr.setRequestHeader('X-API-Key', 'hash copied from the apikey var in bungie.js');`, and this made it load correctly.

One unfortunate thing I did notice though is that it's not possible to use Tower Ghost without first compiling it into an addon, as the "request-message" event never gets called if it's running on unprivileged (i.e. not extension) code :(

**Comment by VagSmashington** [comment]
Just tried 3.2.9 in Firefox and am still having the same problem. Maybe Kovensky's solution can be implemented

**Comment by DMWill** [comment]
i can confirm 3.2.9 doesn't fix the error in Firefox.

**Comment by dasilva333** [comment]
Problem fixed in 3.3.0 thanks @Kovensky I didn't bother to check my xhr module because I was sure I was including that variable in my request, looking at the history for my firefox.js it seems I never included the apikey in there not sure how it ever worked to be honest. Expect it in the Mozilla store by the end of the day. Thanks guys
