### ISSUE TITLE
iOS - 3.2.6 Breaks App!

### ISSUE THREAD

**Issue by drinkc0ke** [dasilva333/TowerGhostForDestiny#402]
With the release of 3.2.6 via the App Store, the iOS app no longer works. It hangs at the login screen and only advances after clicking the XBL/PSN link. Then, it shows a blank screen and will not load anything no matter how long you wait. Clicking Refresh results in a permanent inventory load that will not advance no matter how long you wait.

Troubleshooting Steps Performed:

Initially, I was using iOS 8 on my iPhone 6. I closed & restarted the app several times, no luck. I logged out then back in (with & without closing & restarting prior to logging back in), no luck. I uninstalled & reinstalled, no luck.

At this point, I figured that perhaps with the iOS 9 compatibility update, iOS 8 is no longer supported. So I updated to iOS 9, still no luck. I then repeated all of the troubleshooting steps above yet again, no luck.

I am severely disappointed, as I was a beta tester on day one and since then I have used this app every day, and this is the first app-breaking issue that has arisen. There have been other issues, but none that prevented me from using the app entirely like this one.

Please take a look and let me know if you need any additional details. I have had friends (on both XBL & PSN) perform testing as well (using both iOS 8 & 9, all on iPhone 5, 5S, or 6) and all report the same issues.

Note that these issues only began after installing 3.2.6 from the App Store today. Prior to this installation, I was using the app perfectly without a single issue whatsoever. My friends all report the same.

Thanks!

drinkc0ke

**Comment by Zuzzissm0** [comment]
have the same problem and with the windows standalone as well

**Comment by dasilva333** [comment]
bug being tracked in issue #399 thanks
