### ISSUE TITLE
3.2.8 Loadouts Missing Completely

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#404]
3.2.7 my loadouts would not transfer, now my loadouts in 3.2.8 are simply gone.

Any ideas?

**Comment by dasilva333** [comment]
no one else is reporting the issue, i think it was an isolated case. see if u can get it to reproduce based on what u did. sorry if i can't help further

**Comment by pattont** [comment]
My loadouts started working again today. I just checked them and they load
and transfer. Weird because for over 24 hours on multiple devices I could
not get my loadouts to even show up.


Thanks!

**Comment by pattont** [comment]
My loadouts are now appearing, but I am going to post another issue that I see with them that I figured out how to reproduce.

**Comment by dasilva333** [comment]
great im glad its fixed, please try closing tickets that have been already solved in the future. thank you
