### ISSUE TITLE
3.2.8 & 3.2.9 Loadouts Issue

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#406]
Here is a weird loadouts issue:

First fresh load of 3.2.9 TG:
![fresh load](https://cloud.githubusercontent.com/assets/2903357/10108680/5365e716-6390-11e5-8f02-5c8aadc7d66b.PNG)

Clicking Refresh Button or Transferring a Loadout to another character then pulling up the loadout again:
![after transfer](https://cloud.githubusercontent.com/assets/2903357/10108657/36a6e922-6390-11e5-9b10-e48ade484b5a.PNG)

The next refresh:
![next refresh](https://cloud.githubusercontent.com/assets/2903357/10108662/3c1d0b48-6390-11e5-9ed6-b608fdd151e0.PNG)

I'm loosing items the longer I use TG until I do a forced refresh. The only way to see all of my items in that loadout again is to go to the URL and click enter or using Control + R to refresh tower ghost.

**Comment by dasilva333** [comment]
I can reproduce it, thanks!

**Comment by pattont** [comment]
oh good, it's been bugging the crap out of me :-)

**Comment by dasilva333** [comment]
Problem fixed expect it in 3.3.1 thanks
