### ISSUE TITLE
Frozen on Loading Arsenal - note 10.1 2014

### ISSUE THREAD

**Issue by salsaketchup** [dasilva333/TowerGhostForDestiny#408]
Fixed with version 3.3.1 :) nice work

Version 3.2.9: My psn login seems to work, but the browser window that shows my bungie.net account doesn't close its self, after closing that and returning to the main screen it is still permanently stuck on the please wait loading arsenal screen.
![screenshot_2015-09-26-09-13-39](https://cloud.githubusercontent.com/assets/14847565/10116562/5a3c590e-642f-11e5-8e10-4c7f1c93bf8a.png)
(https://cloud.githubusercontent.com/assets/14847565/10116555/221d9984-642f-11e5-8c7e-4b4337138ed4.png)

![screenshot_2015-09-26-08-53-30](https://cloud.githubusercontent.com/assets/14847565/10116410/510fe592-642c-11e5-985b-b60e0e99ee37.png)

**Comment by dasilva333** [comment]
Great I'm glad its fixed, feel free to close an issue on your own next time. Thanks
