### ISSUE TITLE
3.2.6 stopped working for iOS9.0 on iphone6+

### ISSUE THREAD

**Issue by Khaaang** [dasilva333/TowerGhostForDestiny#409]
3.2.6 build was working great on iOS9.0 until 9/25. Now it goes through the loading screen and loads to a blank grey screen. A reinstall and relogin was not able to fix the issue.

**Comment by dasilva333** [comment]
@Khaaang I'm going to track the loading screen issues on issue #399 please follow the directions provided there if you'd like to help me figure out this problem. Thanks
