### ISSUE TITLE
Api Key Thing?

### ISSUE THREAD

**Issue by Chase100488** [dasilva333/TowerGhostForDestiny#410]
I'm Using Tower Ghost On My Firefox Browser And It Keeps Telling Me  "Please add valid X-API-Key header" How Do I Fix This Issue? Please Help

**Comment by dasilva333** [comment]
Try 3.3.0 in the store let me know if you have any problems thanks

**Comment by Chase100488** [comment]
Yes It Worked Back Then Thanks
