### ISSUE TITLE
iOS 9.0.1 on the IPAD can't log in using 3.2.6

### ISSUE THREAD

**Issue by n34panda** [dasilva333/TowerGhostForDestiny#411]
Hi,

I've been using this app for a while and love it (thanks) - unfortunately in the last week I have had a few issues with it.  Specifically one day I found I couldn't move weapons around so I closed the app via multi-tasking.  After trying to re-open it I found the app tried to log me in, it looks like it does successfully if I click the xbox live link but the app never moves from the "Please wait, loading arsenal from Bungie".  The green bar is moving but I imagine that is not meaningful really.  

I have tried to uninstall and re-install the app twice, with no success.

I have tried to login/logout a number of times with no success.

I have uninstalled, rebooted and re-installed, with no success.

I've hit refresh numerous times with no success.

Have you had any other reports of any similar issues, is a new release coming?

EDIT -> on restarting the app, the login (orange) bar apears but the screen stays grey.  If I hit refresh the green bar appears but does not dissapear.

EDIT -> I downloaded the desktop version on a Win 7 64bit desktop and experienced exactly the same behaviour, could it be my bungie account (website works as I expect?)?

Going to help dasilva333 and use #339 as I think these problems are all related

**Comment by dasilva333** [comment]
@n34panda thank you man I just saw this post, your results have helped me realize that I can also reproduce the problem on tgd win x64 3.2.6 so I'll be publishing 3.3.2 tonight with the fix for Windows and 3.3.2 with the fix for iOS. thanks again

**Comment by n34panda** [comment]
great news - thank you for providing/maintaing/supporting a great app

**Comment by n34panda** [comment]
FYI release 3.3.3 seems to have fixed it - congrats!
