### ISSUE TITLE
Toaster messages have double colons

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#412]
Fixed this in my branch a while ago, and I keep having to fix any new toaster bits when merging in your stuff to my branch, but just wanted to mention this so you can maybe fix up the mainline.

The toaster bits have double colons in the messages:
> **Result:**: all items normalized

It's because the *title* string has a colon and the toaster stuff internally adds a colon to the string:
> $.toaster({
>                priority: 'success',
>               title: 'Result:',
>                message: " The highest set available for " + type + "  is  " + highestSetValue
>            });

**Comment by dasilva333** [comment]
thanks expect it fixed in 3.3.4

**Comment by dasilva333** [comment]
thanks expect it fixed in 3.3.4
