### ISSUE TITLE
Light level auto transfer fails

### ISSUE THREAD

**Issue by slansing97** [dasilva333/TowerGhostForDestiny#413]
Ok, a little complex, but hopefully this adds some debug info.

I can never seem to auto transfer my light level.  It's choking on one specific item every time.  Not sure why it causes the error, but I did seem to find out that the retransfer fails.  I didn't dive into the code enough, but I think app.findReference returns an item that doesn't have a .store function around item.js:745.

Copy/pasted console window below, in some cases I added my own logging or uncommented existing code.  The formatting's ugly, so I tried to add some newline for emphasis.

Tested on fresh pull, 3.3.2.  Let me know if I can provide more info.

**************transferNextItem*************
tgdDefs.js:15 no swapItem, transferTargetItem
tgdDefs.js:15 Chest spaceNeededInVault: 71
tgdDefs.js:15 Chest spaceUsedInVault: 69
tgdDefs.js:15 vault has at least 2 slots to make xfer
tgdDefs.js:15 Corsair's Revenge 2.0 transferTargetItemToDestination 2305843009247966831
tgdDefs.js:15 equip called from 2305843009241553717 to 2305843009247966831
tgdDefs.js:15 item is NOT already in the character
tgdDefs.js:15 Chest bucket max of 10 : false
tgdDefs.js:15 need to transfer 1 items, the target is this full 8
tgdDefs.js:15 loadouts_to_transfer: Corsair's Revenge 2.0
tgdDefs.js:15 equip called from 2305843009241553717 to 2305843009241553717
tgdDefs.js:15 item is already in the character
tgdDefs.js:15 making bungie call to equip Corsair's Revenge 2.0
tgdDefs.js:15 result was OKed for Corsair's Revenge 2.0
tgdDefs.js:15 Object {Response: 0, ErrorCode: 1, ThrottleSeconds: 0, ErrorStatus: "Success", Message: "Ok"…}ErrorCode: 1ErrorStatus: "Success"Message: "Ok"MessageData: ObjectResponse: 0ThrottleSeconds: 0__proto__: Object
tgdDefs.js:15 Corsair's Revenge 2.0  error during transfer!!!
tgdDefs.js:15 Object {Response: 0, ErrorCode: 1656, ThrottleSeconds: 0, ErrorStatus: "DestinyCannotPerformActionOnEquippedItem", Message: "You cannot perform this action on an equipped item."…}ErrorCode: 1656ErrorStatus: "DestinyCannotPerformActionOnEquippedItem"Message: "You cannot perform this action on an equipped item."MessageData: ObjectResponse: 0ThrottleSeconds: 0__proto__: Object
tgdDefs.js:15 reloading bucket Chest
tgdDefs.js:15 2 log request to "4611686018439505236"
tgdDefs.js:15 retransferring
app.js:1151 findReference Corsair's Revenge 2.0

tgdDefs.js:15 The original item:
tgdDefs.js:15 Object {itemHash: 3241810625, bindStatus: 0, itemInstanceId: "6917529060688400045", itemLevel: 49, stackSize: 1…}_id: "6917529060688400045"_isVisible: ()_primaryStatValue: ()armorIndex: 2artRegions: ObjectbindStatus: 0bucketName: "Equippable"bucketType: "Chest"canEquip: truecannotEquipReason: 0character: ProfilecharacterId: "2305843009241553717"classType: 1clone: ()consolidate: (targetCharacterId, description)damageType: 0damageTypeName: "None"damageTypeNodeIndex: -1damageTypeStepIndex: -1description: "Corsair's Revenge 2.0"doEquip: d()equip: (targetCharacterId, callback)equipRequiredLevel: 40extrasGlue: ()getValue: (type)handleTransfer: (targetCharacterId, cb)hasPerkSearch: (search)hashProgress: (state)href: "https://destinydb.com/items/3241810625"icon: "data/common/destiny_content/icons/033ebeebf443ead7d8917920b657677a.jpg"id: 3241810625init: (item, ignoreDups)isEquipment: trueisEquippable: (avatarId)isEquipped: d()isGridComplete: trueisStoreable: (avatarId)isUnique: falseisVisible: g()itemDescription: ""They were Wolves in sheep's clothing. Now we're Awoken in Wolves' clothing." —Paladin Devi Cassl"itemHash: 3241810625itemInstanceId: "6917529060688400045"itemLevel: 49location: 1lockable: truelocked: d()markAsEquip: (item, event)nodes: Array[3]normalize: (characters)objectives: Array[0]perks: Array[2]primaryStat: d()primaryStatValue: g()progression: truequalityLevel: 9stackSize: 1state: 1stats: Object

store: (targetCharacterId, callback)

talentGridHash: 1085490142tierType: 4tierTypeName: "Rare"toggleLock: ()transfer: (sourceCharacterId, targetCharacterId, amount, cb)transferStatus: 1type: 0typeName: "Chest Armor"unequip: (callback, excludeExotic)unlockFlagHashRequiredToEquip: 2166136261useCustomDyes: trueweaponIndex: -1__proto__: Object

app.js:1157 Profile {profile: Object, uniqueName: "40 Exo Male Hunter", classLetter: "H", race: "Exo", reloadingBucket: false…}
app.js:1158 180
app.js:1159 [Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item, Item…]
tgdDefs.js:15 querying with character id 2305843009241553717
tgdDefs.js:15 40 Exo Male Hunter
tgdDefs.js:15 querying with {"_id":"6917529060688400045"}

tgdDefs.js:15 Item {itemHash: 3241810625, bindStatus: 0, itemInstanceId: "6917529060688400045", itemLevel: 49, stackSize: 1…}_id: "6917529060688400045"armorIndex: 2artRegions: ObjectbindStatus: 0bucketName: "Equippable"bucketType: "Chest"canEquip: truecannotEquipReason: 0character: ProfilecharacterId: "2305843009241553717"classType: 1damageType: 0damageTypeName: "None"damageTypeNodeIndex: -1damageTypeStepIndex: -1description: "Corsair's Revenge 2.0"equipRequiredLevel: 40href: "https://destinydb.com/items/3241810625"icon: "data/common/destiny_content/icons/033ebeebf443ead7d8917920b657677a.jpg"id: 3241810625isEquipment: trueisEquippable: (avatarId)isEquipped: d()isGridComplete: trueisStoreable: (avatarId)isUnique: falseisVisible: g()itemDescription: ""They were Wolves in sheep's clothing. Now we're Awoken in Wolves' clothing." —Paladin Devi Cassl"itemHash: 3241810625itemInstanceId: "6917529060688400045"itemLevel: 49location: 1lockable: truelocked: d()nodes: Array[3]objectives: Array[0]perks: Array[2]primaryStat: d()primaryStatValue: g()progression: truequalityLevel: 9stackSize: 1state: 1stats: Object

talentGridHash: 1085490142tierType: 4tierTypeName: "Rare"transferStatus: 1type: 0typeName: "Chest Armor"unlockFlagHashRequiredToEquip: 2166136261useCustomDyes: trueweaponIndex: -1__proto__: Object_isVisible: ()_primaryStatValue: ()clone: ()consolidate: (targetCharacterId, description)equip: (targetCharacterId, callback)extrasGlue: ()getValue: (type)handleTransfer: (targetCharacterId, cb)hasPerkSearch: (search)hashProgress: (state)init: (item, ignoreDups)normalize: (characters)store: (targetCharacterId, callback)toggleLock: ()transfer: (sourceCharacterId, targetCharacterId, amount, cb)unequip: (callback, excludeExotic)__proto__: Object

**Comment by dasilva333** [comment]
thanks for the debug log, doesn't help much though, let me ask you a few questions:

Are you able to reproduce this problem consistently? 
Do you know what you have to do to cause it to error?
Does it only happen sometimes?

**Comment by slansing97** [comment]
Alright, some more info:

Yes, bug is 100% with two of my items as far as I can tell.  Below is from tests on a recent 3.3.3 build:

* Occurs when choosing "equip gear with highest light"
* Occurs with 2 of my items (chest and artifact)
* ONLY occurs if item is equipped on another character.  Does not occur if item is unequipped on another char, if in vault, if on the target character's inventory already, or if equipped on the target character already
* **Seems to also occur if a profile is made with the item in it** (which I suppose means it's not "equip gear with highest" related)
* Does NOT occur at all when transferring item individually
* In both cases, I have 2 of the same item (I have 2 of the artifact, and for the chest, I also have gauntlets with the same name) HOWEVER when testing with other items I have duplicates of, this does not occur
* Thinking back, this must have been occurring for me ever since 2.0.0 dropped with some other items.  I created profiles and they would not always transfer.  Then I'd manually transfer some of them and use the profile transfer for the rest.  This may be why people are reporting issues.  You may be able to reproduce with your own character by creating profiles and transferring between characters until you find an item that fails.

Additional info which includes my 2nd item that's also causing problems.

**************transferNextItem*************
tgdDefs.js:14 no swapItem, transferTargetItem
tgdDefs.js:14 Artifact spaceNeededInVault: 71
tgdDefs.js:14 Artifact spaceUsedInVault: 68
tgdDefs.js:14 vault has at least 2 slots to make xfer
tgdDefs.js:14 Ankh of Sai Mota transferTargetItemToDestination 2305843009247966831
tgdDefs.js:14 equip called from 2305843009241553717 to 2305843009247966831
tgdDefs.js:14 item is NOT already in the character
tgdDefs.js:14 Artifact bucket max of 10 : false
tgdDefs.js:14 need to transfer 1 items, the target is this full 3
tgdDefs.js:14 loadouts_to_transfer: Ankh of Sai Mota
tgdDefs.js:14 equip called from 2305843009241553717 to 2305843009241553717
tgdDefs.js:14 item is already in the character
tgdDefs.js:14 making bungie call to equip Ankh of Sai Mota
tgdDefs.js:14 result was OKed for Ankh of Sai Mota
tgdDefs.js:14 Object {Response: 0, ErrorCode: 1, ThrottleSeconds: 0, ErrorStatus: "Success", Message: "Ok"…}ErrorCode: 1ErrorStatus: "Success"Message: "Ok"MessageData: ObjectResponse: 0ThrottleSeconds: 0__proto__: Object
tgdDefs.js:14 Ankh of Sai Mota  error during transfer!!!
tgdDefs.js:14 Object {Response: 0, ErrorCode: 1656, ThrottleSeconds: 0, ErrorStatus: "DestinyCannotPerformActionOnEquippedItem", Message: "You cannot perform this action on an equipped item."…}ErrorCode: 1656ErrorStatus: "DestinyCannotPerformActionOnEquippedItem"Message: "You cannot perform this action on an equipped item."MessageData: ObjectResponse: 0ThrottleSeconds: 0__proto__: Object
tgdDefs.js:14 reloading bucket Artifact
tgdDefs.js:14 2 log request to "4611686018439505236"
tgdDefs.js:14 retransferring
tgdDefs.js:14 querying with {"_id":"6917529060666085928"}
tgdDefs.js:14 Item {itemHash: 27771124, bindStatus: 0, itemInstanceId: "6917529060666085928", itemLevel: 50, stackSize: 1…}

**Comment by dasilva333** [comment]
@slansing97 can you confirm the problem is still apparent in 3.4.6? Thanks

**Comment by slansing97** [comment]
Fix verified.  Last night I used a couple of different loadouts (including items that were failing before), everything worked as expected, thanks for the fix!
