### ISSUE TITLE
IOS 9.0.1 issue loading loadout

### ISSUE THREAD

**Issue by hjongedijk** [dasilva333/TowerGhostForDestiny#414]
Since the ios 9 update i got problems with the loading of the gear, sometimes i get the message unable to parse data.

How to fix this?

**Comment by Khronok** [comment]
same happen to me, I can't load any of my gear :/

**Comment by mkbnet** [comment]
Same prob ..app hang on loading arsenal.
Please fix it.
Tia

**Comment by dasilva333** [comment]
changes with Bungie made 3.2.6 break expect it fixed with 3.3.3 coming soon thanks
