### ISSUE TITLE
Tower Ghost constantly disabled on Chrome OS X

### ISSUE THREAD

**Issue by dpickard** [dasilva333/TowerGhostForDestiny#418]
Almost every day, sometimes multiple times a day, the TowerGhost extension disappears from the control bar of Chrome on my iMac.

I have to go into extensions and click "reload" for it to work again.
Sometimes it says that the permissions changed and it needs me to OK it again, most of the time it doesn't tell me anything, it's just gone and I have to go reload it.

I'm not sure if this is a bug, or intended behavior on Chrome's part but it's driving me completely nuts.

One note: I use it on Chrome on Windows 10 and and OS X 10.10

**Comment by dasilva333** [comment]
I'm having the same problem too, Ill look into getting it fixed. thanks

**Comment by dasilva333** [comment]
@dpickard is this still happening as of 3.4.0 or 3.3.8? Let me know if so Ill reopen the ticket. Thanks
