### ISSUE TITLE
Can't use on FF41?

### ISSUE THREAD

**Issue by sdholden** [dasilva333/TowerGhostForDestiny#419]
Hi.

Last few releases exhibit same behavior on FF 41.  Click 'XBox Login" and new window opens as expected.  then the window closes and a new tab opens, logged into bungie.net.  And that's all.
If I close the new tab, TGD says "Loading, please wait" in a small green popup, then the loading bar is displayed, then...nothing, so is unusable for me right now.  The box asking to login to xbox or PSN remains in the window after the bar disappears, but no items shown.
Have UBlock_Origin add-in installed that might be an issue?

**Comment by dasilva333** [comment]
Is this version 3.3.5? Can you open the developer console under Tools? Try loading the extension and see if it crashes or displays any error information. Thanks let me know

**Comment by DMWill** [comment]
i'm running Firefox 41.0.1 and TGFD 3.3.5.  so i'm guessing near identical setup.  i however am not having an issue.  i'm not running ublock though; i do have adblock plus, but that has never cause an issue.  would there be some log file or something from my dev console that would help to compare the two?

**Comment by sdholden** [comment]
Yes, also with 3.3.5 (just updated).  Do you need msgs from the Web console or browser console?  No error shown in the Web Console.  Same issue.  I'll restart in safe mode and see if it works, then test each add-on.... Stephen Holden
Ontario, Canada

**Comment by sdholden** [comment]
Disabled all extensions and same result.  A new window opens, then immediately closes and a new tab opens to bungie.  When I close that new tab, TGD triggers.  Of course, now there isn't a tab open & logged in?
Works fine in chrome, wit same/ similar add-in all enabled..  The new window logs into bungie.  No new tab is created, just a new window...


Sent from my Samsung Galaxy Tab®4

-------- Original message --------

**Comment by sdholden** [comment]
3.3.6 is working again.  Not sure what you did, but it loads successfully now.  Thanks!
 Stephen Holden
Ontario, Canada

**Comment by dasilva333** [comment]
@sdholden not sure what I changed in 3.3.6 that would fix your Firefox issue I'm glad its fixed. Feel free to post any other issues if you have problems in the future. Thanks
