### ISSUE TITLE
Export/Backup/Sync Loadouts

### ISSUE THREAD

**Issue by b0bbybacc** [dasilva333/TowerGhostForDestiny#42]
Talked about this with you briefly on reddit; getting around to adding it here, please label as enhancement request:

Add logic to backup loadouts into flat file or otherwise (potential sync server ) so we can then import them into another instance of TGfD IE) Create loadout A on Android, export loadout A to flat file, transfer flat file to PC, import flat file to create/update loadout A in Chrome extension.

Let me know if this is unclear. Thanks, again, so much for your hard work.

**Comment by dasilva333** [comment]
Closing this ticket as I will **not** be adding the ability to export/importloadous. As of version 1.8.3 it supports Cloud Saves for Loadouts so all your changes stay in sync across all platforms without any user interaction. If you're on FlightTest expect to see the new version coming up soon.

Thanks for your feedback
