### ISSUE TITLE
King's Fall raid gear set 

### ISSUE THREAD

**Issue by Tsothoga** [dasilva333/TowerGhostForDestiny#421]
I'm currently not seeing a filter for the King's Fall raid weapons or armor. Not sure if this is waiting on the Hard Mode raid to drop, which is where we will presumably unlock the "Harrowed" versions.

I don't know coding at all, but is this anything I could help with. Maybe tracking down the links for all the gear?

**Comment by dasilva333** [comment]
Usually @schubydoo takes care of this stuff, feel free to help me find the items. Instructions and HOW TO can be found here:

https://github.com/dasilva333/TowerGhostForDestiny/issues/213

The only thing that changed was the js/destinyexotics.js file became data/setDefs.json. Once the changes are completed please submit it as a Pull Request, if done right it should show up here:

https://github.com/dasilva333/TowerGhostForDestiny/pulls

Good luck and let me know if you need me to clarify anything. Thanks

**Comment by Tsothoga** [comment]
Alright, I'm definitely a newbie at this sort of thing, but I'll take a look at it this week and see what I can do. If I need help, I'll squawk!

**Comment by mistral13** [comment]
First time doing this.

```

"ttkArmor": [
3471865172,
3907799187,
2302693613,
2549035183,
2242715338,
       
3471865173,
3907799186,
2302693612,
2549035182,
       
1846107925,
 372855004,
 521951204,
2028036494,
1658688593,
     
1846107924,
 372855005,
 521951205,
2028036495,
       
1245063910,
3176903681,
 217447095,
1601524313,
 130578780,
       
1245063911,
3176903680,
 217447094,
1601524312
],


"ttkWeapons": [
 962497238,
1457207757,
2536361593,
2918358302,
3919765141,
3042333086,
2201079123,
1397524040,
1551744702,
          
 962497239,
1457207756,
2536361592,
2918358303,
3919765140,
3042333087,
2201079122,
1397524041,
1551744703
]
};


```

**Comment by dasilva333** [comment]
@mistral13 thanks for the ids, expect to see it in 3.4.1 however next time please submit it as a formal pull request, if done right it should show up in this list: 
https://github.com/dasilva333/TowerGhostForDestiny/pulls
thanks again

**Comment by matthubb** [comment]
The raid gear doesn't appear under the King's Fall Raid source definition.
Have an open query with Bungie on the API forum over this. "Sources" should
be the reliable way of generating gear sets, but the data from Bungie isn't
up to it.

Not entirely clear whether or not this is intentional. Previous omissions
have been described as unintentional. If fixed, I'll sort something out to
generate / update the gear sets automatically.

**Comment by dasilva333** [comment]
@matthubb there's never been anything in the system to make any of this automatic this has always been a manual process of finding the ids since the app ever offered the Set filter, it was only recently that I automated the exotic armor and weapons list because it's pretty obvious but there's no markers on anything else to allow this for an automatic process.

**Comment by matthubb** [comment]
So I've got a bunch of code that I use to interact with the API and manifest. I build a dictionary of sets for the `itemCategoryHashes` and `sourceHashes` 

Most of the following work, except the Adept weapons for ToO, PoE Armour and the Kings Fall Raid gear:

    filters = dict(
        exotic_weapons = (sets['CATEGORY_WEAPON'] & sets['TIER_EXOTIC']),
        exotic_armour  = (sets['CATEGORY_ARMOR']  & sets['TIER_EXOTIC']),
        vault_weapons  = (sets['CATEGORY_WEAPON'] & sets['SOURCE_VAULT_OF_GLASS']) - (sets['SOURCE_NIGHTFALL'] | sets['SOURCE_VENDOR_BLACK_MARKET']),
        vault_armour   = (sets['CATEGORY_ARMOR']  & sets['SOURCE_VAULT_OF_GLASS']),
        crota_weapons  = (sets['CATEGORY_WEAPON'] & sets['SOURCE_CROTAS_END']) - (sets['SOURCE_NIGHTFALL'] | sets['SOURCE_VENDOR_BLACK_MARKET']),
        crota_armour   = (sets['CATEGORY_ARMOR']  & sets['SOURCE_CROTAS_END']),
        banner_weapons = (sets['CATEGORY_WEAPON'] & sets['SOURCE_VENDOR_IRON_BANNER']),
        banner_armour  = (sets['CATEGORY_ARMOR']  & sets['SOURCE_VENDOR_IRON_BANNER']),
        osiris_weapons = (sets['CATEGORY_WEAPON'] & sets['SOURCE_VENDOR_OSIRIS']),
        osiris_armour  = (sets['CATEGORY_ARMOR']  & sets['SOURCE_VENDOR_OSIRIS']),
        queens_weapons = (sets['CATEGORY_WEAPON'] & sets['SOURCE_PRISON_ELDERS']) - (sets['SOURCE_NIGHTFALL'] | sets['SOURCE_VENDOR_BLACK_MARKET']),
        kingsfall_weapons  = (sets['CATEGORY_WEAPON'] & sets['SOURCE_KINGS_FALL']) - (sets['SOURCE_NIGHTFALL'] | sets['SOURCE_VENDOR_BLACK_MARKET']),
        kingsfall_armour   = (sets['CATEGORY_ARMOR']  & sets['SOURCE_KINGS_FALL']),
    )

One other minor complication is that there are some items with older versions (presumably legacy), having another check to add in item hashes with duplicate names has been necessary in the past.

**Comment by dasilva333** [comment]
@matthubb very cool stuff I'd like to see what you could make out of that, automating the process would definitely be helpful
