### ISSUE TITLE
Year filters for Item Sets?

### ISSUE THREAD

**Issue by Tsothoga** [dasilva333/TowerGhostForDestiny#422]
When looking at some of the Item Sets, especially with the "Show Missing Items" option checked, there is some unusual behavior: lots of items show up on the missing items list. Especially with the new Iron Banner and Trials of Osiris launching in a few weeks, people could be using some of these Item Set filters. I believe the impacted item sets are "Queen's Wrath Armor", "Iron Banner Armor", "Iron Banner Weapons", "TOO armor", "TOO Weapons", "Exotic Armor", and "Exotic Weapons".

Would isolating the Year 1 and Year 2 version of each of these sets (and in the case of Iron Banner, possibly even the version for each expansion) require finding the unique DestinyDB link to each item? Or were the items repurposed in the DB so that it's not even possible to have the sets split out?

**Comment by dasilva333** [comment]
Problem is fixed as of 3.3.6 try it out and let me know how it goes, the items are matched by name now rather than ID so if you have the Y1 version or the Y2 version it won't show up as missing. Cheers
