### ISSUE TITLE
weapon filter menu item gone

### ISSUE THREAD

**Issue by PillowMetal** [dasilva333/TowerGhostForDestiny#423]
In version 3.3.6 on the chrome browser, the weapon filter menu item is gone, e.g. I can no longer filter by scout rifle, sniper rifle, etc. Am I missing something?

**Comment by patchm00** [comment]
Same for me using Chrome on Tablet Windows 10

**Comment by DMWill** [comment]
First, sort by just weapons.  Then you'll have a menu to sort by type of weapon.  Same goes for General and Armor.  :ok_hand:

**Comment by PillowMetal** [comment]
Oh, I see this was a design change that was not obvious to me since I rarely change the view set, I just filter away. I actually prefer main menu items to not appear and disappear based on context (that's for right mouse button actions), but in this situation I can see this would mean three additional top level menu items, so it kind of makes sense. I will close this issue since it is not a bug.

**Comment by patchm00** [comment]
well, that still isn't as useful in my opinion.  I can't necessarily tell what sort of weapon it is by sight (scout vs pulse vs auto rifle for instance.  I really liked the method when you could choose to JUST view one type of weapon.  Personal preference i guess

**Comment by dasilva333** [comment]
Thanks for the feedback guys, expect the next version to show Weapon | Armor | General filter when the View is set to All, my concern initially is it wouldn't fit all fit at 1024px width but I see it does. Cheers and thanks
