### ISSUE TITLE
Sleeper Simulant is out, need updated manifest and what not

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#424]
What the title says, otherwise gear slots appear empty wherever you have a Sleeper Simulant.

**Comment by rkingsla** [comment]
Which, certainly needs to be resolved.

The bigger issue (after spending about 5 hours sitting my ass around on Mars) is that WarSat drops on Mars seem about as plentiful as Cabal on Terra.  WTF?????

Now back to our regularly scheduled AppDev talk....

**Comment by dasilva333** [comment]
@Mulchman 

is the gun still usable in the app? 
Can you transfer the gun around?
Does it show up with a missing icon as classified?
Does it show up in your primary slot?

Let me know thanks

**Comment by Mulchman** [comment]
Not dodging. Will give more details when I can get to a computer. Right
now, in the official Destiny app, it is showing as classified and when
clicking the heavy slot I see nothing in the *equipped* area and nothing
(no list of other heavies on the character) in the *unequipped* area.

**Comment by Mulchman** [comment]
is the gun still usable in the app? 
* no

Can you transfer the gun around?
* no

Does it show up with a missing icon as classified?
* no

Does it show up in your primary slot?
* no

![random](http://i.imgur.com/lZ4nC4N.png)

**Comment by SteffanLong** [comment]
The manifest has not been updated yet. We added a placeholder for now using another item that shares the same icon. I can get you the nodeHash and icon URL.

--
Steffan Long

**Comment by SteffanLong** [comment]
The hash is 3012398149. Here's some information on the weapon we used to manually modify our manifest file. Hope it helps!

```
DestinyWeaponDefinition[3012398149] = {
  name: 'Sleeper Simulant',
  icon: '/common/destiny_content/icons/9be72c64fdd81ccd068e766365cd38c6.jpg',
  subType: 11
};
```

**Comment by pattont** [comment]
Just got mine today :-) Was coming here to post and everyone beat me 2 it!

**Comment by patchm00** [comment]
Just to add something, it doesn't show correctly on bungie web site so they have not upudated either and I'm sure you can't until they do.  Also, in the app, it shows up classified on my primary slot :)

**Comment by dasilva333** [comment]
Sorry guys after acquiring the Sleeper I've concluded there's nothing I can do to make it transferable via the API due to restrictions put in by Bungie expect just a place holder in it's place in the future. Thanks

**Comment by pattont** [comment]
Yea, I don't believe its even transferable via their app either. Guess we
just have to wait on an API update for this weapon.


Travis

**Comment by tmalfor** [comment]
This is what I am seeing:

is the gun still usable in the app?  
I don't understand the question.

Can you transfer the gun around?
No.  When I attempt to transfer the weapon "It says the vendor you requested was not found"

Does it show up with a missing icon as classified?
Yes

Does it show up in your primary slot?
Yes

**Comment by dasilva333** [comment]
As previously posted there's nothing I can do to make the SS work in the app while Bungie hasn't enabled it yet, closing this issue as this isn't something that I can fix.

**Comment by DogBeatr** [comment]
Sleeper was updated by Bungie on the official app. Should be able to fix it now.
