### ISSUE TITLE
Progress filter fails

### ISSUE THREAD

**Issue by Bazzu85** [dasilva333/TowerGhostForDestiny#426]
Since today I'm noticing that Progress filter fails...

From a non-filter situation if you choose for example "Missing Perks" weapons and armor are not showed..same thing if you choose "Missing Borders" or "Maxed".

Another strange thing is that, after choosing a filter and then choosing "All" nothing is showing..

Only "Clear filters" works

Version: last on chrome

**Comment by patchm00** [comment]
Same, choosing Progress filter missing perks no weapons are displayed

**Comment by DMWill** [comment]
yep, here too. didn't even notice because i don't use that feature very often.  
FF 41.0.1
TGD 3.3.8

**Comment by Bazzu85** [comment]
I'm noticing that now with 3.3.9 weapons and armor is showing when filtering..but not correctly..
for example I've maxed FWC Vanity but is still showing as "Missing Perks". The reason is that in descrition 1 perk isn't active as it's active the upper one..

**Comment by dasilva333** [comment]
Problem fixed in 3.4.0 expect it fixed then, feel free to leave any comments here if there's still issues thanks guys

**Comment by Bazzu85** [comment]
ok, I will report when I receive 3.4.0 update..
