### ISSUE TITLE
unable to transfer consumables

### ISSUE THREAD

**Issue by tmalfor** [dasilva333/TowerGhostForDestiny#428]
Haven't tested all of them but I did try to manually transfer three different consumables. It doesn't work. It doesn't provide any feedback as to why it doesn't work either.  I don't know if it makes a difference but I'm experiencing this on Android

**Comment by tmalfor** [comment]
However, I was able to transfer multiple engram's.  It seems that I'm only having this problem on consumables

**Comment by tmalfor** [comment]
It goes without saying that I cannot normalize either. When I attempt to the application does tell me what needs to be moved from what guardian to what other guardian, but when I execute it doesn't do anything.

**Comment by tmalfor** [comment]
The vault show that I had 34 of 36 slots in use. I've seen something strange with the application before that I need to transfer something from the vault to one of the other guardians before I can actually start transferring anything between the Guardians. Is always made sense to me when the vault was full but never made sense when I had open slots in the hole. I went ahead and transferred a consumable from the vault to another Garden. At that moment several of my queued transfers between guardians started working again.  Normalize is now working again too. I never received any feedback through the application explaining why it wasn't working to begin with.

**Comment by tmalfor** [comment]
Ok, this one's on me.  I had 2 artifacts in the vault that weren't counted as General items, even though Destiny counts them that way.  Please fix the counter and provide feedback to the app user that lets them know why they can't transfer.  Or, build capability into your app to temporarily free up a vault space by auto transferring an unrelated item to a guardian with room and auto transferring back after the original requested item transfer is complete and the open space in the vault is no longer needed.

**Comment by dasilva333** [comment]
Problem fixed in 3.4.0 please try it out when it's ready to confirm, thanks
