### ISSUE TITLE
Can the top level refresh have a toaster notification?

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#429]
I like that the new refresh does the in-place refresh that was added for the section headers and what not. But, depending on network speed, sometimes you'll click the refresh button and see nothing visibly happen because it happened so fast. This leads you to wonder if you actually clicked the button and/or if anything actually happened. Some kind of visual indication that the refresh completed/finished would be awesome, IMO.

Example:

* **www/js/Profile.js** in the *_reloadBucket* function
``` javascript
        function done() {
            function reallyDone() {
                self.reloadingBucket = false;
                if (element) {
                    element.removeClass("fa-spin");
                }
+               $.toaster({
+                   priority: 'info',
+                   title: 'Success',
+                   message: 'Refresh completed'
+               });
            }
```

**Comment by dasilva333** [comment]
good fix thanks
