### ISSUE TITLE
1.8.8: WP Crashing/Constant Blue loading Bar

### ISSUE THREAD

**Issue by equesaspe** [dasilva333/TowerGhostForDestiny#43]
1.8.6 Worked perfect. After 1.8.8 constant blue loading bars and occasional crashes when logging into XBL. Rebooting phone did not fix. Problem persists.

**Comment by dasilva333** [comment]
I just tested 1.8.8 on my iPhone 5s and it work's perfectly. I'll try it on my Nokia Lumia when I get home today and see if I have any issues. If I can't reproduce it I'll come up with a debug build to try to figure out your problem. Thanks for the info

**Comment by equesaspe** [comment]
So I was able to get it to work after some troubleshooting. Here is what I did:
Uninstalled app, reinstalled,, updated to 1.8.8, and it worked. Closed it out and it prompted to update again. I did so and it reupdated it to 1.8.8 breaking the app again. Uninstalled reinstalled updated to 1.8.8 and worked. Closed numerous times and hasn't asked to update again. Only thing that consistently glitches now is no matter what I have to press the login button let destiny homepage load up with me logged in and then close it and hit the login again for it to show I am logged in.

**Comment by equesaspe** [comment]
Above is new to 1.8.8 for me.

**Comment by dasilva333** [comment]
I'm not sure that sounds really strange, I'll leave this ticket open until I can verify it's working on my Windows Phone when I get home. Thanks for the input

**Comment by equesaspe** [comment]
Btw. It just prompted me again to update. I didn't and I am sitting at 1.8.8.

**Comment by tylerphlosion** [comment]
I'm having the same problem here on windows phone as well.

**Comment by dasilva333** [comment]
I can confirm I too am having problems not loading on Windows Phone expect the fix in 1.8.9 thanks guys. Also @tylerphlosion  and @equesaspe  feel free to report any WP issues here on Github as I'm not always available to test it on Windows Phone right away.
Thanks

**Comment by equesaspe** [comment]
NP.  Just glad to help.

**Comment by dasilva333** [comment]
I wasn't able to reproduce the problem past one time it was stuck, seems to be working fine now. I'll leave this ticket open until you guys can confirm its loading fine in 1.8.9 (no changes made). Thanks

**Comment by tylerphlosion** [comment]
I had to reinstall it. It seems to be working fine after that though.l

-----Original Message-----

**Comment by equesaspe** [comment]
Yes me also. Thank you.
