### ISSUE TITLE
Missing Strange Coins

### ISSUE THREAD

**Issue by itzchoopa** [dasilva333/TowerGhostForDestiny#430]
I had a total of about 95 strange coins between my hunter and warlock and chose the option to consolidate all to vault and only 45 showed up and both characters didn't not have any strange coins after that. Need assistance with verification please thanks

**Comment by dasilva333** [comment]
There's absolutely nothing I can do in verifying anything for you, the best I can do is point you to my FAQ on losing items here:

http://towerghostfordestiny.com/index.php/faq/

Good luck
