### ISSUE TITLE
Loadouts not moving Kingslayer Shell

### ISSUE THREAD

**Issue by lightmaster** [dasilva333/TowerGhostForDestiny#431]
Any loadouts with a Kingslayer ghost will make that shell as not to be moved or equipped. Manually clicking on the same shell and then hitting move or equip works fine tho.

**Comment by Bazzu85** [comment]
Even if you use the Max light option the shell is not transfered..

**Comment by Bazzu85** [comment]
I don't know if its correlated by when you choose Max Light, the pop-up appearing with Max light avaible report a wrong value..

**Comment by lightmaster** [comment]
I made a separate issue report about the max light level button, as I'm having the same issue

**Comment by lightmaster** [comment]
Also, I'd like to say that it's not moving/equipping any ghost shell between characters, not just refusing the Kingslayer shell

**Comment by RandyKopf** [comment]
Really hoping this get's fixed PDQ. It is the only thing keeping my experience optimal. Wanting to transfer max light includes my Kingslayer shell.

**Comment by dasilva333** [comment]
fixed as of 3.4.6 please confirm thanks

**Comment by lightmaster** [comment]
Waiting for 3.4.6 to show up in the Play Store, then I'll report back on all these bugs that should be fixed.

**Comment by lightmaster** [comment]
This is now working fine
