### ISSUE TITLE
Sleeper Simulant

### ISSUE THREAD

**Issue by DogBeatr** [dasilva333/TowerGhostForDestiny#432]
Bungie updated the app for sleeper simulant. You should be able to update the manifest now for tower ghost. :). Not sure if the tower ghost web add on version has sleeper working, I only use the iOS version.

**Comment by dasilva333** [comment]
Problem is fixed as of 3.7.8 pending store approval thanks

**Comment by DogBeatr** [comment]
Thanks!  Love your app!!!
