### ISSUE TITLE
Fast scrolling switches view mode Android 3.4.4 only

### ISSUE THREAD

**Issue by lightmaster** [dasilva333/TowerGhostForDestiny#433]
If I try to scroll at anything more than a very slow speed, it pops up a blue notification that says it changed view mode, typically to weapons mode or general mode. Seems to do it more often while the icons are still loading, bit still does it at a rate that makes the app very frustrating to use and almost unusable. Happens on both my Note 4 and my wife's S5. Also, it seems to happen more frequently when swiping on the middle of the screen than the sides. If it makes any difference, we both have the view options set to 2 columns for portrait mode (the first view option we changed from 1 to 2).

**Comment by dasilva333** [comment]
Bug introduced in 3.4.4 for Android only

**Comment by mistral13** [comment]
same problem with ios Version 3.4.4

**Comment by lightmaster** [comment]
Reverting to the previous gestures library has temporary fixed this issue for Android.

Also, until this I had no idea TGfD had gestures, and for the life of me I can't seem to find any settings for them or explanation for how to activate them.

**Comment by dasilva333** [comment]
@lightmaster try checking under Help, that's where you can find all the explanations for how to activate them
@mistral13 3.4.4 does not exist for IOS officially. If you're on 3.4.4 for iOS you should switch to the Store version at 3.3.7 and stop using the debug version of the Hydra IPA

Thanks guys
