### ISSUE TITLE
View options have a wrong text string in it.

### ISSUE THREAD

**Issue by lightmaster** [dasilva333/TowerGhostForDestiny#434]
Under View -> View Options, it says Vault Position above both the column options and vault position option. Also, I think this screen could use a description and bit of a redesign to make it more obvious what the column options are and do.

**Comment by dasilva333** [comment]
Thanks for the heads up, surprised no one noticed this before. I'll get it fixed in 3.4.5

**Comment by dasilva333** [comment]
fixed as of 3.4.6 please confirm thanks
