### ISSUE TITLE
Not showing some weapons when language is german

### ISSUE THREAD

**Issue by Korben85** [dasilva333/TowerGhostForDestiny#437]
Hi,
My problem is that I can not see some of my exotics in the extension. For example Sleeper Simulant, Touch of Malice and Black Spindle. When I switch to the english version they are shown, but not when I switch back to german.

I already tried to uninstall, reinstall, clear browser cookies, cache etc.

I use Chrome 64x v47 on a win 7 64x pc.

Cheers

**Comment by dasilva333** [comment]
Fixing this required me to update the remote files, please try it again by reinstalling again, setting the language to German and verify it is still available. Thanks!

**Comment by Korben85** [comment]
Hi,
the problem still persists. 
Reinstalled the extension and switched to german, weapons are not shwon.

**Comment by dasilva333** [comment]
@Korben85 try it again, didn't test it previously. I found a new bug on the server side of things it was still serving the old files. It should work now however there is another bug I found where setting the language doesn't download the language pack properly. So try getting it to work again and expect the language change tool to work better in 3.4.6. Thanks

**Comment by Korben85** [comment]
Yes, that worked.
Many thanks for this very quick support.
