### ISSUE TITLE
Remembering view state

### ISSUE THREAD

**Issue by Mulchman** [dasilva333/TowerGhostForDestiny#44]
Is it possible for the view state to be maintained between usages?

Example:
* open Chrome version
* make it so only weapons are showing
* close Chrome tab (but not Chrome process)
* open Chrome version
* everything is once again showing. Here's where I'd want it to just be displaying weapons due to previously filtering down to just weapons.

**Comment by dasilva333** [comment]
Marking as enhancement I'll take care of this one later thanks for the feedback

**Comment by Mulchman** [comment]
Thanks.

**Comment by dasilva333** [comment]
Alright I got it to remember the state of the following fields now: activeView, dorefresh, tooltipsenabled, refreshseconds, tierfilter

I can add the rest pretty easily now but I'm not sure if some are relevant like progressFilter dmgFilter typeFilter and setFilter

Expect the fix in the next version

**Comment by dasilva333** [comment]
@Mulchman hey let me know if it's remembering all the view states so we can get this ticket closed. Thanks man

**Comment by Mulchman** [comment]
It's remembering the view states I've tested; thanks!
