### ISSUE TITLE
Moving items to vault result in larger than expected item

### ISSUE THREAD

**Issue by rkingsla** [dasilva333/TowerGhostForDestiny#440]
When moving items to the vault, or in transition to another toon, the item becomes ~ 100% larger than other items in the vault.  Often times, moving back to a character results in an icon about %50 smaller.  Refresh resolves all. 

Problem with my settings / config?

Pictures better than words.  (Did not notice this earlier...  My bad!)

http://screencast.com/t/YrjuCtt3zU

**Comment by dasilva333** [comment]
not really in the public branch yet, already fixed before release. let me know if you can confirm the problem is fixed. thanks
