### ISSUE TITLE
[Suggestion] Use placeholders for items not in db

### ISSUE THREAD

**Issue by slansing97** [dasilva333/TowerGhostForDestiny#441]
With newly uncovered items (Black Spindle, Sleeper Simulant, No Time to Explain), I'd like to see the placeholder icon back in the app.  Although you're not able to move the item with any API, TGfD currently fails to transfer items because it believes there is one less item in the character's inventory.

I feel like this placeholder was working correctly before but was removed at some point.  Not sure if this  is a complex change as you'd want the item to be unselectable, etc - but with the new KF hard raid coming out and possible additional hidden items, users may see failing transfers more often.

**Comment by dasilva333** [comment]
@slansing97 this was fixed as of 3.4.7+ please confirm thanks
