### ISSUE TITLE
When equipping max light, artifacts for other classes are being selected

### ISSUE THREAD

**Issue by smgoller** [dasilva333/TowerGhostForDestiny#442]
I have one of each class. I chose to equip max light on my hunter, and it selected a warp fragment (warlock class item) and moved it to my hunter.

**Comment by Bazzu85** [comment]
I confirm the issue

**Comment by lightmaster** [comment]
I can confirm this on Android too

**Comment by dasilva333** [comment]
ill be researching and getting this fixed, thanks guys

**Comment by dasilva333** [comment]
This has been fixed as of 3.4.7please confirm thanks
