### ISSUE TITLE
Scout Rifle missing from Weapons view selection

### ISSUE THREAD

**Issue by apfcclyde** [dasilva333/TowerGhostForDestiny#445]
As of latest update the above.

**Comment by dasilva333** [comment]
Could you share with me the share url w friends link so I can debug it? Thanks

**Comment by dasilva333** [comment]
@apfcclyde let me know thanks

**Comment by apfcclyde** [comment]
https://towerghostfordestiny.com/share/?xbl/WormHole911

   I also noticed that the Firefox version is  3.3.6 while the Chrome 
version is 3.4.6.

   Is the Firefox version no longer maintained as it's missing the 
Weapons, Armor & General drop downs?

-- 
Clyde Tilley

**Comment by apfcclyde** [comment]
I just noticed that the share url loads version 3.2.2 instead 
of 3.4.6
-- 
Clyde Tilley

**Comment by dasilva333** [comment]
The firefox version is still maintained you can find the latest version 3.4.3 available in the same link you used to install it, it does not auto update.
https://addons.mozilla.org/en-us/firefox/addon/tower-ghost-for-destiny/

Are you having the problem with the Scout Rifle option not showing in Chrome 3.4.6 or only on the Share site? I noticed the share site indeed does not show all the options. Let me know thanks

**Comment by apfcclyde** [comment]
It doesn't show in Chrome (3.4.6) or Firefox (updated thank 
you)  (3.4.3).

-- 
Clyde Tilley

**Comment by apfcclyde** [comment]
Here is a pic of the Weapons drop down.




-- 
Clyde Tilley
DP Mgr
Arizona Premium Finance Co., Inc.
12406 N 32nd St, Suite 110
Phoenix, AZ 85032
Phone:  602-992-9898 x115
Fax: 602-992-9868
Web: http://www.arizonapremium.com

**Comment by dasilva333** [comment]
@apfcclyde the pictures are not being included with your message, try onpaste.com it's what I use to share screenshots easily

**Comment by apfcclyde** [comment]
How about the attachment?

-- 
Clyde Tilley

**Comment by dasilva333** [comment]
@apfcclyde nope

**Comment by apfcclyde** [comment]
http://i.imgur.com/t9Teoyq.jpg
-- 
Clyde Tilley

**Comment by dasilva333** [comment]
@apfcclyde can you confirm if it's still a problem in the latest version of TGD 3.5.x? Thanks

**Comment by apfcclyde** [comment]
Yep - works like a charm! Thx.

-- 
Clyde Tilley
DP Mgr
Arizona Premium Finance Co., Inc.
12406 N 32nd St, Suite 110
Phoenix, AZ 85032
Phone:  602-992-9898 x115
Fax: 602-992-9868
Web: http://www.arizonapremium.com
