### ISSUE TITLE
Lost ghost.."

### ISSUE THREAD

**Issue by Ricardowill** [dasilva333/TowerGhostForDestiny#446]
There was a issue when I attempted to transfer my 300+ def. ghost to my newly level 40 Titan. A light blue pop-up said my level was to low then it disappeared. So I looked in my vault like the norm and I was there either. Next thing I do is check the post master, but nothing. I know it's gone but it's a issue. Thank you,happy customer

**Comment by lightmaster** [comment]
One thing you can try is do a refresh from the settings and carefully search each characters Ghost bucket. TGfD uses APIs that aren't capable of deleting any items, even in the event of an error or glitch, so its gotta be in your inventory somewhere.

**Comment by dasilva333** [comment]
http://towerghostfordestiny.com/index.php/faq/ Please refer to "Help I lost my item" subject in the FAQ. Thanks
