### ISSUE TITLE
Incorrect icon placement for various character sections

### ISSUE THREAD

**Issue by bam3339** [dasilva333/TowerGhostForDestiny#447]
Starting with the 3.4.6 Chrome version, all character sections from "Boots" down to and including "Sub Classes" have the currently equipped item showing improperly:

![image](https://cloud.githubusercontent.com/assets/15319811/10723380/b2f62e9e-7b90-11e5-89a0-fd993443b500.png)

**Comment by dasilva333** [comment]
@bam3339 thanks for reporting this problem, can you provide me with your operating system, exact chrome version and resolution? Thanks

**Comment by bam3339** [comment]
This is also an issue on the android 3.4.6 version (on moto x 2nd gen w/Android 5.1).  The same sections have similar issue (with XS set to 1 or 2 in view options).

The chrome version is on windows 10 with resolution at 1920x1200.  I am currently at work so I will check the exact chrome version and reply when I get home.

**Comment by dasilva333** [comment]
3.4.7 released please confirm if the problem is still there thanks

**Comment by bam3339** [comment]
Yes, everything is displaying correctly in version 3.4.7 on both Windows and Android.  Thanks for the fix!
