### ISSUE TITLE
Suggestion: Native Windows Modern App

### ISSUE THREAD

**Issue by equesaspe** [dasilva333/TowerGhostForDestiny#45]
Suggestion to look into the future creating a native windows modern app.  With Windows 10 universal app support (1 App for Windows, Windows Phone, Xbox, etc.) this would be a good idea.  I figured I would suggest it here since I am not much of a redditor.

**Comment by Robinhuett** [comment]
This would be great and I will probably look into it (dont expect anything in the near time :/ ), but this would be a larger project since Universal Apps are written in C# or C++ and TowerGhost is mainly JavaScript.

**Comment by dasilva333** [comment]
Not true actually I found a template online I can use with the sdk to make a windows store app in JavaScript I'll post here later in case anyone wants to port it for me

**Comment by Robinhuett** [comment]
Oh cool. I didn't know that. And thanks for the link. I'll take a look when I'm home later.

**Comment by jayproulx** [comment]
@dasilva333 I could help here, have you considered using http://nwjs.io/ or http://appjs.com/?  It would be compatible with your existing architecture, as well as cross platform (so those of us on a Mac can benefit as well.)

**Comment by dasilva333** [comment]
@jayproulx that's a cool idea and it would work for all versions of Windows but I think it would require a lot of code adapting to make it work. Whereas cordova-cli offers a way to simply compile the existing project as a Windows 8 app but it's limited to that one platform see here:

https://github.com/apache/cordova-cli/

If you'd like to help as always follow this link:
https://github.com/dasilva333/TowerGhostForDestiny/issues/170

**Comment by dasilva333** [comment]
@jayproulx So I gave it a try today, worked really well I'm impressed by how easy it was to get working. It is now usable/testable if you checkout the master branch and run the project using launch.bat (or equivalent command for your operating system)

**Comment by jayproulx** [comment]
@dasilva333 Fantastic!  I’ll pull it and give it a shot.

**Comment by rkingsla** [comment]
I've been using it/testing it on Windows 10 for the past couple of days. Works well, trouble-free and finally a native Windows app that doesn't require Chrome (not that I'm complaining about Chrome...  But Edge is getting a lot of my attention. Of course, Microsoft has delayed the release of the Edge Extensions, killing off for now hopes of moving completely to Edge.  For now...  :(  )

**Comment by dasilva333** [comment]
Hey guys the standalone version has been successfully completed and compiled you can find the appropriate flavor for your machine here:

https://github.com/dasilva333/TowerGhostForDestiny/tree/div-movile-dist

They are labeled tgd-{platform}-{x32 or x64} it's as simple as downloading and launching the executable. Cheers
