### ISSUE TITLE
Headers on Firefox not working for character refresh, but do in Chrome

### ISSUE THREAD

**Issue by DMWill** [dasilva333/TowerGhostForDestiny#451]
For some reason a while ago, clicking on the character headers to refresh that entire character completely stopped working in Firefox.  Then the Vault refresh started to work again, so I thought it would just be a matter of time before the others started working again.  It's been at least a month and it still doesn't work like it does in Chrome, and I'm guessing on other platforms.  The video shows what I'm talking about if I'm not explaining it well enough.

[![Header Refreshing](http://i.imgur.com/7q8mKJz.png)](https://www.youtube.com/embed/V-IW8OG1PZ4 "Header Refreshing Not Working In FF")

**Comment by patchm00** [comment]
I get this too.  I use Chrome for my PS4 charactedrs and Firefox for Xbone and in Firefox not only does the refresh only work on the vault column (not on chars) but the "refresh" button does not refresh page correctly.  Only way to refresh page is with an F5 browser refresh

**Comment by dasilva333** [comment]
Header refresh fixed for Firefox as of 3.7.6.11, try it out and let me know if it's still an issue @DMWill thanks

**Comment by DMWill** [comment]
no issue.  seems to be working great now.  Thanks!
