### ISSUE TITLE
no time to explain is missing in android app

### ISSUE THREAD

**Issue by erker** [dasilva333/TowerGhostForDestiny#452]
in my version 3.4.7 (android 5.1.1) no time to explain is not shown at any char. Cleaning the cache did not help. in the current firefox-addon it is shown without problems.

thx

**Comment by dasilva333** [comment]
Yeah I haven't submit 3.4.8 sorry expect it this week

**Comment by tonyNOS** [comment]
What about the 32/64 Windows version? I think if someone turn on a pc to use towerghost,should use that, I think is faster than add-on for browser.

**Comment by erker** [comment]
In v3.4.7 64bit win the no time to explain (sometimes) is shown without icon and tooltip.

![20151104_tower ghost for destiny](https://cloud.githubusercontent.com/assets/14057841/10938936/43a48458-82fe-11e5-98b9-d6f67e4641c4.png)

**Comment by tonyNOS** [comment]
Wow,never happened to me, I'd settle for that as well.

**Comment by dasilva333** [comment]
Weapon available as of 3.5.0 please confirm thanks @erker

**Comment by erker** [comment]
yes, now it works, thx.
