### ISSUE TITLE
When equipping max light, some weapons selected are not highest light 

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#453]
Been seeing this pattern lately (a week or two?) where equipping max light will select my Telesto (296) over my 300 fusion, or my Thunderlord (290) over my Sword (295). I initially thought all was good since the calculations ended up at the same total light level, but last night I noticed that wasn't the case and selecting my blade over the Thunderlord moved me up one level higher.

Not sure what data to send you to support this, but I can definitely reproduce it.

**Comment by dasilva333** [comment]
Can you reproduce it every single time? What is the final light value when you let TGD do it vs when you do it? The Light button might not work properly if your inventory is not up to date and it's no in sync with the game. Also it's normal for it to pick a 296 exotic over a lesser exotic but it seems if you have higher level legendary gear in the same slot it should pick that nonetheless. 

Let me know the answer to my questions and also provide your Share URL with friends link from TGD so I can debug it. Thanks

**Comment by weborican** [comment]
Yes, every time... but, it changed from equipping the Telesto all the time, to equipping the Thunderlord now. I just looked and it seems there is a strange discrepancy in what TGD thinks is the light level of my swords...
![screen shot 2015-11-04 at 10 23 00 am](https://cloud.githubusercontent.com/assets/12019978/10944342/59e46d2a-82de-11e5-8c54-91aedcbfb5c0.png)

**Comment by weborican** [comment]
I just noticed that TGD displays my sword light lever correctly as long as the "Advanced Tooltips" option isn't enabled. The above screenshot is the incorrect light level value (look at the value shown on the icon) displayed with it enabled. Not sure if this has anything to do with this bug (enhancement?!), but it is worth noting.

**Comment by dasilva333** [comment]
Problem fixed in 3.5.2 thanks @weborican try it out and let me know to confirm

**Comment by weborican** [comment]
Fix confirmed. Legendary swords now show the correct light level with the "Advanced Tooltips" enabled.
