### ISSUE TITLE
Issues with consumable normalization when General in vault is full

### ISSUE THREAD

**Issue by moeyjar** [dasilva333/TowerGhostForDestiny#455]
I use TGD for a lot of great reasons, loadouts, moving quickly, etc, but I also love it for the fact it can normalize materials between my 3 characters, and the vault.

As of last night, this stopped working.  

![image](https://cloud.githubusercontent.com/assets/12259797/10974091/cbb58a5a-83b6-11e5-9c36-478c49153fe7.png)
 (I tried normalizing Weapon Parts and Motes, because they're out of sync)

The OCD in me is struggling.  I've tried on specific items, and the entire section, but normalization does not occur.  It will say complete in green in the upper section, however.  I've tried logging off and back on again.

**Comment by moeyjar** [comment]
I'm running 3.4.8 in Chrome, for what it's worth.

**Comment by moeyjar** [comment]
Ahh, I figured it out.  General was full in the vault.  I blame Halloween items.  In any case, it should error out and not show a success, when it can't move into the vault to normalize. (Still a bug :))

**Comment by dasilva333** [comment]
@moeyjar I think I fixed this as of 3.6.5.4 let me know if you still have issues in versions after that. Thanks for your feedback
