### ISSUE TITLE
Can't equip subclasses or add them to loadouts

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#456]
TGD 3.4.7 for iOS and 3.4.8 for Chrome will not let me equip a subclass - clicking on one displays "Error. This item cannot be transferred with the API.".

Also, if I'm looking at a loadout and click on a subclass to add it to the loadout, TGD displays "Warning: Currently unable to create loadouts with this item type."
These things used to work in TGD and they currently work with another item manager I have been using (I know, blasphemy...)

**Comment by dasilva333** [comment]
Thanks man I hadn't noticed that bug had creeped up, I'll get it fixed with 3.4.9 thanks

**Comment by dasilva333** [comment]
Problem fixed as of 3.5.0 @edmiller47 please confirm to let me know its good now

**Comment by edmiller47** [comment]
Fix confirmed!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Richard PinedoSent: Monday, November 9, 2015 12:19 PMTo: dasilva333/TowerGhostForDestinyReply To: dasilva333/TowerGhostForDestinyCc: edmiller47Subject: Re: [TowerGhostForDestiny] Can't equip subclasses or add them to loadouts (#456)Problem fixed as of 3.5.0 @edmiller47 please confirm to let me know its good now

—Reply to this email directly or view it on GitHub.

**Comment by edmiller47** [comment]
I can click on a subclass now and add it to a loadout but the loadout hangs during processing when there is a subclass included.

**Comment by dasilva333** [comment]
Thanks @edmiller47

**Comment by dasilva333** [comment]
Problem fixed as of 3.5.3.2
