### ISSUE TITLE
Columns no longer fitting on one page in landscape

### ISSUE THREAD

**Issue by burns11** [dasilva333/TowerGhostForDestiny#459]
One character is pushed beneath the vault leaving a character sized blank on the right side of screen.  Had the same issue a couple weeks ago on an update but was able to fix it in settings, the update on the 7th broke that again with no way to fix.

**Comment by dasilva333** [comment]
Can you provide screen shots demonstrating this problem? Thanks

**Comment by burns11** [comment]
![screenshot_2015-11-09-12-27-40](https://cloud.githubusercontent.com/assets/15721993/11041176/373b18c4-86de-11e5-84ee-b779f1eba450.png)
![screenshot_2015-11-09-12-28-00](https://cloud.githubusercontent.com/assets/15721993/11041179/3dbe90f4-86de-11e5-8f00-d9dbd5c49d7a.png)
![screenshot_2015-11-09-12-32-17](https://cloud.githubusercontent.com/assets/15721993/11041184/43c4c7c0-86de-11e5-992b-bea27a8ee895.png)

**Comment by dasilva333** [comment]
It seems you modified the default view settings, the number of columns should be xs:1, sm:2, md:3, lg:4. I do see that they're all set to 4 which should force it to fit 4 columns regardless of the view. Could you provide me with some specs for your device? Thank you

1. Provide me with the resolution of your display: eg: 1024x768px
2. Provide me with your pixel ratio, you may find it here: http://devicepixelratio.com/
3. Provide me w the make and model of your device.

Thanks man

**Comment by burns11** [comment]
1. 1920x1200
2. 2.0
3. LG Gtab 8.3

**Comment by dasilva333** [comment]
Problem fixed, except to see it working in 3.5.3 thanks
