### ISSUE TITLE
[Enhancement] Consider Enabling Filters Through Swipes for Mobile

### ISSUE THREAD

**Issue by chrisdudek** [dasilva333/TowerGhostForDestiny#46]
For later thought, have you considered using swipes (left to right, right to left) to filter your view? Currently you need to go to the hamburger button --> View --> xxxxx. It would be cool if we could filter view by (weapon/armor/misc) by swipes. I could see arguments for other filters (burn type, etc). But I think item type would probably be most preferred, but open for thoughts. 

The reason I bring this up is that using the hamburger icon is always going to lead to multiple "clicks". I'm always a fan of efficiency and quick gestures. The less we have to go into the main menu, the better.

You probably have other ideas for functionality once the app is in a more stable spot. But just wanted to toss this idea out there for consideration.

**Comment by dasilva333** [comment]
@chrisdudek Are you iOS jailbroken? If so try the latest version 2.2.0 it has this feature implemented and I must say I'm really enjoying this new change really improves the usability thanks for your feedback

**Comment by chrisdudek** [comment]
Hey man. I'm not but I'm on that UDID beta program. I tested it out and it's working pretty well. It looks like swiping goes from Weapons/Items/Armor. 

It does seem a little buggy though. When I swipe sometimes nothing happens, after a few attempts it works smoothly again, and then back to being unresponsive. It also seems like it is only a one-way swipe. Only right to left and not left to right. 

I think it's definitely a great start man. If it can get a bit more stable, allow you to swipe from left to right to go back, go from weapons --> armor --> materials, and then if you can hide the sections that aren't relevant, that would be amazing. 

On the last note, if I'm swiping to filter to weapons, it would be great to hide the section headers for Helmet, Gauntlets, Consumables, Materials, etc. 

But seriously impressed with how quick you pushed this out. I need to learn how to code.

**Comment by dasilva333** [comment]
Yeah I noticed when I swipe nothing happens, I think the swipe just has to be done really quickly but I'll narrow down the problem to make sure it's not a real bug. I didn't notice the direction was only working one way I'll test both again to make sure it's working properly. 

I don't understand the comment about hiding the sections that arent relevant. Can you elaborate on that one more time? Thanks

**Comment by chrisdudek** [comment]
ignore that last one, my bad. I see what's going on now that I'm really looking at it. I'm filtered to Armor but I don't have any in the vault. You're showing the relevant sections, I just don't have any in them. I think you're doing it correctly, no need for change.

![image](https://cloud.githubusercontent.com/assets/11835064/7401031/79348864-ee86-11e4-8447-5cb74ce55001.jpg)

**Comment by chrisdudek** [comment]
Also - i tested again and the swipes work in both directions. I don't think I was swiping fast enough before. Is there a way to easily remove filters after swiping? Maybe have the swipes go from:

All --> Weapons --> Armor --> Items --> All --> Weapons--> etc. 

So it's really just getting it more stable/consistent, clearing out filter by swipes, and then (if you agree) the filter order (weapons, armor, then items). 

Seriously impressed though.

**Comment by dasilva333** [comment]
@chrisdudek I tested 2.2.2 with the swipes on android/ios/windows-phone and I found problems with the implementation I'll be adding more enhancements to it. 

The original version you tried probably cycled the All view (All>Weapons>Armor>General) the latest version cycles just the items (Weapons>Armor>General) I too agree that All shouldn't be included in the swipes. 

The next bug I found was where you are in character 2 active (in the quick scroll view) and you swipe in WP/Android the position is lost and you end up somewhere else.

The last thing I would improve is the animation rather than having it look like I'm repositioning the vertical scroll it'd be nice If i could provide a left/right animation instead (no guarantees on this one).

Thanks for your feedback

**Comment by chrisdudek** [comment]
@dasilva333 I love where you're going with it. I agree on all of your points. 

My only question: how can I quickly get back to View All after I swipe to filter? Do I need to go back to the hamburger button? Or if I swipe Left to Right enough times will I get back to View All?

It's great we can now quickly filter, but I think being able to get quickly back to View All is also important.

Thanks man!

**Comment by dasilva333** [comment]
@chrisdudek Thanks for your feedback Chris. 
As you can see in the history I made a few tweaks after we spoke so it's more stable on windows-phone/android but I haven't brought back View All. just find it distracting to see weapons/armor/general and then all again which to the user looks like a repeat of weapons. I think I'll add a toast style notification on swipe to indicate what View you're on and then bring back the All option

**Comment by chrisdudek** [comment]
Sounds great. Look forward to seeing this in the future! Thanks for all of the work!

**Comment by chrisdudek** [comment]
Hey @dasilva333 just wanted to see if you feel good to close this out. For me, right to left is pretty reliable. Left to right is pretty hit or miss. But the notifications at the top are very welcomed; they look great.

**Comment by dasilva333** [comment]
Yeah let's close this out thanks for the reminder I say it's good to go and yeah I agree the swipes are hit or miss sometimes perhaps we can make that a separate ticket to investigate the Hammer js library and what tweaks we can apply to it. Thanks
