### ISSUE TITLE
Helmets being moved around unnecessarily

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#461]
Well, here is another weird and hard-to-explain issue I've been experiencing. I have noticed that when I select the Equip Gear with Highest Light some of my year-1 exotic helmets are shuffled around unnecessarily. I have space on both the vault and on all characters, but yet TGD moves the 4 exotic helmets from the vault and then back again. This happens even if no armor needs to be moved around for that character (it is already the highest light).

I can reproduce 100% of the time, but there are no errors on the Chrome console. What can I provide you in order to track this down?

PS> Just noticed that it also shuffles my one year-1 exotic gauntlet out and back into the vault

**Comment by dasilva333** [comment]
I'll try to see if I can reproduce it or debug the problem going on, I'll try using equip highest light with all my characters and see if there's any extra transfers that shouldn't happen. In the mean time you may install Tower Ghost manually (instructions here: http://towerghostfordestiny.com/index.php/support/) and then open the file in js/tgd/base.js and change localLogging from false to true. Once set you'll be able to reproduce the problem with that extension and see debug output log in the console which you can provide for me to figure this out.

Thanks for your help

**Comment by weborican** [comment]
I have been able to reproduce the problem, and it seems to stem form the following:

Chest spaceNeededInVault: 71
Chest spaceUsedInVault: 73

...even though the true space used in vault is 69. I have attached the log file generated after selecting Max Light for my Warlock.

[tgd-log.txt](https://github.com/dasilva333/TowerGhostForDestiny/files/35978/tgd-log.txt)

**Comment by dasilva333** [comment]
Thanks for the update, can you provide me with an updated Share URL of your inventory as well as a screenshot of your Vault. Would you happen to know why the counts seem to be off? You said it reports 73 used but you count 69 used. Could there be 4 festival of the lost helmets that are not being counted? Let me know thanks

**Comment by weborican** [comment]
Share URL updated:
https://towerghostfordestiny.com/share/?psn/weborican

I currently have 9 (I know!) festival of the lost helmets in my vault.

![screen shot 2015-11-16 at 5 33 41 pm](https://cloud.githubusercontent.com/assets/12019978/11198171/5860efc4-8c88-11e5-910c-b6d566caa949.png)

**Comment by weborican** [comment]
Whoa, I just counted 73! Here's the thing, it seems like Artifacts are grouped with the Armor bucket, rather than the General bucket!!!

![screen shot 2015-11-16 at 5 43 34 pm](https://cloud.githubusercontent.com/assets/12019978/11198321/997f4b8a-8c89-11e5-90cd-a6c0bc316b9e.png)

**Comment by weborican** [comment]
Confirmed. I moved 1 artifact out of the vault and repeated the test. It came back with:

spaceUsedInVault: 72

So, it is indeed counting artifacts (and possibly Ghosts from the looks of the screenshot above) as Armor.

**Comment by dasilva333** [comment]
Thanks for all the info expect it fixed with 3.5.7

**Comment by weborican** [comment]
Fix confirmed. I tested a few different scenarios and it seems to be working as expected. Thanks!
