### ISSUE TITLE
search causing crashing?

### ISSUE THREAD

**Issue by jerrycarlson** [dasilva333/TowerGhostForDestiny#462]
I'm using TGD 3.5.3.4 for Chrome, and TGD 3.5.5 for Firefox.  If I try to use the TGD search function in either browser, TGD appears to crash and go through its 'reboot' procedure every single time (needless to say, there end up being no search results because of the 'reboot').  I'm on Windows 10 and using the latest version of both browsers.

Nonetheless, TGD is and has been a fantastic piece of software.  Thanks so much!

**Comment by DMWill** [comment]
I can confirm this, beginning with 3.5.2  for Firefox.  I haven't tried it on Chrome however.  I noticed it the other day when trying to search for rockets with a certain perk, which I then tested it with other searches, all with the same result.  TGD appears to refresh, but not before briefly showing the filtered items.

**Comment by jzonne** [comment]
I can confirm as well, running 3.5.5 on FF 42. Not only are browsers affected by this "search" bug, but also the Android app. Does the exact same thing, you attempt a search and it refreshes to main item screen.

**Comment by weborican** [comment]
Ditto on Chrome for Mac.

**Comment by dasilva333** [comment]
Problem fixed on 3.5.6. Please confirm thanks

**Comment by jerrycarlson** [comment]
Sorry for the noob question, but how do i get 3.5.6 for chrome?  The chrome store only has 3.5.3.4.

**Comment by weborican** [comment]
Top-right gear icon, select Auto Update.

**Comment by jerrycarlson** [comment]
Awesome; thanks!
