### ISSUE TITLE
iOS App Broken by Destiny Update

### ISSUE THREAD

**Issue by drinkc0ke** [dasilva333/TowerGhostForDestiny#464]
I'm running iOS 9.0.1 on an iPhone 6S, using TGD 3.4.7 (currently the latest version on iOS).

Starting today (when Bungie released an update to Destiny), the app is basically broken. I have my vault listed first/left and it is all that will load, except for materials & consumables. None of the 3 characters' items appear, although there is a large empty box at the bottom with a white outline.

I tried different view options, and moving the vault from first/left to last/right or vice versa will load the characters' items, which do transfer successfully. However, the materials & consumables sections do not appear, just like the vault. In addition, refreshing has no effect on the items, whether it is a global refresh or category refresh.

Killing & restarting the app has the same repeatable effects every time. Although, I will note that when the vault is already listed last/right when the app is opened, the first 2 characters' items appear (except for materials & consumables), but the 3rd character & vault do not appear until I move the vault from first/left to last/right or vice versa.

Let me know if you need more info. Hopefully this is just a matter of using an old version of TGD, but since 3.4.7 is currently the latest on iOS, I figured I would report it. Thanks!

**Comment by dasilva333** [comment]
3.5.8 has been submitted to the app store. i also included an expedited review request hopefully the fixed version will come out soon. thanks for the info
