### ISSUE TITLE
TGD 3.4.7 for iOS completely broken

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#465]
Kudos once again for a great app that I use every day.

Since the Bungie update on 11/17/15, Tower Ghost on iOS will only display some of the items for one of my three characters. It displays weapons and gear, then Class Items shows an empty white box. Nothing else is shown - not the emblems for the other characters, or the vault. Uninstalling/reinstalling and logging out and back in did not correct this. The menus all seem to work, can look at loadouts, etc.

I'm assuming this is known/already fixed and will be available whenever Apple gets around to approving an update, as I was seeing the same behavior on the Chrome and Android versions yesterday, and these problems aren't present with the version 3.5.8 on both of those platforms. Just wanted to get this on record since the iOS version is where I spend most of my time as a user.

**Comment by dasilva333** [comment]
3.5.8 has been submitted to the app store. i also included an expedited review request hopefully the fixed version will come out soon. thanks for the info
