### ISSUE TITLE
All versions only display one character of three in account

### ISSUE THREAD

**Issue by abqwizard** [dasilva333/TowerGhostForDestiny#466]
After bungie patch on Tuesday November 17, 2015 all versions I have tried, Firefox, IOS, MacOS, and Chrome are only displaying the vault and the first character of the three on my account. I use the IOS app the most and it was great until this problem. It was showing the vault and all three characters on the account before that.

**Comment by dasilva333** [comment]
If you have Firefox please update to 3.5.8 using the Auto Updater, if you have iOS please wait until the Reviewers approve the new version, thank you

**Comment by abqwizard** [comment]
Okay Thanks!!! Great app, and thanks for you responsiveness.

**Comment by abqwizard** [comment]
So I was looking and can't fine 3.5.8, only 3.5.5 in the store. Guess I'll have to wait for both.
