### ISSUE TITLE
Tooltips not working in Firefox

### ISSUE THREAD

**Issue by DMWill** [dasilva333/TowerGhostForDestiny#468]
with the latest update (3.6.0.3), the tooltips are no longer functioning in Firefox.  i'd like to see if anyone else can confirm this.  i'm running FF 42.0

**Comment by dasilva333** [comment]
Seems to be working fine for me, try a reinstall and see if that fixes it. Let me know. Good luck

**Comment by DMWill** [comment]
all good!  had to completely remove all traces.  but a reinstall restored the tooltip function.  not sure why it stopped working, but i'm happy it's working now :smile:

**Comment by DMWill** [comment]
Now when it auto-updates, the tooltips no longer work again.

**Comment by dasilva333** [comment]
Good point sir, I'm able to reproduce the problem it's just like you said with updates off the tooltips work fine, with updates on the tooltips stop working. I'll get it fixed. thanks

**Comment by DMWill** [comment]
The latest auto-update which included 3.6.1.3 seems to have fixed the issue with the tooltips not working when the auto-update feature is on.  Closing this out, again :wink:
