### ISSUE TITLE
Order by Light Level

### ISSUE THREAD

**Issue by depraved22** [dasilva333/TowerGhostForDestiny#469]
Can  you add in a sort on light level? That makes it much easier to find items if it's sorted.

Thanks.

**Comment by rkingsla** [comment]
What browser / device?  Looking at Chrome (3.6.0.6) under View - Sort by Light Level?  Or am I thinking something completely the wrong thing?

**Comment by depraved22** [comment]
Cough. User error. Thanks sorry. I completely missed that view tab. I just started using it. Closing out.

**Comment by rkingsla** [comment]
No worries....  That's why we're here!  :O)
