### ISSUE TITLE
Doesn't load characters still in FF42

### ISSUE THREAD

**Issue by sdholden** [dasilva333/TowerGhostForDestiny#470]
Same problem has returned that I had before.  All works fine in chrome, but never loads in FF.  New tab opens, it triggers a new window that just sits empty.  Close window, close tab, then says "loading" but never updates.
Have removed noscript and adblock, using ublock_origin on both FF and chrome now.  Not sure what/why?

**Comment by dasilva333** [comment]
I noticed the same problem too sometimes, first off make sure you're running at least 3.5.8 and above then under Settings, go ahead and disable Auto Updates and enable it again to make sure you're on the latest version 3.6.1.1. If it still doesn't work try logging out and applying the auto update and then logging back in. Let me know if that works for you. Thanks

**Comment by sdholden** [comment]
Spoke too soon.  Was on chrome when 3.6.1.1 updated.  FF says it's downloading and installing updates, but it's stuck at 3.6.0.3 even after re-trying, turning updates off/on.Did you mean i need to log out of windows between?  Will try that anyway...
 Stephen Holden
Ontario, Canada

**Comment by sdholden** [comment]
Logged out of FF and even my account on windows.  Still stuck at 3.6.0.3Removed the add-in from FF and re-started FF.  RE-installed V3.6.0 from the site and it's stll doing the same.  Stuck at 3.6.0.3 and keeps saying it's downloading and installing upgrades, but no change.
 Stephen Holden
Ontario, Canada

**Comment by sdholden** [comment]
Left the tab open for a minute while I made a donation thru paypal - and it updated to 3.6.1.2...Still doesn't load my characters.  
The new window that should show my microsoft login page is blank once the new windows opens.  

Under chrome, the new page shows MS login page with entry boxes, but FF doesn't.  Just shows "if this page doesn't auto close, click to close window"
 Stephen Holden
Ontario, Canada

**Comment by sdholden** [comment]
Copied URL in new window that Chrome uses - it's not the same as FF plugin (at least not displayed same) on two of my PC's at home. 

Chrome opens "https://www.bungie.net/en/Profile/254/10231213" (actual URL has bunch of hex characters at the end and is longer than this, but flashes too fast to capture before it switches to what I pasted above..."
FF uses "https://www.bungie.net/en/User/SignIn/Xuid" and never actually log in...just sits there blank.
both PC's did finally load up 3.6.1.6 in FF.  Chrome was 3.6.0.3 still... Stephen Holden
Ontario, Canada

**Comment by dasilva333** [comment]
Are you still having problems? You installed 3.6.0 and updated to 3.6.1.7? Let me know how that goes. Thanks

**Comment by sdholden** [comment]
Today it updated to 3.6.3 (just a few minutes ago), which said to disable updates, then re-enable them as part of the improvement for updates.  When I did that it reverted to 3.6.0.3?I'll leave it open and running for 10 minutes to see if it updates back up to 3.6.1.7 or 3.6.3
 Stephen Holden
Ontario, Canada

**Comment by sdholden** [comment]
It re-updated to 3.6.3, but it's still doing the exact same thing.  Brings up new tab, then opens separate window that should login to Bungie, but stays blanks.
 Stephen Holden
Ontario, Canada

**Comment by dasilva333** [comment]
Try installing 3.6.3 directly from the Firefox store let's see if that fixes it. Thanks

**Comment by sdholden** [comment]
No difference.  Even if I open a tab to bungie and login first, then open TGD (usually worked) it goes through all the motions but never displays anything other than the top bar of TGD and the two logins selections.  It says it loading the account from bungie with the green bar and all, but never does.  The other tab and new window are exactly the same as before as well.Confirmed latest chrome version works fine, as does the android version.
 Stephen Holden
Ontario, Canada

**Comment by dasilva333** [comment]
@sdholden Sorry I wasn't clear I mean try installing 3.6.3 directly from the Mozilla store (this link: https://addons.mozilla.org/En-us/firefox/addon/tower-ghost-for-destiny/) right now it says 3.6.0 but I'm uploading 3.6.3 hopefully that'll fix it. Good luck let me know

**Comment by sdholden** [comment]
Yup, that'sounds what I did.  Think it was still 3.6.0.3 when I did it.  Will repeat today just to be sure it's the latest 3.6.3 from there.


Sent from my Samsung Galaxy Tab®4

-------- Original message --------

**Comment by sdholden** [comment]
Deleted the add-on.  Re-started FF.  Loaded 3.6.5 from the link.  TGD says it's V3.6.3, so web site doesn't match, by the way.  Same thing.  Tab created, new window that never completes login, just says click here to close window.  
Do that, close tab, TGD says retrieving info and then nothing.
 Stephen Holden
Ontario, Canada

**Comment by sdholden** [comment]
Oh, so I turned off auto updates and the others (pas height, etc) and it 'reverts' to V3.6.5.  I guess the update actually installs 3.6.3 over 3.6.5.In any case, 3.6.5 still the same.
 Stephen Holden
Ontario, Canada

**Comment by dasilva333** [comment]
@sdholden thanks so 3.6.5 is still problematic, I'll do some debugging on my end and try to figure out the issue. Thanks for the feedback

**Comment by sdholden** [comment]
No worries.  I can fall back to firing up chrome now and then until there's a breakthrough!


Sent from my Samsung Galaxy Tab®4

-------- Original message --------

**Comment by dasilva333** [comment]
@sdholden thanks for the update yesterday I'm pretty sure I found the bug as of 3.7.6.6 try it out and let me know if it's fixed for you to recap the process should be:
sign in prompt > pop up window > close window > firefox loading arsenal > loads items (this is the part where it used to not load sometimes)

**Comment by sdholden** [comment]
Found a solution yesterday to the problem with FF, at least V43/44 onwards.  When the new window opens to Bungie, right clicked and opened 'view page info'.  Went to permissions tab and specifically enabled 'install add-ons' and 'open popup windows' instead of defaults (which is disabled).voila, works again.I assume at some point Mozilla made a tweak that changed something, since it would work sometimes before with the defaults.
Thanks!
 Stephen Holden
Ontario, Canada 

    On Tuesday, January 5, 2016 11:12 AM, Richard Pinedo <notifications@github.com> wrote:
 
 

 @sdholden thanks for the update yesterday I'm pretty sure I found the bug as of 3.7.6.6 try it out and let me know if it's fixed for you to recap the process should be:
sign in prompt > pop up window > close window > firefox loading arsenal > loads items (this is the part where it used to not load sometimes)—

**Comment by dasilva333** [comment]
@sdholden I've no clue what that means, would you mind using www.onpaste.com and posting a few screenshots of the process you went through to make it work? I wouldn't mind taking that info and putting it on my site for a FAQ or fixing it if there's something I can do to help it.

Please provide a more detailed explanation so I can further research this issue.
Thanks a lot! :)

**Comment by sdholden** [comment]
Attached screen shots.
1) Click login to xbox.  New window opens to "www.bungie.net....."  (2016-02-03.png)2) right click in new window and select "view page info". (also shown in 2016-02-03.png)3) New dialog opens, starts on 'General' tab (2016-02-03 (2).png)4) Select Permissions tab in the dialog (2016-02-03 (3).png)5) Ensure "Install Add-ons" is set to "Allow" (2016-02-03 (4).png)6) Ensure "Open Pop-up Windows" is set to "Allow" (also shown in 2016-02-03 (4).png)7) Close the dialog and now TGD should work again!
Tried this on 3 machines and all now work fine in FF44. Stephen Holden
Ontario, Canada 

    On Wednesday, February 3, 2016 4:00 PM, Richard Pinedo <notifications@github.com> wrote:
 
 

 @sdholden I've no clue what that means, would you mind using www.onpaste.com and posting a few screenshots of the process you went through to make it work? I wouldn't mind taking that info and putting it on my site for a FAQ or fixing it if there's something I can do to help it.Please provide a more detailed explanation so I can further research this issue.
Thanks a lot! :)—

**Comment by dasilva333** [comment]
@sdholden sorry man there's no attached screenshots available, not sure but I don't see the links to any images available. thanks!

**Comment by dasilva333** [comment]
FAQ added here: http://towerghostfordestiny.com/index.php/hrf_faq/help-i-cant-seem-to-login-to-tgd-with-firefox/
Let me know if you still have any issues @sdholden thanks
