### ISSUE TITLE
3.6.1.6 - Can't select any item in any guardian.

### ISSUE THREAD

**Issue by tmalfor** [dasilva333/TowerGhostForDestiny#472]
App is now completely broken on Android.

**Comment by dasilva333** [comment]
try to disable and enable auto updates, it should say 3.6.1.7 in the top left. let me know thanks

**Comment by tmalfor** [comment]
It doesn't show version number in top left.  It shows TGD and then has icons for the vault and each of my three guardians in the top left.

I had to go to about to get the version number. Disabling auto refresh does not fix the problem. I still cannot click on any of the icons for any of my weapons or armor, consumables, etc

**Comment by tmalfor** [comment]
The application is acting like it doesn't recognize touch. Until you touch something like my hand cannon "imprecation".  Then it tells me that that item cannot be transferred via the API. Everything else that acts like I'm not even touching them

**Comment by dasilva333** [comment]
I'm updating the store with 3.6.3 try that, again try disabling auto updates and see if that fixes it, you could also try clearing the cache for the app using the Android settings. Good luck let me know

**Comment by tmalfor** [comment]
Okay, I will look for that update. Its not showing up in the Play Store yet. I know exactly what you arre talking about when it comes to clearing cache. I've done it before. I've been an IT for over 25 years so I'm pretty comfortable with troubleshooting technology

**Comment by tmalfor** [comment]
I don't know how I missed your instructions to disable auto updates and then reenable it. All I had done so far was disable it.  Once I re-enabled it things seem to work again

**Comment by dasilva333** [comment]
Yeah I think the store version might have been bad, the auto update fixed it and the new store version will fix it for all. thanks for the feedback @tmalfor
