### ISSUE TITLE
 Consumables update for Windows phone ?

### ISSUE THREAD

**Issue by GRAYHAM75** [dasilva333/TowerGhostForDestiny#474]
I cannot transfer consumables. Have noticed this was fixed with update 3.5.9 but can't find this update for windows phone. Usually updates automatically.
Great app by the way and so good its available on windows too. Thanks😊.

**Comment by dasilva333** [comment]
3.6.2 will be out by the end of the day hold tight and thanks for the heads up

**Comment by GRAYHAM75** [comment]
Updated to 3.6.3 automatically today and everything working fine. Great job.
