### ISSUE TITLE
Touch screen doesn't work - Android tablet

### ISSUE THREAD

**Issue by Slickwilli21** [dasilva333/TowerGhostForDestiny#476]
I can't move items in the tablet ap. i Can online. Double tapping and holding down to bring up info no longer works. I want to preface by saying it used to work...

Love the app though!

**Comment by dasilva333** [comment]
Make sure you install 3.6.3, if necessary clear your cache or uninstall and reinstall. Good luck and let me know if it's still an issue. Thanks

**Comment by Slickwilli21** [comment]
Thank you!!!  Working now. 

I had previously uninstalled and reinstalled and it didn't work.  This time I cleared my cache and it started working.  I also closed the window app, which happened to be open at the same time.  Could having the Windows app open and using the tablet have caused the issue?

**Comment by dasilva333** [comment]
I think the problem was on my end, unfortunately it seems clearing the cache is the only solution not even a reinstall seems to fix it. Thanks for the feedback
