### ISSUE TITLE
Put some space between equipped item and unequipped items

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#48]
I think it would make sense to put a little bit of space around the equipped item, to further separate it visually from the other items. Doesn't have to be a lot, maybe just half the space that sits between characters/vault right now.

**Comment by dasilva333** [comment]
Thanks for the feedback but I don't agree, making it it's own column is division enough to indicate it's equipped. I'm using the same layout Destiny uses to show a square of 9 on the left and the 1 equipped on the right. Thanks anyways

**Comment by wickles** [comment]
I agree that it should try to mirror the in-game inventory in some sense. With that in mind I urge you to reconsider. If you look closely in TDG, the equipped item is actually slightly closer to the third column than the 1-3rd columns are to each other. And if you look in-game, the equipped item is actually farther away from the other items than they are to each other (and larger, while I'm at it). The way it works now is contrary to good UX design.

**Comment by wickles** [comment]
I wrote another comment but it was mindless ranting. I'll just point out that in Destiny itself, the equipped item is actually farther from the unequipped items. 

There is also the related issue of vertical spacing. Currently there is none in TDG. If you are not opposed to adding some vertical spacing, maybe equal to the horizontal spacing, I'll make a separate issue for that.
