### ISSUE TITLE
Can't select items in android

### ISSUE THREAD

**Issue by burns11** [dasilva333/TowerGhostForDestiny#481]
I can tap everything else and it works, refresh, etc, but if I tap a weapon, armor, consumable, etc the dialog box to move stuff doesn't come up.  I can tap other stuff like refresh on individual sections, character name, light, just not individual items, so I can't move anything anywhere.  I can also tap stuff that can't be moved and it says immediately that this item can't be moved with the api, so it's not simply not registering touches.  

This only cropped up on latest update.

**Comment by tmalfor** [comment]
This happened to me on the previous update. The resolution was to unselect and reselect auto update.  Apply any updates from the App Store as well

**Comment by dasilva333** [comment]
@burns11 just like tmalfor said go ahead and do an uninstall and reinstall. if that doesn't work try clearing your app cache too. it was the result of a bad update sorry about that. good luck and let us know

**Comment by TheWalt2** [comment]
This was a big issue for me, and doing the auto update turn off / turn on fixed it. Had I not come to github.com, I would have thought the app was just flat broken, because it looked like I had the newest version from the google play store. Pushing a fix out to all of your users would be helpful.
