### ISSUE TITLE
Mega-dark Background

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#482]
Is it me, or did the background color on version 3.6.6.2 suddenly became very dark?

My eyes are complaining :-)

**Comment by dasilva333** [comment]
background hasn't changed, make sure you're up to date and not cached. try disabling/enabling auto updates if nessecary

**Comment by moeyjar** [comment]
Same here.  very dark background.

**Comment by weborican** [comment]
Here are two screenshots, one with auto-update OFF (older version) and with it ON (version 3).6.6.2
![screen shot 2015-12-04 at 11 17 21 am](https://cloud.githubusercontent.com/assets/12019978/11596099/bd181fb6-9a78-11e5-991b-705cdc42c49f.png)
![screen shot 2015-12-04 at 11 16 28 am](https://cloud.githubusercontent.com/assets/12019978/11596098/bd0eba66-9a78-11e5-9a4a-0a2fd5bc0693.png)

**Comment by dasilva333** [comment]
@weborican do you have the Chrome extension installed from the Chrome store or from Github? If you have the Chrome store version installed you're saying with Auto Updates off (stock install) the background works, however when you enable Auto Updates it goes from 3.0.6.1 to 3.6.6.2 and the background stops working. Is that correct? Thanks

**Comment by dasilva333** [comment]
problem fixed in 3.6.6.3 thanks @weborican
