### ISSUE TITLE
Transfers items when current loadout is sufficient and preferable

### ISSUE THREAD

**Issue by adamksib** [dasilva333/TowerGhostForDestiny#483]
When max light option is used, frequently another item is transferred when the current item is of equal value and preferable.

Example: 310 light ghost with INT/STR is transferred from hunter (gunslinger) to Titan, when the titan has a ghost with int/dis, which is preferable.  I then need to manually swap back the ghost.

**Comment by dasilva333** [comment]
I agree this is a good fix, I've been struck by this problem before. Thanks

**Comment by dasilva333** [comment]
Problem fixed as of 3.6.6.6 let me know if you still have issues. Thanks
