### ISSUE TITLE
Refer-a-Friend items aren't loading in 3.6.6.2/3.6.6.3

### ISSUE THREAD

**Issue by moeyjar** [dasilva333/TowerGhostForDestiny#484]
I noticed that the new swords for the Refer-a-Friend quest are showing up with a broken icon.  The shader and emblem are also missing.

See my hunter here - https://towerghostfordestiny.com/share/?xbl/Moeyjar

**Comment by moeyjar** [comment]
Okay, odd.  So I guess it's just my build, because the preview it looks fine.  Again, I'm in 3.6.6.2, and just updated to it today, after being stuck on 3.6.0 for quite some time (needed to update chrome to latest).  Is there a cache somewhere that we can reload?

**Comment by moeyjar** [comment]
I did notice if I hover over them, it won't load up in destinydb mode.  It seems to be pointing to this URL for the sword, but when I visit it, it's giving me a 404.

https://destinydb.com/items/3373414403

**Comment by moeyjar** [comment]
Yeah, I really think this is a destinydb issue, which leads me to wonder how you're getting the icons in the share page to load

**Comment by moeyjar** [comment]
Not a coder, but I figured it out, at least for the emblem.

https://towerghostfordestiny.com/share/data/common/destiny_content/icons/83267356f5cc4201cc8347c2bd82669c.jpg

Looks like you have your own copy of it, but the chrome app is looking to destinydb to load it.

**Comment by dasilva333** [comment]
Refer a friend stuff added as of 3.6.1.1, you might have had an old cached copy of the app. It should work properly in 3.6.6.2. If the tooltip doesn't show/work I can't control that it's upto DestinyDB to fix it. The icon I use and the tooltip they use are independent of each other. Let me know if you still have any issues. Thanks

**Comment by moeyjar** [comment]
Uninstalled the chrome plugin, reinstalled, updated again to 3.6.6.2.  Issue persists.  I still have a blank icon for any of the Refer-a-friend items, not talking about the pop-up from DestinyDB.  When I share the link for my items, they appear fine, just not in my chrome instance.  I think this needs further research (I'm happy to check anything you'd like)

**Comment by dasilva333** [comment]
The store version of the Chrome plugin is 3.6.0.3 so it doesn't have the Refer a friend stuff until 3.6.1.1. You're saying that even with TGD updated to 3.6.6.2 the icon doesn't show up in your inventory in Chrome but when you view your inventory via the Share URL it looks fine there?

Can you provide me the image path it's pointing the broken image to? Try pressing F12 in Chrome and open the console, let me know if you see any errors prop up and post them if you do. Thanks

**Comment by moeyjar** [comment]
Failed to load resource: net::ERR_FILE_NOT_FOUND
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/assets/gradient_green.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/db422812e94df2b7e3ca12528d9318ff.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/8e661a285539b217d61bad80f1a6b426.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/474a93f79d762882a8cbf976fa0d6885.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/83267356f5cc4201cc8347c2bd82669c.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/8e661a285539b217d61bad80f1a6b426.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/474a93f79d762882a8cbf976fa0d6885.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/db422812e94df2b7e3ca12528d9318ff.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/8e661a285539b217d61bad80f1a6b426.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/474a93f79d762882a8cbf976fa0d6885.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/db422812e94df2b7e3ca12528d9318ff.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/7fb4736c308e286fa2f6b5eddf711615.png Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/484da7a7639ede2fcf05381b84749e16.png Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/d6e74d86d8f50ae576ccb613da4074c5.png Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/2ac0743127a5a9d8e31f5a7bd3af9673.png Failed to load resource: net::ERR_FILE_NOT_FOUND
4filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/3.tower_ghos…:5182 Uncaught TypeError: tgd.imageErrorHandler(...) is not a function
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:105 crash reported Uncaught TypeError: tgd.imageErrorHandler(...) is not a function
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:106 ErrorEvent
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:105 crash reported Uncaught TypeError: tgd.imageErrorHandler(...) is not a function
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:106 ErrorEvent
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:105 crash reported Uncaught TypeError: tgd.imageErrorHandler(...) is not a function
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:106 ErrorEvent
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:105 crash reported Uncaught TypeError: tgd.imageErrorHandler(...) is not a function
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:106 ErrorEvent
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/8e661a285539b217d61bad80f1a6b426.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/474a93f79d762882a8cbf976fa0d6885.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/db422812e94df2b7e3ca12528d9318ff.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/8e661a285539b217d61bad80f1a6b426.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/474a93f79d762882a8cbf976fa0d6885.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/db422812e94df2b7e3ca12528d9318ff.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/7fb4736c308e286fa2f6b5eddf711615.png Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/484da7a7639ede2fcf05381b84749e16.png Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/d6e74d86d8f50ae576ccb613da4074c5.png Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/2ac0743127a5a9d8e31f5a7bd3af9673.png Failed to load resource: net::ERR_FILE_NOT_FOUND
4filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/3.tower_ghos…:5182 Uncaught TypeError: tgd.imageErrorHandler(...) is not a function
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:105 crash reported Uncaught TypeError: tgd.imageErrorHandler(...) is not a function
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:106 ErrorEvent
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:105 crash reported Uncaught TypeError: tgd.imageErrorHandler(...) is not a function
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:106 ErrorEventbubbles: falsecancelBubble: falsecancelable: truecolno: 56currentTarget: WindowdefaultPrevented: falseerror: TypeError: tgd.imageErrorHandler(...) is not a function
    at HTMLImageElement.<anonymous> (filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/3.tower_ghost.js:5182:56)
    at HTMLImageElement.m.event.dispatch (filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/1.libraries.js:3:8549)
    at HTMLImageElement.r.handle (filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/1.libraries.js:3:5252)eventPhase: 0filename: "filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/3.tower_ghost.js"isTrusted: trueisTrusted: truelineno: 5182message: "Uncaught TypeError: tgd.imageErrorHandler(...) is not a function"path: Array[1]returnValue: truesrcElement: Windowtarget: WindowtimeStamp: 1449254931196type: "error"__proto__: ErrorEvent
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:105 crash reported Uncaught TypeError: tgd.imageErrorHandler(...) is not a function
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:106 ErrorEvent
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:105 crash reported Uncaught TypeError: tgd.imageErrorHandler(...) is not a function
filesystem:chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/temporary/app/resources/4.extras.js:106 ErrorEvent

**Comment by moeyjar** [comment]
![image](https://cloud.githubusercontent.com/assets/12259797/11598101/4ce407be-9a96-11e5-9cbd-2ec95acab002.png)

**Comment by moeyjar** [comment]
One of those errors is around the gradient green missing, which is the same as what I'm seeing in issue #482

**Comment by dasilva333** [comment]
@moeyjar try updating to 3.6.6.3 to fix the bg, I'll keep investigating the issue thx for the logs

**Comment by moeyjar** [comment]
Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/db422812e94df2b7e3ca12528d9318ff.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/83267356f5cc4201cc8347c2bd82669c.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
3.6.6.3 debug from chrome. It did resolve the background image.

chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/8e661a285539b217d61bad80f1a6b426.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://gdjndlpockopgjbonnfdmkcmkcikjhge/www/data/common/destiny_content/icons/474a93f79d762882a8cbf976fa0d6885.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by moeyjar** [comment]
![image](https://cloud.githubusercontent.com/assets/12259797/11598464/6062328c-9a98-11e5-8708-57b90fd2edb1.png)

**Comment by dasilva333** [comment]
Thanks for the info @moeyjar I'm having a hard time debugging the problem bc I don't have any of the RAF items. Would you mind temporarily sharing your account with me so I can debug it faster? If not it's okay I'll probably figure it out some other way it'll just take longer to do so. Either way let me know, if you'd like to go ahead and send me the details you may email me at support@towerghostfordestiny.com

Thanks

**Comment by moeyjar** [comment]
I'm not keen on account sharing, but if you can tell me what you need from it, I can certainly provide debug or whatnot from bungie's api, etc.

**Comment by dasilva333** [comment]
Problem fixed as of 3.6.6.4 thanks anyhow

**Comment by moeyjar** [comment]
Nice work.  Yep, it's fixed for the shader, sword, and emblem.  Only outstanding is the top bar icon on my hunter still black.  But that's quite minor.

![image](https://cloud.githubusercontent.com/assets/12259797/11600708/f74b34a8-9aa4-11e5-9133-16fdc9f73c49.png)

I can get you another debug output if you'd like

**Comment by dasilva333** [comment]
@moeyjar try 3.6.6.5 that should take care of the hunter icon. let me know thanks

**Comment by moeyjar** [comment]
Icon is there now.  I don't think it will grab the rest of the image though. (like the Warlock and Titan)



reference

https://www.bungie.net/en/Armory/Detail?type=item&item=3580794342&itemname=Sign%20of%20the%20Infinite

![image](https://cloud.githubusercontent.com/assets/12259797/11601635/b7b0ac3c-9aaa-11e5-8a03-978e5bc26b07.png)

But now I think I'm just nit-picking. :)
