### ISSUE TITLE
tooltips don't work for iron banner ghost shells?

### ISSUE THREAD

**Issue by jerrycarlson** [dasilva333/TowerGhostForDestiny#485]
Tooltip showing information does not work for Iron Banner ghost shells (just shows "loading...." forever).  I don't know if IB ghost shells were available prior to the most recent IB because that's when I first got any IB ghost shells, but as far as I can tell the tooltips have never worked for the IB ghost shells.

I'm using the latest Chrome and Firefox browsers for Windows 10, and the latest TGD version for each.

**Comment by dasilva333** [comment]
I'm aware of the issue, nothing I can do to fix it. I contacted DestinyDB to see if they plan to resolve the problem however it seems they might be shutting down? I'm not sure so I'll have to keep asking. THanks for the feedback
