### ISSUE TITLE
Lack of test coverage

### ISSUE THREAD

**Issue by buzzedword** [dasilva333/TowerGhostForDestiny#486]
Where are the tests? Where's the code coverage report? This is a big enough community project that you really should be putting a framework against it. This last break was a big one, nerfing the use for the app on a large cross section of devices.

Add some Travis test running immediately, even if its failing builds, and throw a coveralls report in place to show where you need to add more coverage.

**Comment by dasilva333** [comment]
This is a one man project, sure there are people who contribute every now and then but nothing gets done unless you do it yourself and I frankly have enough time to maintain this free project as it is, feel free to help out if you'd like I'll  accept any PRs as I have in the past. Thanks for the feedback
