### ISSUE TITLE
Tooltips sometimes too large

### ISSUE THREAD

**Issue by nessus42** [dasilva333/TowerGhostForDestiny#487]
Sometimes the tooltip for an item is too large to display properly on my MacBook Air. I.e., the top of the tooltip gets cut off. Since the top of the tooltip is the part that identifies what the item is, this is particularly bad. It would be nice in such circumstances if the tooltip were scaled so that the entire tooltip is visible. If this is too difficult, then the tooltip should be move downward so it is the bottom of the tooltip that is cut off, rather than the top.

**Comment by mistral13** [comment]
Same problem with the portrait mode on a iPhone 6 when i use the Advanced Tooltips.

**Comment by dasilva333** [comment]
The option to disable advanced tooltips is there for low resolution displays where too much data won't allow it to fit properly in most situations. I'll leave this ticket open to investigate and see if I can change the snap functionality and see if it can be sized. Thanks guys

**Comment by mistral13** [comment]
@nessus42: Could you please try this CSS 

```
@media (max-width: 719px) {
 .fhtt {
    -webkit-transform: scale(0.8);
    -moz-transform: scale(0.8);
    -ms-transform: scale(0.8);
    -o-transform: scale(0.8);
    transform: scale(0.8);
 }
}
```

**Comment by nessus42** [comment]
@mistal13 I tried to use the Chrome developers tools to edit the .fhtt CSS on the running page for Tower Ghost, but I couldn't find the entry for .fhtt in the Styles tab. I've never used the Chrome developer tools before, though, so I'm probably doing something wrong. (I've used Firebug in the past to edit live CSS, but the most recent Firefox version doesn't have tooltips that are too large due to the tooltips there eliding important information, rather than scaling down the sizes.)

**Comment by mistral13** [comment]
@nessus42: Try to copy and paste this in the Console form your Chrome developer tools:
``` 
$(document.head).append('<style>@media (max-width: 719px), (max-height: 680px) { .fhtt { -webkit-transform: scale(0.8); -moz-transform: scale(0.8); -ms-transform: scale(0.8); -o-transform: scale(0.8); transform: scale(0.8); }}</sytle>');
```

Could someone else try this also.

Thanks

**Comment by nessus42** [comment]
@mistral13 Yes, that worked great. A few things still get their tops chopped off (e.g. Raze-Lighter), but the issue occurs 1/10th as often. And in the cases in which it still does occur, I can "fix" the issue by either making Chrome run full-screen, or removing the bookmarks bar.

**Comment by dasilva333** [comment]
Thanks for the good fix thanks @mistral13 Expect it in TGD as of 3.7.0.3

**Comment by nessus42** [comment]
Here are some screenshots showing the top of tooltips still being cut-off. Two are from Firefox (one fullscreen and one not) and one is from the Mac application. All of these were taken on a MacBook Air, which has a screen resolution of 1366 x 768.

![screen shot 2015-12-24 at 2 33 02 pm](https://cloud.githubusercontent.com/assets/1322928/11997520/0dff1aa0-aa4c-11e5-8cea-f8e953dcce96.png)
![screen shot 2015-12-24 at 2 33 59 pm](https://cloud.githubusercontent.com/assets/1322928/11997521/12ae4d82-aa4c-11e5-9907-818998b85950.png)
![screen shot 2015-12-24 at 2 34 54 pm](https://cloud.githubusercontent.com/assets/1322928/11997523/15fd7ea4-aa4c-11e5-8a5b-aa006886ec61.png)

**Comment by mistral13** [comment]
Hi
change the js to get the correct div size after CSS3 transformation.
change the breakpoint and scale factor in the css.

**Comment by dasilva333** [comment]
I like the latest implementation after the last set of Pulls you submitted, thanks again @mistral13
