### ISSUE TITLE
Exotic Special Weapon Engram not displaying in TGD 3.6.7.3

### ISSUE THREAD

**Issue by moeyjar** [dasilva333/TowerGhostForDestiny#488]
This one is a bit strange.  I've reloaded TGD on a few desktops to make sure it's not a caching issue.  Other engrams are displaying, but see the attached photo (from TGD and Bungie's app).

Context.  I ran Warpriest challenge mode last night and got an engram from my 3 of Coins.  It is not displaying in TGD.

![image](https://cloud.githubusercontent.com/assets/12259797/11663102/b0a962c2-9db0-11e5-8fcd-46cac88a403f.png)

Let me know if there's anything you need as far as debug.

**Comment by dasilva333** [comment]
@moeyjar can you provide me with the Share URL to your profile, that'll allow me to debug that issue easily. Thanks and please don't decrypt it until we figure this out.

**Comment by moeyjar** [comment]
Found it.  It's because I was filtered by Year 2 items.  The engram doesn't know what year it's from.    Not sure if the bungie API is smart enough for that.  Either that, or you just change it so Year 2 can also include Y1 engrams

**Comment by moeyjar** [comment]
But oddly enough, filtering by year 2 items, still shows other exotic engrams, just not the weapon ones.

![image](https://cloud.githubusercontent.com/assets/12259797/11665019/7958c6a4-9dbb-11e5-9151-b596fc00fb27.png)


So many engrams :)

**Comment by dasilva333** [comment]
Y1/Y2 filter is not supported for engrams and I don't plan to support it either it's created for actual items. Thanks for the feedback nontheless
