### ISSUE TITLE
Character information not displayed if SRL items have been acquired

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#489]
After today's (8 Dec 2015) Bungie update, I went to the tower and started up one of my characters with Sparrow Racing League, ran a couple of races and earned some gear. I logged into my second character but didn't do anything (Happy Horn appeared though). Didn't log on to my third character. 

When I opened Tower Ghost (tried on PC, iPad AND Android versions) after that, the information for characters 1 and 2 are completely blank and the information for the third one appears as normal.

On a side note, when I started up the Android app, it gave me a choice to update and restart the app, or to ignore for now. I chose to ignore the update for but the app updated itself anyway. I do have auto update selected in the settings.

**Comment by dasilva333** [comment]
Make sure you have version 3.6.8 and let me know if you still have any issues, thanks

**Comment by edmiller47** [comment]
How do I get 3.6.8?

**Comment by dasilva333** [comment]
Enable Auto Updates

**Comment by edmiller47** [comment]
I keep auto update turned on. ‎Update didn't come through until late last night. Issue resolved.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Richard PinedoSent: Tuesday, December 8, 2015 10:54 PMTo: dasilva333/TowerGhostForDestinyReply To: dasilva333/TowerGhostForDestinyCc: edmiller47Subject: Re: [TowerGhostForDestiny] Character information not displayed if SRL items have been acquired (#489)Enable Auto Updates

—Reply to this email directly or view it on GitHub.
