### ISSUE TITLE
Loadout not transferring. Can't select character to send it to

### ISSUE THREAD

**Issue by bloodydye** [dasilva333/TowerGhostForDestiny#49]
So whenever I try to send my normal lvl 32 loadout (http://imgur.com/FHY5ipk) it doesn't let me click on any character to send it to (note the entire loadout isn't on screen, more guns are inside it). 

But when I send my PvP loadout (http://imgur.com/jCFP2tp) it works. (Note all weapons/gear are visible on screen, unlike other "Normal 32" loadout)

**Comment by dasilva333** [comment]
Closing this ticket in favor of issue #31 please leave any feedback there thank you
