### ISSUE TITLE
TGD not working after latest Destiny update

### ISSUE THREAD

**Issue by bam3339** [dasilva333/TowerGhostForDestiny#490]
After logging in with a character and receiving the "Happy Horn" sparrow gear, that character will no longer load properly in TGD.  The only sections of the character that load are the "Lost Items" and "Quests", and the character will show as 0 light level.  This is on Chrome 47.0.2526.80 m (64-bit) using TGD version 3.6.7.0

**Comment by dasilva333** [comment]
Make sure Auto Updates is enabled and you are using v3.6.8 that should fix it for you. Thanks

**Comment by samfox92** [comment]
The update on my Google nexus 10 don't want to install (may incan send you some log file)
But on my s6 edge plus that work but only 3 columns, is it possible to get 4 like on 10" ?

**Comment by dasilva333** [comment]
@samfox92 not sure what you mean but basically you can check your version in the top right by clicking on TGD. if you're not on 3.6.8 it's not going to work properly. If you'd like to change the layout that can be found under View > View Options. Good luck
