### ISSUE TITLE
Guardians not loading

### ISSUE THREAD

**Issue by mecster09** [dasilva333/TowerGhostForDestiny#491]
See attached screenshot from my Sony Xperia Z3 Compact tablet, this also happens on 3 of my raid teams phones/tablets (not sure on devices I'm afraid). Only the guardian that I haven't accessed since the December patch (Tuesday 8th) loads and I can't interact with him. The other two guardians do not load at all and even after trying a clean install, clear cache and data, refresh it still doesn't work.

![screenshot_2015-12-09-10-24-56](https://cloud.githubusercontent.com/assets/10955614/11683121/c0170632-9e60-11e5-8501-71b7280a4e6d.png)

**Comment by dasilva333** [comment]
Problem fixed as of 3.6.8, enable Auto Updates in settings to fix it. thanks
