### ISSUE TITLE
Some character gear/inventory does not load (FF plugin version)

### ISSUE THREAD

**Issue by z929669** [dasilva333/TowerGhostForDestiny#494]
I have latest plugin for FireFox installed (3.6.5.0).

I am unable to see any items in most gear/inventory blocks for both my Titan and my Hunter. I cannot refresh any blocks for them either. Vault and Warlock inventory seem to be loading and refreshing properly though.

I have cleared FF cookies,cache, etc, but still same issue. It's as if the API is not functioning correctly on all chars. Android version works fine, it seems.

**Comment by dasilva333** [comment]
You need to have v3.6.8. installed for the latest SRL update to work. On Firefox Auto Updates is enabled by default so after installing 3.6.5 it should automatically update to 3.6.8. If not you can try to disable and enable the Auto Updates setting to download the latest patch.

**Comment by z929669** [comment]
FF auto plugin update or TG auto update?? 

The TG auto update is not working then, because I am stuck at 3.6.5.0. Could you point me to the latest so that I can invoke manually?

**Comment by z929669** [comment]
NM, it finally updated and all is well, thanks
