### ISSUE TITLE
Auto Refresh checkbox behaving erratically

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#495]
I have been noticing for the last few releases (sorry, can't remember since which one) that not only will the Auto Refresh checkbox uncheck itself at times, but it takes two tries before I can check it again.

At least that is what happens visually, but I'm assuming it is actually showing unchecked when it is really checked, thus the need to select it twice to make it show checked again. Clear as mud? :-)

PS. Once I have it checked, unchecking and checking works in a single try no matter how many times I do it.

**Comment by weborican** [comment]
I have confirmed it isn't a UI thing. Once it unchecks itself nothing will refresh automatically until I click on the checkbox twice turn Auto Refresh on.

**Comment by dasilva333** [comment]
I will definitely look into it, thanks for finding this bug

**Comment by weborican** [comment]
Tested with version 3.6.8.8 and all seems to be working properly now.
