### ISSUE TITLE
App not showing items on guardians

### ISSUE THREAD

**Issue by xd3adp00lx6918x** [dasilva333/TowerGhostForDestiny#496]
I can see everything I have in my vault but nothing but my quests show up on my characters. See attached photo.
![screenshot_2015-12-10-04-23-43](https://cloud.githubusercontent.com/assets/16238111/11711665/18275a44-9ef6-11e5-9fda-e0e4d3c33cf8.png)

**Comment by samfox92** [comment]
Check auto update in settings  that work for me on m'y Samsung s6 edge plus 
but not on my Google nexus 10...

**Comment by griffinmills** [comment]
Had the same issue and the auto update tip worked for me, thanks!
iPad mini2 ios 8.3

**Comment by tepain** [comment]
Not working on my iPhone 6s Plus or iPad still missing all items on each class.

**Comment by dasilva333** [comment]
@tepain make sure you're on 3.6.8 that should fix it for you

**Comment by tepain** [comment]
The only version available on the App Store is 3.6.1

**Comment by dasilva333** [comment]
@tepain as griffinmills and samfox said simply enable Auto Updates and that should update you to the latest version available, it can be found under Settings in the top right corner.

Thanks

**Comment by tepain** [comment]
Just replied on the app side, not too familiar with how this works. To respond to your reply however I checked my app version and the available version on the app store for apple and I’m only able to get the 3.6.1 version.

**Comment by dasilva333** [comment]
@tepain the base version found in the store can then be updated once the app is opened, on ios it auto updates by default. on android it has to be enabled manually. this is not a setting on android or ios it's a setting found directly in the app under Settings right next to drag and drop. Good luck

**Comment by tepain** [comment]
As shown in my file attached, I don’t have that option in my settings menu.

**Comment by tepain** [comment]
I found the setting for auto update, thank you for your time. Your app is awesome..
