### ISSUE TITLE
The update don't want to install on my Google Nexus 10

### ISSUE THREAD

**Issue by samfox92** [dasilva333/TowerGhostForDestiny#497]
![screenshot_2015-12-10-17-06-54](https://cloud.githubusercontent.com/assets/16235047/11720672/a15ab698-9f60-11e5-8a97-3e499afe6d83.png)

When I check auto update this message appear rapidly
And nothing download.
What can I do ?

**Comment by samfox92** [comment]
I am on this version
![screenshot_2015-12-10-17-12-42](https://cloud.githubusercontent.com/assets/16235047/11720816/4cb897c6-9f61-11e5-9b26-d530752d08e0.png)

**Comment by dasilva333** [comment]
Try to disable Auto Updates and enable it again, if you see that problem try to go into your Android Settings and clear App Cache or App Data, if problem persists after clearing cache/data then try to uninstall and reinstall and then enable auto updates. Good luck

**Comment by samfox92** [comment]
I ve all ready make all that and no update start
How can I send you log file or more information to resolve that.
Thanks

**Comment by samfox92** [comment]
Could you share the latest version in apk format ?
