### ISSUE TITLE
KF Armor Set

### ISSUE THREAD

**Issue by Bazzu85** [dasilva333/TowerGhostForDestiny#499]
Hi, when filtering with KF armor set many KF items doesn't shown (for ex. Hunter class item for hard mode)

**Comment by dasilva333** [comment]
@Bazzu85 Can you link me to that item? I'm not sure which one that is. Thanks

**Comment by Bazzu85** [comment]
I'm not at home now.
I tried with android app using the auto update function and with 3.6.9.2
version classified item isn't showed..

I write you when i return home..
Il 11/Dic/2015 03:34, "Richard Pinedo" <notifications@github.com> ha
scritto:
