### ISSUE TITLE
Unable to Use

### ISSUE THREAD

**Issue by SpartanSamuel** [dasilva333/TowerGhostForDestiny#5]
App doesn't load my profile. It opens, I can navigate the menus, but they don't do anything. All I see is http://i.imgur.com/Rv9aEMq.png. I was using 1.6.4 as that's the version on the Chrome extension store, but have since removed it and installed manually from the files on GitHub. Same results.

**Comment by dasilva333** [comment]
Try 1.6.7 and report back thanks

**Comment by SpartanSamuel** [comment]
I'm unfamiliar with GitHub's layout and can't find previous versions. Instead, I've installed 1.7.1 and it yields the same issue.

**Comment by dasilva333** [comment]
thank you for the update, could you please try the following and report back:

1. open the extension in chrome
2. press F12 key on your keyboard
3. visit the Console tab (last one on the top)
4. reload the extension by refreshing or F5
5. copy the output provided by the console and paste it here for debugging purposes

thanks!

**Comment by SpartanSamuel** [comment]
index.html:9 Resource interpreted as Script but transferred with MIME type text/plain: "chrome-extension://dmaboljeopgllmfldclonhhfjjbihjdm/www/data/itemDefs.json".
index.html:10 Resource interpreted as Script but transferred with MIME type text/plain: "chrome-extension://dmaboljeopgllmfldclonhhfjjbihjdm/www/data/statDefs.json".
index.html:11 Resource interpreted as Script but transferred with MIME type text/plain: "chrome-extension://dmaboljeopgllmfldclonhhfjjbihjdm/www/data/perkDefs.json".
index.html:12 Resource interpreted as Script but transferred with MIME type text/plain: "chrome-extension://dmaboljeopgllmfldclonhhfjjbihjdm/www/data/talentGridDefs.json".
index.html:13 Resource interpreted as Script but transferred with MIME type text/plain: "chrome-extension://dmaboljeopgllmfldclonhhfjjbihjdm/www/data/raceDefs.json".
index.html:27 GET chrome-extension://dmaboljeopgllmfldclonhhfjjbihjdm/www/cordova.js net::ERR_FILE_NOT_FOUND
app.js:987 loadData
app.js:794 Uncaught TypeError: Cannot read property 'characters' of undefinedapp.js:794 (anonymous function)bungie.js:180 search._request.completebungie.js:98 r.onload

**Comment by SpartanSamuel** [comment]
I've installed the newest version, 1.7.2. Problem resolved. I'm closing the issue now.
