### ISSUE TITLE
Classified Primary Weapon Item

### ISSUE THREAD

**Issue by Bazzu85** [dasilva333/TowerGhostForDestiny#500]
Hi,

here's what I have in tower ghost..

![screenshot 2015-12-11 08 07 34](https://cloud.githubusercontent.com/assets/7345587/11737967/c0ae8078-9fde-11e5-9c2f-e5f3b95e25b5.png)

here's from ps4..

![screenshot 2015-12-11 08 08 49](https://cloud.githubusercontent.com/assets/7345587/11737972/c9d5d412-9fde-11e5-9eda-0b368b55acd1.png)

The classified item from tower ghost is always taking a slot..and I can't move it..

**Comment by superskeetman** [comment]
i have the same problem

**Comment by Bazzu85** [comment]
here's destinydb link:
https://destinydb.com/items/3078564839

**Comment by dasilva333** [comment]
@Bazzu85 not sure what's going on there, is the link provided for the KF class item or for the item in your primary slot? Just so we're clear I see 8 guns in the game and 9 in TGD. So it's pretty much adding in a ghost item that you have no clue what it is? Pls provide me with a Share URL to your profile so I can debug what's going on. Thanks

**Comment by Bazzu85** [comment]
how does share url works?

**Comment by ghost74** [comment]
I have the same problems,the tower ghost shows me 2 classified items,one must be the hardlight and the other one is the dagonsbreath.Both weapons do not show up in the inventory.So i can't switch them to other characters.

**Comment by weborican** [comment]
The new exotics are not showing up, but they aren't showing up on bungie's website either. This is primarily a Bungie problem.

**Comment by Jaz54** [comment]
New exotics are showing as classified and are not transferable. I'm getting the same on bungie's website.

**Comment by Naivedo** [comment]
Bungie is working now, but Tower Ghost isn't. You can move the new exotics but they all show up as Primary even though some are not... which prevents moving if your primary area is full.

**Comment by Doubleken** [comment]
D.I.M & Bungie manager working now, but Tower Ghost still mark as classified with actual light

**Comment by dasilva333** [comment]
Tower Ghost automatically sets an unknown Classified item as a Primary until it is updated with the latest Bungie update. The update has been made live as of 3.7.0 so all this should be cleared up now. Thanks guys
