### ISSUE TITLE
Moving more than 1 item at a time

### ISSUE THREAD

**Issue by ColdAsHeaven** [dasilva333/TowerGhostForDestiny#501]
This is something I don't understand why it hasn't been implemented yet. Similar to Little Light, let us move more than 1 item at a time to other characters.

**Comment by dasilva333** [comment]
Please read the Help documentation and try to fully understand the app prior to opening up a new ticket. Just in case you missed it reads the topics "Transfer Methods Available" and "Transferring Items"
