### ISSUE TITLE
Vault works but Gardians don't since last update

### ISSUE THREAD

**Issue by MasterBry** [dasilva333/TowerGhostForDestiny#502]
Since the update this week my Tower Ghost has stopped displaying anything for my Gardians, I can only see whats in the Vault - I only use iPad, which normally works fantastic for this fantastic app... Is there an update coming soon ?

**Comment by Toyroom** [comment]
Same here.

**Comment by EduardosRage** [comment]
Same problem on my iPad. I really miss this awesome program working well. Thanks.
