### ISSUE TITLE
Titan and Hunter details disappeared.

### ISSUE THREAD

**Issue by Toyroom** [dasilva333/TowerGhostForDestiny#503]
Hi

In the last two days I first lost all details of my Titan (the character I had been playing) and then after switching characters to my Hunter, it's details as well.  I can still see everything in my Vault and on my Warlock.  I have tried uninstalling and reinstalling it on my iPad but no joy.  Just tried it on my windows phone and it works perfectly on that.

Regards, Toyroom.

**Comment by MasterBry** [comment]
I just posted the same thing seconds ago, hahaha, glad its not just me

**Comment by ghost74** [comment]
Did you try the auto update allready on the app.It worked for me.

**Comment by MasterBry** [comment]
![image](https://cloud.githubusercontent.com/assets/16263028/11763545/3eb607fc-a174-11e5-9c66-81b3f3347bd0.png)

I did, but this is all i see, display vault, but nothing for Gardians.
I have deleted and reinstalled several times.

**Comment by MasterBry** [comment]
Well i did turn on auto refresh, and auto update and at first it didnt seem to work, but after a couple of minutes ( while typing this reply) it auto refreshed or auto updated, and all came back, so thanks for that "ghost74" I am working again !! 😎

**Comment by Toyroom** [comment]
Yay!  It works.  Thank you, I missed my TGFD 😃😃😃

**Comment by ghost74** [comment]
No thanks masterbry and Toyroom,glad that i could help you guys out
