### ISSUE TITLE
Refresh Issue

### ISSUE THREAD

**Issue by TheSecretSauce** [dasilva333/TowerGhostForDestiny#505]
The app version for Android seems to have an issue with manual refresh. Lately, when I refresh my inventory I see a never ending scroll of blue boxes telling me that each character has been refreshed. The boxes just keep appearing one after the other, and there is heavy memory usage when this takes place; I then have to kill the app and reload it as a temp fix. I have auto-updates enabled and I have already tried uninstalling and reinstalling the app.

**Comment by weborican** [comment]
I can't seem to reproduce that error on either of my Android devices. What device and/or version of Android are you on?

Have you tried turning OFF auto updates and then back on, or simply reinstalling the app?

**Comment by TheSecretSauce** [comment]
Samsung Note 3, Android 5.0

**Comment by TheSecretSauce** [comment]
And I have tried turning auto updates on and off as well as doing a complete uninstall and reinstall.   I have noticed that the past couple of days it sometimes will repeat the refresh text several times, but then stabilizes to the point where I don't have to force quit it.

**Comment by dasilva333** [comment]
@TheSecretSauce so you're saying on Android when you click the refresh button via the menu, or the refresh header for a character it causes an infinite refresh loop? Does it happen every time or sometimes? Let me know if you can still reproduce it as of 3.7.0.2 Thanks

**Comment by dasilva333** [comment]
No response from OP regarding the problem for 2 weeks, assuming it's been fixed, closing issue
