### ISSUE TITLE
Firefox Bugged?

### ISSUE THREAD

**Issue by Chase100488** [dasilva333/TowerGhostForDestiny#509]
I Can See The Headings For Each Of My Guardians But Not Everything Loads Up I Did The Turn Off Updates Thing And Back On And It Still Didn't Work So I Am Just Curious To Know If This Is Bugged Or If You Have Given Up On The Firefox Version Or If Someone Can Shed Some Light On This And Help Me Because I Love Using Tower Ghost It's So Much Easier So Can Someone PLEASE HELP!

**Comment by NotMeNoWay** [comment]
I am having the exact same issue. Is there a resolution yet?

**Comment by Chase100488** [comment]
not that i have seen yet thats what i'm waiting to hear about

**Comment by NotMeNoWay** [comment]
Same here. I googled the issue and found your question and went from there. I have the page open so I can watch to read if there is a fix soon.

**Comment by Chase100488** [comment]
yeah i figured someone would of said something but i guess either the issue does not matter or something else even though i have to use bungies stuff now when tower ghost is way better

**Comment by NotMeNoWay** [comment]
Still not working. I'm about to install Chrome and use that. Firefox is becoming unusable with their latest updates.

**Comment by NotMeNoWay** [comment]
Working perfectly on Chrome. Time to say goodbye to Firefox. Enough is enough with all the program crashes, glitches and java blocking.

**Comment by Chase100488** [comment]
yeah but i don't think my laptop can handle chrome lol it's running vista and idk how to switch it or whatever but i wish someone would say something so i can finally know

**Comment by DMWill** [comment]
if you guys are running windows, can i suggest you download the standalone app?  i run the firefox addon most of the time, but since the standalone was updated so that it now can auto-update, i've pretty much switched over to just that.  I don't know if this will be the case for anyone else, but it runs significantly faster in the standalone as it does in either firefox or chrome.  just my 2 cents :wink:

**Comment by NotMeNoWay** [comment]
The stand alone program does not work properly. Installed it, can't find it, did a system search when it did not show up inside installed programs or app list for Windows 10, and only found crash dump reports. I ended up deleting everything for tower ghost.

**Comment by Chase100488** [comment]
um i'm on a vista laptop so idk what u mean by standalone or whatever? and i don't think i can just make my laptop change windows without paying someone which i don't have i really like using tower ghost it's faster than bungies and i just wanna have it work like it use to for me so DMWill can u explain this standalone thing is or how to get it?

**Comment by NotMeNoWay** [comment]
I went to the Destiny Tower Ghost website and found extension downloads for Chrome, Firefox, IOS, ect and listed was Linux, Windows, Mac. I downloaded the zip file for Windows and installed it. No desktop icon and not listed in apps or programs. I use a program called "Search Everything" that will find anything on your PC. The only thing that showed up was dump files and the installer program. No program or even an option for "find target". It is junk so don't even bother. I hate that I've had to install Chrome but the Firefox app is not working and apparently there is no fix in sight.

**Comment by DMWill** [comment]
Go to http://towerghostfordestiny.com/index.php/downloads/ and scroll to the bottom.  Find where it says Operating Systems.  Click on the 32bit or 64bit for what ever your operating system is running.  Chase, if you don't know which one you have for your operating system, the 32bit one will work on both.  Save the zip file to a folder of your choice by right-clicking on it and then selecting "save link as" and choose where you want to save it.  Find where you saved that file, and then unzip it.  This will create a folder of the same name as the file.  Inside this folder, there should be a file called "Tower Ghost for Destiny.exe".  Open this and that's it.  If you want to put it on your desktop, right-click on the file and find "create shortcut".  This shortcut can then be dragged onto your desktop.

**Comment by NotMeNoWay** [comment]
DMWill, I have downloaded this exact file six times now and unzipped it to a folder. There is no .exe file in the zip file, all six times. There are all kinds of files but no .exe.

**Comment by DMWill** [comment]
@NotMeNoWay
chances are, you have the file extensions hidden in your folder settings.  if that's the case, the files in the folder should look like in the picture.  Tower Ghost For Destiny is the file that runs the program.
![capture2](https://cloud.githubusercontent.com/assets/2240055/11855523/ce6ca5bc-a418-11e5-9b0a-0e46ce0b56d6.PNG)

**Comment by NotMeNoWay** [comment]
I have unzipped, made sure hidden files were shown and still no .exe
![2015-12-16_17-06-02](https://cloud.githubusercontent.com/assets/16312552/11856646/17a7771c-a418-11e5-8d74-326d68045daa.png)

**Comment by NotMeNoWay** [comment]
I changed the file extension for the matching file on your screenshot to .exe and got this message when I tried to run it.

![2015-12-16_17-19-20](https://cloud.githubusercontent.com/assets/16312552/11856852/68a3a1bc-a419-11e5-8064-1c2dd0673179.png)

**Comment by DMWill** [comment]
i never said anything about hidden files.  i said the extensions were possibly hidden; the ".exe." part is what i meant.  from your screenshot, i can tell that is not the case.  it is possible however, that windows 10 (i'm on 7) hides the .exe extension for whatever reason.  in any case, you shouldn't need to add the .exe to the file, and by doing so have probably rendered it unusable.  i know people have got this to work in windows 10, but i don't have much experience using it yet.  hopefully someone else here will step in with some more advice.  another thing i noticed too, your files have widely varying dates, as mine are all from the same day except for the "locales" folder.  if you've downloaded this 6,7,8 times, delete everything.  start over.  don't rename anything.  do everything else i mentioned above.  if nothing happens, i don't know what else to suggest at this time.

**Comment by DMWill** [comment]
i just realized what you're doing.  you are not downloading the correct zip file.  the one you're downloading is for Linux, NOT Windows.  no wonder it wasn't working for you at all.  

this is the exact zip file you need ----> https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/tgd-windows-x64.zip?raw=true

try that one, and let me know.

**Comment by NotMeNoWay** [comment]
BOOM! That link worked. I was downloaded the link under Windows 64 bit so there must be some sort of problem with that file. Thank you MUCH!

**Comment by DMWill** [comment]
I'm really glad I could help. It took me a minute to realize what was going on.  I haven't used Linux in several years, but when I looked at your screenshots again, I knew right away what the problem was.

**Comment by Chase100488** [comment]
Ok So I'm On Vista And I Got That Standalone To Work Once Then I Went To Move It And Now It Won't Come Back Up So What am I Doing Wrong?

**Comment by Chase100488** [comment]
And Im Running 32bit Operation System And Everytime I Download The 32 Bit One It Just Does Not Work And I Have Windows Vista And I'm Downloading The 32 Bit Windows One So IDK Whats Going On

**Comment by DMWill** [comment]
@Chase100488 you cannot move the "Tower Ghost for Destiny" file from that folder.  It would be like moving critical system files from your Windows folder.  It needs to be there for the app to work.  I suggested before if you wanted it on your desktop, or taskbar, or where ever you want the shortcut to be, you need to first make a shortcut.  To do this, right-click the "Tower Ghost for Destiny" file.  The right-click menu will open, and somewhere in that menu will be "Create shortcut".  You will then have the original file and a new one called "Tower Ghost for Destiny - Shortcut".
![shortcut](https://cloud.githubusercontent.com/assets/2240055/11858299/4d307f08-a42e-11e5-8232-e2d08a63db88.PNG)
You can then drag this file to your desktop or where ever you want that shortcut.  I'll suggest to you that you drag the new shortcut to your Start Menu instead of the Desktop.  You just need to drag it to the Start Menu button in the corner, and drop it in the top left-hand side when it says "Pin to Start Menu". It's just easier to get to there.
![start menu](https://cloud.githubusercontent.com/assets/2240055/11858477/febd0e5c-a42f-11e5-8125-2f5336821e8b.png)


Was this the only issue you're having?  If you've done everything else correctly, aside from moving the executable file, then you should have no more problems.

**Comment by Chase100488** [comment]
I Got It Working Now Thank God Finally LOL I Love Using Tower Ghost
