### ISSUE TITLE
Imprecation hand cannon takes up two classified slots in primary

### ISSUE THREAD

**Issue by ccrotty** [dasilva333/TowerGhostForDestiny#510]
From attached image - primary shows 9 items, but there are only 8 in the game.  The 310 is MIDA, so that can be ignored, but it appears the Imprecation hand cannon (quest) is also using up another slot (listed as the 290 classified). (I don't have a 290 primary in my inventory) 
![capture](https://cloud.githubusercontent.com/assets/1778973/11849414/c171ec0a-a3f5-11e5-8c34-77c507bfb9ee.JPG)

**Comment by villiansv** [comment]
That is most likely Plan C, which shows up in primaries for some reason. New exotics were just unclassified, so I expect an update will fix it quick. DIM already works fine.

**Comment by ccrotty** [comment]
Except I don't own a Plan-C.  Seems like a phantom item. (It actually keeps
me from moving items around)

DIM shows:
[image: Inline image 1]

TGD shows:
[image: Inline image 2]

**Comment by Naivedo** [comment]
New Specials and Heavies show up as Classified Primary. Plan C, Dragon's Breath, Super Good Advice, etc.

**Comment by ccrotty** [comment]
OK, I understand now. Yes, it appears to be Dragons Breath showing up in the primary slot.
