### ISSUE TITLE
3.6.7.3 iOS version broken

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#512]
Weapons on my first character says "Primary 20/10" and lists a bunch of bungie monkey squares (13) mixed in with 7 weapon icons. No info displayed for the other two characters. A bunch of monkey squares are shown in the vault as well.

Let me repeat my praise for the developer on this app. I've come to rely heavily on it for managing my Destiny experience, and use it much more than Bungie's companion app. But I'll be turning off auto updates after the next working version goes up for iOS b/c it is a serious hassle to run back and forth from my computer to the TV room to change loadouts.

**Comment by edmiller47** [comment]
Fixed with update... Thanks

**Comment by dasilva333** [comment]
@edmiller47 please try closing the issue once the problem has been fixed thanks
