### ISSUE TITLE
Y2 dragon's breath rocket launcher not showing up correctly

### ISSUE THREAD

**Issue by jerrycarlson** [dasilva333/TowerGhostForDestiny#513]
I'm using the latest version of Chrome, Firefox, and TGD.  I got a y2 dragon's breath rocket launcher (light 310) as a drop but it shows up in TGD as a 'classified' primary weapon instead of as a heavy weapon, regardless of whether I move it to the vault or leave it on a character.

**Comment by dasilva333** [comment]
Problem fixed as of 3.7.0 thanks try it out and let me know if you still have issues

**Comment by jerrycarlson** [comment]
It works now.  Thank you!!
