### ISSUE TITLE
German language broken

### ISSUE THREAD

**Issue by Korben85** [dasilva333/TowerGhostForDestiny#515]
When I use German language the umlauts are not shown correctly.

I tried to find the language files in my fork, but it was not possible for me to find them.
I also had a look into the files and folders and for me as a beginner all seems a bit confusing.
F.e. the www/data folder is confusing. Some img are here, others are there. Thought to help maybe with this great project, but as I sad as a beginner it's hard to find a start.
Cheers

**Comment by dasilva333** [comment]
The files are in js/tgd/locale.js from there you can edit the "de" object key. Perhaps it's been to denoate the umlauts with \x123 notation instead of how I did it. Not sure good luck and thanks

**Comment by dasilva333** [comment]
Closing this ticket now that you've submitted the Pull Requests for the fixes, thanks again
