### ISSUE TITLE
Information, icons, and weapons missing from display

### ISSUE THREAD

**Issue by nessus42** [dasilva333/TowerGhostForDestiny#517]
I'm using the latest release of Tower Ghost (3.7.0.3) and number of things are missing from the display. The most egregious problem is that it's not displaying my 319 Harrowed Qullim's Terminus at all. It doesn't matter if I move it to a different character. It still does not display.

I also have a 320 version of this gun that it ***is*** displaying, but the tooltip does not mention that it has Extended Mag or Eye of the Storm. (The older version that I have running in Chrome ***does*** display both of these perks.)

Additionally, the icons for perks in the tooltips are often broken. This is clearly a minor issue, but it would sure be nice if it worked again.

P.S. I just toggled the Progress setting from All to Missing Perks (which would be true of my 319 Qullim's Terminus) and back to all, and that fixed the problem with the 319 version going missing from the display, but it didn't fix the other problems.

**Comment by dasilva333** [comment]
@nessus42 do you mind posting a share url so I can see what you mean? Are you aware of the Advanced Tooltip option and is it enabled? Let me know thanks

**Comment by nessus42** [comment]
@dasilva333 I prepared a screenshot to link here, but in the meantime, you've fixed the problem with 3.7.0.4. That was quick!

I ***am*** aware of the Advanced Tooltips option and I leave it on. I don't know what it does, however. Is there a document somewhere that says what these things do? I don't notice a difference with this selected or deselected.

**Comment by nessus42** [comment]
P.S. What do you develop TGD with so that you can deliver it as several different types of plugins and as native apps all at the same time? That's pretty cool! I see that TGD is largely written in JavaScript, which is cross-platform, of course, but I'm only familiar with normal website development using JavaScript for "single-page" web applications, or adding more interactivity to pages on a web site. I also know about Node.js, so you can write your server-side code in JavaScript too. But I'm not familiar with how you deliver an app in Javascript like this one to run as multiple browser plugins, or as native apps, all at the same time.

**Comment by dasilva333** [comment]
Closing the issue as it appears to have been fixed, Advanced Tooltips shows inactive perks, you can read about it more under Settings > Help. I develop using Phonegap and Javascript. It's really just a large single page webapp that has the hooks and compatibility to work as various types of apps.

**Comment by nessus42** [comment]
Thanks for the info! (And the great program.)

Advanced Tooltips doesn't seem to be documented under Settings -> Help.

Also, it seems to work for some perks. E.g., it shows focussed fire vs spin up for my Suros. But it doesn't seem to work for other perks. E.g., for my Qullim's Terminus, I selected Extended Mag, and that's what it shows me. but it doesn't show me the other choices for that perk slot.

**Comment by dasilva333** [comment]
Share URL never posted, can't verify if there's a problem or not. Here's what QT is supposed to look like with Advanced Tooltips enabled or disabled:
http://i.imgur.com/iHeKq6f.png Notice it only shows Small Bore and not all available perks in that column unlike armor

The option is more meant for Armor check out the difference in Chest enabled and disabled:

Enabled: http://i.imgur.com/ofCWG6M.png
Disabled: http://i.imgur.com/PwqKv3b.png

Cheers

**Comment by nessus42** [comment]
Yes, that's how it works for me. Thanks!
