### ISSUE TITLE
Question About Updating

### ISSUE THREAD

**Issue by Chase100488** [dasilva333/TowerGhostForDestiny#518]
I See People Are Saying That There Version Updated But I Have Turned Both Auto Update And Auto Refresh Off And On And It's Still On 3.6.9.0 Version So How Is It People Are Able To Get There's To Update And I'm Using The Firefox Version Since I Finally Found It Can Someone Shed Some Light On This?

**Comment by dasilva333** [comment]
"I Have Turned Both Auto Update And Auto Refresh Off"
It needs to be turned On not Off, you can tell it's on because it's highlighted in the menu. Once enabled it should auto update to 3.7.0.3
