### ISSUE TITLE
Firefox Tower Ghost Verified

### ISSUE THREAD

**Issue by Jaz54** [dasilva333/TowerGhostForDestiny#519]
Firefox has disabled Tower Ghost Saying "Tower Ghost could not be verified for use with Firefox and has been disabled"
Firefox version 43.0.1
Also the version of Tower Ghost on their website is 3.6.5

**Comment by dasilva333** [comment]
http://towerghostfordestiny.com/index.php/hrf_faq/help-my-firefox-43-does-not-work-with-tower-ghost/
