### ISSUE TITLE
Suggestion: Thicker border around the items

### ISSUE THREAD

**Issue by Titus-s** [dasilva333/TowerGhostForDestiny#52]
Just a suggestion. Can you make Thicker border around the items? 
Now you have to look if the item is maxed. With a thicker border will be visible at first sight.

**Comment by dasilva333** [comment]
Agreed I find myself having the same problem

**Comment by dasilva333** [comment]
Expect this in the next version

**Comment by dasilva333** [comment]
@Titus-s if you can confirm it's been fixed as of 1.9.0 that would be great thanks

**Comment by Titus-s** [comment]
To be sure I almost didn't notice any difference, however in zoom it can be see that maxed items has thicker border. Maybe if you can add thicker border for not maxed items it would be better. I compared it to the appearance in game, and I think the difference between maxed and not maxed item it will be more visible. How do you think?

**Comment by dasilva333** [comment]
It was a 1px and I changed it to 2px, sorry man I think 3px is too extreme leaving it as is for now. THanks for your feedback

**Comment by Titus-s** [comment]
I'm sorry but my english is not perfect. 
I don't want 3px border - I agree it's too extreme. 
I just want to thicker white border for items with "Missing XP" and "Full XP".
Please take a look at below picture. I add manually thicker white border on bottom half of picture. Upper part is unchanged. 
![thickerborder](https://cloud.githubusercontent.com/assets/11790750/7218927/959d82c8-e687-11e4-9fa4-b73ba3a183ac.png)

**Comment by dasilva333** [comment]
I'll allow it guardian

**Comment by Titus-s** [comment]
Thanks :)
