### ISSUE TITLE
Firefox Not Updating 

### ISSUE THREAD

**Issue by Chase100488** [dasilva333/TowerGhostForDestiny#520]
I Made Sure Auto Updates And Auto Refresh Where On And It Said Installing Updates But When It Finishes It Still Says TGD Version 3.6.9.0 When Others Are Saying Another Version So Can Someone Shed Some Light On This?

**Comment by dasilva333** [comment]
@Chase100488 Please stop opening new tickets for any issues you are having, if you install the addon from here: https://addons.mozilla.org/en-us/firefox/addon/tower-ghost-for-destiny/ it should be 3.6.5 not 3.6.9, if you are on 3.6.9 then it means it auto updated from 3.6.5 to 3.6.9. Simply make sure you are on v3.7.x by making sure Auto Updates is enabled.

To recap:
Settings > Auto Updates (off) > Auto Updates (on), now wait 10 minutes until the page reloads and you have 3.7.0.4
If that doesn't work try uninstalling the addon completely and reinstall it from the link provided.

Again do not open any new tickets with issues you are having. Thank you

**Comment by Chase100488** [comment]
Um None Of That Works I Have Tried Both Of Those Things And It Still Wont Update Firefox So What Now Sir?

**Comment by dasilva333** [comment]
What version of Firefox are you using? What happens when you install 3.6.5 from the store?

**Comment by DMWill** [comment]
Recently, I had to remove the folder from my **firefox profile folder**, as well as removing the addon normally.  This was after another unrelated issue with firefox; this prevented Tower Ghost from updating automatically as normal.  I think this is similar to what happened to me.

so, @Chase100488, uninstall the addon as you normally would.  Open the Firefox menu (should be on the very end of the location bar toolbar) and then click the little icon with the **?** on it.  From here you need to click on **Troubleshooting Information**.  The first box on this page contains a link that will automatically open your Profile Folder.  **BEFORE** clicking it, scroll down through the addons and find Tower Ghost.  Write down the ID (or just leave this page open to come back to).  Now, click the button in that first box to open the Profile Folder.
![screenshot- domain date time](https://cloud.githubusercontent.com/assets/2240055/11972264/c2d4b0a6-a917-11e5-9438-285b724fbeae.jpg)
Once in your folder, open *storage*, and then *default*.  You are going to delete the folder that says **resource+++(THE ID YOU WROTE DOWN).**  I don't remember if i did or not, but there's another folder that wouldn't hurt to delete as well, **http+++towerghostfordestiny.com**.

Restart Firefox after this is complete.  Go to https://addons.mozilla.org/en-us/firefox/addon/tower-ghost-for-destiny/ and get the latest version there.  Make sure you have auto-updates on.  Hope this works for you.

**Comment by Chase100488** [comment]
Um I Really Confused With All That I'm Sorry I'm Not Very Computer Smart Either :/ Ugh

**Comment by Chase100488** [comment]
And At @dasilva333 I Used This Link To Get The 3.6.9.0 From This Link >https://github.com/dasilva333/TowerGhostForDestiny/tree/div-movile-dist/    And I Also Tried The 32 Bit Standalone Version Because My Computer Is 32 Bit And It Would Just Take Forever For Tower Ghost To Pop Up I Really Don't Know What Else To Do Honestly *Sigh*

**Comment by Chase100488** [comment]
And When I Went To Download 3.7.4.0 It Said "the add-on could not be installed because it does not match what the add- on Firefox expected" what is the all about *sigh* more stuff i don't get

**Comment by Chase100488** [comment]
@DMWill I Did All You Just Said And It's Still Stuck On 3.6.9.0 So IDK What Else To Do :/ This Sucks

**Comment by DMWill** [comment]
If you followed my instructions to the letter, you should not get stuck on 3.6.9.  Version 3.6.9 wasn't even the version in the Firefox store when I wrote those instructions.  Do ***everything*** I said to do, again.  If you don't, or skip something, or do them out of order, there is nothing I can do further to help you.

**Comment by dasilva333** [comment]
@

**Comment by Chase100488** [comment]
@DMWill I Did Everything U Said I Went In And Deleted That Folder And Never Saw The Other One Went In And Tried To Update And It Stayed On The Same Thing Like I Said I'm Not Very Computer Smart Man I'm Sorry

**Comment by Chase100488** [comment]
@dasilva333 Thanks For Telling Me To Manually Install It That Worked I Now Am Using Version 3.7.3.0 Keep Up The Good Work Man Because Tower Ghost Is Freaking Amazing It Makes Things So Much Easier LOL

**Comment by dasilva333** [comment]
http://i.imgur.com/9crLW3i.png

**Comment by dasilva333** [comment]
Re-uploaded it as 3.7.5 hopefully the Mozilla team doesn't make the same mistake again of messing up the hash after changing the status. Thanks guys

**Comment by Chase100488** [comment]
What Is The Link For That One?

**Comment by dasilva333** [comment]
Same link: https://addons.mozilla.org/en-us/firefox/addon/tower-ghost-for-destiny/versions/

**Comment by Chase100488** [comment]
Just Wanna Say Man Keep Up The Good Work With Tower Ghost I REALLY Really Like It
