### ISSUE TITLE
unlocked items sometimes lock when being transferred

### ISSUE THREAD

**Issue by jerrycarlson** [dasilva333/TowerGhostForDestiny#521]
I use the latest version of Firefox, Chrome, and TGD.  The issue has been happening for a while now, and unfortunately I haven't found a pattern to help with the debugging.  The issue is that sometimes I will transfer unlocked gear from one character to another and the gear will end up as locked after the transfer.  It doesn't happen every time, and it doesn't matter whether the gear is leveled or not.  It doesn't seem to happen to locked gear (meaning, I don't think that moving a locked item of gear ends up as unlocked after the transfer).  I haven't noticed whether it happens with anything other than armor.  Sorry I don't yet have more info for you yet.

**Comment by dasilva333** [comment]
Can't seem to reproduce it, let me know if this is still an issue for you as of 3.7.5+ without a consistent reproducible test case it's probably a problem on Bungie's end rather than on TGD. Let me know thanks
