### ISSUE TITLE
Dont like 3.7.1.1

### ISSUE THREAD

**Issue by MasterBry** [dasilva333/TowerGhostForDestiny#523]
FEEDBACK : 
Dont like the new "load as you scroll" you have added.
Never thought that it took too long to load, but if it did, its sure better than loading all the time, thats so much slower, and difficult to use in a hurry, like when you are about to kill a boss, and realise you need to grab a 3ofCoin from the vault.... For me, the loading time was faster and complete, before.... Hope this helps

**Comment by villiansv** [comment]
A further issue with this method is (using Firefox):

Load TG, don't scroll down. Filter for "synth", which are usually below what you see (you'd have to scroll to see them). They show up without icons, and no amount of scrolling will display the icon. The same applies to just about anything when you filter and its icon hasn't been loaded already.

I'd appreciate a settings toggle for this behaviour. I can see how it could be beneficial on phones and other similar devices, but on a PC the experience is worse off.

**Comment by dasilva333** [comment]
Agreed it's not optimal at the moment it could use some fine tuning expect it to get better over time, thanks for the feedback guys

**Comment by MasterBry** [comment]
I didnt like it so much I restored my iPad to a week old back up where I thought I didnt have auto update selected, only to find I did, and it auto updated, but you have fixed it by removing it, so its all good again, Thanks Very Much for a wonderful app, and for listening to us, very much appreciated! 😎
