### ISSUE TITLE
iPad v3

### ISSUE THREAD

**Issue by duffy71** [dasilva333/TowerGhostForDestiny#526]
Have attempted to reinstall several times but when opening the app I get stuck on a blank screen which I assume should be the MS / PlayStation log in screen.
Please fix as I love this app.

Strike last comment, managed to get app up but now no icons, just empty boxes with occasional numbers in corners

**Comment by dasilva333** [comment]
I'm guessing you got it resolved right?

**Comment by duffy71** [comment]
Thanks.
Got logged in but have no icons at the moment. There was a post prior to mine with the same issue so to avoid repetitiveness removed my post.

**Comment by dasilva333** [comment]
Make sure you're on at least v3.7.4.2 to see the icons. good luck
