### ISSUE TITLE
New exotics are not identified with their icons - still classified

### ISSUE THREAD

**Issue by jdf99** [dasilva333/TowerGhostForDestiny#527]
and other strange behaviour

<img width="2560" alt="screen shot 2015-12-24 at 8 24 58 am" src="https://cloud.githubusercontent.com/assets/14198728/11995091/910d4022-aa18-11e5-915f-a4fc8748d7a8.png">

**Comment by dasilva333** [comment]
@jdf99 make sure you have Auto Updates enabled under Settings it should update to 3.7.4.1 in the top left. Good luck

**Comment by jdf99** [comment]
worked - thanks a lot!
Jim
