### ISSUE TITLE
Latest Android version can't access database

### ISSUE THREAD

**Issue by sdholden** [dasilva333/TowerGhostForDestiny#528]
3.7.4.1 update no longer works on Android.  Dialog opens stating it can't access the database, please contact author!

**Comment by dasilva333** [comment]
I've been actively working on it for the past hour perhaps you opened it while an update was being pushed. Try clearing App cache and app data and opening it again. Good luck, if you're still able to access the menu you can try enabling and disabling auto updates to get it to work again

**Comment by sdholden** [comment]
Looks like that was it.  I cleared cache and data one more time and it's working normally again.FF43 still has same old issue.  Got xpi installed and first run showed what looked like the correct url, but the bungie page never loaded.  I pressed link to close window and TGD said it was loading, but didn't show my stuff.  All subsequent attempts to login show a different bungie url, same as previous versions.Chrome and windows app and w8.1 mobile are all fine though.
Take some time to enjoy the holidays.  Folks can wait for any more updates for a week or two!!


Sent from my Samsung Galaxy Tab®4

-------- Original message --------

**Comment by dasilva333** [comment]
@sdholden try 3.7.6 for Android, let me know if you're still having issues with any platform. thanks

**Comment by sdholden** [comment]
Android, windows phone 8.1, ios6, chrome on w7,8.1,10 all work.  Standalone app on w10 slow to start, but works.
Ff 43 still never logs into bungie in popup window and never shows equipment in the browser.

-----Original Message-----

**Comment by dasilva333** [comment]
@sdholden did you try Firefox 3.7.5 from the Mozilla store? Basically shows the login prompt > pop up window opens > you log in > pop up window auto closes (or is manually closed) > TGD throws a prompt saying please wait while firefox refreshes your arsenal > inventory loads, another option you could do is go to Bungie.net and make sure you're logged in and then open Tower Ghost see if that works. Good luck

**Comment by sdholden** [comment]
Tried both.  Popup never loads bungie.  First time I used 3.7.5 it showed the correct URL in the popup window, but failed to load my account on bungie.  All subsequent attempts show a truncated URL and does nothing in the popup window at all.
I think I sent the 2 different URLs I saw in earlier msgs.  No improvement in last dozen or so updates...

-----Original Message-----

**Comment by sdholden** [comment]
Just tried again 3.7.6.5 and same thing.  Opens new window with this url:"https://www.bungie.net/en/User/SignIn/Xuid" and juut sites there.  It's not the same URL that chrome starts with in the popup window...Closing the windows trigger 'laoding arsenal' message and bar shows up, but nothing else is loaded...
 Stephen Holden
Ontario, Canada 

    On Monday, January 4, 2016 3:46 PM, Richard Pinedo <notifications@github.com> wrote:
 
 

 @sdholden did you try Firefox 3.7.5 from the Mozilla store? Basically shows the login prompt > pop up window opens > you log in > pop up window auto closes (or is manually closed) > TGD throws a prompt saying please wait while firefox refreshes your arsenal > inventory loads, another option you could do is go to Bungie.net and make sure you're logged in and then open Tower Ghost see if that works. Good luck—

**Comment by dasilva333** [comment]
problem is still tracked in issue #470 thanks man

**Comment by sdholden** [comment]
3.7.6.7 still exhibits the same problem.  New window opens to "https://www.bungie.net/en/User/SignIn/Xuid" but doesn't load the Bungie page still.  Closing that blank windows (still has text "click here if doesn't close").  Closing it triggers a "loading arsenal" balloon, then a bar across the canvas showing progress, but nothing loads.
I uninstalled the addon, re-started FF and tried again.  Still broken.


 Stephen Holden
Ontario, Canada 

    On Tuesday, January 5, 2016 9:52 AM, Richard Pinedo <notifications@github.com> wrote:
 
 

 problem is still tracked in issue #470 thanks man—
