### ISSUE TITLE
3.7.5.3 displaying error msg : Cannot retrieve data

### ISSUE THREAD

**Issue by SecondCarpet** [dasilva333/TowerGhostForDestiny#529]
Worked yesterday when I re-installed.
After 3.7.5.3 update, it cannot retrieve info from Destiny DB on Android S4 and S6.

Dis complete re-install and still shows message to inform you of error.

Merry Xmas. I'm sure we can live without TGD for one day.

**Comment by edmiller47** [comment]
Loadouts do not work in this version (PC and iOS) or on android 3.6.9.1. Progress bar is displayed, moves once and then sits there forever. No items get transferred. I have deleted and reinstalled the app, same results.

**Comment by dasilva333** [comment]
3.7.5.3 Works fine for android/ios/chrome with loadouts and destinydb as far as i tested it. not sure what to tell you guys other than to do a complete cache clear and reinstall, make sure auto updates is enabled and you should be on 3.7.5.3. Good luck

**Comment by edmiller47** [comment]
I was on 3.7.5.3. When I just opened TG on my iPad, auto updated installed 3.6.7.3. Wha?

**Comment by edmiller47** [comment]
Just uninstalled from PC. Cleared browser cache. Reinstalled 3.7.5.3. Logged out and back in. Auto updates are enabled. Confirmed same version is installed. Tried multiple loadouts, they don't work.

**Comment by dasilva333** [comment]
@edmiller47 so now the only thing that isn't working is the loadouts? It isn't that it's not loading your presets which is what I thought it was but that a certain (or all?) your loadouts don't transfer when you attempt sending them around? Mind sharing your Share URL? Thanks

**Comment by edmiller47** [comment]
https://towerghostfordestiny.com/share/?xbl/BLAMnation
The only thing that is not working is loadouts. They are present in my loadouts menu. When I choose one, and then touch a character to use it on, the list of transfers is shown. Then when the Trannsfer button is pressed, a progress bar is shown. It moves a bit and then stops. I have let it sit for 10 minutes with no items getting moved. Same behavior on Chrome, iOS, Android (actually on Blackberry 10).

**Comment by dasilva333** [comment]
@edmiller47 thanks for the update i'll test loadouts with ships to see if there's any issues involved

**Comment by dasilva333** [comment]
@edmiller47 I looked into the loadouts code and found a problem with transfers (while testing the ships) that I found is this:
If i tried to transfer a ship to my vault nothing would happen, once a ship already existed in the vault I was able to xfer them into the vault freely, try out 3.7.6.5 and let me know if you still have problems with loadouts and transfers there could be another bug in there. Thanks!

**Comment by edmiller47** [comment]
Trying out 3.7.6.5 and now having a different issue with loadout transfers. This has happened intermittently with the last couple of versions and with the current version, and all have occurred on iOS. I have auto updates turned on.

Here's what happens: Auto refresh is turned off. I select a loadout and start the transfer. It progresses a bit, then I start seeing the blue "success: refresh completed" messages on the right of the screen. The transfer stalls and the messages continue to pop up until I force quit the app.

This happened three or four times in a row yesterday after updating to 3.7.6.5 but now seems to have gone away. Odd...

**Comment by dasilva333** [comment]
Try out 3.7.8 it includes more fixes for loadouts, let me know if there's still any problems with it thanks @edmiller47

**Comment by edmiller47** [comment]
Performance of 3.7.8 is improved and I haven't seen the intermittent problem I described above.

One minor issue with materials and consumables. Can't remove them from a loadout (I accidentally clicked on one while modifying a loadout). If you add a consumable such as moldering shards, and then click on it to remove it, TG creates another copy of the item in the loadout.

**Comment by dasilva333** [comment]
@edmiller47 make a new ticket for that one and I'll take care of it when I can, thanks for the heads up
