### ISSUE TITLE
Suggestion: Add Subclasses as an equipable item

### ISSUE THREAD

**Issue by ShodanPT** [dasilva333/TowerGhostForDestiny#53]
Add Subclasses as an equipable item

**Comment by lanejcf** [comment]
With 1.9.6 allowing subclasses that is a good improvement, in line with the Destiny game would it be better positioned directly above weapons at the top ?

**Comment by dasilva333** [comment]
@lanejcf Thanks man I too agree it's a good improvement, also works with loadouts. I'm also satisfied with it's position Thanks for feedback closing ticket now
