### ISSUE TITLE
3.7.4.1 cannot load item definitions

### ISSUE THREAD

**Issue by jaig14** [dasilva333/TowerGhostForDestiny#531]
I'm using tower ghost 3.7.4.1 on my nexus 6 and getting a cannot load item definitions error when I open the app. Tried clearing cache/uninstalling. Still getting the error.

**Comment by dasilva333** [comment]
Try 3.7.6 available for android, let me know if you're still having problems thanks

**Comment by Devincol** [comment]
I am having this issue on my phone I'm using 3.9.1.1 please help
