### ISSUE TITLE
3.7.6.0 Missing buttons in Character Stats Windows

### ISSUE THREAD

**Issue by zebibyte2** [dasilva333/TowerGhostForDestiny#534]
On Chrome Version 48.0.2564.48 beta (64-bit)
OS X 10.11.2 (15C50)

Missing buttons to Equip Gear with Highest XXX, see attached screenshot.

<img width="996" alt="screen shot 2016-01-03 at 2 05 10 pm" src="https://cloud.githubusercontent.com/assets/16530110/12081080/1766c34c-b224-11e5-8639-f00016eb7d41.png">

**Comment by weborican** [comment]
Same on iOS

**Comment by dasilva333** [comment]
Problem fixed as of 3.7.6.1 via Auto Update, thanks guys
