### ISSUE TITLE
Question about view settings

### ISSUE THREAD

**Issue by GRAYHAM75** [dasilva333/TowerGhostForDestiny#536]
Have changed my view settings to 6 coloums instead of 4 but only the vault has changed, characters still have only 4. Would like to have 6 coloums option for everything as find this easier and faster to work with on phone screen size.
If you could let me know if this is possible and I'm just not seeing it, otherwise great app keep up the good work.
Thanks.
P.S. On windows phone.

**Comment by dasilva333** [comment]
@GRAYHAM75 Only the vault has a customizable number of columns, it wouldn't make sense to have 6 columns for characters because it wouldn't match the Destiny UI which I'm trying to emulate, thanks for the feedback anyways have a good day

**Comment by GRAYHAM75** [comment]
Ok thanks for the explanation.
