### ISSUE TITLE
Cannot remove consumables or materials from a loadout

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#539]
One minor issue with materials and consumables. Can't remove them from a loadout (I accidentally clicked on one while modifying a loadout). If you add a consumable such as moldering shards, and then click on it to remove it, TG creates another copy of the item in the loadout.

**Comment by dasilva333** [comment]
Thanks I've seen problems of this sort with consumables I think I have to go back into that code and fix a few things.

**Comment by dasilva333** [comment]
Try it now, problem fixed as of 3.7.9
