### ISSUE TITLE
Chrome app not working

### ISSUE THREAD

**Issue by komarod** [dasilva333/TowerGhostForDestiny#54]
i dont know if anyone else is having this problem but mine refuses to load. i've refreshed, closed chrome and reopened, reinstalled app and still nothing.

**Comment by dasilva333** [comment]
Try to open chrome, press F12, visit the Console tab, let it load and provide any errors messages you encounter. Also make sure the original Destiny Item Manager works for you too, and finally visit your profile page on Bungie.net to make sure you're fully logged in.

Thanks

**Comment by Titus-s** [comment]
I don't know if it's the same issue but when I've click refresh blue bar appear on top and hang. 
Below screenshot with error in console:
![image](https://cloud.githubusercontent.com/assets/11790750/7209041/1f333238-e545-11e4-95ef-5cf14467ef2d.png)

**Comment by dasilva333** [comment]
problem fixed in 1.9.0

**Comment by dasilva333** [comment]
error in loadouts closing ticket in favor of issue #31 @komarod please leave any feedback in the other ticket thank you

**Comment by komarod** [comment]
figured out it wasnt loading because every time i use it i gotta log in i thought it was jst the first time.
