### ISSUE TITLE
TGD 3.7.6.14 problem on firefox 

### ISSUE THREAD

**Issue by Chase100488** [dasilva333/TowerGhostForDestiny#541]
um when i go to click on a gun or armor or whatever the little box that pops up that says (vault,store/equip on character) it is cut off and not letting me see which character is which is this a bug or is there a way i can fix this?

**Comment by dasilva333** [comment]
Can you show me a screenshot? I'm having a hard time visualizing what you're saying. Thanks!

**Comment by Chase100488** [comment]
Um I Can Try I Really Don't Know How To Do That

**Comment by Chase100488** [comment]
![img_1156](https://cloud.githubusercontent.com/assets/14864369/12249638/fa59af5a-b88e-11e5-9ef6-5e4e7624bb4a.JPG)

**Comment by Chase100488** [comment]
![img_1157](https://cloud.githubusercontent.com/assets/14864369/12249679/3b3f1a96-b88f-11e5-8996-0a28f31a8a5d.JPG)

**Comment by Chase100488** [comment]
As You Can See It's Like It's Cutt Off And All IDK How It Happened Or How to Fix It LOL

**Comment by Chase100488** [comment]
i mean idk whatt else to do lol

**Comment by dasilva333** [comment]
Thanks @Chase100488 I'll take care of it

**Comment by Chase100488** [comment]
What Could Be The Cause Of It Ya Think?

**Comment by Chase100488** [comment]
and can u let me know when u fixed it or whatever?

**Comment by dasilva333** [comment]
Expect to see the fix in tonight in version 3.8.x, I just removed the part that was making it bug out so I'll leave this ticket open until I can get a proper fix implemented for that section.

**Comment by Chase100488** [comment]
Thanks @dasilva333 I Really Love Using Tower Ghost To Move My Stuff Back And Forth Thanks Again Man

**Comment by Chase100488** [comment]
Hey Um Can U Send Me A Link To The Version You Make For Firefox Because I'm Still At 3.7.6.14 Unless U Didn't Update It Yet

**Comment by Chase100488** [comment]
And Now My Version Won't Update To 3.8.0 It's Still At 3.7.6.14 I Did The Both Auto Things Off Then Back On And It Acted Like It Was Installing Updates And When It Got Done It Was Still Version 3.7.6.14 So IDK What To Do Now *Sigh* Why Is Technology So Cruel LOL

**Comment by dasilva333** [comment]
Try installing 3.8.0 from the Store 
https://addons.mozilla.org/en-us/firefox/addon/tower-ghost-for-destiny/
Enable and disable auto updates, seems to be working fine for me.

**Comment by Chase100488** [comment]
Hey @dasilva333 I Removed Tower Ghost To Get That Version In The Link U Posted And As Soon As It Installed It Took Me Back To 3.7.6.14 And I Disabled And Enabled Auto Updates And It Still Made Me Stay On 3.7.6.14 IDK What Else To Do How Can I Update It To The Newest Version If It Won't Update It On Firefox?

**Comment by Chase100488** [comment]
Care To Shed Some Light On This Man Because I Wanna Use Tower Ghost But If I Can't See It And It Won't Update IDK What Else To Do?

**Comment by dasilva333** [comment]
Not sure bro, uninstall Firefox if you need to I guess. Short of uninstall and reinstalling the extension and clearing your cache there isn't much I can recommend to get it fixed.

**Comment by Chase100488** [comment]
That Will Dude Tried Telling Me How To But It Never Worked I Don't Understand Why Mine Isn't Updating I Mean Could It Be My Version Of Windows Which Is Vista?

**Comment by DMWill** [comment]
I've explained this to you before, @Chase100488.  You need to uninstall TGD, and then DELETE the folder in your profile folder that holds the data for TGD.  I am not going to explain it to you again though.  I suggest you use this link to the other post and follow the instructions there.  Good luck.

https://github.com/dasilva333/TowerGhostForDestiny/issues/520

**Comment by Chase100488** [comment]
Ok Weird Thing Is I Turned On Tower Ghost Today And It Went From 3.7.6.14 To 3.8.0.5 LOL IDK How It Happened

**Comment by Chase100488** [comment]
so no one has nothing to say about this? i think It's Weird

**Comment by Chase100488** [comment]
so what is the newest version of tower ghost?

**Comment by dasilva333** [comment]
I created a helpful guide a few weeks back to resolve those who are stuck on an older version of Firefox, follow these instructions and you should be able to install TGD 3.8.0 from the app store and update itself to 3.9.0.7

Good luck and thanks!

http://towerghostfordestiny.com/index.php/hrf_faq/my-tower-ghost-is-stuck-on-an-older-version-on-firefox/
