### ISSUE TITLE
iPad Air 1 won't load up properly

### ISSUE THREAD

**Issue by MEPevy** [dasilva333/TowerGhostForDestiny#542]
Tried loading up the app and I just get a white screen over the top of the app and it won't go away. Turn the iPad into vertical mode and then can only see about 3cm of the actual app which is not good. Tried deleting the app and reinstalling to no avail, please do something about this app as it has very good potential. Works fine on my iPhone 6s just can't use it at the moment on my iPad which is a bummer.

**Comment by dasilva333** [comment]
Problem was fixed as of the latest version, I'll be submitting an update to the Apple store with the fix included in the base code, for now open the app in portrait, make sure Auto Updates is enabled in Settings, if it is then disable it and enable it again so it updates itself to the latest version. good luck
