### ISSUE TITLE
Suggestion: Auto close menu after action

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#543]
It would be great if after pressing the, say "Light" button for maximizing your light level,  the menu would automatically close. I find myself having to constantly click back on that menu to make it go away after an action has been performed. it also won't go away by clicking anywhere else on the screen, so you have to click back on just the right spot if you want to dismiss it.

![image](https://cloud.githubusercontent.com/assets/12019978/12268836/196cd4a0-b914-11e5-9e56-124b72961228.png)

**Comment by dasilva333** [comment]
Good point, I agree with that change I'l get that implemented soon

**Comment by dasilva333** [comment]
Changed as of 3.7.9.2 thanks @weborican
