### ISSUE TITLE
iOS version reverted back to 3.6.7.3

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#544]
Opened Tower Ghost a little while ago, and the auto-updater told me it was downloading new updates. When it was finished, TG was back to 3.6.7.3 which is not a usable version on the iPad.

I tried turning auto-update off and then back on, to no avail. I then deleted the app, restarted the iPad, and redownloaded the app. Same version was re-installed.

My Chrome and Android versions are up to date and working fine.

**Comment by dasilva333** [comment]
That's really strange I had someone else email me about the same problem this morning, It might be a problem with my server possibly being overloaded and not being able to serve the update? Try it again go through the whole process if you like, it should auto update to 3.7.9 which I'm also submitting to the Apple App store today

**Comment by LtHitlis** [comment]
Same thing happened to me. Was working fine all day then all of a sudden it stopped. 
![image](https://cloud.githubusercontent.com/assets/14055765/12270533/24c404b0-b91c-11e5-9e16-1282c159be85.png)
![image](https://cloud.githubusercontent.com/assets/14055765/12270534/24d541f8-b91c-11e5-98f1-eade9cdb1f16.png)

**Comment by dasilva333** [comment]
I just tested it myself on a brand new install and the same thing happened to me, this is a new problem I'll be investigating it right away. Thanks guys

**Comment by dasilva333** [comment]
Problem fixed as of 3.7.9.1 try it out now, thanks for letting me know

**Comment by edmiller47** [comment]
Fix confirmed
