### ISSUE TITLE
Possible issue with equip max light

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#546]
Basically max light isn't getting me max light. For example, at the moment I have equipped the highest level of weapon and armor I have, with the exception of my special weapon. For my special I have a 313 KF fusion equipped (not sure why it is looking at my 310 Invective), but I have a 315 Black Spindle, a 320 1000-yard stare, and a 320 Defiance of Yasmine. Still, when I click on the Light button I get this:

![screen shot 2016-01-13 at 10 23 43 am](https://cloud.githubusercontent.com/assets/12019978/12309897/bfce0888-ba12-11e5-8b5a-a9492cc8e132.png)

PS> I can get to 318 light level on this character, yet max light level logic claims it should be 316.

**Comment by dasilva333** [comment]
Thanks for the heads up, can you provide me with the Share URL for your profile I'd like to further investigate what's going on. Thanks

**Comment by weborican** [comment]
Today it is obsessed with my Black Spindle (rather than my Invective), maxing my light level at 317. It is still ignoring my 320 snipers that would make me 318.
https://towerghostfordestiny.com/share/?psn/weborican

**Comment by dasilva333** [comment]
Thanks man you found a nice bug with max light expect it fixed in 3.8.0.3 let me know if you still have problems after that

**Comment by weborican** [comment]
Awesome! Did a bunch of max light actions under different scenarios and it all seems to be working perfectly now.
