### ISSUE TITLE
Build instructions or an ARM standalone version?

### ISSUE THREAD

**Issue by pattonwebz** [dasilva333/TowerGhostForDestiny#547]
I can't seem to find any instructions for building this from source. I'm particularly interested in rebuilding the Android version however recently noted that there have been standalone versions and some info regarding how those are built as well would be much appreciated.

Also (I know this is probably a bit of a stretch even before I ask it) but any chance of a compiled version for debian ARM? Thinking a standalone version that works on my Raspberry Pi would be an excellent starting point for a cool weekend project I had an idea for.

**Comment by dasilva333** [comment]
The project is built using Phonegap Build for mobile platforms like iOS, Android and Windows-Phone. The standalone versions are built using NWJS, check out the downloads section for downloading them for your platform: http://towerghostfordestiny.com/index.php/downloads/ Unfortunately I don't provide an NWJS for ARM. You're going to have to google how to do that on your own: 
https://www.google.com/search?q=nwjs+arm&ie=utf-8&oe=utf-8

Good luck
