### ISSUE TITLE
Something broke again. 

### ISSUE THREAD

**Issue by LtHitlis** [dasilva333/TowerGhostForDestiny#548]
Been gone a couple days. Came back to load up and:
![image](https://cloud.githubusercontent.com/assets/14055765/12396618/1216288c-bdce-11e5-88ce-5a0969733876.png)
![image](https://cloud.githubusercontent.com/assets/14055765/12396619/121dbf66-bdce-11e5-8d70-1498b091a6f8.png)

**Comment by dasilva333** [comment]
Try disabling and enabling Auto Updates in Settings, make sure you are on 3.8.x and up. Good luck
