### ISSUE TITLE
Vault width in custom view not working

### ISSUE THREAD

**Issue by Korben85** [dasilva333/TowerGhostForDestiny#550]
Since 3.8.1 the vault width is no longer working in custom view. 
I have the following settings:
Container width: 90%
Layout mode: custom
Vault width: 50%
Vault colums: 12

I'm using Chrome.

Now the images in the characters are very big and these in the vault are very small.
I attached a screenshot.

Regards,
Thomas

![unbenannt](https://cloud.githubusercontent.com/assets/9113325/12527293/c62db5bc-c178-11e5-896b-2112674c7759.png)

**Comment by PillowMetal** [comment]
I have the same problem, but strangely it can be fixed if you just move the vault to the first/left instead of the last/right. But I prefer the latter rather than the former.

**Comment by Dazlaah** [comment]
Seems to be an issue still in IOS. Uninstalled several times and reinstalled but still the same issue. Will show vault and 2 characters in landscape view, 3 rd character appears right down the bottom after the vault.

**Comment by DMWill** [comment]
Same in Firefox.  But, changing the Vault to the left/first position does fix it, as @PillowMetal said.  I too prefer to have the vault on the right/last.  Guess this temporary fix will do for now.

**Comment by dasilva333** [comment]
Hey guys sorry for the bug, I tested it, and then tested it some more, and then broke it and released it. Again I apologize it should be resolved as of 3.8.1.5 make sure Auto Updates is enabled and try it out. If you're still having any issues let me know. Thanks everyone

**Comment by DMWill** [comment]
3.8.1.5 does not fix it for me.  Firefox, Chrome, and the standalone (Windows) all still have the vault displaying like in @Korben85's original pic.  Am I missing something?  I turned off auto-update, and then re-enabled it to no avail.  Three platforms wouldn't all be messed up without there being some shared issue, no?

**Comment by dasilva333** [comment]
@DMWill Thanks for the update I'll revisit it again today and make sure the Vault width is properly working

**Comment by Dazlaah** [comment]
It seems to be working fine for IOS now. Thanks Richard

**Comment by dasilva333** [comment]
@DMWill Try it now I added a fix as of 3.8.1.6 that should take care of the issue you were seeing. Let me know thanks

**Comment by DMWill** [comment]
Fantastic!  As of 3.8.1.7, all platforms I use regularly: Firefox, Chrome (and Opera), and the stand-alone are all functioning normally where the Vault/View layout is concerned.  Thanks a ton.

**Comment by dasilva333** [comment]
Alrighty I'm closing this ticket, thanks for the feedback and for letting me know when trouble arises. Have a good guys!
