### ISSUE TITLE
Version rollback from 3.8 to 3.7 ?

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#551]
I know I was on 3.8.x for a while, and now I'm back on 3.7.x, which is the Chrome store version. Auto updates don't upgrade, but it definitely looks like 3.8.x is the newest version.. What's going on?

**Comment by wickles** [comment]
I just fiddled with it a bit, turned off auto updates, refreshed, turned on auto updates, didn't seem like it was updating but I left and came back and it's updated again, now at 3.8.1.3. For reference it rolled me back to 3.7.5.3, not sure why.

**Comment by dasilva333** [comment]
Not sure, sometimes the auto update behaves strange when the server is being overloaded I think. It seems to be working now let me know if you're still having an issue. Thanks

**Comment by edmiller47** [comment]
Version rollback is happening to me repeatedly on Chrome - at least one or more times a day now, for about the last week. Currently at 3.8.6.5, but it keeps rolling back to 3.8.2.1. I have to disable auto updates and then re-enable it. If it starts up at 3.8.2.1 it doesn't auto update itself. Uninstalling and reinstalling TG from the Chrome store hasn't made a difference.

**Comment by wickles** [comment]
Try uninstalling and deleting all relevant files and folders in your Chrome user folder (search for the extension ID: gdjndlpockopgjbonnfdmkcmkcikjhge), then reinstalling. If that doesn't work you'll know there's a real problem :P
