### ISSUE TITLE
Chrome window is treated as MD size in View Options, no matter how wide I make it

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#552]
My chrome window under version 3.8.1.2 is now only showing me 3 columns, even though I have LG set to 4. I have to change MD to 4 in order to have my normal standard view back.

![image](https://cloud.githubusercontent.com/assets/12019978/12531106/87377b96-c1b8-11e5-96ad-82503120f064.png)

![image](https://cloud.githubusercontent.com/assets/12019978/12531107/98a2b6ca-c1b8-11e5-82aa-c3f09585136f.png)

**Comment by dasilva333** [comment]
Problem reported in issue #550 and fixed as of 3.8.1.5 sorry for that problem @weborican let me know if it's been resolved already for you. thanks

**Comment by weborican** [comment]
All is well once again, thanks!

Saw a few reporting the problem on reddit as well, so I knew I wasn't alone :-)
