### ISSUE TITLE
Sort by tier/type/rarity, AND light level / primary stat. 

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#553]
I've been wanting this for a while, and I noticed DIM has it now. I'd like my items sorted by rarity, then primary stat. See DIM's option for what I mean – basically you'd have all exotics first, regardless of light, but sorted by light within exotics. Then legendaries, sorted by light among themselves. Then rares, etc. 

AFAIK this isn't implemented yet but I would really appreciate it, seems simple enough :+1:

**Comment by wickles** [comment]
For reference, here are screenshots of the two related sort options in TGD versus the desired implementation in DIM. 

![screen shot 2016-01-23 at 12 49 47 pm](https://cloud.githubusercontent.com/assets/4229542/12532748/3f7574b2-c1d0-11e5-824e-f7457b92e4e9.png)
![screen shot 2016-01-23 at 12 49 53 pm](https://cloud.githubusercontent.com/assets/4229542/12532749/3f76b4c6-c1d0-11e5-8b22-f7fb5b733d86.png)
![screen shot 2016-01-23 at 12 49 59 pm](https://cloud.githubusercontent.com/assets/4229542/12532747/3f74e9de-c1d0-11e5-87aa-d9f89214f73d.png)

**Comment by dasilva333** [comment]
I'll add Tier, Light as an option for sorting. thanks for the feedback

**Comment by dasilva333** [comment]
New sorting options added as of 3.8.1.7 check it out and let me know if that's what you wanted. Thanks

**Comment by wickles** [comment]
Looks great now, thanks!
