### ISSUE TITLE
Incorrect magazine size in details

### ISSUE THREAD

**Issue by ccrotty** [dasilva333/TowerGhostForDestiny#554]
I have a Diluvian 10/4X machine gun in my inventory.  The game shows the magazine size as 74, but the TGD shows it as 30.  (Since it is a high ROF gun, I assume 74 is correct).

Attached is a snap of the gun details in TGD.

Thanks,
Chris

![image](https://cloud.githubusercontent.com/assets/1778973/12605128/cce87012-c48f-11e5-9d5a-1909224b1d8d.png)

**Comment by mistral13** [comment]
TGD shows only the DB and the magazine size is wrong in the Destiny DB 
http://db.destinytracker.com/items/3322979578-diluvian-104x.

**Comment by dasilva333** [comment]
@mistral13 thanks for the info however if the API is correctly returning the magazine size of the actual weapon that should be used rather than the DestinyDB info, @ccrotty do you mind posting your Share URL of your inventory? That will help with trying to determine the issue. Thanks!

**Comment by dasilva333** [comment]
I tested a few examples I know to be true with TGD and the game, turns out the magazine size is controlled entirely by the data I receive from Bungie/DestinyDB.com so if it's wrong it's just a matter of waiting for the appropriate party to fix it in their source. Thanks!
