### ISSUE TITLE
A Way To Lock View Settings?

### ISSUE THREAD

**Issue by DMWill** [dasilva333/TowerGhostForDestiny#555]
Enhancement:
I really love that there are so many ways to sort and view everything.  However, I prefer to have everything sorted by Light.  Someone else might like to sort by Type, and so on.  I also tend to use the filter box quite often or sort out just a certain weapon type.  Then the easiest way to get everything cleared off and back to normal, or default, is obviously "Clear Filters".  This clears off how I prefer to have it sorted all the time.  Is there anyway to add an option to lock certain filters so that it could ignore the "Clear Filters" button?  This is obviously not an app breaking problem, but more of something I've wanted to see in TGD but never thought it was really worth bringing up.  Thanks.

**Comment by dasilva333** [comment]
Not sure how this would be implemented, the easiest solution would be to prevent Clear Filters from clearing the Sorting, after all sorting is not a filter, perhaps in the future add a second button to say Clear Settings that resets the sorting too. What do you think of that idea? Let me know thanks

**Comment by DMWill** [comment]
I don't think that's a bad idea at all.  Just having two "clear" functions instead of one would possibly handle that.  The way I'd like it to work would be to leave the sort setting alone completely.  In a scenario where it's being sorted by light, and then maybe i'm showing all Auto Rifles, and then i filter to show all above 300 with ">300", I want to be able to clear off everything but the "sort by".  Would/could a second "Clear" function handle just the filter and any other filter-type settings, but leave the sorting setting alone?  If so, that's exactly what I'm looking for.

**Comment by dasilva333** [comment]
the sort filter is now locked, I'll opt out of a second clear button just for the sorting with a consideration for adding it later. let me know if you can confirm sort isn't reset by clear filter button as of 3.8.2.8. 
thanks

**Comment by DMWill** [comment]
This is perfect.  If you don't think having a clear button for sort is necessary, I am in agreement.  Thanks.
