### ISSUE TITLE
Place Holder icons

### ISSUE THREAD

**Issue by Baltezar** [dasilva333/TowerGhostForDestiny#556]
Since the recent patch in Destiny I am seeing 7 Placeholder icons in my TGD on my Windows Phone and even tried using the App in Firefox and it shows them there as well.
![clipboard01](https://cloud.githubusercontent.com/assets/17178283/12979377/3a8b5644-d09c-11e5-83c9-94cf814011ea.jpg)
Here is a Screenshot of the issue.

**Comment by DMWill** [comment]
looks to be fixed now with the addition of the Crimson Days items.  this is as of 3.8.4.0

**Comment by Baltezar** [comment]
Not seeing an update for windows phone yet, haven't checked Firefox though.

**Comment by DMWill** [comment]
Firefox is good :)  there was also an update for Android, but i didn't actually check it.  so let's assume a windows phone update can't be too far behind.

**Comment by Baltezar** [comment]
I can hope it's soon. Easier to do on phone than having to boot up the pc to use Firefox.

**Comment by Baltezar** [comment]
Not sure if it matters but I am using 8.1 windows phone.

**Comment by DMWill** [comment]
yeah i feel ya.  but i'm the opposite.  i prefer the pc over mobile.  doesn't hurt that my desktop sits feet away from my tv.

**Comment by Baltezar** [comment]
Checking back. Is there an update for Crimson Doubles coming for windows phone (8.1) anytime soon?

**Comment by Baltezar** [comment]
Still using version 3.8.2.0

**Comment by Baltezar** [comment]
Thank you for the update to WP version, working fine now.
