### ISSUE TITLE
Equip Gear with Highest: Light returns 0

### ISSUE THREAD

**Issue by MidnightNinja83** [dasilva333/TowerGhostForDestiny#557]
I was leveling my secondary character (Currently hunter 17) and selected the "Light" button in the Equip Gear With Highest group.  Instead of equipping the appropriate items, it is returning the highest available light level is 0.  Latest test with version 3.8.5

**Comment by dasilva333** [comment]
Can you provide me with the Share URL for your profile? Having this information will help me debug the issue. To get the URL simply click on Settings (cog icon) and click on Share URL with friends to display the link to share. Thanks!

**Comment by MidnightNinja83** [comment]
Absolutely: http://towerghostfordestiny.com/share/index.html?psn/MidnightNinja_83

Thank you for your contributions!

**Comment by rkingsla** [comment]
Ninja, you've GOT to do something about that poor Hunter. Not going to survive the Winter, I think....  ;o)

**Comment by MidnightNinja83** [comment]
I really do.  I started her a month ago and hit the bug.  It helped me realize how much I appreciate the light level and other gear selector helpers that make TowerGhost my go to.  Oryx or Crota would sneeze on me and I would be vaporized.  :-P  I'm hoping to level her soon :-)

**Comment by dasilva333** [comment]
@MidnightNinja83 I found and fixed the problem expect to see the fix in by tonight on 3.8.4.2 test it out and let me know if it's fixed. thanks

**Comment by MidnightNinja83** [comment]
You're the best.  

I see that 3.8.4.1 has been released on Chrome.  I'll check tomorrow for 3.8.4.2.  On my android phone and kindle I see version 3.8.5.  Out of curiosity, will your changes go across to that version as well?

**Comment by dasilva333** [comment]
@MidnightNinja83 try 3.8.5.1 now out in Auto Updates let me know if that fixes it for you. Thanks

**Comment by MidnightNinja83** [comment]
Sorry for the delay.  Everything works great again.  Thank you very much!
