### ISSUE TITLE
Endless cycle of refreshing on Android

### ISSUE THREAD

**Issue by Apolliyon** [dasilva333/TowerGhostForDestiny#559]
Sometimes, when the app encounters a situation it doesn't expect (for instance, I try to move a primary gun to a character. The app thinks primary weapons are full. In reality, primary is not full because I deleted an item) it will begin an endless cycle of refreshing. It will pop up little blue boxes saying "Success: Warlock Awoken 40 refreshed" (I forget the exact text) "Success: Titan exo 40 refreshed" etc over and over and over, for upwards of one minute. I usually have to completely exit the app and restart to fix this.

**Comment by dasilva333** [comment]
A lot of these problems have been resolve as of 3.9.0.7, Let me know if you still have this issue and I'll get it fixed right away. To check your version click on the top right corner of the app that says TGD.

Thanks!
