### ISSUE TITLE
Profile and items fail to load if Bungie.net profiles are linked to PSN/XBL services without a Destiny account

### ISSUE THREAD

**Issue by tylers** [dasilva333/TowerGhostForDestiny#56]
The extension loads, but stalls and displays blue loading bar if there's an error determining profile/system to use. 

The current try/catch throws an error when trying to handle *e.error* after *self.activeUser().activeSystem()* request.

The user can still select "Use Microsoft Account" (or PSN Account) from settings and the extension will behave properly.

Error found on chrome extension on OSX. Both PSN and XBL were linked on bungie.net, but PSN account had no related Destiny profiles.

**Comment by dasilva333** [comment]
I actually have the same setup using an XBL account linked to an empty PSN account and it works fine for me. If you could give me the exact error you're getting perhaps a copy and paste with line number or a screen shot that would be helpful thanks.

**Comment by dasilva333** [comment]
Can't reproduce the error, please produce some debug logs if it's still happening for you in the latest version and I'll reopen the ticket to look into it. Thanks
