### ISSUE TITLE
BC-Full vs BC-Quick

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#560]
According to the descriptions, if I'm understanding it correctly, BC-Quick should be a sub-set for BC-Full. If that is the case, how come I'm getting a single Tier 11 when I do a BC-Full:
![screen shot 2016-03-04 at 3 41 37 pm](https://cloud.githubusercontent.com/assets/12019978/13541135/10587fb0-e220-11e5-9c74-03cc82982363.png)

...but a bunch Tier 10 suggestions for BC-Quick?
![screen shot 2016-03-04 at 3 42 19 pm](https://cloud.githubusercontent.com/assets/12019978/13541156/2e707eda-e220-11e5-86b6-3cd6d7f5823e.png)

**Comment by dasilva333** [comment]
Not really a subset, more like a faster yet less accurate algorithm. BC-Full is still the way to go if you're looking for the T11 build. Congrats by the way that looks bad ass.

**Comment by weborican** [comment]
So... if didn't have anything to reach a T11 build, what would BC-Full show? A single T10 or all of those listed on BC-Quick? And, can we talk about those labels?  ;-)

**Comment by weborican** [comment]
Oh, and are you displaying everything in this order: Discipline, Intellect, Strength?

The "stat tiers" are ordered that way (Dis, Int, Str), but the "stat values" do not match any particular order

**Comment by dasilva333** [comment]
The difference between BC-Full and BC-Quick can be better explained in the Help guide, I'll also make sure to fix the order of stat values so it makes sense what you're looking at. To give you the full rundown here's how it works:
BC-Full: Analyzes all your armor, every single piece of armor for that class no matter where it is so it'll be able to find the T11 build regardless of what you do
BC-Quick: Analyzes only the armor on your character, sorts each bucket type, let's say Helmets by CSP (Combined stat points), and picks the top 2 (lets say Helmet #1 with 88 pts and Helmet #2 with 86 points), after that it sends this filtered list of items to the Best Combo algorithm to make what the best out of that filtered set.

**Comment by weborican** [comment]
Understood.

So, what are the limitations of what is listed for BC-Full then? Let's say I didn't have anything for that character to achieve T11 (apparently on the example above I only have 1 way to achieve T11), would it then show me combos (all of them?) for T10 instead?

In other words, do you **only** show the available combos **only** for the top tier you can achieve on that character?

**Comment by dasilva333** [comment]
Yes I only show you the combos for the top tier you can achieve on that character, however as you saw I'll only suggest T10 combos if the key item you need for T11 is not in the top 2 list by csp. Hope that makes sense. Let me know if you need more clarification. Thanks
