### ISSUE TITLE
Sugary Shell graphic not showing in Loadouts

### ISSUE THREAD

**Issue by SeethingSage** [dasilva333/TowerGhostForDestiny#561]
When I add my "Sugary Shell" Ghost Shell to an existing (or new) Loadout, the graphic for it isn't displayed in the Loadout pane at the bottom of the page.  However, the graphic shows up fine on each character and in the vault.  See attached screenshot.  Also, based on the URL I see when I hover my cursor on them, both links appear to point to the same image on destinydb.com.

I'm using the TGD 3.8.5.9 Chrome browser extension, running on a Win 7 64-bit PC.  I tried completely clearing the browser cache/history and restarting Chrome and TGD, but that didn't help.  Then I noticed that the same thing is happening in the Firefox version.  [The graphic shows up fine in the Android version].

![tgd_sugary shell graphic error](https://cloud.githubusercontent.com/assets/13490944/13586209/9e82a8c8-e48d-11e5-8986-92197a86eca7.png)

**Comment by dasilva333** [comment]
Thanks for the report, I'll get it fixed
