### ISSUE TITLE
Max Stat Point Percentage Incorrect When Viewing Armor By Combined Stat Points

### ISSUE THREAD

**Issue by jbarnett-r7** [dasilva333/TowerGhostForDestiny#562]
STR: 
1. Click the Armor dropdown 
2. Under View By select Combined Stat Points 
3. Mouse over a piece of armor

http://imgur.com/uEhYxEW

**Comment by dasilva333** [comment]
Try 3.8.5.12 and let me know if it's still an issue. Thanks!
