### ISSUE TITLE
Stat Roll % Inconsistency

### ISSUE THREAD

**Issue by anthonyrayton** [dasilva333/TowerGhostForDestiny#563]
Hello,

Just following up from my comment on Reddit as per your request:

I'm a little confused by the %'s I'm seeing. Please see the attached image for details, this is happening on all gear I've tapped.

Thank you!
![uuttmxv](https://cloud.githubusercontent.com/assets/17752007/13650814/1a37ba26-e60a-11e5-9b70-33423ebbdab2.jpg)

**Comment by dasilva333** [comment]
See issue #562 for more info, try 3.8.5.12 and see if u can replicate the bug w the tooltip for stat rolls, refer to the Help guide in app for details on what each value means

**Comment by anthonyrayton** [comment]
Resolved!

Thx
