### ISSUE TITLE
Armor stat % rolls not showing consistently with unleveled pieces

### ISSUE THREAD

**Issue by JokerSmilez** [dasilva333/TowerGhostForDestiny#564]
At least with the Chrome Extension, it is not properly showing %'s for unleveled gear. Sometimes it includes the bonus stat node, sometimes it doesn't.

![image](https://cloud.githubusercontent.com/assets/17788940/13713395/f5c0435c-e785-11e5-9b8a-11318da758f8.png)

In the above example, both chest pieces are currently unleveled and have a total of 103 stats at 310 which will be 106 at 320. The Armentarium includes the stat node of 24 at 320 when calculating the final % but the Crest of the Alpha Lupi does not so despite the total stats being the same, one is shown at 70-72% while the other is being shown at 90-93%.

**Comment by dasilva333** [comment]
Are you able to follow the instructions for manual chrome install? 

http://towerghostfordestiny.com/index.php/support/

If so please install Chrome manually from master and you should be on v3.8.6 once installed try the tooltip and you should see it say Stat Roll: base (normalized) %-% (x-x) for unleveled items. If you can't get it to install that's alright just let me know.

Thanks

**Comment by JokerSmilez** [comment]
I installed it manually following the instructions and it seems to be
working now with unleveled items.

However it now seems to be adding the bonus node twice on leveled items
when calculating expected rolls when infused to 320.

[image: Inline image 1]


--
-Tyler W.
c.403.200.8361

**Comment by dasilva333** [comment]
@JokerSmilez let me know if you still have problems with Stat Rolls and I'll reopen this ticket. Make sure to include a screenshot example or otherwise. Thanks!
