### ISSUE TITLE
Menu button (hamburger icon) not working on on iOS

### ISSUE THREAD

**Issue by weborican** [dasilva333/TowerGhostForDestiny#566]
It only works on landscape mode on iPad since it can show individual menu items at the top, but as soon as you need to consolidate everything under the "hamburger" icon, you can not longer access those items. You can see the tap registering on the button, but nothing happens.

**Comment by dasilva333** [comment]
I noticed that too this weekend, do you know if the problem started as of 3.8.6? I doubt the problem started when I fixed the iPad issue which is the last time i made a StatusBar change but I'll definitely check it out and get it fixed.

**Comment by weborican** [comment]
I'm not sure when the problem started, but I'm pretty sure it did not start after you fixed the iPad issue.
