### ISSUE TITLE
Cannot transfer heavy weapons

### ISSUE THREAD

**Issue by villiansv** [dasilva333/TowerGhostForDestiny#567]
Ever since the last update (3.8.6.3, tested both Firefox and Chrome), I can't transfer heavy weapons. I get an error message:

Cannot transfer XYZ because Heavy is full.

Neither character inventory, nor vault, is full, though.

**Comment by DMWill** [comment]
a workaround i found is to turn off auto-update and let it revert to the previous version.  hope that helps, for now.

**Comment by villiansv** [comment]
I personally switch to DIM when a showstopper bug like this pops up, but good to know.

**Comment by edmiller47** [comment]
I ran into this as well. Turned off auto-update and then turned back on, 3.8.6.3 reinstalled itself and I haven't had this error again. ??

**Comment by villiansv** [comment]
Toggled auto update off (went to 3.8.0.5 I think) - heavy transfer worked. Toggled it back on, updated to 3.8.6.3 - still no heavy transfer.

**Comment by dasilva333** [comment]
thanks for the update guys, can you detail exactly how you manage to reproduce this problem? Is it a xfer from character to vault? character to character? vault to character? Let me know the details so I can fix it thanks!

**Comment by villiansv** [comment]
did a bit more testing.

When Weapons vault is 62/72, I cannot transfer heavy to Vault or char to char. Vault to char works, and once vault is 63/72, everything works. 

As soon as I send a heavy back to the vault, so it's 62/72 again, char to char and char to vault stops working again.

If it matters, I have 10 heavies in vault when at 62/72. 5 actual weapons and 5 exotic engrams.

**Comment by dasilva333** [comment]
Try 3..8.6.5 and let me know if its fixed for you thanks!

**Comment by villiansv** [comment]
Seems to be working fine with 3.8.6.5. Thanks.

**Comment by DMWill** [comment]
yep, 3.8.6.5 does seem to have resolved the issue.  thanks :)
