### ISSUE TITLE
3.8.6.3 - Loadouts menu unsorted

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#568]
The loadouts menu used to be sorted alphabetically, but in 3.8.6.3 on Chrome the list of my loadouts is all mixed up. Editing a loadout and saving results in the list being scrambled into a different order.

This isn't happening on 3.8.6.3 on iOS - loadouts are listed there in alphabetical order.

Update: since 3.8.6.5 arrived via auto-update on Chrome and iOS, loadouts menu is un-alphabetized on both platforms.

**Comment by Chase100488** [comment]
what is the newest version of tower ghost?

**Comment by edmiller47** [comment]
Auto-update gave me 3.8.6.5

**Comment by Chase100488** [comment]
I Did The Auto Update And It's Stuck On 3.8.0.5 I Use Firefox LOL So I Have No Clue Whats Up With It

**Comment by dasilva333** [comment]
Closing this ticket in favor of issue #138 expect to see Loadout sorting fixed in 3.9.0.7 let me know if it's still a problem after that. thanks!
