### ISSUE TITLE
OFFLINE?

### ISSUE THREAD

**Issue by STBOSSO** [dasilva333/TowerGhostForDestiny#569]
Hey! I'm an user of TGD on chrome and iOS, but since April 1st the app is offline, can´t retrive any information about my itens. Today (april 4th) is still off, on both plataforms. There are no informationn on your twitter as well. Now I'm using DIM, but the TGD interface is so much better for me. Help! Thx

**Comment by dasilva333** [comment]
Are you getting a specific error message? What is the problem you are experiencing?

**Comment by STBOSSO** [comment]
Nope! No error code or message. When I click on the TGD icon on Chrome or the iOS app, the app says: "Info: Cheking for Updates". Nothing more.. the background appears, but nothing happen.

**Comment by STBOSSO** [comment]
Still having problems here! Any clue? The app was updated on iOS but still blank. I don't know what to do.

**Comment by dasilva333** [comment]
That is super weird! Have you tried uninstalling and reinstalling it? I'll be releasing a new version in the Chrome store soon that's 3.8.8 so I'll update this ticket once I do so you acn try it out

**Comment by STBOSSO** [comment]
Yes, many times! Now i'm trying to login on Firefox, but still the same problem. I've update all my browsers, and TGD not working. At last, I'm trying to login on my laptop, and the screenshot is attached. Nothing happen after that!
![image](https://cloud.githubusercontent.com/assets/18267693/14371262/4c37e12c-fd0c-11e5-923e-c50d170a75fd.png)

**Comment by dasilva333** [comment]
When it says Please wait loading arensal from Bungie, can you try to visit Bungie.net on a different tab and see if you're logged in? even if you are try logging out and logging back in then refresh Tower Ghost and see if that works. If all fails try running the Chrome version with an extra ?debug in the URL and then open the console and provide me with the logs in there. Thanks!

**Comment by STBOSSO** [comment]
Yes, i'm logged on Bungie. I can see on the tab.I can't refresh on app, the button does not work. If I refresh on browser, the app stop work at all, just like the first attach that i send. I'll do what you say!

**Comment by STBOSSO** [comment]
Here some errors 
![image](https://cloud.githubusercontent.com/assets/18267693/14432257/ba81e1ca-ffdf-11e5-93a9-960050357cc2.png)

**Comment by dasilva333** [comment]
thank you for the bug report, that will help me find a fix for your problem. I was unaware it was crashing at that point. from the console where it says "new manifest available" try typing in "tgd.version" and let me know what it returns. thanks, expect a debug version to be provided soon so we can figure this out. thanks

**Comment by dasilva333** [comment]
Alright I have a debug build ready for you to test, the way we're going to do this is you're going to install an unpacked Chrome extension,
basically you go into Settings > Extensions > enable developer mode > point it to the folder of the zip file provided.

Here is the manual Chrome install instructions:
http://towerghostfordestiny.com/index.php/support/

Here is TGD 3.8.7.9, make sure it says 3.8.7.9 when it opens to know you're testing the right build.
https://github.com/dasilva333/TowerGhostForDestiny/blob/div-movile-dist/tower_ghost_issue569.zip?raw=true

Once you got it open simply test to see if it loads, if it works great just let me know, if it doesn't then open the console (F12 key)
and provide me with any debug error messages just like you did in your last message.

Thanks!

**Comment by STBOSSO** [comment]
Hey! Thanks for send me this version, but I'm still getting blank page. Here the errors on debug:

Failed to load resource: net::ERR_FILE_NOT_FOUND
base-definitions.js:23 init auto updates
base-definitions.js:23 Checking for auto updates
base-definitions.js:23 refresh handler enabled
base-definitions.js:23 bungie.init
base-definitions.js:23 bungie.login
knockout.js:66 Uncaught TypeError: Unable to process binding "template: function (){return 'navbar-template' }"
Message: Unable to process binding "text: function (){return $root.activeText().menu_refresh }"
Message: Cannot read property 'menu_refresh' of undefined$element.text @ VM443:3a.d.text.update @ knockout.js:91function.a.j.q @ knockout.js:66l @ knockout.js:44a.w.a.j @ knockout.js:47(anonymous function) @ knockout.js:66a.a.o @ knockout.js:10g @ knockout.js:65h @ knockout.js:63k @ knockout.js:63h @ knockout.js:63k @ knockout.js:63h @ knockout.js:63k @ knockout.js:63h @ knockout.js:63k @ knockout.js:63h @ knockout.js:63k @ knockout.js:63h @ knockout.js:63k @ knockout.js:63h @ knockout.js:63a.ub @ knockout.js:69(anonymous function) @ knockout.js:103b @ knockout.js:102d @ knockout.js:103e @ knockout.js:104(anonymous function) @ knockout.js:105l @ knockout.js:44a.w.a.j @ knockout.js:47a.eb @ knockout.js:105a.d.template.update @ knockout.js:107function.a.j.q @ knockout.js:66l @ knockout.js:44a.w.a.j @ knockout.js:47(anonymous function) @ knockout.js:66a.a.o @ knockout.js:10g @ knockout.js:65h @ knockout.js:63k @ knockout.js:63h @ knockout.js:63a.ub @ knockout.js:69init @ app.js:2319j @ jquery.js:2k.fireWith @ jquery.js:2m.extend.ready @ jquery.js:2J @ jquery.js:2
cordova-app-loader-complete.js:210 New manifest available, but an earlier update attempt failed. Will not download.
base-definitions.js:23ajax complete
base-definitions.js:23bungie.login.complete, now getCookie
base-definitions.js:23bungied started with token 6741663287653760244
2base-definitions.js:23ajax complete
base-definitions.js:232 log request to "4611686018446136764"
4base-definitions.js:23ajax complete

**Comment by STBOSSO** [comment]
But now, when I click on the app button, on Chrome, I can see the top menu, print attached. I think app can't reach my inventory on bungie. I don't know. When I hit refresh button, app says my inventory is updated, but I can't see itens. Side menu apparently isn't work as well (attach 2)
![image](https://cloud.githubusercontent.com/assets/18267693/14462308/c6ce6724-009c-11e6-9a96-9403462ada86.png)
. I'm logged on bungie.
![image](https://cloud.githubusercontent.com/assets/18267693/14462236/74b32dee-009c-11e6-866d-cb3a04aaa74b.png)

**Comment by dasilva333** [comment]
Have you changed your language in Bungie.net? 
Have you changed it in TGD under Language? 
Did the problem just start happening suddenly?
In the console run these commands for me:

console.log(typeof app);
console.log(typeof app.activeText());
console.log(app.currentLocale(), app.locale());

Let me know of the results, once that's done try running this command:

localStorage.clear();
location.reload();

The app should hopefully start working after clearing the internal settings, good luck and let me know what the results are

**Comment by STBOSSO** [comment]
Yes.. I change the language on Bungie. I'll change again. Wait a minute.

**Comment by dasilva333** [comment]
Don't change it again until you run those commands from the console, it's important you provide me this information while the problem is happening so I can make sure it doesn't happen for others in the future. Please provide me with the language it's set to now also just so I can try to debug it from my side.

Thanks!

**Comment by STBOSSO** [comment]
Here are the results:

console.log(typeof app);
console.log(typeof app.activeText());
console.log(app.currentLocale(), app.locale());
VM664:2 object
VM664:3 undefined
VM664:4 pt-br pt-br
undefined

After clear, app is blank again. I went to the bungie settings and changed my native language (pt-br) to english and app is WORKING AGAIN! Problem was on the language on bungie's server? Let me know if you want to running other tests. I would be happy to help you, as you helped me on this issue. Many thanks!
![image](https://cloud.githubusercontent.com/assets/18267693/14463112/2eb05eb2-00a0-11e6-86e7-d15b970cf4e1.png)

**Comment by dasilva333** [comment]
Alright great! So just to recap it seems that when changing your language on Bungie.net to Portuguese it seems to cause a crash on my side, I'll debug it and get it fixed. Thanks for your help, you can switch back to the normal Chrome store version now that we figured out the problem. Thanks again

**Comment by STBOSSO** [comment]
Ok! Thanks again! Great app, by the way!
