### ISSUE TITLE
Loadouts have stopped working in Chrome app for me

### ISSUE THREAD

**Issue by flthrtl** [dasilva333/TowerGhostForDestiny#57]
Just came across your app this morning and was creating different load outs. They had been working for most of the morning but just recently have ceased to function. I can still move individual items but full loadouts don't swap. I've tried restarting, reinstalling, clearing cache and what not. No Luck. Saw on your other ticket you asked to see the errors from the console tab. Have attached a screenshot of the tab.
![screen shot 2015-04-17 at 2 15 41 pm](https://cloud.githubusercontent.com/assets/11998924/7209233/457b072e-e50c-11e4-8c60-13b5d4a5a875.png)

**Comment by dasilva333** [comment]
closing ticket in favor of issue #31 please leave any feedback there
