### ISSUE TITLE
Donation Not Working?

### ISSUE THREAD

**Issue by DMWill** [dasilva333/TowerGhostForDestiny#570]
Since you were absolutely on the ball today with the update :wink:, I was going to donate again.  However, both the android app and the standalone will not let me make donation with google.  Please see what's up so I can throw money at the screen.

**Comment by dasilva333** [comment]
will do thanks for the heads up, so what happens when you try to use the Google Pay links? Let me know thanks!

**Comment by DMWill** [comment]
In Firefox, there is no option for Google (Wallet or Pay).  Only a button for PayPal is displayed.  For the standalone Windows app, once you click on any of the Google options, it stays depressed like you're holding it down.  I'm not able to test android at the moment, but if I remember it correctly from yesterday, it was the same thing.  PayPal on the other hand, opens a new window.  That's great, but I don't want to use PayPal lol.  I was the guy who emailed you last year about adding the option for Google.  Let me know if there's something more I can do on this end.

**Comment by dasilva333** [comment]
Here's a recap of the donation options available per platform:

-Chrome: Google Wallet, Paypal
-Standalone: Paypal only
-Firefox: Paypal only
-Android: Google Wallet, Paypal
-iOS: Apple Pay, Paypal
-Windows Phone: Paypal only

I tested the standalone app and indeed the Google Wallet option is offered there despite being only available to the native Chrome app and Android.
Thanks for the bug report and the heads up, let me know if there's any other problems you see of if there's a different donation method you'd like to see be made available.

Thank you for your support

**Comment by DMWill** [comment]
I'll try Chrome then.  If it's the same, where I click and nothing happens, then that's all I can do.  Android wasn't working and neither was the standalone, despite it being there ;)

**Comment by dasilva333** [comment]
Try pressing F12 to reveal the console, open the console tab and then click on Small Donation and see if you're getting any error messages. I tried it myself as well in Chrome (only works in the Chrome Store version does not work if you install it manually as an extension from a folder) and it seems to work fine the following is a screenshot of what it should look like if it works properly:

http://i.imgur.com/UxuIcNf.png

Good luck and keep me updated. Thanks!

**Comment by DMWill** [comment]
Yep, it works like that in Chrome.  What happened to the option to pay with your PlayStore balance, or is that only available via the Android app itself?  Here's the thing... I have $$ on my playstore account and that's how I want to donate.  It's how I donated before.  I really don't want to use my PayPal or Google Wallet.  If it's only available to pay that way, I'll just have to wait until it works on the Android app again.

**Comment by dasilva333** [comment]
I haven't had a chance to test the android app I'll do so and make sure it's still working. Thanks for the heads up :)

**Comment by dasilva333** [comment]
I was able to confirm with 2 different parties that Android donations are still working, it could be an issue with your App Store or libraries installed. I know for my android device without the Google Play Store the donation button doesn't do anything so you could be in a similar situation. Let me know if that clears it up for you. Thanks!

**Comment by DMWill** [comment]
if by cleared up, you mean i am currently not able to donate the same way i have in the past, then yes.  yes, it's all cleared up.  lol.  my android device has the playstore.  however, it's about 4 years old.  i'm happy it runs TGD at all.  i'm going to install an emulator on my desktop and just do it that way.  thanks for looking into it though.

**Comment by dasilva333** [comment]
Here's the thing right, I want to fix this problem. But I haven't changed anything regarding donations and it still works for other people. Only thing I can imagine is something changed on your device between when it worked and when it didn't. I wish I had a good solution or advice I could provide you with to get this resolved. I think the emulator is a good idea, there's also other emulators you could try such as Andy I've tried it before with much success. Good luck
