### ISSUE TITLE
Place holder icons (classified)

### ISSUE THREAD

**Issue by Baltezar** [dasilva333/TowerGhostForDestiny#571]
Again with the recent update to Destiny there are several Place holder icons on the Windows Phone app. as well as the Vault space increase isn't in. would appreciate an update for the Windows Phone app.

**Comment by dasilva333** [comment]
I submit the app today it is 3.8.9.2, Microsoft has been rejecting my app recently so I haven't been able to get it updated. Let me know if you don't see it in the store by Monday. Thanks!
