### ISSUE TITLE
Armor Set Builder crash for 1	character (iOS) 

### ISSUE THREAD

**Issue by mistral13** [dasilva333/TowerGhostForDestiny#572]
Hi
Armor Set Builder "Max Tier" and "Character" crash for my Titan on my iPhone and iPad (only tested on iOS). 
For my 2 Warlock with more armor it work fine, also the "Top 3" and "Custom" Funktion work without a crash for my Titan.

Version 3.8.9.2

https://towerghostfordestiny.com/share/?psn/mistral75

P.S: @dasilva333 please update the version for "Share URL with friends". THX

**Comment by edmiller47** [comment]
I'm finding 3.8.9.2 crashes routinely on my iPad. It could be just sitting idle on the screen and after a couple of minutes, suddenly exits to the home screen.

**Comment by dasilva333** [comment]
Max Tier and Character perform intensive calculations based on the inventory found on your character, if you want to move certain armor pieces you dont want considered to the vault it will make it load faster and not crash. For now I dont have a good solution for reducing or preventing crashes under a heavy load. As for the routine crashes on 3.8.9.2 that should be resolved as of 3.8.9.5 let me know if you guys need any more help. thanks!
