### ISSUE TITLE
..remote control script?

### ISSUE THREAD

**Issue by The13erserker** [dasilva333/TowerGhostForDestiny#573]
Whenever I open the app it says,

 "ALERT. You will see this warning once per session...You are using a remote control script on this site. If you accidently push it into production, anyone will have control of your visitors browser. Remember to remove this script. "

Soooo, what is this and how do I fix it? Any help would be appreciated!

**Comment by dasilva333** [comment]
Thank you for the update, where are you seeing this message? Android, iOS, Chrome, Firefox? Let me know and Ill quickly fix this oversight thank you

**Comment by The13erserker** [comment]
Right when I first start the app..I'm not too sure what OS..im on my blackbeery classic

**Comment by The13erserker** [comment]
I'm seeing the message in the tower ghost btw

**Comment by dasilva333** [comment]
Can you click on the version in the top left corner that says TGD and tell me what the version is thanks

**Comment by The13erserker** [comment]
Well, I guess that new update you just did yesterday or today fixed it because I didn't see the message pop up when I opened the app... Thank you!

**Comment by dasilva333** [comment]
Great thanks!
