### ISSUE TITLE
Weird Issue 3.8.9.4

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#574]
Check out the weird numbers:

![image](https://cloud.githubusercontent.com/assets/2903357/14713197/2a5f6a50-07ae-11e6-81c4-d2f6d55cdd2d.png)

From DIM (just for clarity of what the items are supposed to be - verified in game):
![image](https://cloud.githubusercontent.com/assets/2903357/14713229/458ef228-07ae-11e6-8f3c-9a2933df8983.png)

**Comment by edmiller47** [comment]
Yup, experiencing the same thing. Quantities are correct when TG is first started, but this then happens.

**Comment by dasilva333** [comment]
thanks for the heads up guys I already got a fix for it in, expect to see it by tonight 3.8.9.5

**Comment by pattont** [comment]
Excellent! Thanks!


Travis

**Comment by dasilva333** [comment]
Fix has been deployed, let me know if there's still any issues
