### ISSUE TITLE
Share URL with friends version: non stat points

### ISSUE THREAD

**Issue by mistral13** [dasilva333/TowerGhostForDestiny#575]
Hi
Since the online version update (Share URL with friends version), i have some problems.
- I can't see the stat points when I activited "View by Combined Stat Point.
- The Tooltips don't show all information
 
![image](https://cloud.githubusercontent.com/assets/5049663/14734438/bfac58ea-086a-11e6-8fb1-89cd5affafc8.png)

**Comment by dasilva333** [comment]
Ill try to get that resolved soon, thanks for the heads up

**Comment by dasilva333** [comment]
Problem fixed, let me know if u still see an issue thanks

**Comment by mistral13** [comment]
Thx
