### ISSUE TITLE
3.8.9.5 iOS - Cannot apply loadouts

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#576]
With this version of the app, after selecting a loadout from the menu, the buttons to start the transfer do not function. I can still make changes to the loadouts, save, save as, close, etc, but cannot start a transfer. This is a huge problem for me, makes the app almost unusable. I have toggled auto updates, logged out and back in, and restarted my iPad, to no avail.

Plus, this version is EXTREMELY slow to load the loadouts menu, it's taking minutes.

Help.

**Comment by dasilva333** [comment]
Can you provide me a screenshot of the loadouts you're trying to use? Ive tested it with a few combinations and it seems to be working fine for me. As for the slow loading that's something I'm aware of and I'll try to improve in the future. Thanks for the feedback

**Comment by edmiller47** [comment]
![image](https://cloud.githubusercontent.com/assets/13838005/14744348/791435f6-0874-11e6-992d-be32275f9a3c.png)
This screenshot was taken on my PC but is one of the ones that doesn't work. The others all have similar numbers of items, and I can screenshot more of them if you like. Note that the problem only occurs on iOS.
I can't imagine how much time and effort you put into making this an outstanding tool so please don't misunderstand my complaint about performance. It just seems there was a pretty big drop in performance compared to the last version just a few days ago. Thanks for your quick response as always.

**Comment by dasilva333** [comment]
So you're saying the same loadout (A Raid Gear Titan), same version of TGD (3.8.9.5), works in Chrome but doesn't work in iOS? if that's the case let me know and Ill build a debug iOS version for you. Thanks!

Also I'm aware of the drop in performance recently it happened because I changed some major ways in which reloads happen which may or may not have affected the performance directly. Ill keep looking into that.

**Comment by edmiller47** [comment]
Oops - small correction - turns out I had 3.8.9.0 on Chrome (I'd had 3.8.9.5 installed, apparently it rolled itself back at some point). That loadout doesn't work on Chorme either. Let me be specific - when the loadout is displayed as in the screenshot, clicking (or touching) on the character icon to start the transfer does nothing.

**Comment by dasilva333** [comment]
I figured out the bug since I last posted a comment, thanks for the feedback expect it fixed by tonight's 3.8.9.6 version thanks

**Comment by dasilva333** [comment]
Problem fixed as of 3.8.9.6 let me know if you still have any issues thanks

**Comment by edmiller47** [comment]
Working now and faster... thanks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Richard PinedoSent: Friday, April 22, 2016 6:21 PMTo: dasilva333/TowerGhostForDestinyReply To: dasilva333/TowerGhostForDestinyCc: edmiller47; AuthorSubject: Re: [dasilva333/TowerGhostForDestiny] 3.8.9.5 iOS - Cannot apply loadouts (#576)Problem fixed as of 3.8.9.6 let me know if you still have any issues thanks

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub
