### ISSUE TITLE
Slow to start since the April update

### ISSUE THREAD

**Issue by zoowar** [dasilva333/TowerGhostForDestiny#577]
For about a week of so (maybe since the April update), TGD is slow to start. Basically, it hangs for about a minute after displaying "Info: Checking for updates". During this time media images are empty and often the app crashes. This is experienced in chrome running 3.8.9.5.

**Comment by dasilva333** [comment]
I'm aware of the problem and I'm working on ways to improve the situation. Thanks

**Comment by dasilva333** [comment]
Problem resolved as of 3.8.9.6 let me know if it's still slow and I'll reopen this ticket for you. Thanks!
