### ISSUE TITLE
BUG: Materials & Consumables not updating/refreshing properly (Android) 

### ISSUE THREAD

**Issue by Wh1rledPeas** [dasilva333/TowerGhostForDestiny#579]
When using the "double square" icon to transfer multiple Materials or Consumables to a character, the display does not update to show that the items are now on a new character. 

Upon tapping the refresh button next to those categories, the items and quantities are all messed up.

Sometimes they are all still there, but with a quantity of 1 for each. 

Doing a master refresh doesn't fix the problem. The only way to recover is to close the app and restart it.

**Comment by dasilva333** [comment]
So for example: 

double square icon > select heavy & special synth from warlock > click on titan character > prompt shows up > finishes > 
warlock still has synth? titan does not have synth? refreshing ruins the count for the warlock synth or the titan synth?

Let me know and I'll see if I can reproduce this problem. thanks

**Comment by dasilva333** [comment]
Problem fixed as of 3.8.9.6 let me know if you still have any issues thanks

**Comment by Wh1rledPeas** [comment]
Sorry for not getting back to you right away. Glad you tracked it down. Will wait for update.

**Comment by Wh1rledPeas** [comment]
STEP 1:  Add items from Hunter to the loadout transfer panel

Screenshot_2016-04-29-12-30-41.png
![screenshot_2016-04-29-12-30-41](https://cloud.githubusercontent.com/assets/3685437/14943475/8007ccd4-0fa8-11e6-9358-c49abaf0f16a.png)


STEP 2:  Transfer items to Titan

Screenshot_2016-04-29-12-31-36.png
![screenshot_2016-04-29-12-31-36](https://cloud.githubusercontent.com/assets/3685437/14943478/8ac6ec36-0fa8-11e6-8cb7-4314c87ea154.png)


STEP 3:  Confirmation that all items have been transferred. 

Screenshot_2016-04-29-12-32-30.png
![screenshot_2016-04-29-12-32-30](https://cloud.githubusercontent.com/assets/3685437/14943479/96a30b70-0fa8-11e6-9368-e028943d56c5.png)



STEP 4:  Reviewing items for Hunter shows that item counts have not changed...

Screenshot_2016-04-29-12-32-46.png
![screenshot_2016-04-29-12-32-46](https://cloud.githubusercontent.com/assets/3685437/14943481/a1187d38-0fa8-11e6-9ade-ca928b986dae.png)


STEP 5:  Manually refreshing Hunter.  (Notice that item counts are showing 1 of each) 

Screenshot_2016-04-29-12-33-10.png
![screenshot_2016-04-29-12-33-10](https://cloud.githubusercontent.com/assets/3685437/14943482/a94d3cfa-0fa8-11e6-9409-2fd7767e133f.png)


STEP 6:  Manual refresh of all items (Notice item counts are now 7 or 8 for each item)

Screenshot_2016-04-29-12-34-37.png
![screenshot_2016-04-29-12-34-37](https://cloud.githubusercontent.com/assets/3685437/14943485/b5a1a66c-0fa8-11e6-93d3-4efa4fd56f1b.png)
