### ISSUE TITLE
Unresponsive then crashing on Chrome and Firefox when clicking Max Tier and Character

### ISSUE THREAD

**Issue by alohafromhelll** [dasilva333/TowerGhostForDestiny#580]
When selecting either Max Tier or Character from the armor set builder Tower Ghost hangs then crashes.

<img width="1366" alt="screen shot 2016-04-23 at 1 11 57 pm" src="https://cloud.githubusercontent.com/assets/13604099/14763523/1e008052-0955-11e6-96c1-e80b330632f0.png">

**Comment by dasilva333** [comment]
That is normal and expected it is working as intended, when using Max Tier, Top 3 and Character buttons a lot of processing occurs underneath the hood to calculate the best combinations, if you prefer a quick loading tool to view the best combos you can use the Custom button. Thanks!

**Comment by Jangla** [comment]
Mine straight up hard crashes. No dialog to wait for completion.

**Comment by dasilva333** [comment]
@Jangla thanks for literally providing zero details as to which one works and doesn't work for you, as I said earlier it is working as intended, some buttons load quicker than others and some buttons might not load at all depending on how speedy your device is or isn't. Hope that clears it up for you, good luck

**Comment by Jangla** [comment]
Apologies for lack of detail.

Crashes on Character option 100% of the time.

Running:

Chrome 50 
OSX 10.11.3
iMac 3.4GHz i7
16GB RAM

**Comment by dasilva333** [comment]
If the character button isn't loading for you try moving things you know you won't need or use out of the character into the vault.
What happens underneath the hood is that a simple 7 item armor set combination becomes 127 possible armor sets that get analyzed for optimal stats.
Once you introduce multiple pieces of armor for each type the calculations grow exponentially therefore it takes a lot of time to process.
I just tried the character button on my machine and it loaded in under a minute, 4770K-i7 3.5 Ghz 16GB RAM Windows 7 YMMV.
