### ISSUE TITLE
updated calculateStatRoll with new formula implementation

### ISSUE THREAD

**Issue by mistral13** [dasilva333/TowerGhostForDestiny#582]
Hi
 I think, there is a fault in the updated calculateStatRoll implementation.
example: The Ram from kiosk 

- (36/32 int/str) - total : 68 + 15 Bonus =  83 @ 280LL
- (45/41 int/str) - total : 86 + 19 Bonus = 105 @ 335LL 
- TGD Info from 280LL - total : 77 + 19 Bonus = 96 

I compute the base stats with new formula from /u/iihavetoes 
new Base Stat= 36 + 1/6 * (335-280) + 32 + 1/6 * (335-280) = 45 + 41 = 86 (correct)

I think you compute like this:
new Base Stat= 36 + 32 + 1/6 * (335-280) = 77 (too low)

**Comment by dasilva333** [comment]
You are totally right man, thanks for catching that real and large oversight on my part, so the logic is duplicated in two areas one for calculateFutureRolls which was implemented property and calculateStatRoll which was implemented incorrectly. The fix has been put in, expect to see it in TGD 3.8.9.9 or in Github's master branch if you want to do a checkout. thanks!

**Comment by mistral13** [comment]
3.8.9.8 not fix the bug
![image](https://cloud.githubusercontent.com/assets/5049663/14835781/f27835d8-0c0b-11e6-843a-69eda36e9355.png)

**Comment by dasilva333** [comment]
problem fixed as of 3.8.9.9 let me know if there's still any issues left
