### ISSUE TITLE
Max tier not equipping as calculated

### ISSUE THREAD

**Issue by Jangla** [dasilva333/TowerGhostForDestiny#583]
Couple of screenshots to help:

http://puu.sh/owdf6/79b36ce205.png - Yay I have a T12 build in 5/5/2 configuration!
http://puu.sh/owdfN/f0981870ab.png - equipping
http://puu.sh/owdgo/a1045a029c.png - Oh. That's a T8 setup. WTF?

Not sure what else to add.

Selected Max Tier from the drop down. Overlay shows T12 possible in 5/5/2. Equipped reality not as expected.

**Comment by mistral13** [comment]
Is all of this gear updated and have max Light Level (335)
What Stat Roll % has all your equipped gear?

**Comment by Jangla** [comment]
Ah that's probably it - one of the pieces wasn't 335 yet.
