### ISSUE TITLE
Firefox will not update to a post April update version. It doesn't update past 3.0.8.5

### ISSUE THREAD

**Issue by derrickgw1** [dasilva333/TowerGhostForDestiny#584]
Firefox will not update to a post April update version. It doesn't update past 3.0.8.5 based on the internal number.

These are the things I've already tried
1. i have already toggled Auto update.
2. I have reinstalled Firefox and reinstalled the plugin.
3. I've unchecked Auto updated, deleted the plugin. Closed out of Firefox. Reopened. It Reinstalled the plugin and toggled the auto update feature
4. I've gone into the tools settings, add ons, and made sure updated is checked in the browser (as opposed to the app).
5. Tried to install manually from an xpi file according to the support page here 

I contacted support through email but unfortunately that didn't solve the issues. And was told "Firefox automatically updates on it's own after install TGD 3.8.5 from the store it'll automatically update itself to the latest version 3.8.9.5." So from the internal app number (top left & in the about section) it's still on 3.0.8.5. See pictures. As you can see from the pictures the app has "auto updates" checked. The app says "installing updates" but after it's done, None of the post April update changes are reflected (materials, buffs, weapons, armor). Images are not show, vault counts are still off, you can't transfer Post April weapons. All post April Update weapons say "classified" so you can't tell what the weapon is.
Here you can see it says "updating", "installing" but i when it's done there is no change. http://towerghostfordestiny.com/index.php/support/
![tower ghost two](https://cloud.githubusercontent.com/assets/18667888/14832553/b986228c-0baf-11e6-8f21-e4490af7e436.jpg)

I'm just showing this so you get that "auto update" is actually checked.
![tower ghost](https://cloud.githubusercontent.com/assets/18667888/14832567/ccb8404c-0baf-11e6-9f57-71def8cf3d87.jpg)

I've check support, and tried to navigate github to find an maybe a most up to date xpi file. No matter what I do my App does not show any of the new items. So I'm at a loss. Any help is appreciated. 

Thank you.

**Comment by derrickgw1** [comment]
Please help.

**Comment by dasilva333** [comment]
I think I should investigate why sometimes FIrefox doesn't Auto Update for users, I think @DMWill provided some instructions you can try to completely reset the plugin and it's internal cache, link is below: https://github.com/dasilva333/TowerGhostForDestiny/issues/520

**Comment by derrickgw1** [comment]
Thank you. I will try that. I will let you know if it was successful.

**Comment by derrickgw1** [comment]
Success. 

@DMWill 's didn't exactly work because the folder names were different but it led me in the right direction.

This is exactly what i did.

-Uninstalled Tower Ghost Plugin
-Restarted firefox.
-On the menu I went to "Help", clicked on "Troubleshooting Information"
-Scrolled down under "Extentions" for the Tower Ghost entry and took note of the "id" on the right which for me was "jid1-Lecsmv0nvgnC2g@jetpack"
-Scrolled back up to the top and where it says "Profile Folder" I clicked on "Show Folder"
-Opened the "Permanent" folder.
-deleted the resource+++jid1-Lecsmv0nvgnC2g@jetpack, the same id that i took note of above. 
-deleted the folder http+++towerghostfordestiny.com.
Note: when i deleted these folders there was NO folder titled "default". I don't know why but after reinstall there is "default" and the two folders above are in there. So for others i'm guessing the two folders may be located there the entire time.
-Restarted Firefox
-Went to the Firefox plugin page and downloaded the xpi file.
-Manually installed the xpi file
-Started Tower Ghost. It said updating but it stayed at version 3.8.0.5.
-Went to settings, and toggled "Auto Updates" off and then on.
-It downloaded a new update, 3.8.8.9.

So everything seems to be updated now. Post April items all show up and vault capacity numbers are all accurate too. I think whatever was wrong had to do with getting rid of that resource+++jid1-Lecsmv0nvgnC2g@jetpack folder. Mostly because when i only deleted the http+++towerghostfordestiny.com folder the plugin did not update. 

Thank you for the help. I appreciate it.

**Comment by dasilva333** [comment]
Thanks for your feedback, I created a new FAQ this morning for users on Firefox having issues found here:

http://towerghostfordestiny.com/index.php/hrf_faq/my-tower-ghost-is-stuck-on-an-older-version-on-firefox/

let me know if you still have any issues. thanks!
