### ISSUE TITLE
Firefox focus not on Transfer Amount like on Chrome

### ISSUE THREAD

**Issue by patchm00** [dasilva333/TowerGhostForDestiny#585]
Hello, i am pretty sure it did it nicely before a recent update but...when you select an item to transfer that has more than 1, the popup asks for the amount.  On Chrome, the # of items is highlights so you can just type in the number.  In Firefox, it is not so you have to go through extra steps and since I'm used to Chrome i just type "1" ENTER and it transfers everything.  What's odd is that i can't seem to double click to change the number either so i have to use the "-" or "+" or just transfer them all then back.  Seems like a focus problem?

thanks for all you do

**Comment by dasilva333** [comment]
expect it fixed in 3.8.9.10 let me know if it's still an issue by then thanks!
