### ISSUE TITLE
Firefox not showing all Materials

### ISSUE THREAD

**Issue by patchm00** [dasilva333/TowerGhostForDestiny#587]
Works in TG for Chrome, seems that when you have more than one stack of the same kind of materials, it only displays one of the stacks.  So, if i have two stacks of Relic Iron and 2 stacks of Wormspore for example, Tower Ghost only shows 1 stack of each and the total it displays is incorrect as well.  This leads to getting errors of it being full when it may only say it has 11 items.  I've attached screenshots showing TG display and inventory display of same character.
![inventory_display](https://cloud.githubusercontent.com/assets/13669869/14917571/cabee8b4-0ded-11e6-8f9c-1a3c848a83b5.JPG)
![tgdisplay](https://cloud.githubusercontent.com/assets/13669869/14917572/cac10d24-0ded-11e6-913a-bc8f410a6676.JPG)

thanks

**Comment by macnode** [comment]
Happening in latest Chrome and Firefox for me. Only displays one stack of each kind of planetary mats even if I have more then 200 of a specific type.

**Comment by dasilva333** [comment]
Thanks guys this is on the top of my list of stuff to fix I haven't had the chance to earn a stack of 200+ planetary items to be able to test this bug, once I do I'll be getting this fixed. Thanks again for reporting this.

**Comment by macnode** [comment]
Appears to have been resolved for me in TG 3.9.0.0 for Chrome

**Comment by patchm00** [comment]
I never had the issue in chrome, only in Firefox as my op stated.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by dasilva333** [comment]
Issue has not been resolved yet I am literally trying to earn marks to buy planetary mats to then be able to reproduce the bug and fix it. Probably will have a fix later on this week. Thanks guys

**Comment by Greg117** [comment]
Can confirm this same issue on Android as well.  The last few days I've had to run another app to transfer extra mats to the vault.  It also seems that when this bug occurs, it shows some item counts incorrectly as well.  For instance, it said I had 200 strange coins.  So when this bug occurs, I do not trust that area of the app.

**Comment by macnode** [comment]
Appears to be resolved

**Comment by dasilva333** [comment]
@macnode thanks for the update

if you or @patchm00  or @Greg117 notices any issues with transferring materials or consumables or displaying it properly let me know. I rewrote that entire section and hopefully it is now much more stable and bug free. Feel free to make a new ticket if you do see any additional issues.

Thanks!

**Comment by patchm00** [comment]
The only thing I noticed is now it defaults to transfer then entire stock you have in inventory rather than the number of stack you select.  For instance, if I have 750 worms pore and I select one stack of 200 , it pops up and defaults to 750 to transfer instead of the 200 it used to do.  Some may freak out if they don't look at the number (like I did the first time lol) as it looks like they lost stock



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
