### ISSUE TITLE
Normalization/consolidate window

### ISSUE THREAD

**Issue by Baltezar** [dasilva333/TowerGhostForDestiny#588]
The icons for vault and each character is supersized in the extras window. They are to big and overlap each other.

**Comment by dasilva333** [comment]
Can you include a screenshot of what it looks like for you? thanks!

**Comment by Baltezar** [comment]
Here is a ss.
![wp_ss_20160430_0001](https://cloud.githubusercontent.com/assets/17178283/14935735/dea1ae8a-0ea0-11e6-9ecf-f4052fb0bffc.png)

**Comment by Baltezar** [comment]
The latest update fixed it. It's back to the way it was before.

**Comment by dasilva333** [comment]
Great thanks!
