### ISSUE TITLE
Filter Weapon type then change to "All" and all dissappears

### ISSUE THREAD

**Issue by patchm00** [dasilva333/TowerGhostForDestiny#589]
Been an issue for me a while and don't know why i never reported it.   Does this on both the Chrome and Firefox addin.

**Comment by DMWill** [comment]
huh, that's weird.  i never noticed that on Firefox, which is what i use the most.  i always just use the clear filters when i'm done sifting through different weapon types.

**Comment by dasilva333** [comment]
Good catch expect the fix in the next version .12
