### ISSUE TITLE
Firefox Still Showing New Stuff As Classified 

### ISSUE THREAD

**Issue by Chase100488** [dasilva333/TowerGhostForDestiny#590]
All The New Stuff I'm Getting From The Update Is Showing Ass Classified So I Don't Know What is Which Would Like To Know If There Is A Fix For It And All

I Got A New Ghost And It Didn't Even Show Up In Tower Ghost So IDK

**Comment by Chase100488** [comment]
So Ur Just Gonna Close It Instead Of Telling Me How to Fix It?

**Comment by rkingsla** [comment]
A) No one owes you an explanation. If it's been reported by others, it gets closed. He only needs one bug report. Go look at the open bugs and see if it's been reported already. Would you rather have Richard fixing things or explaining why he's closing things? Me == Fixing stuff.
B) Possibly he's offended by Ass Classified. IDK.
C) Why All Camel Case? It's Weird.
