### ISSUE TITLE
Calculation time optimization

### ISSUE THREAD

**Issue by mistral13** [dasilva333/TowerGhostForDestiny#591]
An idea to optimize the Set Bulider.

One of the most timespending functionw is the tgd.joinStats.
And insinde this function the 2 loops.
If you use "For" Instead of "Each", it should reduce the runtime a lot.

http://www.sitepoint.com/speed-question-jquery-each-vs-loop/

**Comment by dasilva333** [comment]
thanks for the suggestion, i'd be interested to se how you profiled what is taking the most time, in my opinion it is the tgd.cartesianProductOf that takes the most time, I'll def check it out thanks, just FYI tho I'm using underscore _.each loops not a $.each loop.

**Comment by mistral13** [comment]
I use firefox or chrom with their onboard developer tools. I try to test with the different Armor Set Bulider function. The long runtime often is a problem to make a good profile without a browser crash. The compressed JS are also a challenge.

At the moment tgd.cartesianProductOf takes “only” 2% runtime, tgd.joinStats over 20%.


![time](https://cloud.githubusercontent.com/assets/5049663/15008112/3f7613fa-11de-11e6-90f5-920fa536e197.PNG)

**Comment by dasilva333** [comment]
That's very interesting I'll try to debug that myself as well and see if I can make any improvements, if you'd like to further debug non-compressed and minified code you may always check out master, let me know if you need help getting it running.

**Comment by mistral13** [comment]
Hi

This is my improvement for the calculation time optimization.
I have some  problems to debug the code.
Could you please review and test the function,
I think it should reduce the runtime a lot
THX.  


```
tgd.joinStats = function(arrItems) {
	var tmp = {"Intellect":0, "Discipline":0, "Strength":0, "bonusOn":""};
	for ( var i = 0, len = arrItems.length; i < len; i++ ) { 
		if (arrItems[i].activeRoll) {
			var item = arrItems[i].activeRoll			
		} else {
			var item = arrItems[i].stats;			
		}
		for ( var key in item ) { 
			temp[key] += item[key];
		}	
	}; 
	return tmp;
};

```

**Comment by dasilva333** [comment]
@mistral13 send me your email to support@toweghostfordestiny.com or post it here and I'll send you an invite to the Tower Ghost slack group, there we can talk about your changes, test it and debug it.
Let me know thanks!

**Comment by mistral13** [comment]
You've got mail. 

This is my improvement from the improvement.
This reduce the runtime a lot.

```
joinStats = function(arrItems) {
	var tmp = {"Intellect":0, "Discipline":0, "Strength":0, "bonusOn":""};
	for ( var i = 0, len = arrItems.length; i < len; i++ ) { 
		if (arrItems[i].activeRoll) {
			var item = arrItems[i].activeRoll;			
		} else {
			var item = arrItems[i].stats;			
		}
		tmp["Intellect"] 	+= item["Intellect"];
		tmp["Discipline"] += item["Discipline"];
		tmp["Strength"] += item["Strength"];		
		tmp["bonusOn"] += item["bonusOn"];
	}; 
	return tmp;
};
```

**Comment by dasilva333** [comment]
Thanks for all the optimizations @mistral13 you've done a terrific job so far, let me know if there's any more improvements you have in store via Slack. Thanks again
