### ISSUE TITLE
3.8.9.12 Empty loadouts menu

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#592]
My loadouts menu is empty - just has manage, create, cancel options.

**Comment by dasilva333** [comment]
SSL certificate expired, getting it back up thanks

**Comment by pattont** [comment]
ohh I miss TG so badly :-). Hope the cert fix is coming soon!

**Comment by Chase100488** [comment]
Hey @dasilva333 What Does The SSL Mean? I Don't Know Anything About Computer Terms LOL Firefox Is Also Saying Insecure Connection To Tower Ghost So I'm Totally Confused LOL

**Comment by dasilva333** [comment]
@Chase100488 it means TGD for Firefox will be broken until I get this thing fixed on my side

**Comment by Chase100488** [comment]
Oh Allright I'm Sorry U have Alot Of Stuff To Deal With Man But I Love Using Ur Tower Ghost Feature And I Like The Whole Um Farm Mode Thing To Thats A Nice Touch I'll Just Keep Checking Back To See How It's Going With It

**Comment by zoowar** [comment]
Just in case you didn't know about letsencrypt https://letsencrypt.org/

**Comment by Chase100488** [comment]
yeah all that stuff gives me a headache I am not good with coding and such but @dasilva333 knows what he is doing he should have it fixed in no time

**Comment by dasilva333** [comment]
SSL certificate has been installed, all services returned to normal. Let me know if anyone is still having an issue. thanks

**Comment by edmiller47** [comment]
Looks good, thanks. Now if you could just get that loadouts menu to sort alphabetically, ‎I'd be happier than a hog in you-know-what...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Richard PinedoSent: Thursday, May 5, 2016 1:16 PMTo: dasilva333/TowerGhostForDestinyReply To: dasilva333/TowerGhostForDestinyCc: edmiller47; AuthorSubject: Re: [dasilva333/TowerGhostForDestiny] 3.8.9.12 Empty loadouts menu (#592)SSL certificate has been installed, all services returned to normal. Let me know if anyone is still having an issue. thanks

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by tribblehelix** [comment]
my issue, stuck on checking for update has been resolved.  many thanks for the prompt attention to the issue.
