### ISSUE TITLE
3.6.9.0 Unable to update from new windows installation

### ISSUE THREAD

**Issue by erwjack** [dasilva333/TowerGhostForDestiny#594]
hello,
due to new pc I reinstalled TGD from the W32 download that reports a 3.6.9.0 release.
I can't see any item on my pgs and it seems impossible to update to 3.8.9.12 due to a "manifest timeout". "Auto update" option is enabled.
Same issue with the w64 TGD download.
Thanks in advance for your kind reply.

ej

**Comment by dasilva333** [comment]
My server is having problems with an expired certificate, it will be up shortly, please track issue #592 for any future updates on the issue
