### ISSUE TITLE
stuck on looking for update

### ISSUE THREAD

**Issue by tribblehelix** [dasilva333/TowerGhostForDestiny#597]
click the chrome icon > tower ghost tab opens, the green stripe loading bar is static, message "checking for update" is displayed, remains frozen there until chrome asks to kill it.

checking the chrome store feedback i am not alone in this issue.  updated to the most recent 3.9 version, but issue was occuring on prior version as well.

**Comment by dasilva333** [comment]
issue being tracked as part of ticket #592 thanks
