### ISSUE TITLE
Website Security Certificate has expried.

### ISSUE THREAD

**Issue by ultra1437** [dasilva333/TowerGhostForDestiny#598]
The security certificate for towerghostfordestiny.com has expired.  Firefox threw me this screen and won't let me go on without adding an exception.  Figured I'd let you know.

[Imgur Link](http://imgur.com/S1ysNbM)

**Comment by Chase100488** [comment]
that is the same thing i got it and trust me he knows about it and is working to fix it so please be patient

**Comment by dasilva333** [comment]
working on a fix, tracking issue on #592 thanks for your feedback
