### ISSUE TITLE
app doesn't load completely

### ISSUE THREAD

**Issue by Baltezar** [dasilva333/TowerGhostForDestiny#599]
After this recent update(windows app) the app doesn't finish loading. It goes through the arsenal load, then to the login but after that it stops and doesn't finish loading the profile. Here is a screen sho of where it stops.
![wp_ss_20160505_0001](https://cloud.githubusercontent.com/assets/17178283/15044916/3f68a44e-129d-11e6-95ed-060450bd8e74.png)

**Comment by dasilva333** [comment]
Expect this fixed by tonight, my deepest apologies for the unforseen issues.

**Comment by Baltezar** [comment]
Np, things happen. Thanks for all your hard work.

**Comment by dasilva333** [comment]
3.9.0.1 submitted to the MS App Store you should be seeing it by tonight or tomorrow morning, let me know if it works for you. Thanks!

**Comment by Baltezar** [comment]
Thank you, it's working again. It also fixed the normalization/consolidate window.

**Comment by plunginghornets** [comment]
Having the same problem. Also on Windows phone. I would post screenshot, but it is exactly the same as above.
