### ISSUE TITLE
Include Kiosk Exotics when adding Vendor Armor in Custom

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#600]
Thank you SOOO MUCH for adding the vendor gear in there to see what I can buy to help my builds out. Is it possible to get the exotics in there that are re-rolled each week from the kiosk? Not sure if that is something available to you in the API or not.

**Comment by dasilva333** [comment]
Sounds interesting, I didnt know they were rerolled each week. I'll look into the API to see if it's possible. Thanks for the feedback

**Comment by pattont** [comment]
Yea, I always check each Tuesday for better rolls on things I have since infusion is 1:1 now. Not been a huge concern, but if they have the right roll + stats then you can save yourself the materials and glass needles.

**Comment by dasilva333** [comment]
I just checked it's possible to add it, 94% roll on the celestial nighthawk ;) expect to see it in 3.9.0.1. Thanks

**Comment by pattont** [comment]
SO AWESOME!!!! Now I can check each char on Tuesday SUPER EASY! Can't wait
for 3.9.0.1


Travis

**Comment by dasilva333** [comment]
@pattont 3.9.0.1 has been pushed live to Auto Update channel, check it out and let me know if there's any issues. thanks!

**Comment by pattont** [comment]
@dasilva333 Just updated and it looks great. My only suggestion is you could probably remove the Y1 stuff from the vendor selection. Also, put a note somewhere in the popup that states the Vendor Exotics change weekly - so come back and keep checking. I swear I tell that to people (like I did you earlier) and it's always a surprise. I guess I read DTG and CP Reddit way to much!

**Comment by dasilva333** [comment]
Yeah I personally didn't even know the exotic armor rotated on a weekly basis, defintely good SGA i'll include it inside the Help button at the Custom prompt. Good suggestion I'll get rid of the y1 armor options. Thanks!

**Comment by pattont** [comment]
@dasilva333 Dude you are so awesome! I swear every party I get in when I am swapping chars I'm like, Do you guys use Tower Ghost? So many have never heard of it and I tell them about loadouts and they instantly go load it. SUCH a great product!

**Comment by pattont** [comment]
@dasilva333 Thought of a couple of more vendors - Varik's class items do not change, but eventually I could see you putting in Iron Banner gear when it rolls when it comes around. I know last IB the Titan boots had a 99% int/dis roll!
