### ISSUE TITLE
custom layout vault and other character

### ISSUE THREAD

**Issue by mistral13** [dasilva333/TowerGhostForDestiny#601]
Hi

Is it possible that we could have options to add the vault and other characters in the custom layout (like the vendors). Only the year 2 armor from the vault.

THX

**Comment by dasilva333** [comment]
issue already tracked as part of ticket #600 thanks for the feedback

**Comment by mistral13** [comment]
Hi
In #600, i don't find somthing about armor from the vault and from other characters.
Is this already implementet in 3.9.0.1?

**Comment by dasilva333** [comment]
Sorry at first glance I thought I understood the request now I realize I have no clue what you mean, please expand on the request so I can consider the feature enhancement. Thanks

**Comment by mistral13** [comment]
Ok try.
If you start the costom layout/function you see only the armor from this character.
With the button "Vendor Itme" could i add the armor and items from the different vendors.
I have 2 warlock and a vault with a lot armor.
I want a button to add my armor from the vault for this character (only year 2 item) and a button to add the armor from my other character.
Example: my best chest i in the vault and my best helmet is on my second warlock. With this two button, could i add this armor to the custom tool.

**Comment by dasilva333** [comment]
Oh okay cool I had someone else make a similar request on /r/TGD so I'll make this as an enhancement take care of it some time. thanks!

**Comment by dasilva333** [comment]
Requested completed as of 3.9.0.7 you can now use the Custom button to add existing or new/fake items to the comparison tool. Thanks for the feedback, let me know if there's any issues.

**Comment by mistral13** [comment]
Thx
A lot of work handwork if i want use my gear.
Please, could you add a selection "all items" at the Item name box?

**Comment by dasilva333** [comment]
@good suggestion, expect that in tgd 3.9.0.8 thanks!
