### ISSUE TITLE
Loadout Ordering

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#602]
@dasilva333 can we get some sort of Loadout Ordering? Alphabetical is fine, our personal ordering would be better, but obviously more complicated for you. 

I just have some loadouts like "Hunter - Nightstalker - ToO" and it would be nice to put the class specific loadouts toward the bottom of the Loadouts list or move them under the class specific flyout menu where the buttons for loadouts are. Either way, I think the Loadouts menu needs some sort of ordering.

Thanks in advance!

**Comment by dasilva333** [comment]
Issue already tracked as part of ticket #138 please check existing issues before opening a new one thank you
