### ISSUE TITLE
could not load definition loop

### ISSUE THREAD

**Issue by folksyjester** [dasilva333/TowerGhostForDestiny#604]
3.8.9.12

tower ghost loads in with message to report bug here.

![screenshot 1](https://cloud.githubusercontent.com/assets/19233468/15089871/4219101c-13c3-11e6-89a0-4d7205ab0d51.png)

**Comment by dasilva333** [comment]
Should be fixed, let me know if it just works for you or if you had to clear anything to get it to work again. Thanks!

**Comment by folksyjester** [comment]
still does not work, same problem
