### ISSUE TITLE
Perk Images Not Loading

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#605]
![image](https://cloud.githubusercontent.com/assets/2903357/15189945/66ab5e2e-177b-11e6-9ff0-eda8493c1f54.png)

On all gear / weapons the perk images aren't loading. Issue on your end?

**Comment by dasilva333** [comment]
Thanks for the heads up, expect it fixed within the next hour, let me know if it's still an issue after that. 

thanks again!
