### ISSUE TITLE
Tier 12 Issue

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#606]
I was able to obtain 4-4-4 and 2-5-5 on my hunter yesterday using your tool which is AWESOME, but I saw one thing that threw me off a bit.

According to Tower Ghost the Hunter Vanguard has these gloves and moving them to 335 should net a 98% roll which would be excellent. 

![image](https://cloud.githubusercontent.com/assets/2903357/15225940/a3d22ab6-184e-11e6-8c91-b1ea1cffd923.png)

Unfortunately, I bought these gloves, maxed them out, and then infused them to 335 only to find this:

![image](https://cloud.githubusercontent.com/assets/2903357/15225952/b07b6390-184e-11e6-884f-b32140c9ce54.png)

Now they are 95% roll and aren't Tier 12 compatible. Basically, my Tier 12 gloves that get me the 4-4-4 have hand cannon reload and I wanted some pulse reload gloves. Well, after seeing that the vendor had a great roll I thought I was going to be a 1:1 swap to these given the handcannon gloves are int/dis just like these.

Any thoughts on the reason why TG says it's a 98% and then when it's infused it's not?

**Comment by dasilva333** [comment]
Here's a good relevant recent link:
https://www.reddit.com/r/DestinyTheGame/comments/4iptmv/dim_vs_tower_ghost_roll_accuracy/d32xysz?context=10000

**Comment by pattont** [comment]
Holy crap you guys threw down. Alright, after reading through that it makes sense. It's not like I'm out anything except marks so it's not a big deal. Next time I will open up TG and DIM to get an average and make a judgement call. I had assumed (I know.. ass out of you and me) that the numbers shown from the vendor item were good to go.

Funny part is the gloves that give me 4-4-4 aren't 97% either but since I have some items that are higher than 97% it offsets my lack in the glove slot. I thought I was gonna win because the perfect roll on the vendor gloves and being green. 

Thanks for getting back with me.

**Comment by weborican** [comment]
This is right up my ally, so I'm adding myself to the convo.

**Comment by dasilva333** [comment]
As of tgd 3.9.0.7 predictions like the Bog Wild 1.0 should be more consistent and more accurate. Try it out. I checked it out today and instead of predicting 97 pts it's now predicting 96 pts, it's gotten more accurate with an error margin of 2 instead of 3 so be warned there will always be a discrepancy.

Thanks guys

**Comment by pattont** [comment]
Richard,

Thank you so much for all your hard work. Looks like the only issue I see
is the icons for each gun/armor perk aren't loading again. I'm guessing
that's on your end because it also said something about unable to check for
updates because of an issue with the manifest.





Travis
