### ISSUE TITLE
"Could not load item definitions, please report the issue to my Github including the version number being used."

### ISSUE THREAD

**Issue by miriax** [dasilva333/TowerGhostForDestiny#607]
I'm getting the error "Could not load item definitions, please report the issue to my Github including the version number being used." in Firefox with version 3.9.0.3. Please help?

**Comment by dasilva333** [comment]
You should be on 3.9.0.4, try to uninstall, reinstall, under settings enable/disable auto update. If all else fails you may follow these instructions to completely reset your app:

http://towerghostfordestiny.com/index.php/hrf_faq/my-tower-ghost-is-stuck-on-an-older-version-on-firefox/

Good luck and let me know if you still have issues, thanks!
