### ISSUE TITLE
Enhancement: Improve performance by only considering equipped ghost shells

### ISSUE THREAD

**Issue by Jangla** [dasilva333/TowerGhostForDestiny#608]
Right now, most build algorithms seem to examine every single ghost shell across the account: http://puu.sh/oQe6O/eaf85a12bf.png

Would performance be improved by only considering those equipped on a character?

At the moment I have minimised everything to have 2-3 armour pieces on my character and the app crashes when trying to do a "Character" analysis. I think it may be due to the admittedly large number of ghost shells I have across my account. Bear in mind, the character only has 4 shells in it's inventory: http://puu.sh/oQee2/12c0ca4155.png

**Comment by dasilva333** [comment]
@Jangla can you provide me the armor view for the character that is crashing when you try to do a Character analysis? 

Here's what my Ghost shells look like:
http://i.imgur.com/jxXOgbu.png

The goal of the armor set builder tools is to allow you to exclude armor by placing it outside the character, the ghosts are the only exceptions as they work with any character. If you have too many Ghosts I suppose that could be an issue. Ill have to consider how I can improve the UI to provide options to only include Character-items or include class-wide items.

Thanks for the feedback!

**Comment by Jangla** [comment]
Here's the Armour currently equipped to the Hunter: http://puu.sh/oQtmY/2768dfd807.png

Machine details:
iMac, Intel Core i7 3.4 GHz
Memory:	16 GB

**Comment by dasilva333** [comment]
And it crashes for you when you try to use the Character button for your Hunter? Thanks let me know

**Comment by Jangla** [comment]
Yes. Also just tested on IOS 9.3.1 iPhone 6. Also crashes.

**Comment by dasilva333** [comment]
Suggestion integrated into Tools section for stats display as of TGD 3.9.0.10. Thanks!
