### ISSUE TITLE
Bug: Icons in "Item List" view are broken

### ISSUE THREAD

**Issue by Jangla** [dasilva333/TowerGhostForDestiny#609]
http://puu.sh/oQtlZ/8221f60ec4.png

Additional: when you flip back to "Image Grid", each armour class area doesn't resize to match the other characters: http://puu.sh/oQtBG/83d7325dd1.png

Refreshing the page returns the view to expected layout: http://puu.sh/oQtFe/c8a5bb5f09.png

**Comment by dasilva333** [comment]
Problem fixed as of 3.9.0.5+ let me know if it's still an issue for you. thanks
