### ISSUE TITLE
Now - Chrome not showing all materials

### ISSUE THREAD

**Issue by patchm00** [dasilva333/TowerGhostForDestiny#613]
Well, i found this bug in Firefox a while back and you fixed it, with 3.9.00 i find it is an issue in the Chrome addin as well.  Seems that when you have more than one stack of the same kind of materials, it only displays one of the stacks. So, if i have two stacks of Relic Iron and 2 stacks of Wormspore for example, Tower Ghost only shows 1 stack of each and the total it displays is incorrect as well. This leads to getting errors of it being full when it may only say it has 11 items.

**Comment by dasilva333** [comment]
Click on the top left corner where it says TGD and ensure you are running TGD 3.9.0.7. If so please provide some examples as to how to reproduce the problem, otherwise  upgrade to get your problem resolved. Good luck!

**Comment by patchm00** [comment]
oops,so sorry, some reason my autoupdate got turned off.  works fine
