### ISSUE TITLE
Loadout menu items move to bottom of list when updated

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#614]
Thank you thank you thank you for providing the ability to rearrange the order of the items in the loadout menu!

The issue I'm reporting is that when making a change to a loadout, that loadout moves to the bottom of the list, so I then have to move the item back to the spot where I had it originally. TG knew where the item was before it was updated, seems that TG should take care of that.

**Comment by dasilva333** [comment]
Thanks man will fix

**Comment by dasilva333** [comment]
Problem fixed as of TGD 3.9.0.9 or 3.9.0.10 but either way it's resolved, let me know if you still have any issues. Thanks!
