### ISSUE TITLE
I cannot check for updates anymore after today's Destiny update.

### ISSUE THREAD

**Issue by YogoH** [dasilva333/TowerGhostForDestiny#615]
Hello. This is my first post, I apologies if that is not the correct section. In short, the app says: Could not load item definitions, please report the issue to my Github including the version number being used. It shows every time I try to check for updates; deactivating the Auto update under Settings fixes it. Version is 3.9.0.0 and I am using Google Chrome. I do not know what exactly it is but I wanted to report it nonetheless; I thought it may be a serious issue. Kind regards. :)

**Comment by xXProphet56Xx** [comment]
I'm having the same issue. Same version and internet browser....Hope it gets fixed asap or at least to find some other way to get rid of this issue :)

**Comment by rkingsla** [comment]
To clarify, if you uncheck the Auto-Update and then select Auto-Update, it DOES fix the issue and the update downloads? If so, it's a long known issue and a known workaround. If it's a consistent issue that does NOT let you complete the update - that would be new.

**Comment by YogoH** [comment]
Hey rkingsla, unfortunately unchecking and checking Auto update did not solve this issue; uninstalling and reinstalling Tower Ghost did not solve it as well. I do not know if this happens on Mozilla and cell phones too. It repeatedly tries to check for updates but constantly shows me the message "Could not load item definitions, please report the issue to my Github including the version number being used". The only fix for my issue is to completely uncheck Auto update, only this works. I truly hope it is nothing serious. Thanks and regards. :)

**Comment by rkingsla** [comment]
I 'm not 100% certain, but this may the reason... Frankly, I'm somewhat surprised you're seeing this. Chrome user (test iOS, Firefox, and yes - Windows Phone 10.... :o)

As a quick question , you are downloading from the Chrome store, yes? I fork the code and download via a Git client. If you're loading directly from source, take a quick look at this and see if it might provide some relief (Ignore if you are getting the current build from Auto-Update or from Chrome Store...): 

Editing CSS

Go to the build directory of the project (cd build)
First you need to make sure you have Node.js
Run npm install -g grunt-cli
Run npm install -g grunt-init
Run npm install
Run bower install
Run grunt dev to watch the /www/scss folder to build the scss changes
NOTE! If you make changes to the SCSS, you need to run grunt prod before you put in your PR, so it has a production build of the SCSS (aka, no source maps)

**Comment by YogoH** [comment]
Hello. 10 days after your response rkingsla, I have the same issue: "Could not load item definitions, please report the issue to my Github including the version number being used".
I have tried on Firefox also other than Chrome, version 3.9.0.7; I get the error on that browser as well.
I know nothing about all that editing CSS stuff. Yes I have downloaded from the store; I even tried to fork the code and install it but I do not know how to do it.
I do not know what is causing the issue but a colleague of mine is reporting it as well on Google Chrome.
It works perfectly on my smartphone but I use the phone for other things, also it is already hard for me to use Tower Ghost on my laptop so the phone version of the app is out of question.
Thanks in advance for any response. If you need further info please let me know. Kind regards.

**Comment by dasilva333** [comment]
@YogoH are you still having issues updating to the latest version? You should be on TGD 3.9.0.10. Let me know if you still have any issues and if so on what browser the issue is in.Thanks
