### ISSUE TITLE
Suggestion for vendor stat rolls page

### ISSUE THREAD

**Issue by jkewley** [dasilva333/TowerGhostForDestiny#616]
First of all - thanks for building this tool - it's incredibly helpful. I wasn't sure where to put this since you added the link to it in the latest version, so I'll put it here.

I would suggest adding a new column to the grid which identifies the class type when one isn't selected. This would make it easier to shop all a vendor's wares and quickly identify which pieces are for which character types. As a Warlock guy I sometimes have trouble remembering which gauntlet pieces face left versus right for my Hunter and Titan.

Thanks again!

**Comment by dasilva333** [comment]
Column added, thanks for the feedback

**Comment by jkewley** [comment]
Thanks for doing that. Hate to be a pest, but it would be nice to have the green/red/yellow colors back for quick glance

**Comment by dasilva333** [comment]
you bet, thanks for noticing, i had modified the styles and removed it by mistake.thanks again!

**Comment by jkewley** [comment]
Thank me when I make the time to contribute code to the project. Already sent you some $$.
