### ISSUE TITLE
Shader "Walkabout" displays with default Classified icon

### ISSUE THREAD

**Issue by rkingsla** [dasilva333/TowerGhostForDestiny#617]
http://db.destinytracker.com/items/194424271-walkabout

Item displays in latest version/pull from source as Classified.

**Comment by dasilva333** [comment]
Let me know if it's still a problem as of 3.9.1.0 Thanks!

**Comment by rkingsla** [comment]
I will, Richard.  It’s just weird. Looking at the code – it should be populating.  But….  I’ll check here shortly.  Thanks!

**Comment by rkingsla** [comment]
Just checked – ‘tis fixed.  Nice job!
