### ISSUE TITLE
Could not load item definitions...

### ISSUE THREAD

**Issue by erwjack** [dasilva333/TowerGhostForDestiny#618]
Hi,
starting from today TGD on my Windows 10 don't load item definitions anymore.
I downloaded a brand new TGD 3.6.9.0 for W32 from your site,
When TGD starts, a dark prompt appears with...
"Could not load item definitions, please report the issue to my Github including the version number being used."
After a few seconds the prompt dissapears and TGD try to update. I see "please wait, downloading autoupdates" and, for a moment, the large prompt with the 3.9.0.9 "what's new". Then this prompt disappears and reappears the "Could not load..." prompt.
This is an infinite loop...

Thanks in advance.

**Comment by dasilva333** [comment]
Seems to be working for me, perhaps it was a temporary problem with the server? Let me know if you're still having issues so I can reopen this ticket. Thanks!

**Comment by erwjack** [comment]
Hi dasilva,
still the same, I think this is not a server problem.
Today I completely delete my tgd folder, downloaded the x64 version (seems ) from your site and launched.
Same message "Could not load item definitions, please report the issue to my github included the version number being used".
When TGD seems to download updates I can read a 3.6.9.0 at top left, then again the same error message.
Maybe some infos cached somewhere in my Windows? If so, is there a way to deploy a new clean installation?
Thanks
