### ISSUE TITLE
Sort by Quality is done by text not by value

### ISSUE THREAD

**Issue by ppokorny** [dasilva333/TowerGhostForDestiny#619]
The current Tower Vendor Rolls page has a 100 rated item on it (House Judgement Kings Bond) but when sorting by the Quality column, the rating of 100 appears at the very bottom, not the top of the list.  As if it sorted based on the leading digit, not the numerical value.

http://towerghostfordestiny.com/index.php/tower-vendor-rolls/

**Comment by dasilva333** [comment]
thanks will fix

**Comment by dasilva333** [comment]
problem fixed thanks for the heads up
