### ISSUE TITLE
error Could not load item definitions

### ISSUE THREAD

**Issue by N30Exca** [dasilva333/TowerGhostForDestiny#621]
I'm getting the error "Could not load item definitions, please report the issue to my Github including the version number being used." in Chrome with version  3.9.0, tryed allready to uninstall the extension and load it form lolcal no results

**Comment by dasilva333** [comment]
I uploaded Chrome 3.9.1 to the store let me know if you still have any issues, thanks!

**Comment by dasilva333** [comment]
I updated Chrome to 3.9.1 try it out and let me know if you're still having issues. Thanks!
