### ISSUE TITLE
Stuck on 3.9.0.3 on Firefox

### ISSUE THREAD

**Issue by villiansv** [dasilva333/TowerGhostForDestiny#623]
I have been unable to update to the latest version for a few days now on Firefox (works fine in Chrome). Things I've tried:

1. Toggle auto updates off and back on, with browser restarts inbetween toggles.
2. Remove and reinstall addon, including an older version from addons.mozilla.org
3. The steps outlined here: http://towerghostfordestiny.com/index.php/hrf_faq/my-tower-ghost-is-stuck-on-an-older-version-on-firefox/

Nothing works. If relevant, I originally did have entries in the "default" folder from step 3., but now I no longer do so.

edit: If it helps, here's a link to a gif screen recording I took showing a weird flash of the update available warning that happens every time I start it - http://imgur.com/jaShsyh

**Comment by dasilva333** [comment]
I made a fix as of 3.9.1.1 with a problem in the Settings panel when checking and unchecked auto updates it wouldn't clear the version from manifest completely so I suggest you try it now in this order:

1. Just open the app see if it notices the new update for 3.9.1.1
2. Reinstall the addon from the addons.mozilla.org like you said
3. Completely remove it from cache like outlined in that link

If all those steps don't work after the latest update let me know and I'll debug further what's wrong with it.

Thanks!

**Comment by villiansv** [comment]
It's now updated to 3.9.1.1, so the original issue is gone. However, the startup time is really long - takes on average 15-20s for anything to appear. Once loaded, refreshing etc work fine, it's just going from the blank grey-black screen to icons/interface being visible that takes long.

**Comment by dasilva333** [comment]
Yeah it's a known issue you can make a new ticket for that if you'd like thanks for the feedback

**Comment by villiansv** [comment]
If it's a known issue, I'll let you handle it at your convenience. Feel free to close this one.
