### ISSUE TITLE
Clear filters bug for class armor selection

### ISSUE THREAD

**Issue by jkewley** [dasilva333/TowerGhostForDestiny#624]
If you apply the armor filter for a given class and then click the Clear Filters button the filter is effectively removed from the UI, but the checkbox for that class remains checked. You then need to click it twice to reapply the filter. if you apply another class filter without resetting the first, it'll filter to the sum of the two classes.

**Comment by dasilva333** [comment]
Expect it fixed by 3.9.1.2 thanks
