### ISSUE TITLE
TG not loading in Chrome

### ISSUE THREAD

**Issue by Ziggy0011** [dasilva333/TowerGhostForDestiny#625]
I have tried to load TG on my desktop and (2) surface pro 2 & 4. I have reinstalled the extension and still it will not load. Please help.

Love you guys.

**Comment by teaconsult** [comment]
Same on Mac running chrome Version 51.0.2704.103 (64-bit). Page just keeps downloading updates

**Comment by Weavus** [comment]
Yup, same here

**Comment by Grimsalt** [comment]
Same on Android 5.1.1 with Google Nexus 10 using TG v.3.8.9.12 : after working fine for weeks, all of a sudden yesterday morning, auto-update hangs at about a third of the green progress bar and eventually times out, making it impossible to load inventory and use the app.  Reinstalling & switching the auto-update function on/off doesn't help.  Please help, can't go into Trials without this app!

**Comment by edmiller47** [comment]
And broken on iOS too.

Have rebooted computer, reinstalled TG, toggled auto updates off and on, seeing same behavior on Chrome on my PC as described by Grimsalt.

**Comment by MasterBry** [comment]
Not working for days on iPad, i wish you would stop BETA testing on us, just riuns whole app that once was just awesome

**Comment by dasilva333** [comment]
Sorry about that guys I packaged it for a different platform before I deployed it, should be fixed now, latest version is 3.9.1.1 Let me know if anyone still has issues. Thanks!

**Comment by teaconsult** [comment]
No problem...:) great app and appreciate all the hard work. Just hope others donate to help ur hard work. Most don't understand the work that goes into these app and doing it all on donations and free time

**Comment by dasilva333** [comment]
Thanks man I apreciate  the kind words, I love the game so i don't mind putting time and effort to make the app and donations definitely help. Thanks again

**Comment by Grimsalt** [comment]
Confirmed working on Android now. Thanks for fixing it within just about 24h, will donate on Android, GG dev 👍

**Comment by MasterBry** [comment]
Working again now, thanks again !

**Comment by Ziggy0011** [comment]
Good job !

I know it is tough keeping up with all the updates. I have donated twice and will continue to help out. :)

 

-          Ziggy0011
