### ISSUE TITLE
Unexpected Error : Let us know if you see this

### ISSUE THREAD

**Issue by jkewley** [dasilva333/TowerGhostForDestiny#629]
Getting this
![image](https://cloud.githubusercontent.com/assets/1148930/16662277/4f52bc3e-443c-11e6-8e18-624ab9e93427.png)
because of this
![image](https://cloud.githubusercontent.com/assets/1148930/16662296/64a9a91c-443c-11e6-9175-185c5c8525a7.png)

**Comment by mistral13** [comment]
Is this on the share URL with friends site (https://towerghostfordestiny.com/share/)? 

Or which Browser/AddOn and which Version?

**Comment by jkewley** [comment]
Right, sorry. This was Chrome latest as of that moment in time on Windows 10 running the app via the chrome extension. 
Since resolved and is now functioning, so feel free to close.
