### ISSUE TITLE
From Reddit: Suggestion - Collapsible Characters

### ISSUE THREAD

**Issue by JBurd67** [dasilva333/TowerGhostForDestiny#63]
Sorry if this is in the wrong spot... Can you make it so that characters/the vault is collapsible? Scrolling through one character to get to another can take a while with all the gear to see.

**Comment by dasilva333** [comment]
After I added the quick scroll icons to the menu bar the ability to have collapsible characters doesn't seem as useful, I'll be implementing the enhancement request of issue #40 so expect it to get better.
Thanks

**Comment by JBurd67** [comment]
Yeah, that's totally fine. I made the suggestion before the quick scroll
icons came in. Love the work you're doing! Thanks!
