### ISSUE TITLE
Logic for statrolls?

### ISSUE THREAD

**Issue by bluetidepro** [dasilva333/TowerGhostForDestiny#630]
For the code that deals with the stat roll min/max, how does that actually work?

https://github.com/dasilva333/TowerGhostForDestiny/blob/a67a98eb6022b843e7e845f03491f5845db1974d/www/js/app/Profile.js#L653

I tried to dig into the code some, but couldn't really full make it out. Can you give me a better idea of how that logic actually works to show you how good the roll of an item is?

**Comment by bluetidepro** [comment]
Any update on this?

**Comment by dasilva333** [comment]
So the rolls for each item is calculated here:

https://github.com/dasilva333/TowerGhostForDestiny/blob/a67a98eb6022b843e7e845f03491f5845db1974d/www/js/app/Item.js#L279

Calculate future rolls predicts the stats at max light (335)
https://github.com/dasilva333/TowerGhostForDestiny/blob/a67a98eb6022b843e7e845f03491f5845db1974d/www/js/app/Item.js#L309

Each stat is calculated using cornman0101's formula here:
https://github.com/dasilva333/TowerGhostForDestiny/blob/a67a98eb6022b843e7e845f03491f5845db1974d/www/js/app/Item.js#L332

Calculate Infused Stats can be found here:
https://github.com/dasilva333/TowerGhostForDestiny/blob/a67a98eb6022b843e7e845f03491f5845db1974d/www/js/tgd/bonusStat.js

Closing this ticket as it really isn't an issue, @bluetidepro are you planning a PR for stat rolls?

Let me know thanks

**Comment by bluetidepro** [comment]
Thanks @dasilva333! 💃
