### ISSUE TITLE
New Shader and Emblem displays with default Classified icon

### ISSUE THREAD

**Issue by mistral13** [dasilva333/TowerGhostForDestiny#632]
Items displays in latest version 3.9.1.2 as Classified.

Shader:
https://destinydb.com/items/139252900
https://destinydb.com/items/139252901

Emblem:
https://destinydb.com/items/2596665930
https://destinydb.com/items/2596665931

The 7-7 ad infinitum Emblem works.

**Comment by mistral13** [comment]
https://destinydb.com/item/4128744703/

**Comment by davidhosier** [comment]
Seconded.  It's been over a month now since this content came out.

**Comment by dasilva333** [comment]
Expect it fixed as of 3.9.2, let me know if there's still problems after updating to the latest version. thanks
