### ISSUE TITLE
Personal perks not displayed on DestinyDB tooltips

### ISSUE THREAD

**Issue by wickles** [dasilva333/TowerGhostForDestiny#64]
I see on the readme that personal perks should be displayed. I don't think this has ever worked for me. 

![2015-04-18 14_51_04-greenshot-small](https://cloud.githubusercontent.com/assets/4229542/7217349/b9336a66-e5da-11e4-9933-5aced2a24d51.png)

**Comment by dasilva333** [comment]
Try it on 1.9.7 and report back thanks, also try out the personal stats on your armor. It's a new feature

**Comment by wickles** [comment]
Seems to work now, thanks! I'm curious about a few things. Is this built in to the API or did you have to hack it in some other way? On bungie.com you can see the whole upgrade tree and which upgrades are activated, is it possible to read these off through the API or otherwise? And is it possible to read off the personalized current/real weapon stats? e.g. say you activate an RoF upgrade, it will show the increased RoF on bungie.com but not in TDG since the stats just come from DestinyDB. I'm sure you see where I'm going with this.

**Comment by wickles** [comment]
Also I noticed a small visual issue when a piece of armor has 3 perks instead of 2. The text is moved over a bit and there's an extra line that shouldn't be there. 

![screen shot 2015-04-18 at 4 29 04 pm](https://cloud.githubusercontent.com/assets/4229542/7217583/5813e090-e5e8-11e4-9ec1-01b56c0f6ff5.png)

vs

![screen shot 2015-04-18 at 4 29 10 pm](https://cloud.githubusercontent.com/assets/4229542/7217584/5815af06-e5e8-11e4-8820-233d9a6fe24d.png)

**Comment by dasilva333** [comment]
@wickles good eye for detail guardian. Problem fixed in 1.9.7 let me know so we can close this ticket thanks

**Comment by wickles** [comment]
Yep looks good now, thanks @dasilva333
