### ISSUE TITLE
Suggestion: plugin for Edge browser

### ISSUE THREAD

**Issue by jkewley** [dasilva333/TowerGhostForDestiny#643]
MS have released a tool that lets you convert a Chrome plugin for use in Edge. I know, I know - one more platform to support. But I, for one, would love to take that last step away from Chrome. [Here is the tool](https://www.microsoft.com/en-us/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb) (warning, launches store app on Windows 10). 

How cool would it be to say that you're the first Destiny app that runs on HoloLens?

**Comment by jkewley** [comment]
Bah. Nevermind - [edge extension support is closed for now](https://developer.microsoft.com/en-us/microsoft-edge/platform/faq/), to be opened to general devs in the future. I might fork and create a build for those of us who would like to side-load

**Comment by dasilva333** [comment]
Feel free to make a new issue when developers are able to submit an extension again, I don't mind porting it myself or helping you port it. Just let me know thanks
