### ISSUE TITLE
Vendor report not updating

### ISSUE THREAD

**Issue by germotlp** [dasilva333/TowerGhostForDestiny#644]
I just checked on the mobile and Chrome extension and the vendor report not updating with the latest vendor items at todays reset. It appears the report is from last weeks, ie The Speaker vendor items. i haven't checked any other vendor yet.

**Comment by jrgeek** [comment]
Any news on this one?  The tools are showing as offline versus incorrect stats at this point.

**Comment by germotlp** [comment]
Now the vendor report is not pulling anything from a mobile device

**Comment by dasilva333** [comment]
What do you guys mean? I don't understand the problem, please recheck it to make sure it's working properly.
To get to the Vendor report in-app you:
- Click on the emblem image 
- Click on Tools
- Click on Custom
- Click on Vendor Items
- The items sold at the Tower should be listed along with your armor

If you guys are talking about the website:
http://towerghostfordestiny.com/index.php/tower-vendor-rolls/

It's currently updated and working however I'm still trying to wrangle the problem with it not udpating during resets.

Thanks, please update with feedback so I can decide if this is a valid issue or not
