### ISSUE TITLE
Farming bot suggestion

### ISSUE THREAD

**Issue by grimmjoww** [dasilva333/TowerGhostForDestiny#646]
It would be nice it the farm bit could work in the background.  I have an issue on my galaxy s7 because I can only set screen timeout to ten. If it could work even if my screened turned off that would be nice. This also causes my timer to go negative if I don't watch it and make me reset the entire application

**Comment by dasilva333** [comment]
nice tip, i'll keep that in mind thanks

**Comment by dasilva333** [comment]
Problem will be fixed as of 3.9.2.8 I managed to test it out for iOS I have this new plugin that prevents the screen from going blank therefore allowing Farm Mode to always stay active and monitoring your inventory. Thanks for the suggestion
