### ISSUE TITLE
Tower Ghost won't load

### ISSUE THREAD

**Issue by LordofthStrings** [dasilva333/TowerGhostForDestiny#647]
When I open the app it will not load my items, loadouts etc. after awhile I get a error message saying checking for updates failed, manifest timed out. I have tried logging out, closing the app, uninstalling the app and hard resetting my kindle fire(5th generation). If anyone can shed some light on this issue it would be much appreciated.

**Comment by dasilva333** [comment]
I'm pushing an update tonight for 3.9.2 that should include the new definitions, let me know if youre still having issues with your stuff loading. thanks!
