### ISSUE TITLE
1 subclass not loading

### ISSUE THREAD

**Issue by as4k** [dasilva333/TowerGhostForDestiny#648]
Hunter subclass and all loadouts not populating.  Warlock and Titan work fine, as does Vault.  This of course makes moving weapons from my Hunter impossible with the app, which I love!

**Comment by dasilva333** [comment]
Are you still having an issue with loading? If so let me know so I can get that fixed for you thanks

**Comment by as4k** [comment]
This issue has been resolved.  I figured you guys did something :).  I appreciate the comment back.  We are good!!
