### ISSUE TITLE
Bug can't load item description 

### ISSUE THREAD

**Issue by Devincol** [dasilva333/TowerGhostForDestiny#649]
I have 3.9.1.1 and I keep getting this message it will let me see the stuff 1 out of 10 trys then kicks me.  Bug.

**Comment by Devincol** [comment]
If it helps I'm on an Android phone and downloaded from the app store

**Comment by dasilva333** [comment]
Can you take a screenshot of the message? Let me know so i can help u fix it thanks

**Comment by Devincol** [comment]
I have a screen shot but I'd how to upload it

**Comment by Devincol** [comment]
I have a screen shot but I'd how to upload it

**Comment by mistral13** [comment]
Drag and drop in this field or use the link under this field

**Comment by dasilva333** [comment]
You may upload a screenshot using the tool of your choice, I personally like to use www.onpaste.com and then upload it to Imgur using the top right button in the corner. Good luck and thank you

**Comment by Devincol** [comment]
![screenshot_2016-08-27-11-01-02](https://cloud.githubusercontent.com/assets/21088655/18411375/3f758ad6-7744-11e6-8b89-3c7c4a9144df.png)

**Comment by Devincol** [comment]
![screenshot_2016-08-27-11-01-04](https://cloud.githubusercontent.com/assets/21088655/18411379/52d33196-7744-11e6-878f-b445d2a7ee71.png)

**Comment by Devincol** [comment]
It does seem to be working now after the update so I may be fixed

**Comment by dasilva333** [comment]
Make sure you're on 3.9.2.6, let me know if you're still having issues. Thanks
