### ISSUE TITLE
Towreghost will not load on my iPad.

### ISSUE THREAD

**Issue by kingkor1234** [dasilva333/TowerGhostForDestiny#660]
I will see the menus at the top and can asses them all but no items will show. It's been like this as long as I can remember,

**Comment by edmiller47** [comment]
I have not been able to use Tower Ghost on my iPad since yesterday (9/21). Splash screen is displayed, then black screen, then exits to iPad home screen. Guessing it's version 3.9.2.4 but can't tell...

**Comment by edmiller47** [comment]
3.2.9.6 now installed and working on iPad.
