### ISSUE TITLE
Not loading on windows phone

### ISSUE THREAD

**Issue by GRAYHAM75** [dasilva333/TowerGhostForDestiny#662]
Hi, Can not get app to load on windows phone have deleted and reinstalled still just stops after entering gamer tag loads header but will not go any further. So I'm back to flying in and out tower to swap gear. Man you forget how good this app is till you lose it. Thanks.

**Comment by dasilva333** [comment]
I will be posting 3.9.2.7 (coming soon) to windows phone this week. Hopefully by tonight I can submit it to Microsoft and you guys can have it by tomorrow morning. Thanks!

**Comment by GRAYHAM75** [comment]
That's great news 🙂. This app must save me about 50 trips to the tower each week. Thanks for the good work.

**Comment by GRAYHAM75** [comment]
Hi , I see there has been an update at Microsoft store but now tells me I can not install as this app does not work on my device. Phone is a Lumia 535 running Windows 10 is this a bug as has always worked before. Thanks.

**Comment by dasilva333** [comment]
I think it's my fault I unchecked Windows 10 when uploading the app. I tried logging in but the ability to check that option is unavailable now. I'll try to submit a 'fake' update called 3.9.2.8 with that box checked tonight and see if that fixes it for you, thanks for the feedback @GRAYHAM75

**Comment by dasilva333** [comment]
Update alright so I built 3.9.2.8 only to find out I can check the Windows 10 mobile checkbox without having to reupload a new version as part of a new approval process. So it'll probably be available by tonight or tomorrow morning their turnaround is pretty fast. Keep me updated let me know if it works for you. Thanks

**Comment by GRAYHAM75** [comment]
Just installed from Windows Store and working great. Thanks again.
