### ISSUE TITLE
Unknown loadouts in my primary slots [BUG]

### ISSUE THREAD

**Issue by djelis82** [dasilva333/TowerGhostForDestiny#669]
![tghost](https://cloud.githubusercontent.com/assets/22659556/19151809/75dc31ae-8bd7-11e6-96d4-6048392f2cde.JPG)

I've got some columns that don't really exist in my real gear. Those ghost primaries are there for me all the time and i don't know how can i delete them as those don't really exist. I've reinstalled the plugin, same. It keeps my primary slots busy but those do not exist in my loadout.

gamertag: djelis82, psn, Chrome Plugin, Windows7 x64

**Comment by mistral13** [comment]
Hi
This are quests and not weapons.

To you use the version 3.9.2.8 (1 quest is fixed with this Version)

One is the Engine for the Outbreak Prime quest. 

Or do you have the Khvosrov Quest open?

**Comment by djelis82** [comment]
Kvostov is already made, i finished it. I have the Outbreak Prime quest on two characters and that might be it. I will try to update to 3.9.2.8, I have the previous version, 3.9.2.7.

**Comment by dasilva333** [comment]
I fixed the bug permanently as of my commit today, if you would like to check out master to try it that would be great otherwise try it out once I push it live tonight. Thanks!

**Comment by edmiller47** [comment]
Is 3.9.2.8 available for Chrome? I'm still on 3.9.2.7, toggled auto update this morning and it didn't get a new version.

**Comment by edmiller47** [comment]
How do I get 3.9.2.8 onto Chrome? Auto update isn't pulling it in. Thanks

**Comment by dasilva333** [comment]
So there is a bug with 3.9.2.7 it is impossible to update out of it, please uninstall and reinstall Tower Ghost or wait until 3.9.3 is available in the Chrome Store at which point it'll automatically update you via the Chrome store. Thanks!
