### ISSUE TITLE
no icons on screen

### ISSUE THREAD

**Issue by DeePrime** [dasilva333/TowerGhostForDestiny#674]
I'm on windows phone and my app will sign in then none of the icons will show up. I've reinstalled twice and no change so far. It says loading arsenal for a second then nothing comes up besides the grey screen and the menu options.

**Comment by rkingsla** [comment]
What OS version? Just tried on my phone (Windows 10) and it's working fine. Make no mistake - not saying you aren't having an issue...

**Comment by DeePrime** [comment]
Nokia Lumia 920 OS 8.10.14234.375
It's windows phone 8.1

**Comment by rkingsla** [comment]
Perfect!  Thank you. That will aid Richard in tracking it down.

**Comment by DeePrime** [comment]
Ok, I'm guessing it'll take a bit to sort out. All good for now, I do look forward to it being back up and running cause it works great.

**Comment by edmiller47** [comment]
Same thing was happening for me on Chrome. I had version 3.9.3.0 installed and it wasn't auto-updating.
I installed 3.9.3.2 manually via the instructions here: http://towerghostfordestiny.com/index.php/support/
and now it's back up and running on my PC.

**Comment by hawksco** [comment]
I have the same problem on my windows phone. It hasn't been usable for a few days now. I have a Nokia 950 OS 10.0.14393.321, version 1607. The app is v3.9.2.7, which is the latest available from the windows store.
![tgdv3927wp10blankscreen](https://cloud.githubusercontent.com/assets/19540496/19866747/f22b8762-9f66-11e6-8063-f53cc8ee56f4.png)

**Comment by DeePrime** [comment]
Thanks guys, the app is back up and running great. I appreciate your time and effort very much.
