### ISSUE TITLE
Superblack icon still won't display on iPad (iOS 10.1) with TG 3.9.3.3

### ISSUE THREAD

**Issue by Celevas** [dasilva333/TowerGhostForDestiny#678]

**Comment by rkingsla** [comment]
It's not displaying for anyone (that I know of) I'm not sure that Bungie has made it available through the API. Other 3rd party tools don't show it, of the few others that I've looked at.

**Comment by rkingsla** [comment]
FWIW, Bungie does not even display it correctly in Gear Manager. If things don't display there, then it certainly is not going to be available via the Public API. I suspect that Bungie has an 'in' as far as the API is concerned. :)
