### ISSUE TITLE
[bug] 3.9.3.3 Info and Tools causes crash

### ISSUE THREAD

**Issue by edmiller47** [dasilva333/TowerGhostForDestiny#679]
On iOS, touching Info and Tools spot on the character box causes TG to freeze. Have to force quit and restart the app. It functions normally otherwise, as long as I don't try to use that function.

**Comment by edmiller47** [comment]
Clicking on Info and Tools in the character box on Chrome causes Tower Ghost to crash. 
![image](https://cloud.githubusercontent.com/assets/13838005/20388097/52ca5af8-ac91-11e6-9aa1-2936a97547c8.png)

**Comment by rkingsla** [comment]
OS, version of Chrome? Windows 10 and Chrome 54.0.2840.99 m - working fine here.

**Comment by dasilva333** [comment]
@edmiller47 thanks for the info. if you don't mind can you provide me some debug logs of the issue?

So here's what you do:

1. Open Chrome's TGD
2. Press F12 to open the Developer Console
3. Visit the tab labeled 'Console' at the top next to Elements
4. Reproduce the problem so it crashes
5. Record/note down any errors shown in the console
6. Provide those logs here

Let me know if you get anything in there, might not show anything bc it seems to be crashing the whole plugin but it's worth a try.

Thanks!

**Comment by edmiller47** [comment]
@rkingsla Windows 7 Home Premium Service Pack 1, Chrome Version 54.0.2840.99 m
iOS 8.4

**Comment by dasilva333** [comment]
@edmiller47 did you manage to get anything out of the console before it crashes? Knowing what the crash is exactly goes a long way in getting this fixed, as an alternative if you like try to publish your stuff via the share URL and see if it crashes there so:

1. click on the cog in the top right
2. click on Share URL with friends
3. provide me the link displayed 

(also visit the link and check if it crashes when u click Info / Tools on that page)

Thanks!

**Comment by edmiller47** [comment]
@dasilva333 So this appeared in the console *before* reproducing the bug:
![image](https://cloud.githubusercontent.com/assets/13838005/20393433/ed3facb0-aca9-11e6-8c1b-e577aa291851.png)
Once I clicked on the Info and Tools button, the crash reoccurred and the console disappeared. I repeated the process a couple of times and what you see in the image is all that appears.
Hope this helps.

**Comment by edmiller47** [comment]
@dasilva333 Here's the link: 
https://towerghostfordestiny.com/share/?xbl/BLAMnation

I visited it and clicked on Info/Tools, and nothing happened. No crash, no information displayed.

**Comment by edmiller47** [comment]
After visiting that link I opened the console again:
![image](https://cloud.githubusercontent.com/assets/13838005/20394717/8b98c9b0-acae-11e6-8e2a-3e7f1adc1598.png)

**Comment by dasilva333** [comment]
@edmiller47 alright thanks for all the debug information, so far I haven't managed to trace the root issue even with all the information provided. Would you be open to the idea of sharing your Bungie account with me even if it's only for a few hours? You could change your password to something temporary and then just change it back. If so feel free to email me the details at support@towerghostfordestiny.com

Thanks!

**Comment by mistral13** [comment]
Fyio: same problem on my iPhone 6.
@dasilva333: did you see my comment in Slack?

**Comment by mistral13** [comment]
I don't know, if this is helpful. 
Load the share url on my iPhone (Safari or iCabMobile).
https://towerghostfordestiny.com/share/?psn/mistral75
First touching Info and Tools for each character, the icon is highlighted, but no information displayed.
Second touch for each character -> deselect the icon, like normal
Third touch for each character ->  information displayed, like normal.

**Comment by edmiller47** [comment]
Tried this on Chrome with my Share URL and saw the same behavior.

**Comment by mistral13** [comment]
In this case, the lightlevel in Info and Tools are empty:

![img_3152](https://cloud.githubusercontent.com/assets/5049663/20431347/d2925eda-ad99-11e6-843d-7ac963742c96.PNG)


![img_3153](https://cloud.githubusercontent.com/assets/5049663/20431357/d948f004-ad99-11e6-812d-3c7bcaab8ba1.PNG)

**Comment by mistral13** [comment]
please roll back the "improving character box w computed max light values" or roll back to 3.9.3.2
THX

**Comment by xClutchCardx** [comment]
Problem loading anything on my iPad Air 2 on iOS 10.1.1.

Before this point anytime I tried to touch character bar to it would crash the app. So I deleted reinstalled and now I get nothing.

![img_0180](https://cloud.githubusercontent.com/assets/24307155/20820581/e06f3fec-b801-11e6-92c4-1c1bcb7a9786.PNG)
![img_0181](https://cloud.githubusercontent.com/assets/24307155/20820583/e084a5e4-b801-11e6-9ada-a5d7a53b09af.PNG)
![img_0182](https://cloud.githubusercontent.com/assets/24307155/20820582/e0839398-b801-11e6-856e-820ba20585f8.PNG)

**Comment by edmiller47** [comment]
@xClutchCardx, it looks like you now have a pretty out of date version of the app, and since you are getting that manifest timeout error it isn't updating to a version that will let you display your inventory.

App has been broken for almost 3 weeks now, so I don't know what to tell you, maybe the dev is away or dealing with other priorities. I love this app too but can't use the functions I rely upon so I've had to turn to alternatives. Hope it gets fixed soon.

**Comment by xClutchCardx** [comment]
Ya, that's the crazy thing my app was up to date. Had a problem where it wouldn't save newly created loadouts, so I deleted and reinstalled. When I did that it rolled back to this version. Hope it gets figured out soon, I prefer to use this app over any other on iOS.

Is there a reason the developer choose to change all the headings? Looks like that was where things went wrong for me.

**Comment by edmiller47** [comment]
@xClutchCardx Dev is always adding features to make TG a more useful tool. Sometimes bugs get introduced.

**Comment by MoleyMole** [comment]
I'm experiencing the same issue.  However have just found that if I click on my Titan then it works..... warlock and hunter both crash

**Comment by mistral13** [comment]
MoleyMole. How many gear has you on your titan? And for your warlock and hunter?

**Comment by MoleyMole** [comment]
@mistral13 I have less on my Warlock than my Titan.... but more on my hunter than my Titan.... so neither make a difference unfortunately.

**Comment by mistral13** [comment]
and with including the vault?

**Comment by xClutchCardx** [comment]
I have 3 Titans crashes regardless which one I click on.
