### ISSUE TITLE
Suggestion: Progress for loadout

### ISSUE THREAD

**Issue by Titus-s** [dasilva333/TowerGhostForDestiny#68]
Add some progression during transferring items in loadout.
Loadout dialog covers main screen and you can't see how items moving.

**Comment by dasilva333** [comment]
Thanks

**Comment by Titus-s** [comment]
It works but I noticed that it reach 100% and items are still moving. 
After deeper investigation (I add some logs to loadouts.js) it turn out that progressValue exceed 100.
I'm coding a bit and I found a fix (sorry, I've tried but I don't know how to request change in GitHub). 
It's enough to change in loadouts.js 2 lines:
line 92 with
var itemIndex = -1, increments = parseInt(Math.round(95 / (1.0 * swapArray.length))), progressValue = 5;
line 109 with:
progressValue = progressValue + increments;

and then delete lines 103 and 104.

**Comment by dasilva333** [comment]
Thanks for the code change, I'll be testing it when I get home today and adding it in as a fix. In the future it's easier if you submit a pull request. You can do so by following these steps:

1. https://github.com/dasilva333/TowerGhostForDestiny/ (click Fork)
2. https://github.com/<your username>/TowerGhostForDestiny/ (check out the code using Git/SVN)
3. make your changes as you see fit and commit them back to your branch
4. https://github.com/dasilva333/TowerGhostForDestiny/pulls (click new pull request)
5. Setup a request between TGD/master and your branch

After that I'll pull it in test it and apply it to the next version.

Thanks

**Comment by dasilva333** [comment]
@Titus-s alright the new loading is part of 2.0.7 check it out thanks

**Comment by Titus-s** [comment]
Thank you, works fine.
