### ISSUE TITLE
Firefox Error - 523 Origin is not Reachable

### ISSUE THREAD

**Issue by RlxdN10sity** [dasilva333/TowerGhostForDestiny#680]
I keep getting this page the past few days? Something wrong on my end?

[Screenshot.pdf](https://github.com/dasilva333/TowerGhostForDestiny/files/621286/Screenshot.pdf)

**Comment by edmiller47** [comment]
Might be caused by the same problem that has caused my loadouts menu to be empty again on Chrome and iOS. 

![image](https://cloud.githubusercontent.com/assets/13838005/20793422/f264d7e2-b794-11e6-95ac-367c5173569b.png)

**Comment by dasilva333** [comment]
I was having some server issues, try it again the problem should be fixed now. thanks
