### ISSUE TITLE
Cloudflare SSL error

### ISSUE THREAD

**Issue by MoleyMole** [dasilva333/TowerGhostForDestiny#681]
I've been getting this  for a couple of weeks now.  Shame as I love this tool
[https://gyazo.com/d07ec922040bce8e1983dae375ffe2b3](https://gyazo.com/d07ec922040bce8e1983dae375ffe2b3)

**Comment by Awsomonium** [comment]
I have the same error. I had to download Chrome so I could use DIM as a stopgap. While DIM is cool, it just doesn't feel as good.

**Comment by og545** [comment]
Same here.  Been down for two weeks approximately.  With Firefox I get the SSL CloudFlare Error 525.  With the app on PC i can't sign in.  Much prefer this tool over the others.  Please fix.

**Comment by MoleyMole** [comment]
This now appears fixed.  However, when clicking to get to the menu for the Tier 12 builder the application just hangs and crashes

**Comment by og545** [comment]
Yay!!!!!-- Patrick L. HintonHinton Law Office, PLLCP.O. 10933Bainbridge Island, WA 98110206 855-4191 -- direct206 201-5654  -- facsimile206 790-1108 -- mobileConfidentiality Notice:  This document may contain confidential information which is legally privileged.  The information is solely for the use of the addressee named above. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or other use of the contents of this information is strictly prohibited.  If you have received this e-mail in error, please notify us by telephone immediately.CallSend SMSAdd to SkypeYou'll need Skype CreditFree via Skype


-------- Original Message --------
Subject: Re: [dasilva333/TowerGhostForDestiny] Cloudflare SSL error
(#681)
