### ISSUE TITLE
Error 525 (CloudFlare SSL handshake failed)

### ISSUE THREAD

**Issue by og545** [dasilva333/TowerGhostForDestiny#683]
Similar to a couple of other issues opened here, when logging on to TGFD via Firefox, it fails to connect to the website and instead generates a page with the above error message.  When I try to log in via the app on PC, it won't get through the xboxone login prompt.  On my iphone, it gets stuck on "Checking for updates" for a minute or so before reverting back to the phone group window.  So that is that.  Love my TGFD.  Hope it comes back soon.

**Comment by dasilva333** [comment]
Try it out again and let me know if it's still an issue. thanks!

**Comment by og545** [comment]
All is good.  Many thinks, both for the fix and the app.  Good work all around!-- Patrick L. HintonHinton Law Office, PLLCP.O. 10933Bainbridge Island, WA 98110206 855-4191 -- direct206 201-5654  -- facsimile206 790-1108 -- mobileConfidentiality Notice:  This document may contain confidential information which is legally privileged.  The information is solely for the use of the addressee named above. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or other use of the contents of this information is strictly prohibited.  If you have received this e-mail in error, please notify us by telephone immediately.CallSend SMSAdd to SkypeYou'll need Skype CreditFree via Skype


-------- Original Message --------
Subject: Re: [dasilva333/TowerGhostForDestiny] Error 525 (CloudFlare SSL
handshake failed) (#683)
