### ISSUE TITLE
Tower Ghost breaks other destiny web applications by stripping origin header

### ISSUE THREAD

**Issue by v-fedorov** [dasilva333/TowerGhostForDestiny#691]
I had an email come in from a user that was unable to search their gamertag on our site, turns out it only happens when they have the Tower Ghost chrome extension open. 
I also had them and others confirm the same issue while searching destinytrialsreport.com as well as other sites such as guardian.theater and destinytailor.com.

This only affects us now since we just recently switched away from our proxy to CORS which requires the origin to match the api key.

Pretty sure the culprit is this
https://github.com/dasilva333/TowerGhostForDestiny/blob/59ae56fa3ca60903c8c4086e2bf5f518f8e81148/www/js/tgd/bungie.js#L413

**Comment by dcaslin** [comment]
This breaks Oauth on gear.destinychecklist.net as well, please fix ASAP

**Comment by dcaslin** [comment]
Btw, filtering for chrome extensions should do the job without side-effects: 

chrome.webRequest.onBeforeSendHeaders.addListener(details => {
    let headers = details.requestHeaders.filter(h => {
          return !(h.name === "Origin" && h.value.startsWith("chrome-extension://"));
});
