### ISSUE TITLE
"Error: The given Platform API Key is invalid or is expired." on Firefox and Chrome versions

### ISSUE THREAD

**Issue by hendersj** [dasilva333/TowerGhostForDestiny#693]
Launching TGD from Firefox or Chrome, I get the error in the subject line.

**Comment by Celevas** [comment]
Same thing happens in TGD 3.9.3.4 on iPad Air running iOS 10.1.1

**Comment by RlxdN10sity** [comment]
Getting same message. I'm on Firefox as well.

**Comment by Toyroom** [comment]
Ditto iPad Air 2 IOS 10.2.1

**Comment by TheWhiteWolves** [comment]
not just me then, I'm running Chrome 56.0.2924.87 (64-bit) with TGD v3.9.3.0

**Comment by edmiller47** [comment]
Same here on Chrome

**Comment by macnode** [comment]
Also this.

**Comment by Celevas** [comment]
It's working fine now. Thank you!

**Comment by TheWhiteWolves** [comment]
same here, working now

**Comment by hendersj** [comment]
And here, closing the issue.
