### ISSUE TITLE
Thumbnails not loading

### ISSUE THREAD

**Issue by Toyroom** [dasilva333/TowerGhostForDestiny#696]
Hi

Earlier today I started getting a few thumbnails not loading so I tried reinstalling and now none of them are appearing, all I get is and error meassge "Error: Problem checking for updates: new manifest timeout".  This is on an iPad Air2.

Regards, Alan.

**Comment by Celevas** [comment]
Same thing here with TGD 3.9.3.4 on iPad Air, running iOS 10.1.1

**Comment by Celevas** [comment]
To add to the above, the frames load, then the emblems, then 5% or so of the thumbnails when it stops loading any more thumbnails and the error message appears.  It gets exactly this far each time.

**Comment by jerrycarlson** [comment]
Same here with 3.9.3 on Win10/Google Chrome

**Comment by NotAClue** [comment]
Same here on Chrome Version 56.0.2924.87 (64-bit) on Windows 10 no thumbs and the error "Error: Problem checking for updates..." only had time to read the first few words then you get no more errors just remains blank apart from the menu.

**Comment by NotAClue** [comment]
Thanks that is fixed for me :)
