### ISSUE TITLE
tower ghost still doesnt work when downloading from Blackberry World.

### ISSUE THREAD

**Issue by KingARTHURofKC** [dasilva333/TowerGhostForDestiny#699]
Been out of service since November or so. Can someone please tell me if this is intentional or if something is wrong? The app opens then is totally blank except for the yellow menu icon but no characters or items show up at all. Any feedback would be appreciated.

**Comment by edmiller47** [comment]
There haven't been any updates made in some time. My guess is that the app may simply have been abandoned. It was a labor of love by the developer, and perhaps it became too much effort for not enough of a return.
