### ISSUE TITLE
Addition of the bounties that each guardian has open

### ISSUE THREAD

**Issue by lanejcf** [dasilva333/TowerGhostForDestiny#70]
I do not know if it is possible to get the information, and I understand that it has nothing to do with Guardian configuration or loadouts, but I would find it helpful if the bounties that each guardian has open were listed at the bottom of each guardian column whilst viewing in Chrome on my laptop.

The history behind this suggestion is when you are in a fire team and one of your colleagues has a particular bounty they want to do, it would be great to see easily and clearly if any of your 3 characters has it, so you can swap to it and get the benefit of completing the bounty whilst helping a team mate, maximising XP and weapon/armour/subclass upgrades.

**Comment by dasilva333** [comment]
feature will be added as part of 2.7.3 closing out this issue thanks for the feedback

**Comment by Mulchman** [comment]
Just a heads up that clicking on a bounty pops up the transfer box. (2.7.2)

**Comment by dasilva333** [comment]
yeah i know i just havent pushed the latest version yet thx tho :)

**Comment by Mulchman** [comment]
Sorry :P

Just get excited when I see development happening!
