### ISSUE TITLE
Improvement to horizontal allignment

### ISSUE THREAD

**Issue by lanejcf** [dasilva333/TowerGhostForDestiny#71]
I am running 1.9.8 under chrome on my laptop and the horizontal alignment can be off when there are complete blank rows of items in a block.

I apologise for the bad graphics, but the height 'b', when there is a complete blank row is less then the height 'a' when the equivalent row for another guardian has items in it, see below-

![capture](https://cloud.githubusercontent.com/assets/11978393/7220144/4799f736-e6b5-11e4-871d-28da926c2ffd.GIF)

**Comment by dasilva333** [comment]
Agreed it seems the code for issue #48 is coming back to creep thanks for bringing it up expect it fixed

**Comment by wickles** [comment]
I think this is also related to #52, I noticed it before #48 was fixed but it seems to have gotten worse with those two fixes.

**Comment by lanejcf** [comment]
I believe this is now fixed
