### ISSUE TITLE
Option to Auto-Collapse Empty Categories

### ISSUE THREAD

**Issue by yunaforever009** [dasilva333/TowerGhostForDestiny#72]
I know that there is difficulty inherent to developing a cohesive UI across both mobile and desktop versions but something that may help recover excessive vertical space on mobile UIs would be an option to auto-collapse empty categories so that it only displays the category name.

**Comment by dasilva333** [comment]
Thanks for the feedback, I'll be closing this issue in favor of issue #37 they're almost related and I feel like I can roll both changes in together once I get that one started.
