### ISSUE TITLE
Request: Filter class specific items (armour) for each class

### ISSUE THREAD

**Issue by TopTenTiger** [dasilva333/TowerGhostForDestiny#74]

**Comment by dasilva333** [comment]
You mean similar to how I have [Weapons] filter with [Scout, Auto, Fusion Rifle] filters also have another one called [Armor] with [Helmet, Boots, Chest, Class] ?

**Comment by TopTenTiger** [comment]
I was thinking of [Armor] with [Hunter, Titan, Warlock]

**Comment by dasilva333** [comment]
Sorry man closing this ticket in favor of #65 and you'll be able to mix it with the current View > Armor to get the desired effect. thanks

**Comment by TopTenTiger** [comment]
Imagine you have a lot of different class armor in the vault. Wouldn't it be nice to filter it out?
