### ISSUE TITLE
App Crashes on PSN Login 

### ISSUE THREAD

**Issue by Brendonnaftel** [dasilva333/TowerGhostForDestiny#75]
Using iPhone 4S. App runs normally until signing in, at which point the screen turns black after submitting login and app crashes to springboard. Version 2.0.1
Using jailbreak 
iOS version 8.1.2

**Comment by dasilva333** [comment]
Closing in favor of issue #3 please leave any feedback there thanks

**Comment by dasilva333** [comment]
I started experiencing an issue might be related, while attempting to load my profile on my android tablet it crashes back to the main screen. Are you still having issues with TGD 3.7.6 @Brendonnaftel ?
