### ISSUE TITLE
Add a small leveling progress bar for items

### ISSUE THREAD

**Issue by SirLugash** [dasilva333/TowerGhostForDestiny#77]
I really love this program and use it quite often since I discovered it.
One little thing that would help me in particular is a little progress bar on each item that isn't fully leveled yet (I mean a percentage bar, like in the game on the lower portion of the item image).
To clarify I mean a bar representing the percentage between XP gained so far and total XP until fully leveled. Also specifically upgrade unlocks, not purchased upgrades themselves.

Should be an optional thing since probably not anyone will have use for this.
For me personally it would be helpful since I have a batch of legendary weapon that I level up before dismantling (just leveling, not buying upgrades).
With a little progress bar as it is in the game it would make it easier to track which weapons I'm currently upgrading (especially when you have weapons twice or more times).

**Comment by matthubb** [comment]
The progression stats are a bit obscure, as far as I know, only the progression of the current step is available, not the overall progression.

[See this forum post](https://www.bungie.net/en/Forum/Post/88785601)

**Comment by dasilva333** [comment]
@matthubb agreed the API data doesn't provide me enough information to provide this level of detail sorry @SirLugash closing this ticket as it is something I can't fix
