### ISSUE TITLE
Unable to select and item and move on iOS 

### ISSUE THREAD

**Issue by TheCondorman** [dasilva333/TowerGhostForDestiny#78]
When selecting an item the item pop-up appears but not the character selection. Sometimes it does appear but not for the selected weapon. 
http://imgur.com/UVn8HSC
http://imgur.com/Tiy4Ph9

**Comment by dasilva333** [comment]
When you double tap an item it shows you the tooltip, when you single tap it shows the move box, also explained under About, to dismiss the popup you simply tap it. Not a bug thanks for your feedback

**Comment by TheCondorman** [comment]
I’m getting this behaviour with both single and double tap.

**Comment by dasilva333** [comment]
Make sure DestinyDB tooltips is disabled under the menu settings (gear) > DestinyDB tooltips should not be highlighted

**Comment by TheCondorman** [comment]
Ah that's did it! My mistake.
