### ISSUE TITLE
Search within all perks & Progress XP remaining

### ISSUE THREAD

**Issue by Titus-s** [dasilva333/TowerGhostForDestiny#79]
Currently it's possible to search within perks displayed in DestinyDB tooltips (correct me if I'm wrong).
I don't know if it's possible, but it would be fantastic to add option to search within all perks in weapons. 
Recently I wanted to quickly find weapons with perk "Armor piercing rounds" - unfortunately now it's not possible.

**Comment by matthubb** [comment]
My open pull request has the start of this, it loads node / step information onto the itemObject.

**Comment by dasilva333** [comment]
This issue has been addressed with the new tooltips @Titus-s and @matthubb let's open a ticket in the future to continue evelopment for progress xp remaining
