### ISSUE TITLE
iPhone 6 Plus Crash on XBL Login

### ISSUE THREAD

**Issue by lambs0n** [dasilva333/TowerGhostForDestiny#8]
Non-jailbroken phone, installed via FlightTest, iOS 8.3

input my XBL credentials, and it crashes during the loading of the next page..

I saw that you mentioned the jsconsole.com page on another open issue, do I need to do the same with same details? If so, do everything from my phone, or pc?

**Comment by dasilva333** [comment]
thanks for the feedback, its a known issue and I can only try to debug it if you're on a jailbroken device closing this issue in favor of issue #3 after I fix it there I'll create a TestFlight update with a hopefully fixed build thanks
