### ISSUE TITLE
Vault rearranges after reopening the app

### ISSUE THREAD

**Issue by lambs0n** [dasilva333/TowerGhostForDestiny#80]
I'm sure there's going to be someone who will complain about this once it goes live on the Apple Store, so I'm giving you the heads up on it now =) If you arrange the vault in a certain order (I tried to do exotics, then legendaries, etc), close the app entirely (swiping the app completely out), and then reopen the vault, it will be rearranged.. I've done this a few times now to make sure it was reproducible, and it looks like it rearranges in the same order every time (not sure if that means they're based on an ID or something).. Anyway, screenshots of before and after are included. 

Tested this on an iPhone 6Plus, running 2.0.2, iOS 8.3 non-JB.. I chalked the issue up to the fact that it's telling me that I have to login to my Windows Live ID every time I open the app, but I'll leave the debugging to you..

![image1](https://cloud.githubusercontent.com/assets/11874795/7253029/89f53020-e807-11e4-8d60-14ee782bc07c.PNG)

![image2](https://cloud.githubusercontent.com/assets/11874795/7253035/8e6a2052-e807-11e4-9bea-4d58146aaa19.PNG)

**Comment by dasilva333** [comment]
Sorry man the API doesn't provide me any actual values I can use to maintain the order in which they should be so expect them to be ordered randomly according to the order in which they load/are processed/etc.. Thanks for your feedback
