### ISSUE TITLE
Settings button not properly selectable

### ISSUE THREAD

**Issue by yunaforever009** [dasilva333/TowerGhostForDestiny#81]
Following the 2.0.5 update that adds character selection icons in the floating status bar, the settings drop down menu has been difficult to engage. My guess is that the clickable portion of the settings button was moved slightly or shrunk accidentally and does not line up perfectly with the GUI of the settings button. I am not able to reproduce the exact functioning click location but the difficult selection of the button is reproducible.

I am on 2.0.5 on a Galaxy S4, tested in both portrait and landscape orientations.

**Comment by b0bbybacc** [comment]
S3 Checking in. Same thing happening. Proof upcoming if necessary.

**Comment by dasilva333** [comment]
I am able to reproduce it sorry for not catching it earlier I'll get this fixed asap thanks guys

**Comment by FabienO** [comment]
OnePlus phone here (android) and I can't access menu at all. Icons for scroll to character work fine but drop down isn't selectable.

**Comment by FabienO** [comment]
Actually it is selectable but its very difficult. Have to tap like a mad man to finally get it :p

Appreciate all your work on this BTW. Awesome app.

**Comment by dasilva333** [comment]
2.0.6 fixed the issue please confirm and close ticket thanks

**Comment by weborican** [comment]
Confirmed fixed on iPhone 6 (iOS 8.3) and Nexus 7 (Android 5.0.2 - Lollipop).
