### ISSUE TITLE
WP: Quick Scroll view not functional

### ISSUE THREAD

**Issue by equesaspe** [dasilva333/TowerGhostForDestiny#82]
When I press the new icons up top nothing happens. When I long press on them they do display information about each character but will not scroll to them. I am using a Lumia 1520.

**Comment by dasilva333** [comment]
I'll test this when I get home thanks for the heads up

**Comment by dasilva333** [comment]
try 2.0.7 and let me know how it goes thanks

**Comment by equesaspe** [comment]
It works not.  The only annoying thing is that when you use it; it also scrolls the top bar (with icons for menu and quick selects)down about half way.  You have to scroll up a bit to make it all appear again.  However when you scroll down a bit again it hides again.  Does the same thing with the location select bar that pops up at the bottom.  Don't know if it is related or a new issues but both bars like to scroll to include the central area.

**Comment by equesaspe** [comment]
If you want me to put in a new bug for the scrolling menu/select bars let me know.  Thanks.

**Comment by dasilva333** [comment]
Yeah I'm aware that's a separate issue and it applies to other platforms too. Thanks for your feedback
