### ISSUE TITLE
Rollover still says "Destiny Item Viewer" for Firefox extension 2.0.7

### ISSUE THREAD

**Issue by M3Rocket** [dasilva333/TowerGhostForDestiny#84]
The mouse rollover text on the Destiny Tower Ghost icon/extension 2.0.7 for Firefox still says "Destiny Item Viewer." Probably an easy fix.

**Comment by dasilva333** [comment]
Thanks will fix

**Comment by M3Rocket** [comment]
Looks fixed to me in 2.1.0. Thanx!
