### ISSUE TITLE
2.0.8 - Needs Repair???

### ISSUE THREAD

**Issue by pattont** [dasilva333/TowerGhostForDestiny#87]
My Chrome for Mac (42.0.2311.90 (64-bit)) updated to the Tower Ghost plugin to 2.0.8 and now it says that it needs repair. I have tried removing it and re-adding the extension and I get the same error. It just goes corrupt every time I click to open the extension.

2.0.7 worked perfectly!

![screen shot 2015-04-22 at 10 03 41 pm](https://cloud.githubusercontent.com/assets/2903357/7289283/cb781f14-e93b-11e4-9a2a-2c90b9c0bf3c.png)

**Comment by flthrtl** [comment]
Experiencing the exact issue described as well.

**Comment by wrotte** [comment]
Same here. Re-installing/re-starting chrome has no effect.

**Comment by wickles** [comment]
Same here. Guess I'll go back to the dark ages of DIM in the mean time :P

**Comment by PillowMetal** [comment]
Having the same problem, repairing or re-installing has no effect in Chrome on Windows (version 2.0.8). However, the Android version of the app is working fine (version 2.0.9).

**Comment by matt-cahill** [comment]
Yep getting the same here as well. Chrome 42.0.2311.90 64bit

**Comment by matthubb** [comment]
The current Chrome Store version (2.0.8) is working fine on my windows Chrome. I've tried reloading without "developer mode" enabled, still fine.

Some of my cosmetic fixes went in between these releases and a local cache of icons (which I was going to suggest for performance).
[Comparison between 2.0.7 and 2.0.8](https://github.com/dasilva333/TowerGhostForDestiny/compare/6060b27e4669b02affcee0fbf3476c0e1ea3d347...59c7dd89ccc4d1946d120954921504427f5548a0)

If you want to manually install the Chrome app at version 2.0.7 you can [get tower_ghost.zip here](https://github.com/dasilva333/TowerGhostForDestiny/tree/25d78880d2ac84e3ccb6996e879d2eedf8b14734).

**Comment by dasilva333** [comment]
Can someone provide me with the exact error message or error code you're getting? I'm going to have to research and investigate a fix, sorry about the problem it's just working fine for me on Windows too.

Thanks guys!

**Comment by matt-cahill** [comment]
Seems to be working correctly now with 2.0.9. Thanks!
