### ISSUE TITLE
Bug in 2.1.0 - Post Master items appear in inventory

### ISSUE THREAD

**Issue by NoCodeLeftBehind** [dasilva333/TowerGhostForDestiny#89]
2.1.0 introduced a new bug wherein items at a Guardian's Post Master no longer show up there in TGD (PM section shows 0/20), and the items instead show up in the regular invenory under their respective sections (e.g. ships in the PM show up under Ships inventory section). Everything was fine in 2.0.9.

**Comment by dasilva333** [comment]
@NoCodeLeftBehind thanks man I'll investigate the bug I was optimizing the loading of the items I must've made an accidental change.

**Comment by pattont** [comment]
I'm seeing the issue as well.

**Comment by DougerusG** [comment]
I am seeing this issue as well seems to cause program to think inventory is full when it is not.

**Comment by pattont** [comment]
In 2.1.1 I am seeing duplicate Postmaster rows, but not items. Not a big issue, but wanted to let you know.

![image](https://cloud.githubusercontent.com/assets/2903357/7347519/6aa5ee1c-ecb7-11e4-9ede-228c93f4f623.png)

**Comment by dasilva333** [comment]
@pattont can you confirm it's still happening for you in 2.1.8? thanks

**Comment by pattont** [comment]
Still happening on 2.1.8 at least on the iOS beta. Haven't checked PC yet.

**Comment by dasilva333** [comment]
@pattont thanks man I think I got it now expect it fixed in 2.1.9

**Comment by pattont** [comment]
Updated works great. iOS requires re-authentication every time you force
close on iOS?

**Comment by dasilva333** [comment]
Yes it does, on android it loads right away without any interaction. I might improve that in the future to make the reauth more seamless. Thanks guys
