### ISSUE TITLE
Proposal for new style move item tooltip

### ISSUE THREAD

**Issue by joshhunt** [dasilva333/TowerGhostForDestiny#94]
I always get confused when moving items - I struggle to identify which character is which, so I quickly mocked up a 'redesigned' moved item tooltip.

http://s.codepen.io/joshhunt/debug/NqPPNg

![screen shot 2015-04-25 at 12 56 37 pm](https://cloud.githubusercontent.com/assets/46142/7331200/9034fb6e-eb4a-11e4-93f2-254f483f0228.png)

I just wanted to grab your thoughts on this before I spend time to implement this to get your thoughts on it and see if you have any suggestions for it.

**Comment by dasilva333** [comment]
I suppose if it's only for desktop, for mobile that would be too big, I'd like to get other people's approval too before I make this big change. Not sure whether to post a poll in http://www.reddit.com/r/towerghostfordestiny. What do you think?

**Comment by joshhunt** [comment]
It would easily fit on mobile - it would just obscure a lot more than the current one and I think that's OK - all you're interested in doing is moving that item.

More feedback and suggestions would be good.

**Comment by pattont** [comment]
I like the current method.. It's simple and doesn't take a lot of moving the mouse to click on the icon I'm moving to. I guess it's fine either way I mostly use loadouts.

**Comment by lanejcf** [comment]
The current method is clean and simple and minimises movement.  I have 3 titans so rely on the colour of the icon rather than guardian type.
Another option ?

**Comment by pattont** [comment]
I do the same thing :-)

**Comment by ssoriche** [comment]
Where I have one of each class but all with the same emblem.

I like the proposed layout but only if the screen size supports it.

I'd like to see a constant order to Guardians and the transfer pop up. I thought it was happening but every now and then the order changes.

**Comment by matthubb** [comment]
I'm in the same boat as @ssoriche: three different classes, but prefer the same emblem. 

This is why I made the PR with class initials in the lower left corner for move popup and loadouts. 

I like Josh's proposal. I don't see any problem with it dominating a mobile screen. Especially if it gains a close button. 

Perhaps the move popup could be more like a context menu? Could provide an inspect/destinydb link too?

**Comment by matthubb** [comment]
A feature that isn't entirely possible yet because of missing information is to fetch materials required to activate an unlocked node (I keep all my materials in the vault). 

A context menu approach would make it simpler to fit extra features later.

Also thinking of a Progression/XP manager, for bounty hand ins: a place to add an item to a priority queue would be handy.
