### ISSUE TITLE
Can't close help or about on iOS

### ISSUE THREAD

**Issue by matthubb** [dasilva333/TowerGhostForDestiny#98]
Running hydrated TestFlight on iOS on iPhone 6. 

There's no version number anymore. Went to check on the about page and couldn't close it. Killed app and checked it's the same with the help page too.

**Comment by dasilva333** [comment]
Just tried it on my iPhone 5 I used both the new ios branch and installing it directly from the TestFlight app and they both seem to work fine. Try a reinstall I suppose, not sure.

**Comment by matthubb** [comment]
Tap anywhere is supposed to close?

Just tried reinstalling. Still can't get them to close, but the hydration triple tap causes a reload and that sorts it.

**Comment by dasilva333** [comment]
I got this to happen to me, I'm glad I didn't close this ticket. There's a little x in the corner to close it however for some reason it wouldn't click for me, so I'll mark this as a bug and allow clicking on the popup to close it thanks @matthubb

**Comment by weborican** [comment]
On that note, I would request to make that closing X much more visible, it super-stealthy as of version 2.1.9.

**Comment by dasilva333** [comment]
This has been fixed as of 2.2.6 thanks guys
