### ISSUE TITLE
Firefox loadouts to don't save to the cloud

### ISSUE THREAD

**Issue by r3b3lspy** [dasilva333/TowerGhostForDestiny#99]
After installing the app none of the loudest will sync, if I create new one they will sync between iPad and iPhone devices but they will not sync at all with the browser extension.

Also how can I save the loudest as mentioned by you in reddit?

**Comment by dasilva333** [comment]
If the loadouts open for you in Chrome then open the developer tools (F12), visit the console, type JSON.stringify(app.loadouts()) and save that to a file as your backup, if you happen to lose your loadouts then you can grab the contents of the file and type this into the console to restore it:
app.loadouts("paste the contents here") and it should show up in your menu, after that hit save to make sure it saves to the cloud permanently.

Can you describe the two platforms that don't sync? If it's two browsers like Firefox and Chrome that don't sync then you can type this: console.log(app.activeUser().user.membershipId) and make sure they both match otherwise it won't sync.

Thanks

**Comment by r3b3lspy** [comment]
Thank you for the advice on how to backup loadouts.

The platforms that don't sync are iOS and the browser extensions, on my iPhone and iPad after installing the app I get no loadouts at all,  I can create new ones and they will sync between iOS devices but in the chrome and firefox extensions I have loadouts that are not syncing at all, basically it will sync newly created loudest between iOS devices but it will not sync the ones already created in Chrome or Firefox and the ones created in iOS will not sync to the browser either.

**Comment by dasilva333** [comment]
That is weird indeed, attempt the following:

1. on firefox and chrome visit the developers tools (f12 in chrome) (ctrl+shift+k firefox)
2. in the console type this in: console.log(app.activeUser().user.membershipId)
3. Post your id in this thread so I can debug the issue and see if there's anything weird at the server side
4. I'll be providing you a debug build so you can get the membershipId it uses when you're on mobile to see what's going on. (are you jailbroken or flighttest?)

thanks!

**Comment by r3b3lspy** [comment]
Thanks I just did it on FireFox and I got this on the console:

undefined
"4156521"

on iOS I'm on TestFlight.

Let me know.

**Comment by r3b3lspy** [comment]
Any news on the sync issue? Sometimes also on my son's iPad and my iPad it will logout and then when try to go to login again via the windows live link it will get stack on the bungie page and it will not load the vault.

**Comment by dasilva333** [comment]
@r3b3lspy two things I realized last night that Firefox doesn't have cloud saves supported yet
second thing is when you login via mobile it's normal for the bungie page to stay there for a while until it loads
Sorry for not realizing it earlier I'll still look into the other issue with it not syncing on mobile. thanks

**Comment by r3b3lspy** [comment]
Thank you, I was using Firefox and my son was using Chrome, his app was syncing but you pushed an update last night and now all loadouts are lost on his too and he was using only your app for a couple of days. Mine never synced. 

The bungie scree will not go away after 20 minutes, only works if you sign out of your bungie profile and re-sign again.

Let me know wha you find.

**Comment by jantjis** [comment]
Hi Richard,

first of all thanks for this great App on iOS and the TestFlight Invitation. I got the exact same issue on syncing iOS App with the Firefox extension. I created loadouts in the iOS App & can't find them in the FF extension.

I also got the same log-in bug. After an update, i need to login again. Looks like Bungie saved my login for a longer time, but your iOS app don't recognize it and i see my bungie profile in the App. If i log-out & in again everything works fine.

Thanks ;)

**Comment by r3b3lspy** [comment]
I understand that Firefox does not have cloud saves but I'm doing it in Chrome and it is not working either, also it will not sync from iOS device to iOS device either.

After the update that was pushed yesterday the app will not load at all it will just blink intermitently with a loading legend at top. 

Let me know what you can find.

**Comment by r3b3lspy** [comment]
I've deleted the app to re-install and see if the issue is fixed but now the app is not in test flight anymore? 

Can you please send the invite or enable it again for download?

Thanks!

**Comment by dasilva333** [comment]
@r3b3lspy check out the FAQ at http://www.towerghostfordestiny.com/flighttest.cfm it explains the situation on why you can't reinstall the app yet.

Regarding the loadouts not syncing from ios to ios that's definitely sounds like an issue I'll be looking into. Thanks

whenever there's an update it'll do that blue loading bar and sometimes it takes a lot longer than normal. I've seen it get stuck on windows phone where the only solution is to uninstall/reinstall but just be patient on ios and it should load eventually.

**Comment by r3b3lspy** [comment]
OK no problem and thanks for pointing to the app reinstall issue, are you pushing an update today and we can download from TestFlight again? it will show up automatically in TestFlight?.

You've mentioned that you'll investigate about iOS to iOS syncing issue, are you going to investigate why is not syncing from Chrome to iOS too?

Also after installing anew update yesterday on my son's iPad all loudest created on iOS were missing on the new(iOS) version, are they deleted on every update?

**Comment by dasilva333** [comment]
-The update is on Apple to push to you guys 
-It will show up automatically
-Yes all issues will be fixed
-No your loadouts are saved to the cloud to they should stay with you through updates
-Loadouts have been buggy lately so there has been reports of people losing their saves

**Comment by r3b3lspy** [comment]
Thank you for your reply, have you submitted the update and we are waiting for Apple now?

Can we expect to get it before the weekend?

It will show up by itself on testFlight again? now TestFlight is empty.

Thanks a lot.

**Comment by zxaos** [comment]
On a clean install of the iOS app, I had it successfully show and use a load out created in the chrome version.

**Comment by dasilva333** [comment]
@r3b3lspy 2.1.3 should be available to everyone as of today good luck

**Comment by r3b3lspy** [comment]
Thanks I'll test today and post feedback. Any idea on when you will be going live?  A new Destiny loudest native iOS app was released yesterday it looks good but no iPad integration is no-go for me and I like your app better.

**Comment by dasilva333** [comment]
2.2.7 added improvements to the syncing, still no Firefox Cloud save support but it should be working better now.

**Comment by r3b3lspy** [comment]
Sync is working better now, I'll keep testing, thanks, any idea when the app will go live?

**Comment by dasilva333** [comment]
The app is literally under review as we speak so I should get the rejection by today or tomorrow. I'll change this ticket from a bug to enhancement and leave it open as a reminder to get cloud saves for Firefox working. thanks guys

**Comment by dasilva333** [comment]
I already created the solution for adding cloud saves to Firefox in this branch:

https://github.com/dasilva333/TowerGhostForDestiny/tree/content-script-xhr

The next step is now simply to integrate the changes into the master branch.

**Comment by patchm00** [comment]
sorry but how do i apply that since there is no .xpi file?  I don't think it has been integrated with master branch since the newest version does not download my cloud loadouts i created in chrome.  seems this last release (or maybe some weird Windows 10 update or Firefox) deleted my loadouts

**Comment by dasilva333** [comment]
@patchm00 it's not something you apply. it's just work I did to enable it in the future but it's not ready yet. No cloud saves supported yet

**Comment by dasilva333** [comment]
Firefox loadouts save to the cloud for the last couple of months, forgot to close out this issue. let me know if anyone still has problems with it. thanks
